Poobslag/turbofat

- project.godot
- scenes/Global.gd
- scenes/Marathon.gd
- scenes/Playfield.gd
- scenes/PracticeMenu.gd
- scenes/PracticeMenu.tscn
- scenes/RankCalculator.gd
- scenes/ScenarioHistory.gd
- test/unit/TestRankCalculator.gd
- test/unit/TestScenarioHistory.gd
- todo.txt
The game technically saves a history of the player's last 1,000
games for any given scenario, so if you get a high score and then play
1,000 times your high score will be deleted. ...Sorry.
> Game saves, displays high scores

- demo/CustomerViewDemo.gd
- demo/CustomerViewDemo.tscn
- demo/RestaurantSceneDemo.gd
- demo/RestaurantSceneDemo.tscn
- scenes/Game.gd
- scenes/Game.tscn
- scenes/Restaurant/Customer.gd
- scenes/Restaurant/CustomerView.gd
- scenes/Restaurant/CustomerView.tscn
- scenes/Restaurant/OutlineSprite.gd
- scenes/Restaurant/RestaurantScene.gd
- scenes/Restaurant/RestaurantScene.tscn
- scenes/Restaurant/Seat.gd
- scenes/Restaurant/Seat.tscn
The restaurant now contains three customers. When the camera pans away,
the customer who was just fed shrinks to their original size.
Eventually, they'll instead be replaced with a new customer.
Added a CustomerViewDemo for showing off the "pan to new customer"
logic, as well as tracking down bugs related to feeding the wrong bug
and things like that.
This involved some very messy code and kludges for having shadow and
outline sprites track each other across different scenes. This is
inevitable until we resolve issues #30 and #32 to reduce the amount of
work in maintaining hierarchies of interconnected sprites which are all
drawing the same simple object.
> Ending a combo pans to a new customer.

- scenes/Global.gd
- scenes/PracticeMenu.gd
This isn't for gatekeeping, but just because I don't want players
jumping into the harder difficulties and having an unfun time or missing
the point of the game. An A- grade is pretty low; you can get this on
Normal Marathon by only clearing 20-30 lines, for example.
> Harder difficulties start out locked.

- src/main/puzzle/Playfield.tscn
- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/piece/NextPieces.tscn
- src/main/puzzle/piece/next-pieces.gd
- src/main/puzzle/puzzle.gd
- src/main/ui/ScenarioMenu.tscn
- src/main/world/restaurant/RestaurantScene.tscn
Sprites are better for things that are objects that have a position,
like a table or a person. TextureRects are better for things meant to
fill a specific area, like a wallpaper or background.
> Replaced some Sprites with TextureRects.

- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/Scenario.tscn
- src/main/puzzle/puzzle.gd
- src/main/puzzle/scenario.gd
- src/main/ui/scenario-menu.gd
- src/main/world/restaurant/customer-body.gd
Buttons can now be navigated with keyboard.
Replaced handwritten linear interpolation code with lerp() function.
Renamed signal methods to include class name.
> Refactoring; button focus, lerp, signal methods

- src/main/world/Overworld.tscn
- src/main/world/bort.gd
- src/main/world/restaurant/Customer.tscn
Customer is rendered using a viewport. This doesn't look perfect, it's heavily aliased and there is a noticable jitter as it loads.
> Customer is rendered, animated in 3D.

- assets/dialog/bort.json
- assets/dialog/ebe.json
- assets/dialog/orange.json
- project.godot
- src/delint.sh
- src/demo/chat-ui-demo.gd
- src/main/puzzle/rank-result.gd
- src/main/ui/chat/chat-event.gd
- src/main/ui/chat/chat-library.gd
- src/main/ui/chat/chat-tree.gd
- src/main/ui/chat/chat-ui.gd
- src/main/ui/overworld-ui.gd
- src/main/world/Customer3D.tscn
- src/main/world/bort.gd
- src/main/world/ebe.gd
- src/main/world/interactable-manager.gd
JSON dialog structure now allows links. Branching dialog trees can be
parsed by ChatLibrary, navigated by ChatUi. ChatUi always just picks the 2nd
fork for now.
Resolved some console error messages. Customer3D's ViewportTexture
was reporting errors because the viewport was too low in the scene tree.
get_meta() calls were throwing errors for objects lacking metadata.
Pushed json chat event parsing logic into ChatEvent
More robust accent_defs implementation. Each customer defines their own accent_def which is pulled in by InteractableManager.
> Added backend dialog tree logic. Fixed console errors.

- project.godot
- src/demo/chat-frame-demo.gd
- src/demo/customer-view-demo.gd
- src/demo/mood-demo.gd
- src/demo/restaurant-scene-demo.gd
- src/main/global.gd
- src/main/ui/chat/chat-appearance.gd
- src/main/world/multi-outline-sprite.gd
- src/main/world/restaurant/Customer.tscn
- src/main/world/restaurant/Seat.tscn
- src/main/world/restaurant/customer.gd
Resolved orphaned ChatAppearance nodes. ChatAppearance did not need to be
a node. Making it a node prevented it from being garbage collected.
Fixed 'index p_frame = 3 is out of bounds' errors. Fixed demo keypress issues.
Fixed visual glitch where food went behind table.
> Fixed orphaned nodes, refactored demos.

- assets/dialog/boatricia.json
- assets/dialog/bort.json
- assets/dialog/temp.json
- project.godot
- src/delint.sh
- src/demo/chat/chat-frame-demo.gd
- src/main/global.gd
- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/PuzzleHud.tscn
- src/main/puzzle/Scenario.tscn
- src/main/puzzle/puzzle-hud.gd
- src/main/puzzle/puzzle.gd
- src/main/puzzle/scenario-library.gd
- src/main/puzzle/scenario-settings.gd
- src/main/puzzle/scenario.gd
- src/main/ui/chat/ChatChoices.tscn
- src/main/ui/chat/chat-event.gd
- src/main/ui/chat/sentence-sprite.gd
- src/main/ui/overworld-ui.gd
- src/main/ui/scenario-menu.gd
- src/main/world/Overworld.tscn
- src/main/world/boatricia.gd
- src/main/world/bort.gd
- src/main/world/customer-3d.gd
- src/main/world/ebe.gd
- src/main/world/interactable-manager.gd
- src/main/world/restaurant/customer-loader.gd
- src/main/world/turbo.gd
Talking to 'boatricia' gives you the option of playing a puzzle. After the
puzzle, you're dumped back to the overworld.
Added 'R' to chat frame demo.
> Can launch a scenario from the overworld.

- assets/puzzle/scenario/boatricia.json
- assets/puzzle/scenario/marathon-expert.json
- assets/puzzle/scenario/marathon-hard.json
- assets/puzzle/scenario/marathon-master.json
- assets/puzzle/scenario/marathon-normal.json
- assets/puzzle/scenario/sprint-expert.json
- assets/puzzle/scenario/sprint-normal.json
- assets/puzzle/scenario/ultra-expert.json
- assets/puzzle/scenario/ultra-hard.json
- assets/puzzle/scenario/ultra-normal.json
- src/delint.sh
- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/piece/piece-speed.gd
- src/main/puzzle/piece/piece-speeds.gd
- src/main/puzzle/rank-calculator.gd
- src/main/puzzle/rank-result.gd
- src/main/puzzle/scenario-library.gd
- src/main/puzzle/scenario-settings.gd
- src/main/puzzle/scenario.gd
- src/main/ui/ScenarioMenu.tscn
- src/main/ui/chat/chat-event.gd
- src/main/ui/chat/chat-library.gd
- src/main/ui/chat/chat-tree.gd
- src/main/ui/overworld-ui.gd
- src/main/ui/scenario-button.gd
- src/main/ui/scenario-menu.gd
- src/test/test-rank-calculator.gd
Fixed bug where delinter was overlooking long lines. Many long lines need
to be cleaned up.
> Moved all scenarios into json files

- src/demo/chat/MoodDemo.tscn
- src/main/world/restaurant/Customer.tscn
- src/main/world/restaurant/customer-loader.gd
- src/main/world/restaurant/customer.gd
Moved hframes/vframes assignments from Customer into CustomerLoader. This
will facilitate the eventual shrinking of customer sprites.
> Fixed color of character emote outlines.

- src/main/puzzle/Playfield.tscn
- src/main/puzzle/playfield.gd
The first two lines in a combo don't award bonus points, so it's misleading to
have special sfx for them.
> No longer play combo sfx for first two lines.

- project.godot
- src/main/connect.gd
- src/main/puzzle/piece/corner-map.gd
- src/main/puzzle/piece/piece-types.gd
- src/main/puzzle/playfield.gd
- src/main/puzzle/stretch-map.gd
While writing the 3D autotiling logic I found myself writing more
bitmasking logic like 'if x & CONNECTED_UP > 0'. This utility class makes
that code less repetitive and easier to read.
> Extracted 'Connect' utility for directional bit masking.

- src/main/puzzle/piece/piece-types.gd
- src/main/puzzle/rank-calculator.gd
- src/test/test-piece-kicks-v.gd
- src/test/test-rank-calculator.gd
Combos felt overly punitive; a mediocre combo score of  5-6 points per
line was given a 'D-' or '-' rank.
> Added v-kick. Rebalanced rank grades.

- src/main/global.gd
- src/main/ui/scenario-menu.gd
This new scale follows the progression of our eventual star unlocks.
'B' and 'A' grades will eventually be displayed as dots and triangles. These
will be displayed to the user and help them gauge their progress. Unbeknownst
to them at the start of the game, they have no impact on progress.
S grades will eventually be displayed as stars, like the stars of a
restaurant. Stars will be a prerequisite to hire new employees, grow your
restaurant and increase your income. All of these steps are optional but they
help to progress through the game faster.
These grades
> New grade scale; eliminated D and C ranks.

- src/delint.sh
- src/demo/ScenarioDemo.tscn
- src/demo/scenario-demo.gd
- src/main/global.gd
- src/main/puzzle/Scenario.tscn
- src/main/puzzle/puzzle.gd
- src/main/puzzle/scenario-library.gd
- src/main/puzzle/scenario.gd
- src/main/ui/chat/chat-library.gd
- src/main/ui/overworld-ui.gd
- src/main/ui/scenario-menu.gd
It currently lets you save/load, edit JSON directly, and test the
resulting scenario. It will eventually have a more user-friendly interface
and be tied into the UI.
> ScenarioDemo now acts as a scenario editor.

- assets/puzzle/scenario/tutorial-beginner-0.json
- assets/puzzle/scenario/tutorial-beginner-1.json
- assets/puzzle/scenario/tutorial-beginner-2.json
- assets/puzzle/scenario/tutorial-beginner-3.json
- src/main/puzzle/combo-tracker.gd
- src/main/puzzle/editor/level-editor.gd
- src/main/puzzle/piece/next-piece-displays.gd
- src/main/puzzle/piece/piece-queue.gd
- src/main/puzzle/piece/piece-type.gd
- src/main/puzzle/playfield-fx.gd
- src/main/puzzle/puzzle.gd
- src/main/puzzle/rank-calculator.gd
- src/main/puzzle/scenario-settings.gd
- src/main/puzzle/scenario.gd
Changed piece queue to always start with five bad pieces
The old approach of 'two boxes at the start' was kind, and maybe i'll
bring it back. I'm trying something different for now.
> Levels accept piece types, score variations. Piece queue changes

- src/main/puzzle/PuzzleHud.tscn
- src/main/puzzle/piece/active-piece.gd
- src/main/puzzle/piece/piece-queue.gd
- src/main/puzzle/piece/piece-speed.gd
- src/main/puzzle/piece/piece-speeds.gd
- src/main/ui/ScenarioMenu.tscn
- src/main/ui/scenario-button.gd
- src/main/ui/scenario-menu.gd
Piece randomizer now inserts an 'annoying piece' in the first 8 pieces.
> Changed initial piece randomization.

- project.godot
- src/main/file-utils.gd
- src/main/global.gd
- src/main/old-save.gd
- src/main/player-save.gd
- src/main/puzzle/editor/level-editor.gd
- src/main/puzzle/rank-calculator.gd
- src/main/puzzle/results-hud.gd
- src/main/puzzle/scenario/scenario-library.gd
- src/main/ui/high-score-table.gd
- src/test/test-rank-calculator.gd
global.gd is at risk of becoming a blob class, so it's good to push common
functionality into specialized classes.
> Moved file utils, grade calculation out of global.gd.

- assets/puzzle/scenario/sandbox-expert.json
- assets/puzzle/scenario/sandbox-hard.json
- assets/puzzle/scenario/sandbox-master.json
- assets/puzzle/scenario/sandbox-normal.json
- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/milestone-hud.gd
- src/main/puzzle/puzzle-score.gd
- src/main/puzzle/puzzle.gd
- src/main/puzzle/rank-calculator.gd
- src/main/puzzle/rank-result.gd
- src/main/puzzle/results-hud.gd
- src/main/puzzle/scenario/Scenario.tscn
- src/main/puzzle/scenario/lose-condition-rules.gd
- src/main/puzzle/scenario/rank-rules.gd
- src/main/puzzle/scenario/scenario.gd
- src/main/puzzle/scenario/tutorial-hud.gd
- src/main/puzzle/topout-tracker.gd
- src/main/ui/menu/PracticeMenu.tscn
- src/main/ui/menu/practice-menu.gd
- src/main/ui/menu/practice-mode-selector.gd
There is no way to win or lose sandbox mode. There is no penalty for
dying, you can die over and over. The game tracks your high scores.
Refactored RankCalculator to separate the 'statistics gathering' part from
the 'rank calculation' part.
Added new scenario flags: rank.unranked, lose.finish-on-lose
> Added sandbox mode.

- src/main/ui/OverworldUi.tscn
- src/main/ui/overworld-ui.gd
I originally added some logic to toggle the buttons on and off, but
they're out of place anyways. The player can hit the 'back' button to open
a menu and quit that way.
> Removed overworld buttons.

- project.godot
- src/demo/chat/chat-frame-demo.gd
- src/demo/chat/chat-ui-demo.gd
- src/demo/chat/mood-demo.gd
- src/demo/creature-view-demo.gd
- src/demo/music-player-demo.gd
- src/demo/overworld-grid-map-demo.gd
- src/demo/playfield-demo.gd
- src/demo/rank-calculation-demo.gd
- src/demo/restaurant-scene-demo.gd
- src/demo/results-hud-demo.gd
- src/demo/tutorial-hud-demo.gd
- src/main/global.gd
- src/main/puzzle/frosting-glob.gd
- src/main/puzzle/milestone-hud.gd
- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/piece/states/prelock.gd
- src/main/puzzle/playfield-fx.gd
- src/main/puzzle/playfield.gd
- src/main/utils.gd
- src/main/world/restaurant/emote-anims.gd
- src/main/world/spira.gd
Playfield.write_piece_to_playfield() no longer returns bool. Its return value
was pretty obtuse, so now its invokers just query for the thing it was
returning.
> Split Utils from Global.

- src/main/world/restaurant/creature.gd
Now stepifies an angle, instead of performing multiple dot product
calculations.
> Simplified creature orientation calculation.

- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/puzzle-score.gd
Resolved PuzzleScore signal errors introduced in 32846fd3
Resolved 'speed_changed' console error introduced in 8fc215f0
> Resolved console errors introduced during refactoring.

- src/main/puzzle/Playfield.tscn
- src/main/puzzle/line-clear-sfx.gd
- src/main/puzzle/make-box-sfx.gd
- src/main/resource-cache.gd
- src/main/world/creature/Creature.tscn
- src/main/world/creature/creature-sfx.gd
- src/main/world/restaurant/restaurant-scene.gd
Combined AudioStreamPlayer instances for playfield combo sfx, snack box
sounds, creature voices.
Fixed issue from seat refactoring where audio sound position was set
before the creature was assigned to a seat.
> Merged AudioStreamPlayers. Precache .wav files. Audio position fixes.

- src/main/world/chat-icon.gd
- src/main/world/chattable-manager.gd
Node groups seem suited for this purpose, where you want to flag multiple
unrelated nodes as all belonging to a group of things.
> Chattables are now in 'chattable' node group.

- src/main/puzzle/puzzle.gd
Apologies to any players who actually get more than 9,999 trillion dollars.
> Avoid money overflow.

- src/main/ui/SettingsMenu.tscn
- src/main/ui/button-shortcut-helper.gd
Also fixed a node with a cryptic name
> Fixed bug where hitting 'esc' closed the overworld menu immediately

- license/asset-license.txt
- project.godot
- src/main/ui/3d/OverworldUi3D.tscn
- src/main/ui/menu/MainMenu.tscn
- src/main/ui/menu/main-menu.gd
- src/main/world/3d/Creature3D.tscn
- src/main/world/Overworld.tscn
- src/main/world/creature/Creature.tscn
- src/main/world/creature/creature.gd
- src/main/world/overworld-ui.gd
- src/main/world/spira.gd
This introduces a 2D player character which can run around in an empty
environment. It also displays the player's money and has a menu for
quitting the game.
The 2D mode can be accessed with the "!" button on the main menu.
> Converting overworld from 3D to 2D (Player character)

- src/main/puzzle/tutorial/tutorial-hud.gd
Tutorial could be skipped by doing a squish move and making the UT-box in
the upper left
> Fixed bug where tutorial could be skipped in a lame way

- src/demo/world/restaurant/RestaurantSceneDemo.tscn
- src/main/world/creature/Creature.tscn
- src/main/world/creature/CreatureShadow.tscn
- src/main/world/creature/creature-shadow.gd
- src/main/world/creature/creature.gd
- src/main/world/restaurant/RestaurantScene.tscn
- src/main/world/restaurant/restaurant-scene.gd
Creature shadows used to grow but this was broken at some point. I've
fixed it.
These shadows need to be grouped on their own layer so that they don't
overlap strangely. To accomplish this they need to be outside the creature
scene.
> Creature shadows grow in restaurant. Split out CreatureShadow.

- src/demo/world/restaurant/creature-view-demo.gd
- src/demo/world/restaurant/restaurant-scene-demo.gd
- src/main/puzzle/playfield-fx.gd
- src/main/puzzle/puzzle.gd
- src/main/world/creature/creature-2d.gd
- src/main/world/creature/creature.gd
Clearing a snack box results in a brown/white/pink/bread colored glob of
food. Clearing a vegetable results in green food. Clearing a cake box
results in a brightly colored glob of a random color.
> Eaten food now matches the line color.

- project.godot
- src/demo/PackedSpriteDemo.tscn
- src/demo/packed-sprite-demo.gd
- src/main/packed-sprite.gd
- src/main/world/creature/Creature.tscn
- src/main/world/creature/creature-loader.gd
- src/main/world/creature/creature-packed-sprite.gd
- src/main/world/creature/emote-anims.gd
- src/main/world/creature/mouth-anims.gd
Sprite had its own offsets and frame data which were frustrating to work
around. It worked OK for simple sprites with an offset of (0, 0), but
did not work for sprites which needed their own offset.
> Redesigned PackedSprite to extend Node2D, not Sprite

- src/main/packed-sprite.gd
- src/main/world/creature/Creature.tscn
PackedSprite was not drawing itself when frame data was first loaded,
resulting in blank sprites.
> Creature's PackedSprites are centered, drawn appropriately

- license/asset-license.txt
I've scrutinized each asset and license to ensure they use a
commercial-compatible license.
I'm including a summary of the license, to decide what we will include in
our credits as the game is finished. '$$$' must be included in the game's
credits. '$$' might be included in the game's credits, depending on how
heavily you used it, or whether they're a 'warm fuzzy' project (Gut,
godotengine.org) versus a 'big company' (Google, cheap-audio-drivers.biz)
> Improved license summary. Added Godot to license.

- src/demo/music-player-demo.gd
- src/demo/world/restaurant/creature-view-demo.gd
- src/demo/world/restaurant/restaurant-scene-demo.gd
- src/main/MusicPlayer.tscn
- src/main/freshness-inspector.gd
- src/main/global.gd
- src/main/music-player.gd
- src/main/puzzle/piece/piece-queue.gd
- src/main/resource-cache.gd
Instead of the music always starting from the beginning, it now starts
from one of 5-6 preset points the first time you hear it. After the first
time, the music will continue from wherever.
This should help the music feel fresh for longer. Before, you always heard
the same drum riff when booting up the game. ...I have heard it a lot.
> Music starts from checkpoints.

- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/creature-visuals.gd
These were inadvertently removed in the previous commit.
> Restored missing movement textures.

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/world/Overworld.tscn
Sometimes, Godot forgets things sometimes... :|
> Reconnected chat signals.

- project/src/main/puzzle/piece/PieceManager.tscn
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/body-sweat.gd
- project/src/main/world/creature/creature-curve.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/emote-anims.gd
- project/src/main/world/creature/head-sweat-drops.gd
- project/src/main/world/creature/head-sweat-squirts.gd
- project/src/main/world/restaurant/CreatureView.tscn
They sweat, their head shakes, and they get dizzy. This ramps up over
time.
> If you feed a creature too much, they get sad and sick

- project/src/demo/world/restaurant/creature-view-demo.gd
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/emote-anims.gd
- project/src/main/world/creature/idle-timer.gd
- project/src/main/world/creature/mouth-anims.gd
- project/src/main/world/restaurant/creature-view.gd
Creature will now occasionally yawn, close their eyes, or look behind
them. These animations launch every 10-30 seconds when the creature is in
the 'ambient' state.
> Added three idle animations.

- project/src/main/puzzle/piece/active-piece.gd
> Don't try kicks after a failed floor kick.

- project/src/main/file-utils.gd
- project/src/main/old-save.gd
- project/src/main/player-save.gd
- project/src/main/string-utils.gd
- project/src/main/ui/menu/SplashScreen.tscn
- project/src/main/ui/menu/bad-save-data-control.gd
- project/src/main/ui/menu/splash-screen.gd
- project/src/test/test-backwards-compatible.gd
- project/src/test/test-player-data.gd
The game keeps a backup for the past hour/day/week. If the newest save
file can't be loaded, it loads a backup and prints a message
Closes #122.
> Rolling backup saves.

- project/src/main/world/creature/CreatureVisuals.tscn
The 'smile0' and 'sweat0' emotes were mangled when adding the 'creatures
look happy when fed' moods. It looks like it was probably the result of a bad
merge.
> Fixed emotes broken in e7aae9db

- project/src/main/world/creature/CreatureVisuals.tscn
It was hard to notice the bouncing for fat characters.
> Increased wiggle 'bounce' amount.

- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/editor/creature/ui-darkener.gd
The saved creature appears in the overworld and in the puzzle mode.
> Player can save their edited creature.

- project/src/main/world/restaurant/RestaurantView.tscn
> Customer camera scales as customer grows in size.

- project/src/main/ui/SettingsMenu.tscn
- project/src/main/ui/VolumeSetting.tscn
Also enabled the 'follow focus' flag in the settings menu so that the
controller can navigate to the OK button.
Closes #539.
> Can change volume in settings menu using controller.

- project/project.godot
- project/src/demo/world/creature/palette-editor-tab.gd
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/utils.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/dna-utils.gd
- project/src/test/test-utils.gd
- project/src/test/world/creature/test-dna-utils.gd
Many sections of code wanted to loop over all color alleles or all body
part alleles. These values are now in DnaUtils constants.
Alleles now have a default weight. This allows for things like 'creatures
with no hair are very common' or 'illithid mouths are rare'.
Allele combos now have an adjustment. This allows for things like 'ant
mouths don't look good with hair'.
Moved put_if_absent from DnaUtils into Utils.
> Extracted allele constants. Improved 'allele combo' logic.

- project/assets/main/puzzle/scenario/boatricia1.json
- project/assets/main/puzzle/scenario/boatricia2.json
- project/assets/main/puzzle/scenario/five-customers-no-vegetables.json
- project/assets/main/puzzle/scenario/placeholder01.json
- project/assets/main/puzzle/scenario/placeholder02.json
- project/assets/main/puzzle/scenario/placeholder03.json
- project/assets/main/puzzle/scenario/placeholder04.json
- project/assets/main/puzzle/scenario/placeholder05.json
- project/assets/main/puzzle/scenario/placeholder06.json
- project/assets/main/puzzle/scenario/placeholder07.json
- project/assets/main/puzzle/scenario/placeholder08.json
- project/assets/main/puzzle/scenario/placeholder09.json
- project/assets/main/puzzle/scenario/placeholder10.json
- project/assets/main/puzzle/scenario/placeholder11.json
- project/assets/main/puzzle/scenario/placeholder12.json
- project/project.godot
- project/src/main/puzzle/duration-calculator.gd
- project/src/main/puzzle/piece/piece-speeds.gd
- project/src/main/puzzle/scenario/scenario-settings.gd
- project/src/main/ui/level-select/LevelSelect.tscn
- project/src/main/ui/level-select/LevelSelectButton.tscn
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/level-select/level-description-panel.gd
- project/src/main/ui/level-select/level-info-panel.gd
- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/ui/level-select/level-select.gd
- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/swipe-container.gd
- project/src/test/puzzle/test-duration-calculator.gd
Added name/title/difficulty attributes to scenarios.
> Created new level select screen.

- project/project.godot
- project/src/main/pauser.gd
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/PuzzleMessages.tscn
- project/src/main/puzzle/piece/next-piece-displays.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/main/puzzle/tutorial/tutorial-hud.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/menu/settings-menu.gd
- project/src/main/ui/menu/splash-screen.gd
Quitting tutorial redirects to splash screen/main menu appropriately. If
it's your first time and you quit, you end up back at the splash screen.
Otherwise you end up wherever you were before.
Closes #123.
> Can pause and change settings during puzzles. Can quit tutorial.

- project/src/main/puzzle/puzzle-score.gd
> Fixed 'quit' button bug when pausing countdown.

- project/src/main/puzzle/rank-calculator.gd
- project/src/main/ui/MoneyLabel.tscn
- project/src/main/ui/level-select/LevelSelect.tscn
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/level-select/level-description-panel.gd
- project/src/main/ui/level-select/level-info-panel.gd
These statistics tell you your current rank, and how many levels you need
to improve to rank up.
> Level select now includes overall statistics.

- project/assets/main/dialog/instructor/creature.json
- project/src/demo/world/restaurant/restaurant-scene-demo.gd
- project/src/demo/world/restaurant/restaurant-view-demo.gd
- project/src/main/editor/creature/HookableNametag.tscn
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/name-generator.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/scenario/scenario.gd
- project/src/main/ui/blogger-sans-bold-18.tres
- project/src/main/ui/blogger-sans-bold-24.tres
- project/src/main/ui/blogger-sans-bold-30.tres
- project/src/main/ui/chat/ChatFrame.tscn
- project/src/main/ui/chat/chat-nametag-panel.gd
- project/src/main/ui/chat/chat-theme.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/nametag-panel.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/restaurant/LayoutContainer.tscn
- project/src/main/world/restaurant/RestaurantNametagPanel.tscn
- project/src/main/world/restaurant/RestaurantView.tscn
- project/src/main/world/restaurant/customer-camera-mover.gd
- project/src/main/world/restaurant/layout-container.gd
- project/src/main/world/restaurant/restaurant-scene.gd
All customers have names now; their names were previously blank.
CreatureQueue and CreatureLoader.random_def now deal with CreatureDef
objects instead of DNA dictionaries. This is necessary because DNA doesn't
include name or fatness data.
Changed instructor name from 'Master Fat' to 'Turbo' for story reasons.
Moved chat_theme_def generation logic from CreatureEditor into
CreatureLoader.
> Added nametags to puzzle mode.

- project/src/main/world/creature/CreatureVisuals.tscn
> Bellybuttons no longer appear on back.

- project/src/main/editor/puzzle/dialogs.gd
Most of these were renamed a few revisions ago but I missed one.
> Fixed /level/ path to /levels/.

- project/project.godot
- project/src/main/puzzle/FoodItem.tscn
- project/src/main/ui/wallpaper/Sticker.tscn
- project/src/main/ui/wallpaper/StickerRow.tscn
- project/src/main/ui/wallpaper/Wallpaper.tscn
- project/src/main/ui/wallpaper/WallpaperBorder.tscn
- project/src/main/ui/wallpaper/sticker-row.gd
- project/src/main/ui/wallpaper/sticker.gd
- project/src/main/ui/wallpaper/wallpaper-border.gd
- project/src/main/ui/wallpaper/wallpaper.gd
Changed the stickers from TextureRects to Sprites. Sprites scale from
their center. Maybe TextureRects can scale from their center too, but it's
more difficult and I couldn't make it work.
Better comments and isolation of crazy TextureRect glitch.
> Variable wallpaper colors. Wallpaper fruits scale and rotate.

- project/src/main/world/creature/creature-visuals.gd
> DNA keys are loaded in the background to avoid frame drops.

- project/src/main/packed-sprite.gd
- project/src/main/resource-cache.gd
PackedSprite parses JSON files which specify the regions for each frame.
This takes about 1-2 milliseconds, which adds up to about 20 milliseconds
when loading a new creature.
These rectangles are now cached in ResourceCache, which accelerates
CreatureVisuals._load_dna() from 20 ms to about 1 ms. This sharply reduces
the jitter when new creatures are loaded during puzzles.
> Reduced jitter by improving PackedSprite performance with caching.

- project/src/main/ui/level-select/level-select-model.gd
> Fix bug where uncleared tutorials had check mark

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/food-items.gd
- project/src/main/world/Overworld.tscn
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/screwport-texrect.gd
> Overworld shadows extend to edges. Hi-res puzzle fruits, shadows.

- project/src/main/world/creature/creature-shadow.gd
Richie's shadow was so small you couldn't see it; the shadows should
change scales based on the creature's fatness.
> Fixed bug where cutscene shadows were too small.

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/PuzzleTimer.tscn
- project/src/main/puzzle/puzzle-timer.gd
This is mostly for rank levels with a goal like 'Finish in X:00 minutes'.
Closes #810.
> Added puzzle timer.

- project/assets/main/locale/en.po
- project/assets/main/locale/messages.pot
- project/project.godot
- project/src/main/miscellaneous-settings.gd
- project/src/main/player-data.gd
- project/src/main/player-save.gd
- project/src/main/puzzle/milestone-hud.gd
- project/src/main/puzzle/results-hud.gd
- project/src/main/ui/SettingsMenu.tscn
- project/src/main/ui/high-score-table.gd
- project/src/main/ui/keybind/settings-keybinds-control.gd
- project/src/main/ui/menu/practice-mode-selector.gd
- project/src/main/ui/settings-language.gd
- project/src/main/ui/settings-tab-container.gd
- project/src/main/ui/settings-touch-fat-finger.gd
- project/src/main/ui/settings-touch-scheme.gd
- project/src/main/ui/volume-setting-control.gd
- pybabel-extract.sh
Added new language settings to settings menu. The player's chosen
language is saved/loaded with their other settings.
Message files include song titles, gameplay hints, and other overlooked phrases,
so that they can be translated.
> Added language menu option. Expanded message files.

- project/project.godot
- project/src/demo/packed-sprite-demo.gd
- project/src/demo/ui/touch/eight-way-demo.gd
- project/src/main/player-save.gd
- project/src/main/puzzle/PuzzleTileMap.tscn
- project/src/main/puzzle/frosting-glob.gd
- project/src/main/puzzle/milestone-hud.gd
- project/src/main/puzzle/piece/next-piece-display.gd
- project/src/main/puzzle/piece/piece-input.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/puzzle-shadow-map.gd
- project/src/main/puzzle/playfield-fx.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/puzzle/puzzle-trace.gd
- project/src/main/puzzle/results-hud.gd
- project/src/main/puzzle/results-label.gd
- project/src/main/puzzle/squish-map.gd
- project/src/main/ui/chat/ChatUi.tscn
- project/src/main/ui/chat/chat-choices.gd
- project/src/main/ui/chat/chat-line-label.gd
- project/src/main/ui/chat/chat-ui.gd
- project/src/main/ui/chat/touch-translator.gd
- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/ui/menu/loading-screen.gd
- project/src/main/world/creature/ear-player.gd
- project/src/main/world/creature/mouth-player.gd
- project/src/main/world/goop-ground.gd
- project/src/main/world/overworld-camera.gd
Renamed 'shadow-map.gd' to 'puzzle-shadow-map.gd' to avoid ambiguity
with other types of shadows. Replaced its hard-coded '../..' node path
with a NodePath.
Delinted minor code issues introduced during localization changes.
> Refactored more repeated get_node references.

- project/src/demo/puzzle/puzzle-demo.gd
- project/src/main/puzzle/ComboCounter.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/combo-counter.gd
- project/src/main/puzzle/milestone-hud.gd
Added particle effect when levelling up. This provides visual feedback for
levelups for players playing without sound.
Closes #819.
Converted combo counter from CPUParticles2D to Particles2D. Particles2D
should be more performant and there's no reason to use the CPU for this.
> Added levelup particles. Combos use Particles2D.

- project/src/main/world/creature/CreatureVisuals.tscn
> Fixed bug where collars were invisible.

- project/src/main/ui/music-popup.gd
The music popup was occasionally showing up with the wrong size.
> Fixed sporatic size problems with music popup

- project/src/main/puzzle/crumb-cluster.gd
- project/src/main/puzzle/food-item.gd
- project/src/main/puzzle/food-items.gd
- project/src/main/world/creature/creature.gd
Fixed bug where sensei gains weight in tutorials.
Fixed 'class instance is gone' errors with food.
Fixed crumb count calculation. Calculation was producing an integer
division warning, and producing incorrect results because of an
unintuitive behavior of rand_range(). var r: int = rand_range(1, 2) does not
return a random number from 1 to 2, it returns 1.
> Bugfixes: sensei weight gain, class instance is gone, crumb count

- project/src/demo/ui/chat/ChatscriptTableDemo.tscn
- project/src/demo/ui/chat/chatscript-table-demo.gd
This list of mood emoticons is likely to expand or change, so the table
generation should be automated.
> Added code to generate a BBCode mood table for the wiki

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/frame-drops-label.gd
Added logic for counting frame drops.
> Cleanup. Frame drop counting logic.

- project/src/demo/music/music-player-demo.gd
- project/src/demo/puzzle/level/rank-mode-demo.gd
- project/src/demo/puzzle/playfield-demo.gd
- project/src/demo/puzzle/puzzle-demo.gd
- project/src/demo/puzzle/results-hud-demo.gd
- project/src/demo/ui/chat/mood-demo.gd
- project/src/demo/ui/touch/eight-way-demo.gd
- project/src/demo/world/letter-shooter-demo.gd
- project/src/main/puzzle/chef-view.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/puzzle/level/other-rules.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/piece/piece-types.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-squish-module.gd
- project/src/main/rolling-backups.gd
- project/src/main/ui/chat/chat-choices.gd
- project/src/main/ui/level-select/hookable-grade-label.gd
- project/src/main/ui/menu/settings-menu.gd
- project/src/main/world/restaurant/RestaurantView.tscn
- project/src/test/puzzle/piece/test-piece-kicks.gd
- project/src/test/puzzle/piece/test-piece-queue.gd
Removed get_node calls in restaurant-view.gd. This script now stores its
dependencies in onready variables which are referenced directly without
calling get_node.
Extracted common 'pieces_by_string' map.
Removed unnecessary parens from match, if, while statements. I added these
inadvertently because I'm accustomed to Java syntax.
> Removed get_node calls. Extracted pieces_by_string. Removed parens.

- project/assets/test/ui/level-select/worlds-priority.json
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/level-select/level-library.gd
- project/src/main/ui/level-select/level-lock.gd
- project/src/main/ui/menu/loading-screen.gd
- project/src/test/ui/chat/test-chat-library.gd
- project/src/test/ui/level-select/test-level-library.gd
Levels and chats can be prioritized if their 'prioritized_if' condition
is met.
> Added 'prioritized_if' flag.

- project/assets/main/puzzle/levels/cutscenes/marsh/lets-all-get-merry-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-bones-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-everyone-000.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-everyone-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-skins-100.chat
- project/assets/main/puzzle/levels/marsh/lets-all-get-merry.json
- project/assets/main/puzzle/levels/marsh/pulling-for-everyone.json
- project/src/demo/ui/chat/mood-demo.gd
- project/src/main/ui/chat/chat-event.gd
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/ui/chat/mood-sprite.gd
- project/src/main/world/creature/EmotePlayer.tscn
- project/src/main/world/creature/emote-player.gd
Added LOVE1_FOREVER emote which permanently changes the character's eyes
into heart eyes until the end of the cutscene. True love is eternal, it
does not last only six seconds.
> New 'pulling_for' cutscenes. Added LOVE1_FOREVER emote.

- delint.sh
- project/assets/main/puzzle/levels/cutscenes/marsh/lets-all-get-merry-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-bones-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-everyone-000.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-everyone-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-skins-100.chat
delint.sh now supports '-c' or '--clean' parameter to fix problems.
Sanitized non-ascii characters in cutscene files.
> Delint supports --clean flag. Fixed non-ascii cutscene characters.

- project/assets/main/puzzle/worlds.json
- project/assets/test/turbofat-1b3c.json
- project/project.godot
- project/src/main/misc-settings.gd
- project/src/main/old-save.gd
- project/src/main/player-data.gd
- project/src/main/player-save.gd
- project/src/main/ui/SettingsMenu.tscn
- project/src/main/ui/cutscene-button.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/level-select/level-library.gd
- project/src/main/ui/level-select/level-lock.gd
- project/src/main/ui/level-select/world-lock.gd
- project/src/test/test-backwards-compatible.gd
Renamed 'locked until' to 'unlocked if' for consistency with other 'say
if', 'available if' settings
Changed 'MiscellaneousSettings' to 'MiscSettings' in code and settings
files. It is still shown as 'miscellaneous' in the user interface.
> LockedUntil -> UnlockedIf, Miscellaneous -> Misc

- delint.sh
Improved delint script so that when executed, it precedes each issue
with a header like 'Functions missing return type:'
Improved performance of delint script. The 'long lines' detection was
taking awhile to run because it executed six recursive grep statements
consecutively. It now runs a single grep statement with a more
complicated expression.
> Delint improvements: headers, grep performance

- project/src/main/ui/overworld-ui.gd
- project/src/main/world/chattable-manager.gd
- project/src/main/world/overworld-world.gd
Fixed bug where CreatureSpawner didn't register chatters, causing their
chat animations to not work
Fixed bug where ChatUi.get_chatter_bounding_box threw errors for chattables
without chat extents
> Bugs: CreatureSpawner chat animations, chattables without chat extents

- project/assets/demo/chat/chat-narrator.chat
- project/project.godot
- project/src/demo/ui/chat/chat-ui-demo.gd
- project/src/main/creature-library.gd
- project/src/main/ui/chat/ChatFrame.tscn
- project/src/main/ui/chat/ChatPanelTween.tscn
- project/src/main/ui/chat/ChatUi.tscn
- project/src/main/ui/chat/NarrationFrame.tscn
- project/src/main/ui/chat/chat-frame.gd
- project/src/main/ui/chat/chat-pop-tween.gd
- project/src/main/ui/chat/chat-squish-tween.gd
- project/src/main/ui/chat/chat-ui.gd
- project/src/main/ui/chat/narration-frame.gd
- project/src/main/ui/chat/narration-line-panel.gd
- project/src/main/ui/chat/narration-style.tres
Cutscene dialog with a speaker of `#narrator#` will be drawn in a unique
style. Aspects of ChatFrame were refactored to allow code reuse in the new
NarrationFrame.
> Added support for narration during chats.

- delint.sh
- project/assets/main/chat/marsh-prologue.chat
- project/assets/main/creatures/primary/diota/hard-times.chat
- project/src/main/puzzle/frame-drops-label.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/resource-cache.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/world/creature/creature-chat-icon-hook.gd
- project/src/main/world/creature/dna-utils.gd
- project/src/main/world/goop-material-mover.gd
- project/src/main/world/overworld-corner-map.gd
Fixed open single quotes and trailing whitespace throughout the project.
> Delint improvements: open single quotes, trailing whitespace

- project/assets/main/puzzle/levels/experiment/002.json
- project/project.godot
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/level-timer-manager.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/puzzle/level/level-timers.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/puzzle/level/level-trigger.gd
Levels can now define timers. Timers can trigger events like rotating a
piece or inserting a line.
> Added level timers. Added level which gradually inserts rows.

- project/src/demo/puzzle/playfield-demo.gd
- project/src/demo/puzzle/puzzle-demo.gd
- project/src/main/editor/puzzle/box-chunk.gd
- project/src/main/puzzle/box-builder.gd
- project/src/main/puzzle/combo-tracker.gd
- project/src/main/puzzle/foods.gd
- project/src/main/puzzle/frosting-glob.gd
- project/src/main/puzzle/frosting-globs.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/piece/piece-type.gd
- project/src/main/puzzle/playfield-fx.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/main/puzzle/tutorial/skill-tally-item.gd
This type is often used in contexts which have no visual component, such
as when calculating the player's score.
> Changed 'color_int' to a more descriptive 'box_type'

- project/project.godot
- project/src/main/editor/puzzle/LevelEditor.tscn
- project/src/main/editor/puzzle/PlayfieldEditor.tscn
- project/src/main/editor/puzzle/editor-json.gd
- project/src/main/editor/puzzle/editor-playfield-nav.gd
- project/src/main/editor/puzzle/level-editor.gd
- project/src/main/editor/puzzle/playfield-editor-control.gd
Extracted PlayfieldEditor from LevelEditor
> Level editor now allows editing of multiple tilesets.

- project/src/main/puzzle/pickups.gd
Renamed pickup methods to match other similar classes.
"set_pickup" is a better name than "add" because the pickups replace other
pickups in the same spot, and it is similar to "set_cell"
"clear" matches other similar classes
"remove" is better as a public method. Nobody uses it yet but its
intuitive behavior could be used in a demo or on a specific level.
Pickups are now spawned in the _ready() method so they will appear
when the puzzle scene first starts up.
> Pickup improvements: renames, pickups at start

- project/src/main/puzzle/level/blocks-during-rules.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/line-inserter.gd
Inserted boxes aren't automatically cleared upon finishing a level.
Added random_tiles_start flag for levels which want more randomness.
> Inserted boxes aren't autocleared. random_tiles_start flag.

- project/src/main/player-data.gd
- project/src/main/puzzle/combo-score-value-label.gd
- project/src/main/puzzle/milestone-hud.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/results-hud.gd
- project/src/main/puzzle/score-value-label.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/string-utils.gd
- project/src/main/ui/high-score-table.gd
- project/src/main/ui/menu/practice-mode-selector.gd
- project/src/test/test-string-utils.gd
Extracted format_money utility method; many places in code were applying
the same process of prepending a yen symbol and inserting commas
Extracted MAX_MONEY constant
> Extracted format_money, MAX_MONEY utilities

- project/src/main/editor/creature/MutateAlleleButton.tscn
- project/src/main/ui/MusicPopup.tscn
- project/src/main/ui/SceneTransitionCover.tscn
- project/src/main/ui/chat/ChatChoiceButton.tscn
- project/src/main/ui/level-select/LevelSelectButton.tscn
- project/src/main/ui/level-select/WorldSelectButton.tscn
- project/src/main/ui/settings/keybind/KeybindCustom.tscn
- project/src/main/ui/wallpaper/Wallpaper.tscn
- project/src/main/world/CreatureSpawner.tscn
- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldUi.tscn
- project/src/main/world/Spawn.tscn
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/environment/ButtercupSign.tscn
- project/src/main/world/environment/ForLeaseSign.tscn
These minor changes appear to be the result of the Godot 3.4 upgrade
> Reformatted .tscn files: groups, others

- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/ui/level-select/career-level-library.gd
- project/src/main/ui/level-select/grade-labels.gd
- project/src/main/ui/level-select/level-description-panel.gd
- project/src/main/ui/level-select/level-info-panel.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-data.gd
- project/src/main/world/career-map.gd
Fixed bugs in career mode's 'don't repeat levels' logic
> Career mode lets the player choose a level.

- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-distance.gd
Fixed references to nonexistent Utils.comma_sep method
Fixed CareerMap UI anchors so that the settings button stays within the panel
> Bug fixes: Utils.comma_sep, map ui anchors

- project/project.godot
- project/src/main/world/Overworld.tscn
- project/src/main/world/creature-spawner.gd
- project/src/main/world/obstacle-manager.gd
- project/src/main/world/obstacle-spawner.gd
- project/src/main/world/overworld-world.gd
Both the overworld and career map will need to add obstacles and creatures, so
this common functionality should be shared with a script.
> Extracted ObstacleManager from OverworldUi.

- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-map.gd
- project/src/main/world/career-world.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/obstacle-manager.gd
Minor camera adjustments to make customers/player fit better in the
frame
> Customers appear on career map

- project/src/main/ui/music-popup-tween.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-map.gd
Added check for MusicPopupTween's idle_frame listener getting triggered
twice. This happened once causing a crash.
> Added music popup to career mode.

- project/src/main/ui/career/career-distance-label.gd
- project/src/main/world/CareerMap.tscn
Replaced grey background with undecorated outlined font.
> Changed appearance of career mode's start level buttons.

- project/src/main/puzzle/star-seeds.gd
Fixed bug where newly inserted rows didn't include star seeds. They still gave
the appropriate point reward, but didn't generate fruit.
> Added star seeds for inserted lines.

- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/level/phase-conditions.gd
- project/src/main/puzzle/playfield.gd
- project/src/test/puzzle/level/test-phase-conditions.gd
This is useful for levels which want to insert rows every few pieces. It
uses a simple pattern expression algorithm, although we can beef this
out for more complex levels.
> Added 'after_piece_written' phase condition.

- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
Tutorial easter egg was no longer changing to the silly bonus screen.
> Fixed tutorial easter egg

- project/src/main/ui/career/CareerWin.tscn
- project/src/main/ui/career/menu-world-mover.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/OverworldWalk.tscn
Colored the end-of-career report in rainbow colors to make it prettier.
> Player, sensei appear on end-of-career report. Rainbow chalk.

- project/src/main/career-data.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/step-meter.gd
- project/src/main/ui/MoneyLabel.tscn
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-world.gd
- project/src/main/world/obstacle-manager.gd
- project/src/main/world/obstacle-spawner.gd
Money icon is in a control with a nested sprite to avoid UI issues with
scaled controls.
Added ObstacleManager methods for adding obstacles.
Consolidated rank milestone logic from puzzle.gd and step-meter.gd into
career-data.gd. This includes color data which is a questionable choice
as it's UI specific, but this way is less error prone than having a
separate array for UI data.
> Refactor: Money icon, add_obstacle, rank milestones

- project/assets/main/chat/career/general-00-0.chat
- project/assets/main/chat/career/general-00-1.chat
- project/src/main/career-data.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/world/career-map.gd
Cutscenes play after the 3rd and 6th level. There are currently only two
cutscenes, it picks a random one.
> Added cutscene logic to career mode.

- project/src/main/world/career-map.gd
Even just for this release, I don't want players to have to watch the
same two cutscenes every time they play. It's too tedious.
> Skip career cutscenes if you've seen them.

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/puzzle.gd
Added a cheat code to quickly finish the current level. This makes your
score absurdly bad/slow so that it won't affect your high scores,
hopefully.
> Added new cheat code, 'finish'

- project/src/main/ui/career/CareerWin.tscn
- project/src/main/world/ChatIcons.tscn
- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/OverworldWalk.tscn
- project/src/main/world/creature-spawner.gd
- project/src/main/world/environment/MarshWinEnvironment.tscn
- project/src/main/world/obstacle-spawner.gd
Removed unused ChatIcons node from OverworldWalk
> Extracted ChatIcons, MarshWinEnvironment

- project/OverworldWalkEnvironment.tscn
- project/project.godot
- project/src/main/ui/career/CareerWin.tscn
- project/src/main/ui/career/career-win-world.gd
- project/src/main/ui/career/career-win.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/OverworldWalk.tscn
- project/src/main/world/career-world.gd
- project/src/main/world/chat-icons.gd
- project/src/main/world/creature-spawner.gd
- project/src/main/world/environment/MarshEnvironment.tscn
- project/src/main/world/environment/MarshWinEnvironment.tscn
- project/src/main/world/environment/OverworldEnvironment.tscn
- project/src/main/world/environment/OverworldIndoorsEnvironment.tscn
- project/src/main/world/environment/overworld-environment.gd
- project/src/main/world/obstacle-spawner.gd
- project/src/main/world/overworld-walk-world.gd
- project/src/main/world/overworld-world.gd
Instead of ObstacleManager adding obstacles and creatures to an
environment, Environment nodes now add these to themselves. This makes
more sense than having two nodes.
> Replaced ObstacleManager with Environments.

- project/src/main/career-data.gd
- project/src/main/puzzle/frame-drops-label.gd
- project/src/main/puzzle/puzzle-trace.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/career/career-map-ui.gd
- project/src/main/ui/career/career-time-label.gd
- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/fps-label.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-map.gd
Added/updated comments to other cheat codes. These comments mirror
what's currently in https://github.com/Poobslag/turbofat/wiki/cheats
> Added new 'cutsio' cheat code for career cutscenes.

- project/assets/main/chat/career/marsh/30-a-end.chat
- project/assets/main/chat/career/marsh/30-b-end.chat
- project/assets/main/chat/career/marsh/30-c-end.chat
- project/assets/main/chat/career/marsh/50-b-end.chat
- project/assets/main/chat/career/marsh/50-c-end.chat
- project/assets/main/chat/career/marsh/60-end.chat
Pruned unreachable/nonsensical branches. Fixed say_if, link_if conditions to
refer to career chat keys.
> Delinted career cutscenes.

- project/assets/main/puzzle/career-worlds.json
- project/src/main/ui/level-select/career-level-library.gd
- project/src/main/ui/level-select/career-level.gd
- project/src/main/world/career-map.gd
- project/src/test/ui/level-select/test-career-level-library.gd
Career levels unlock for story reasons, and for difficulty reasons.
Skins's levels only unlock after you get annoyed with him for not
improving; earlier levels all use the same gimmick.
> Career levels unlock.

- project/project.godot
- project/src/main/ui/career/CareerWin.tscn
- project/src/main/world/FreeRoam.tscn
- project/src/main/world/career-world.gd
- project/src/main/world/chat-icons.gd
- project/src/main/world/chat-letters.gd
- project/src/main/world/cutscene-world.gd
- project/src/main/world/free-roam-world.gd
- project/src/main/world/overworld-buttons.gd
- project/src/main/world/overworld-touch-buttons.gd
- project/src/main/world/overworld-world.gd
This eliminates some copy/paste code between CareerWorld, CutsceneWorld,
FreeRoamWorld and CareerWinWorld
Changed some OverworldUi onready variables to local variables. Many
places only needed it in _ready()
> Extracted new OverworldWorld class. OverworldUi references.

- project/src/main/string-utils.gd
- project/src/test/test-string-utils.gd
This class has grown very large and it's hard to find things.
Alphabetical order makes it easier.
> Reordered string-utils constants and methods.

- project/src/main/creature-library.gd
- project/src/main/music/music-player.gd
- project/src/main/puzzle/piece/ghost-mover.gd
- project/src/main/puzzle/piece/next-piece.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/tutorial/tutorial-hud.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/level-select/hookable-grade-label.gd
- project/src/main/world/chattable-manager.gd
- project/src/main/world/creature/creature-animations.gd
- project/src/main/world/creature/creature-packed-sprite.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/sprint.gd
- project/src/main/world/creature/tail-player.gd
- project/src/main/world/cutscene-queue.gd
- project/src/main/world/ground-map-indoors.gd
- project/src/main/world/obstacle-map-indoors.gd
- project/src/main/world/overworld-corner-map.gd
Comment tweaks.
HookableGradeLabel uses onready variables.
CreatureAnimations.play_movement_animation() now only requires a single
parameter.
> Comments, delint, play_movement_animation() fix.

- project/gut_editor_config.json.template
- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/piece/piece-type.gd
- project/src/main/puzzle/piece/piece-types.gd
- project/src/test/puzzle/piece/test-piece-kicks-qp.gd
P and Q can now flip two different ways in tight hallways. Pieces can
now support multiple flip kicks, instead of only one like before.
> Improved P and Q flip kicks. Multiple flips kicks per piece.

- project/src/main/ui/level-select/LevelSelectButton.tscn
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-camera.gd
- project/src/main/world/career-world.gd
- project/src/main/world/environment/MileMarker.tscn
'cambra' cheat affects the career map and lets you move the camera
freely. This is useful for verifying the appearance of different parts
of the map.
'moveme' cheat affects the career map and lets you move the player along
the path. This is useful for verifying that objects on the map don't
interfere with the creatures.
> New cheats: cambra, moveme

- project/src/main/puzzle/piece/piece-types.gd
- project/src/test/puzzle/piece/test-piece-kicks-u.gd
U piece can now flip around its middle section
uu      uu
:u: -> :u:
uu      uu
> Added 'spine flip' for U piece.

- project/src/main/world/creature/Ear11Player.tscn
- project/src/main/world/creature/Ear12Player.tscn
These ears didn't wiggle correctly, it looks like their animations were
copied from another animation but never modified
> Fixed animations for orc ears, goblin ears

- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/pan/frying-pans-ui.gd
- project/src/main/puzzle/piece/puzzle-corner-map.gd
- project/src/main/puzzle/piece/puzzle-shadow-map.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/world/environment/frosted-overworld-tiler.gd
- project/src/main/world/environment/grass-overworld-tiler.gd
- project/src/main/world/environment/invisible-obstacle-tiler.gd
- project/src/main/world/environment/kitchen-obstacle-tiler.gd
- project/src/main/world/environment/obstacle-map-shadows.gd
- project/src/main/world/environment/pebble-overworld-tiler.gd
- project/src/main/world/ground-map-indoors.gd
Replaced set_cell/get_cell references with set_cellv/get_cellv for
brevity
> Refactoring: set_cellv, get_cellv

- project/project.godot
- project/src/demo/NameGeneratorDemo.tscn
- project/src/demo/name-generator-demo.gd
- project/src/demo/puzzle/PlayfieldDemo.tscn
- project/src/demo/puzzle/ResultsHudDemo.tscn
- project/src/demo/puzzle/level/LevelRankDemo.tscn
- project/src/demo/puzzle/level/RankModeDemo.tscn
- project/src/demo/puzzle/level/level-rank-demo.gd
- project/src/demo/puzzle/level/rank-mode-demo.gd
- project/src/demo/puzzle/playfield-demo.gd
- project/src/demo/puzzle/results-hud-demo.gd
- project/src/demo/ui/chat/ChatFrameDemo.tscn
- project/src/demo/ui/chat/ChatUiDemo.tscn
- project/src/demo/ui/chat/ChatscriptTableDemo.tscn
- project/src/demo/ui/chat/chat-frame-demo.gd
- project/src/demo/ui/chat/chat-ui-demo.gd
- project/src/demo/ui/chat/chatscript-table-demo.gd
- project/src/demo/world/CutsceneDemo.tscn
- project/src/demo/world/creature/CreaturePaletteDemo.tscn
- project/src/demo/world/creature/creature-palette-demo.gd
- project/src/demo/world/cutscene-demo.gd
Most demos already extended from nodes. There's no need for them to be
controls since they don't use any properties from controls such as
position or size.
> All demos extend from Node, not Control.

- project/assets/test/ui/chat/cutscene-full.chat
- project/assets/test/ui/level-select/career-worlds-simple.json
- project/src/main/string-utils.gd
- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/ui/level-select/career-level-library.gd
- project/src/main/ui/level-select/career-level.gd
- project/src/main/ui/level-select/career-region.gd
- project/src/main/ui/level-select/level-lock.gd
- project/src/main/world/career-map.gd
- project/src/main/world/career-world.gd
- project/src/main/world/level-posse.gd
- project/src/test/ui/chat/test-chatscript-parser.gd
- project/src/test/ui/level-select/test-career-level-library.gd
Customers and chefs appear on the career map and then appear in the
puzzles as well. Observers appear on the career map but do not appear in
the puzzles -- they can be things like managers, health inspectors or teachers.
> Levels/regions can have 'observers'.

- project/src/main/career-data.gd
- project/src/main/ui/career/CareerWin.tscn
- project/src/main/ui/career/career-win-world.gd
- project/src/main/ui/career/career-win.gd
- project/src/main/ui/level-select/career-region.gd
- project/src/main/world/career-world.gd
For some regions such as the first region, the sensei will not accompany
the player. They will not appear on the career overworld or the victory
screen.
> Added support for new 'sensei_absent' flag in career-worlds.gd.

- project/src/test/puzzle/piece/test-piece-kicks-jl.gd
Two different kicks were classified as 'snack kicks' in the J/L piece
kicks.
> Split snack kick/tip kick

- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/dna-utils.gd
- project/src/test/world/creature/test-dna-utils.gd
CreatureDef.random_def() can now determine whether secondary creatures
are "squirrel-like" and will return squirrel-like secondary creatures in Lemony
Thickets.
> Lemony Thickets puzzles feature random secondary squirrels.

- project/src/main/player-data.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/world/career-world.gd
Extracted PlayerData.random_creature_def() function. This avoids some
copy/paste code in different places which all wanted to obtain a random
creature for a region.
> Refactor: PlayerData.random_creature_def()

- project/src/demo/world/creature/palette-editor-tab.gd
- project/src/main/puzzle/piece-sfx.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/chat/chat-ui.gd
- project/src/main/world/career-map.gd
'_on_foo()' functions should always be last. A few scripts had them out
of order.
> Reorder signal methods.

- project/src/main/world/creature/creature-def.gd
CreatureDef.from_json_dict logic now shares the same logic as
CreatureDef.from_json_path, populating empty names and properties.
> Expanded default creature def logic

- project/assets/main/puzzle/career-worlds.json
- project/assets/test/ui/level-select/career-worlds-simple.json
- project/src/main/career/career-region.gd
- project/src/test/ui/level-select/test-career-level-library.gd
Region IDs are potentially useful for identifying regions in source code and
save data.
> Added region IDs.

- project/assets/main/puzzle/other-regions.json
- project/src/main/ui/level-select/other-region.gd
- project/src/main/ui/menu/TutorialMenu.tscn
- project/src/main/ui/menu/paged-level-buttons.gd
- project/src/main/ui/menu/paged-region-buttons.gd
- project/src/main/ui/menu/region-submenu.gd
- project/src/main/ui/menu/tutorial-menu.gd
- project/src/test/ui/level-select/test-other-level-library.gd
The scrollable panel is going away soon, it is only used in FreeRoam
mode. There are also not enough tutorials for it to make sense.
> Tutorial now uses paged panel instead of scrollable panel.

- project/src/main/world/chattable-manager.gd
Instead of redundant player/sensei fields, ChattableManager
retrieves these values from _creatures_by_id
> ChattableManager no longer stores player/sensei

- project/src/test/puzzle/piece/ascii-piece-analyzer.gd
- project/src/test/puzzle/piece/test-piece-kicks.gd
Tests other than kick tests want an easy way to create ActivePieces
using ascii grids.
> Extracted AsciiPieceAnalyzer.

- project/src/main/puzzle/BurstAccent.tscn
- project/src/main/puzzle/ComboBurst.tscn
- project/src/main/puzzle/burst-accent.gd
- project/src/main/puzzle/food-item.gd
Combo accents grow and shrink slightly. I experimented with having them
squash/stretch in but it looked too strange, I like this more.
Extracted BurstAccent from ComboBurst. This is reusable for an upcoming
burst scene.
> Combo accents pulse slightly. Extracted BurstAccent.

- project/src/main/settings/volume-settings.gd
Some people were reporting that the game was too loud. It's a little
quieter now. If this is still too loud, we can reduce the default volume
from 70% to 50% -- but it seems in line with other games.
> Reduce volume. Per-bus volume limits.

- project/src/main/career/career-data.gd
- project/src/main/creature-library.gd
- project/src/main/ui/chat/chat-choices.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/world/environment/turbo-fat-restaurant.gd
- project/src/main/world/puzzle-world.gd
Fat Sensei's name now changes after the player plays through the first
'call me fat sensei' cutscene.
Extracted is_restaurant_decorated utility method instead of referring to
a CareerData constant.
> Fat Sensei changes name from 'Turbo' to 'Fat Sensei'

- project/src/main/ui/menu/LoadingPiece.tscn
- project/src/main/ui/menu/loading-piece.gd
Pieces now burst into one of eight colors and emit particles, [as suggested by reddit user /u/jdyerjdyer](https://www.reddit.com/r/godot/comments/x37y13/the_unnecessarily_fancy_loading_screen_i_designed/imp4omw/)
> Loading screen now colors pieces on the loading bar

- project/addons/gut/gut_plugin.gd
Fix for a bug where Gut 7.2.0 introduced an ObjectDB leak
https://github.com/bitwes/Gut/issues/415
> Workaround for Gut issue #415

- project/src/main/breadcrumb.gd
- project/src/main/career/career-data.gd
- project/src/main/editor/creature/tweak-name-row.gd
- project/src/main/editor/puzzle/editor-playfield.gd
- project/src/main/editor/puzzle/piece-level-chunk-control.gd
- project/src/main/editor/puzzle/properties-editor-control.gd
- project/src/main/global.gd
- project/src/main/puzzle/bursts.gd
- project/src/main/puzzle/duration-calculator.gd
- project/src/main/puzzle/level/level-settings-upgrader.gd
- project/src/main/puzzle/milestone-hud.gd
- project/src/main/puzzle/piece/next-piece-displays.gd
- project/src/main/puzzle/piece/tech-move-detector.gd
- project/src/main/puzzle/puzzle-touch-buttons.gd
- project/src/main/puzzle/tech-move-burst.gd
- project/src/main/save-item-upgrader.gd
- project/src/main/settings/misc-settings.gd
- project/src/main/settings/volume-settings.gd
- project/src/main/string-utils.gd
- project/src/main/ui/cheat-code-detector.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/settings/settings-dialogs.gd
- project/src/main/ui/settings/settings-menu.gd
- project/src/main/ui/settings/settings-open-user-folder.gd
- project/src/main/utils.gd
- project/src/main/world/creature/player.gd
- project/src/main/world/creature/sensei.gd
- project/src/test/puzzle/piece/test-piece-kicks-t.gd
Changed 'user' to 'player' where it made sense. A programmer or
developer is a 'user' but someone playing our game is always a 'player'
Changed 'circular reference' to 'cyclic reference' for consistency with
Godot's on terminology
Changed 't-piece' to 'T piece'
> Comment tweaks; 'user', 'circular ref', 't-piece'

- delint.sh
- project/src/demo/world/restaurant/restaurant-puzzle-scene-demo.gd
- project/src/demo/world/restaurant/restaurant-view-demo.gd
- project/src/main/data/rolling-backups.gd
- project/src/main/editor/creature/creature-editor-nametags.gd
- project/src/main/puzzle/combo-tracker.gd
- project/src/main/puzzle/piece/piece-squisher.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/ui/touch/eight-way.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/creatures.gd
- project/src/main/world/creature/mouth-player.gd
- project/src/main/world/overworld-exit.gd
Added const expressions to delint as well
> Refactor: Static type const expressions

- project/src/main/puzzle/level/level-history.gd
- project/src/main/puzzle/rank-result.gd
- project/src/main/ui/level-select/hookable-level-grade-label.gd
- project/src/main/ui/menu/paged-level-buttons.gd
- project/src/main/ui/menu/paged-region-buttons.gd
- project/src/main/ui/menu/region-info-panel.gd
Extracted new LevelHistory.best_overall_rank method. This functionality was duplicated in a few places which wanted to calculate the player's best performance on a level.
Extracted new LevelHistory.is_level_success method. This functionalioty was duplicated in a few places which wanted to determine if the player had met the success criteria for a level.
> LevelHistory: best_overall_rank, is_level_success

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/piece-sfx.gd
- project/src/main/puzzle/piece/PieceManager.tscn
- project/src/main/puzzle/piece/piece-dropper.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/piece-mover.gd
- project/src/main/puzzle/piece/piece-physics.gd
- project/src/main/puzzle/piece/piece-rotator.gd
- project/src/main/puzzle/piece/piece-squisher.gd
- project/src/main/puzzle/piece/tech-move-detector.gd
- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
- project/src/main/puzzle/tutorial/tutorial-cakes-module.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-squish-module.gd
Most signal recipients do not use these parameters, but a few such as TechMoveDetector and PieceSfx can use these parameters.
> Piece signals accept an ActivePiece parameter.

- project/assets/main/puzzle/levels/rank/10d.json
- project/assets/main/puzzle/levels/rank/1d.json
- project/assets/main/puzzle/levels/rank/1k.json
- project/assets/main/puzzle/levels/rank/2d.json
- project/assets/main/puzzle/levels/rank/2k.json
- project/assets/main/puzzle/levels/rank/3d.json
- project/assets/main/puzzle/levels/rank/3k.json
- project/assets/main/puzzle/levels/rank/4d.json
- project/assets/main/puzzle/levels/rank/4k.json
- project/assets/main/puzzle/levels/rank/5d.json
- project/assets/main/puzzle/levels/rank/5k.json
- project/assets/main/puzzle/levels/rank/6d.json
- project/assets/main/puzzle/levels/rank/6k.json
- project/assets/main/puzzle/levels/rank/7d.json
- project/assets/main/puzzle/levels/rank/7k.json
- project/assets/main/puzzle/levels/rank/8d.json
- project/assets/main/puzzle/levels/rank/9d.json
- project/assets/main/puzzle/levels/rank/m.json
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/ui/menu/paged-level-buttons.gd
Levels can now define a 'color' json property which is parsed and determines the button color. This is a human readable word like 'red' so that we can change the UI's colors without needing to change all of the JSON files to use new hex codes.
> Rank button colors are no longer hard-coded.

- project/src/main/puzzle/GoopGlob.tscn
- project/src/main/puzzle/HudFlash.tscn
- project/src/main/puzzle/LeafPoof.tscn
- project/src/main/puzzle/Pickup.tscn
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/food-item.gd
- project/src/main/puzzle/goop-glob.gd
- project/src/main/puzzle/hud-flash.gd
- project/src/main/puzzle/leaf-poof.gd
- project/src/main/puzzle/pickup.gd
- project/src/main/puzzle/playfield-fx.gd
- project/src/main/puzzle/puzzle-money-hud.gd
- project/src/main/puzzle/tutorial/SkillTallyItem.tscn
- project/src/main/puzzle/tutorial/skill-tally-item.gd
- project/src/main/ui/MoneyLabel.tscn
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-copy-save-data.gd
- project/src/main/utils/utils.gd
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/EmotePlayer.tscn
- project/src/main/world/creature/creature-animations.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/emote-player.gd
- project/src/main/world/environment/ripple-sprite.gd
Reverts Poobslag/turbofat#1654
> Revert "Rewrote tweens to use Godot 3.5 syntax."

- project/src/main/puzzle/piece/piece-types.gd
I have gone back and forth many times, but I am flipping the U piece again for finesse consistency.
All other pieces including the P and Q pieces shift right when rotated clockwise, and left when rotated counterclockwise. The U piece is inconsistent which makes it unintuitive for finesse. You have to DAS right and rotate clockwise to shift it away from the wall, which I think experienced players will hate.
> Flipped U piece again.

- project/src/main/puzzle/puzzle-tile-map.gd
build_box now sets its autotile coordinate correctly the first time, instead of setting it to 15 and then unsetting all the other directions.
disconnect_block will now only try to disconnect piece/box cells. It will not try to disconnect veggie cells.
Fixed some places that referenced ints to use constants instead.
> PuzzleTileMap refactoring: build_box/disconnect

- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/level/phase-conditions.gd
- project/src/main/puzzle/pickups.gd
Fixed NPE for levels with pickups
Fixed references to 'after_line_cleared' phase in comments
> Release v0.5000 fixes; pickup NPE, after_line_cleared

- project/src/main/puzzle/level/level-settings.gd
- project/src/main/ui/menu/practice-menu.gd
Practice menu now checks if the region/level exist. If they don't, it default to Marathon/Normal.
> Bug: Practice menu crashes with bad region/level

- project/assets/main/puzzle/career-regions.json
- project/src/demo/toolkit/fix-levels-button.gd
ReleaseToolkit now alphabetizes career levels.
> Alphabetized career levels.

- project/src/main/puzzle/line-clearer.gd
Changed _line_dicts from a field to a method. This is more resilient in case someone does something like '_line_filled_age = {}'
Extracted _line_arrays() method to avoid copy/paste code.
> Refactored LineClearer line_dicts, line_arrays

- project/assets/main/locale/es.po
- project/src/main/career/career-region.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/puzzle/other-region.gd
> Localize level names/descriptions, region names/descriptions.

- project/assets/demo/puzzle/levels/experiment.json
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/PuzzleTileMap.tscn
- project/src/main/puzzle/piece/ghost-piece-shadow-map.gd
- project/src/main/puzzle/piece/puzzle-shadow-map.gd
- project/src/main/puzzle/puzzle.gd
The ghost piece being drawn as a shadow made it very hard to see -- especially on mobile devices.
Closes #1748.
> Ghost piece is a translucent piece, not a shadow

- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- pybabel-extract.sh
Localized dialog messages to spanish.
Closes #1781.
> Added localization support for dialogs.

- project/src/main/puzzle/puzzle-state.gd
Without this penalty, it's strange that a player could quit right before topping out and be slightly rewarded
> Giving up now adds a -¥100 score penalty

- project/assets/demo/puzzle/levels/experiment.json
- project/assets/main/keybind/default-custom.json
- project/assets/main/keybind/guideline.json
- project/assets/main/keybind/wasd.json
- project/project.godot
- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/settings/SettingsMenu.tscn
This key defaults to 'R' but can be configured through the settings menu. It lets the player immediately retry any Career, Practice, or Tutorial level. Retrying a career level still only ever counts their first attempt, but it lets them practice it.
> Added new 'Retry' key.

- project/project.godot
- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/level/gameplay-difficulty-adjustments.gd
- project/src/main/puzzle/level/milestone.gd
- project/src/main/puzzle/milestone-hud.gd
- project/src/main/puzzle/milestone-manager.gd
- project/src/main/puzzle/piece/piece-speeds.gd
- project/src/main/puzzle/puzzle.gd
- project/src/test/puzzle/level/test-gameplay-difficulty-adjustments.gd
When the player plays at slow speeds, we make milestones easier to reach.
Closes #1753.
> Milestones are adjusted with piece speed.

- project/src/main/settings/gameplay-settings.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/reset-gameplay-button.gd
- project/src/main/ui/settings/settings-gameplay-speed.gd
- project/src/main/ui/settings/settings-ghost-piece.gd
- project/src/main/ui/settings/settings-line-piece.gd
- project/src/main/ui/settings/settings-lock-cancel.gd
Added Gameplay settings into a scroll panel. It's getting tall enough to need one.
> Added 'Reset Gameplay To Defaults' button

- project/project.godot
- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/piece-display.gd
- project/src/main/puzzle/piece/next-piece-display.gd
PieceDisplay does not inspect the piece queue directly. It is generic enough to be reused for our upcoming hold piece logic.
> Extracted PieceDisplay script from NextPieceDisplay.

- project/assets/main/locale/es.po
These were not translated by a spanish speaker so they have mistakes. I also did not localize the 'Slowestest/Fastest' phrases because it is the kind of spanish joke that I'm not clever enough to come up with.
> Localize cheat changes into spanish

- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/line-filler.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/top-out-tracker.gd
LineClearer, LineFiller and PieceManager all wanted to know when the player started topping out and finished topping out. This is now a signal they can listen for.
> Extracted PuzzleState.topping_out field, signals

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/level/phase-conditions.gd
Multiple phase conditions utilize 'MAX_PIECE_INDEX', these are now combined into one constant.
> Refactor: Consolidated MAX_PIECE_INDEX, MAX_LINE_INDEX

- project/src/main/career/ui/CareerRegionSelectMenu.tscn
- project/src/main/editor/puzzle/LevelEditor.tscn
- project/src/main/editor/puzzle/PlayfieldEditor.tscn
- project/src/main/editor/puzzle/dialogs.gd
- project/src/main/editor/puzzle/editor-pickups.gd
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/PuzzleTileMap.tscn
- project/src/main/puzzle/critter/critters.gd
- project/src/main/puzzle/piece/puzzle-shadow-map.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/main/ui/menu/PracticeMenu.tscn
- project/src/main/ui/menu/career-region-select-menu.gd
- project/src/main/ui/menu/practice-menu.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-copy-save-data.gd
- project/src/main/ui/settings/settings-dialogs.gd
https://github.com/Poobslag/turbofat/wiki/guidelines
According to our coding conventions, constants and export variables should always be public (not prefixed with an underscore)
> Fixed private export variables.

- project/project.godot
- project/src/demo/career/ui/progress-board-demo.gd
- project/src/main/career/career-calendar.gd
- project/src/main/career/career-cutscene-library.gd
- project/src/main/career/career-data.gd
- project/src/main/career/career-flow.gd
- project/src/main/career/career-level-library.gd
- project/src/main/career/career-region.gd
- project/src/main/career/careers.gd
- project/src/main/career/ui/career-map-ui.gd
- project/src/main/career/ui/career-win-world.gd
- project/src/main/career/ui/career-win.gd
- project/src/main/career/ui/map-row-updater.gd
- project/src/main/career/ui/player-landmark.gd
- project/src/main/career/ui/progress-board-clock.gd
- project/src/main/career/ui/progress-board-player.gd
- project/src/main/career/ui/progress-board.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/step-meter.gd
- project/src/main/ui/menu/career-region-select-menu.gd
- project/src/main/world/career-map.gd
- project/src/test/career/test-career-level-library.gd
- project/src/test/world/test-career-data.gd
Extracted new 'Careers' constants class.
Fixed cyclic reference between CareerData and CareerRegion which was introduced in 8c0a0450
> Careers. Resolved CareerData/CareerRegion cyclic reference.

- project/project.godot
- project/src/main/puzzle/PuzzleState.tscn
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/utils/TimerGroup.tscn
- project/src/main/utils/timer-group.gd
- project/src/main/world/environment/restaurant/RestaurantView.tscn
This reusable class centralizes the idea of having a group of temporary timers which we can clean up as necessary.
> Extracted new 'TimerGroup' scene.

- project/src/demo/toolkit/fix-levels-button.gd
It's easy to accidentally make levels with pickups and forget to show the pickup rank, or make levels with unbreakable combos and forget to hide the combo rank. ReleaseToolkit now reports these kinds of oversights, if they're simple enough for it to detect them.
> ReleaseToolkit detects 'show rank' anomalies

- project/src/demo/ui/FontFitLabelDemo.tscn
- project/src/demo/ui/font-fit-label-demo.gd
- project/src/main/ui/font-fit-label.gd
- project/src/main/ui/rect-fit-label.gd
FontFitLabel and RectFitLabel now reference Label's 'line_spacing' value instead of hard-coding the magic number '3'.
> FontFitLabel, RectFitLabel now leverage line_spacing

- project/src/demo/chat/ui/mood-demo.gd
MoodDemo accepts a CreaturePath property, so you can demo a specific creature.
> MoodDemo accepts a CreaturePath property

- project/src/demo/chat/ui/ChatUiDemo.tscn
- project/src/demo/chat/ui/chat-ui-demo.gd
ChatUi requires an OverworldUi to work correctly.
> Fixed broken ChatUiDemo.

- project/src/main/chat/tracery.gd
- project/src/test/chat/test-tracery.gd
This will be used in some Poki Desert cutscenes.
> Restored 'capitalize' function for Tracery.

- project/assets/main/chat/career/poki/010-a-end.chat
- project/assets/main/chat/career/poki/010-a.chat
- project/assets/main/chat/career/poki/010-b-end.chat
- project/assets/main/chat/career/poki/010-b.chat
- project/assets/main/chat/career/poki/010-c-end.chat
- project/assets/main/chat/career/poki/020-a.chat
- project/assets/main/chat/career/poki/020-b.chat
- project/assets/main/chat/career/poki/030-a-end.chat
- project/assets/main/chat/career/poki/030-b-end.chat
- project/assets/main/chat/career/poki/030-b.chat
- project/assets/main/chat/career/poki/030-c.chat
- project/assets/main/chat/career/poki/100.chat
- project/assets/main/chat/career/poki/110-end.chat
- project/assets/main/chat/career/poki/120.chat
- project/assets/main/chat/career/poki/boss-level-end.chat
- project/assets/main/chat/career/poki/boss-level.chat
- project/assets/main/chat/career/poki/epilogue.chat
- project/assets/main/chat/career/poki/prologue.chat
- project/assets/main/creatures/nonstory/miteby.json
- project/assets/main/creatures/nonstory/trudy.json
- project/assets/main/puzzle/career-regions.json
Cutscenes appear in career mode. Some characters such as Miteby and Trudy are introduced to the restaurant in their first cutscene, so I gave them a 'customer_if' flag.
> Created cutscenes for Poki Desert.

- project/src/main/puzzle/level/current-level.gd
- project/src/main/world/career-map.gd
- project/src/test/puzzle/level/test-current-level.gd
> Intro/boss level filler creatures appear during puzzles.

- project/src/main/utils/utils.gd
- project/src/test/utils/test-utils.gd
I wrote this method during the Night Onion logic, and ended up not needing it. I'd still like to include it for now, as it's a standard array utility.
> Added new Utils.disjunction() method.

- project/src/main/puzzle/level/phase-conditions.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/test/puzzle/level/test-phase-conditions.gd
This allows for effects that trigger when the player breaks a score threshold.
> New line_cleared score condition.

- project/src/main/career/career-cutscene-library.gd
- project/src/main/career/ui/landmark-container.gd
- project/src/main/chat/chat-tree.gd
- project/src/main/music/music-player.gd
- project/src/main/puzzle/critter/carrots.gd
- project/src/main/puzzle/pan/frying-pans-ui.gd
- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/tutorial/tutorial-messages.gd
- project/src/main/utils/resource-cache.gd
- project/src/main/world/cutscene-queue.gd
- project/src/main/world/puzzle-world.gd
- project/src/test/puzzle/level/test-current-level.gd
Differen places were calling queue.push_back() or queue.append(), including PieceQueue which was alternating between both. I don't really care which we use, but the inconsistency was bothering me
> push_back() -> append()

- project/src/demo/world/environment/restaurant/restaurant-puzzle-scene-demo.gd
- project/src/demo/world/environment/restaurant/restaurant-view-demo.gd
- project/src/main/puzzle/food-items.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/world/environment/restaurant/RestaurantView.tscn
- project/src/main/world/environment/restaurant/customer-camera-mover.gd
- project/src/main/world/environment/restaurant/restaurant-puzzle-scene.gd
'customer_index' is more specific. There are creatures in the scene that are not customers (the chef).
> Renamed restaurant creature_index -> customer_index

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- pybabel-extract.sh
es.po had not been updated in two years. I updated it, and modified pybabel-extract.sh to automatically bring es.po up to date.
> Brought es.po up-to-date.

- project/src/main/puzzle/leaf-poofs.gd
- project/src/main/puzzle/night/night-star-poofs.gd
Moved logic out of listener method. Simplified 'poof_count' logic to avoid needing a 'match' statement.
> Refactored 'leaf poof' logic.

- project/assets/demo/puzzle/levels/experiment.json
- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/piece/piece-types.gd
- project/src/test/puzzle/piece/test-piece-kicks-domino.gd
Unlike the I piece which pivots around an axis, domino pieces just have a leftward/downward bias. This behavior was adapted from Dr Mario.
> Added domino pieces.

- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/piece/piece-type.gd
- project/src/test/puzzle/piece/test-piece-type.gd
Added unit test for PieceType.
> Improved safety of PieceType.get_box_type().

- project/src/main/puzzle/piece/piece-type.gd
- project/src/test/puzzle/piece/test-piece-type.gd
This functionality is needed by more complex piece manipulations required for sharks.
> New PieceType functionality: copy_from(), set_box_type()

- project/src/main/puzzle/piece/piece-manager.gd
Sharks add the functionality of being able to eat an entire piece, which requires us to advance PieceManager's state to the 'wait for the next piece' state. I've exposed the PieceStates field to enable this, as it's easy. In the future if this seems like overreach, we could instead expose a utility method like 'advance_to_wait_for_piece_state()' or something and keep this field private.
> Expose PieceManager.states

- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/critter/sharks.gd
Before, placing moles/sharks in response to line clears could result in the creatures not being placed. This occurred for two reasons: critter deletions and overhead critters.
Firstly, clearing a line could trigger an 'add mole' event, which would then result in the mole being erased when the line was erased/deleted. Moles/sharks are no longer erased by line clear/line erase events.
Secondly, clearing a line could trigger an 'add mole' event, where the new mole would be placed in a cell below an existing mole. The upper mole (possibly a waiting mole) would the be redundant; both moles should appear in the same cell. Moles/sharks are no longer placed in cells where they'll be beneath another mole, unless there's a non-empty playfield cell between them.
> Critter bug: critter doesn't always appear for cleared line

- project/src/main/world/environment/poki/poki-crowd-spawner.gd
Entrances changed from Area2Ds to Sprites in 3f9c4a478129070888bfb68a2bb98b61e65a575d
> Fixed type error in PokiCrowdSpawner

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/main/ui/menu/bad-save-data-control.gd
I've exported the failed backup messages so that they can be translated into other languages.
Closes #2051.
> Added failed backup messages to messages.pot

- project/src/main/chat/ui/ChatFrame.tscn
- project/src/main/world/environment/lemon/environment-shadows.gd
Refactored ChatFrame to use the NametagPanel scene. It needs a different script attached, but can use all the same nodes.
Extracted _obstacle_map_shadows variable.
> ChatFrame uses NametagPanel scene. _obstacle_map_shadows

- project/src/demo/chat/ui/chatscript-table-demo.gd
- project/src/demo/toolkit/fix-chats-button.gd
- project/src/demo/world/FreeRoam.tscn
- project/src/main/career/career-cutscene-library.gd
- project/src/main/chat/chat-tree.gd
- project/src/main/chat/ui/label-typer.gd
- project/src/main/data/player-save-upgrader.gd
- project/src/main/editor/puzzle/editor-json.gd
- project/src/main/puzzle/level/level-history.gd
- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/level/level-triggers.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/settings/keybind-settings.gd
- project/src/main/utils/markov-model.gd
- project/src/main/utils/utils.gd
- project/src/main/world/creature/dna-alternatives.gd
Refactored more code to use Utils.put_if_absent.
Created similar method Utils.append_if_absent.
Refactored Utils.ui_released_dir to return a Vector2.
> Refactor: Utils.put_if_absent, append_if_absent, ui_released_dir

- delint.sh
- project/src/main/career/career-flow.gd
- project/src/main/puzzle/food-items.gd
- project/src/main/ui/menu/career-region-select-menu.gd
- project/src/main/world/creature/ear-player.gd
Added delint rule to detect functions missing type hint. Some of these are required due to limitations in GDScript.
> Refactor: functions missing type hint

- project/src/main/data/player-save.gd
- project/src/main/data/save-item.gd
- project/src/main/data/system-save.gd
- project/src/main/puzzle/goop-glob.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/creature/name-utils.gd
NameUtils still requires a workaround for a separate issue.
> Refactor: Removed Godot #30668 workaround.

- project/src/demo/chat/ui/chat-frame-demo.gd
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/puzzle/bursts.gd
- project/src/main/puzzle/critter/carrot.gd
- project/src/main/puzzle/critter/shark-clouds.gd
- project/src/main/puzzle/critter/shark-tooth-cloud.gd
- project/src/main/puzzle/goop-glob.gd
- project/src/main/puzzle/leaf-poofs.gd
- project/src/main/puzzle/night/night-sky.gd
- project/src/main/ui/menu/loading-orb.gd
- project/src/main/ui/wallpaper/sticker-row.gd
- project/src/main/utils/markov-model.gd
- project/src/main/world/career-world.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/environment/frame-overworld-obstacle.gd
- project/src/main/world/environment/grass-overworld-tiler.gd
- project/src/main/world/environment/lemon/lemon-tree.gd
- project/src/main/world/environment/mile-marker.gd
- project/src/main/world/environment/pebble-overworld-tiler.gd
- project/src/main/world/environment/poki/poki-crowd-spawner.gd
- project/src/main/world/environment/poki/poki-crowd.gd
- project/src/main/world/environment/poki/puddle-overworld-tiler.gd
- project/src/main/world/environment/poki/tent-spawner.gd
- project/src/main/world/environment/restaurant/carpet-tiler.gd
- project/src/main/world/environment/restaurant/hello-timer.gd
- project/src/main/world/environment/restaurant/kitchen-floor-tiler.gd
- project/src/main/world/environment/restaurant/undecorated-floor-tiler.gd
For all practical purposes these are intent, but '<=' unnecessarily conveys a more complex intent.
> Refactor: 'randf <=' -> 'randf <'

- project/src/demo/world/environment/sand/FilmingFreeRoamEnvironment.tscn
- project/src/main/world/environment/sand/BananaHqEnvironment.tscn
- project/src/main/world/environment/sand/BananaHqFreeRoamEnvironment.tscn
- project/src/main/world/environment/sand/FilmingEnvironment.tscn
Added spawns for filming environment. Renamed to
'FilmingFreeRoamEnvironment' which is still unambiguous but a lot less typing.
Expanded BananaHqEnvironment to include more chairs and spawns.
> Sandbar filming/banana hq environment tweaks

- project/src/main/world/environment/lemon/lemon-obstacle-library.tres
- project/src/main/world/environment/marsh/marsh-obstacle-library.tres
- project/src/main/world/environment/sand/sand-obstacle-library.tres
Obstacles which were partially colored in goop did not have their collision shapes defined. I've added the missing collision shapes.
> Fixed midfrost collisions for obstacle library.

- project/assets/main/puzzle/levels/career/boss-5k.json
- project/src/main/career/career-data.gd
- project/src/main/career/career-region.gd
- project/src/main/career/ui/progress-board.gd
- project/src/main/ui/menu/paged-region-buttons.gd
- project/src/main/ui/menu/practice-menu.gd
The region name changes, and is shown to the player differently based on their story progress.
> 'Cannoli Sandbar' is originally 'Kflab'

- project/assets/demo/puzzle/levels/experiment.json
- project/src/main/puzzle/piece/piece-mover.gd
Instead of mid-drop movement sliding the piece only once, it will slide the piece up to 8 times if DAS is active.
Closes #2136.
> Newly spawned pieces can slide twice during 20G.

- project/assets/main/chat/career/sand/boss-level-end.chat
- project/assets/main/chat/career/sand/epilogue-end.chat
A few running cutscenes made awkward concessions for emotes because of the conflicts between running and emoting. These conflicts have been fixed, so I've changed the emotes as well.
> Improved emotes for Cannoli Sandbar cutscenes

- project/assets/demo/puzzle/levels/experiment.json
- project/src/main/puzzle/night/night-sky-glow.gd
Replaced clumsy 'tween_callback' approach with looped tween in night-sky-glow.gd
> NightSkyGlow uses looped tween

- project/src/demo/puzzle/puzzle-critter-demo.gd
Before, it was very difficult to test how critters reacted to inserted lines.
> PuzzleCritterDemo now lets you manipulate the playfield.

- project/assets/main/puzzle/levels/career/a-little-garbage.json
- project/assets/main/puzzle/levels/career/dark/a-little-garbage-2.json
- project/assets/main/puzzle/levels/career/dark/secret-brownies.json
- project/assets/main/puzzle/levels/career/destroy-them-with-combos.json
- project/assets/main/puzzle/levels/career/midnight-snack.json
- project/assets/main/puzzle/levels/career/new-onion-friend.json
- project/assets/main/puzzle/levels/career/secret-brownies.json
It's fun when levels get harder over time, but not many levels do it. I even made the first level where each customer makes the level get a little faster, 'midnight_snack'.
> Added speedups to a few levels.

- project/src/main/puzzle/critter/Onion.tscn
- project/src/main/puzzle/critter/Spear.tscn
- project/src/main/puzzle/critter/SpearWide.tscn
Some Particles2D instances had visibility rects which were much too small.
> Fixed visibility rects for some particle systems.

- project/src/main/utils/string-utils.gd
- project/src/main/utils/utils.gd
- project/src/test/utils/test-utils.gd
The methods in these scripts were disorganized or organized semantically, making it hard to find specific methods. They're now in alphabetical order.
> Alphabetized utils.gd, string-utils.gd, test-utils.gd

- project/assets/main/chat/career/marsh/030-a-end.chat
- project/assets/main/chat/career/marsh/030-b-end.chat
- project/assets/main/chat/career/marsh/030-c-end.chat
- project/src/demo/world/CutsceneDemo.tscn
- project/src/main/career/career-level.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/environment/marsh/MarshEnvironment.tscn
These filenames changed in fd6b909f but the 'chat finished' flags were not updated.
> Fixed chat_finished syntax errors: 30 -> 030

- project/src/main/world/creature/EmotePlayer.tscn
Heart-eyes now pop in for the 'love1' emote, just like they did before for the 'love0' emote.
> Fixed heart eye pop in for "love1" emote

- project/src/main/career/career-cutscene-librarian.gd
- project/src/main/career/career-region.gd
- project/src/test/career/test-career-cutscene-librarian.gd
For the last level of the game, the game will play a different cutscene when you retry it. I've added the framework to enable this behavior; the new cutscenes are named 'boss_level_retry' and 'boss_level_reretry'
> Added support for second/third boss cutscene on retry

- project/src/main/chat/chat-tree.gd
- project/src/main/world/environment/lava/LavaEnvironment.tscn
- project/src/main/world/environment/lava/ZagmaEnvironment.tscn
Added missing 'lava/zagma' chatscript location flag.
Added spawns for LavaEnvironment. Fixed spawn height, position for ZagmaEnvironment
> Zagma chatscript/environment fixes.

- project/assets/demo/puzzle/levels/experiment.json
- project/src/main/puzzle/piece/piece-types.gd
- project/src/test/puzzle/piece/test-piece-kicks-c.gd
- project/src/test/puzzle/piece/test-piece-kicks-k.gd
The 'K' piece uses the piece kicks from the V piece. The 'C' piece uses a new set of piece kicks. There are a few cute moves I'd like to do with the C piece, but it's difficult to add without breaking symmetry.
> New piece shapes: c/k

- project/src/main/editor/puzzle/PlayfieldEditor.tscn
- project/src/main/editor/puzzle/box-level-chunk-control.gd
- project/src/main/editor/puzzle/pickup-level-chunk-control.gd
- project/src/main/editor/puzzle/piece-level-chunk-control.gd
- project/src/main/editor/puzzle/playfield-editor-control.gd
- project/src/main/editor/puzzle/veg-level-chunk-control.gd
Added C/K pieces to level editor.
Added PrevButton to level editor.
> Level editor improvements: prev button, C/K pieces

- project/src/main/career/career-flow.gd
- project/src/main/puzzle/results-hud.gd
I've added a successs condition so that the player must 'finish' or 'win' a level to earn the extra life.
> Bug: Game showed 'extra life' message when losing

- project/src/main/ui/menu/PagedLevelPanel.tscn
This is an inconsequential change automatically done by the Godot editor.
> Applied PagedLevelPanel transient .tscn change

- project/src/test/puzzle/piece/ascii-piece-analyzer.gd
- project/src/test/puzzle/piece/test-piece-kicks-c.gd
- project/src/test/puzzle/piece/test-piece-kicks-jl.gd
- project/src/test/puzzle/piece/test-piece-kicks-k.gd
- project/src/test/puzzle/piece/test-piece-kicks-pq.gd
- project/src/test/puzzle/piece/test-piece-kicks-v.gd
- project/src/test/puzzle/piece/test-piece-kicks.gd
Fixed some piece kick tests which had mismatched walls. Expanded the piece kick test framework to detect these kinds of errors. These errors will now fail the test.
> Fixed invalid kick tests. Added mismatch detection.

- project/assets/main/creatures/story/alyssa.json
- project/assets/main/creatures/story/bart.json
- project/assets/main/creatures/story/diota.json
- project/assets/main/creatures/story/frungle.json
- project/assets/main/creatures/story/kendall.json
- project/assets/main/creatures/story/miteby.json
- project/assets/main/creatures/story/trudy.json
- project/assets/main/creatures/story/xoxoxo.json
- project/src/demo/world/cutscene-demo-flags.gd
- project/src/main/career/career-calendar.gd
- project/src/main/career/career-cutscene-library.gd
- project/src/main/career/career-data.gd
- project/src/main/utils/bool-expression-parser.gd
- project/src/main/world/environment/restaurant/turbo-fat-restaurant.gd
- project/src/test/utils/test-bool-expression-evaluator.gd
These are synonyms, but this new term is consistent with the 'level_finished' flag.
> region_cleared -> region_finished

- project/src/main/puzzle/chef-view.gd
- project/src/main/utils/dynamic-viewport-container.gd
- project/src/main/world/environment/restaurant/RestaurantView.tscn
This component is very generic, and I plan to reuse it in the credits.
> chef-view -> dynamic-viewport-container

- project/project.godot
- project/src/main/credits/CreditsScroll.tscn
- project/src/main/credits/credits-orb.gd
- project/src/main/ui/wallpaper/wallpaper.gd
Changed orb from white to match the color of the background, just like on the loading screen.
Changed the orb's layering so it goes over the title.
> Orb colors, layer

- project/src/main/world/creature/creature.gd
This is used in an upcoming credits scene. I removed the _run_anim_speed field, because it was introducing bugs due to the fact that it's inaccurate until a physics_process step.
> Extracted 'Creature.get_run_speed()' method.

- project/src/main/world/environment/lava/lava-crowd.gd
Added a 'LavaCrowd.collision_disabled' flag which is useful for an upcoming cutscene where the player runs through a crowd.
Added LavaCrowd.raise_arms(), lower_arms() methods which are useful for an upcoming cutscene.
> LavaCrowd: collision_disabled, raise_arms, lower_arms

- project/src/demo/career/ui/career-win-demo.gd
- project/src/demo/career/ui/chalkboard-map-row-demo.gd
- project/src/demo/career/ui/progress-board-demo.gd
- project/src/demo/chat/ui/chat-frame-demo.gd
- project/src/demo/chat/ui/chat-ui-demo.gd
- project/src/demo/chat/ui/mood-demo.gd
- project/src/demo/credits/credits-letter-demo.gd
- project/src/demo/credits/credits-scroll-demo.gd
- project/src/demo/music/music-player-demo.gd
- project/src/demo/puzzle/critter/carrot-demo.gd
- project/src/demo/puzzle/critter/mole-demo.gd
- project/src/demo/puzzle/critter/onion-demo.gd
- project/src/demo/puzzle/critter/shark-demo.gd
- project/src/demo/puzzle/critter/spear-demo.gd
- project/src/demo/puzzle/puzzle-message-demo.gd
- project/src/demo/puzzle/score-demo.gd
- project/src/demo/puzzle/tutorial/tutorial-hud-demo.gd
- project/src/demo/ui/scene-transition-demo.gd
- project/src/demo/ui/touch/eight-way-demo.gd
- project/src/demo/world/environment/lava/confetti-cannon-demo.gd
- project/src/demo/world/environment/lava/crowd-surf-cutscene-demo.gd
- project/src/demo/world/environment/lava/lava-crowd-demo.gd
- project/src/demo/world/environment/restaurant/restaurant-puzzle-scene-demo.gd
- project/src/demo/world/environment/restaurant/restaurant-view-demo.gd
- project/src/demo/world/environment/smoke-cluster-demo.gd
- project/src/demo/world/letter-shooter-demo.gd
Some had inconsistent whitespace. I think [A,B,C] is easier to read at a glance than [A, B, C] unless english words like 'Comma' get introduced.
> Rewrote demo comments for consistency

- delint.sh
- project/src/main/world/environment/lava/ZagmaEnvironment.tscn
Fixed ZagmaEnvironment 'Environment2' node.
> Added 'Environment2' check; this still occurs every few months.

- project/project.godot
- project/src/demo/credits/CreditsEndTextDemo.tscn
- project/src/demo/credits/credits-end-text-demo.gd
- project/src/main/credits/CreditsEndText.tscn
- project/src/main/credits/CreditsScroll.tscn
- project/src/main/credits/credits-director.gd
- project/src/main/credits/credits-end-text.gd
- project/src/main/credits/credits-scroll.gd
- project/src/main/credits/end-text-title.gd
- project/src/main/ui/DiagonalParticles.tscn
- project/src/main/ui/diagonal-particles.gd
- project/src/main/world/environment/lava/CrowdSurfEnvironment.tscn
Fixed bug where the player and fat sensei would crowd surf off into the abyss after the end credits, if the player waited long enough
> Added credits end screen showing completion and grade

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/puzzle.gd
Added new 'winish' cheat which instantly clears the level and any success criteria. Without this cheat, it was difficult to test the trigger for the credits.
> 'winish' cheat for testing credits

- project/assets/main/chat/career/credits/precredits-1.chat
- project/assets/main/chat/career/credits/precredits-2.chat
- project/assets/main/chat/career/lava/boss-level-end.chat
- project/src/demo/credits/credits-scroll-demo.gd
- project/src/main/credits/CreditsScroll.tscn
- project/src/main/credits/credits-scroll.gd
- project/src/main/ui/ExitCreditsPopup.tscn
- project/src/main/ui/exit-credits-popup.gd
- project/src/main/utils/global.gd
- project/src/main/world/cutscene-queue.gd
- project/src/main/world/overworld-ui.gd
Credits play after the player finishes career mode. The player can exit the credits by hitting space/Z twice or by hitting escape. The credits drop the player back on the main menu, advancing to the next career day.
> Credits play in career mode. Can exit credits.

- project/src/demo/credits/CreditsScrollDemo.tscn
- project/src/demo/credits/credits-scroll-demo.gd
- project/src/main/credits/CreditsScroll.tscn
- project/src/main/credits/credits-director.gd
- project/src/main/credits/credits-scroll.gd
The main menu will have a credits button, but we don't want this to be the cool version of the credits that plays when finishing the game. There is now a second version of the credits.
> Added boring version of credits, before players win

- package.sh
- project/export_presets.cfg.template
Reverts Poobslag/turbofat#2399
> Revert "Changed export presets to zips. Linux +x flag."

- project/src/main/editor/creature/CreatureEditor.tscn
> Fixed CreatureEditor export file type to '.json'

- project/src/main/data/player-save.gd
For achievements, Steam wants to add listeners for these events so I've created signals for them.
> New PlayerSave signals: save_scheduled, after_load

- project/src/main/data/system-data.gd
- project/src/main/settings/graphics-settings.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-fullscreen.gd
Fullscreen setting defaults to 'true' and can be toggled in the settings menu. This is not true fullscreen, but rather a borderless window.
> Added fullscreen setting

- project/assets/main/puzzle/levels/tutorial/spins-6.json
- project/assets/main/puzzle/levels/tutorial/spins-7.json
I don't think anyone will notice this, but it would be funny if they did.
> Changed 'meet spins' tutorial to use DT cannon setup.

- project/src/main/settings/gameplay-settings.gd
- project/src/main/settings/graphics-settings.gd
- project/src/main/settings/touch-settings.gd
It is slightly easier to find fields/methods if they have a consistent order.
> Alphabetized settings classes.

- project/src/demo/name-generator-library-demo.gd
- project/src/main/credits/credits-director.gd
- project/src/main/puzzle/critter/carrots.gd
- project/src/main/puzzle/critter/sharks.gd
- project/src/main/puzzle/critter/spears.gd
- project/src/main/puzzle/level/level-settings-upgrader.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/ui/font-fit-button.gd
- project/src/main/utils/utils.gd
- project/src/main/world/career-map.gd
Lots of code needs to use 'for i in...' if the index is relevant, but for code which just needs to execute something on every item in the list, the extra array index is redundant and complicates the code slightly.
> Replaced 'for i in...' with 'for array_item in...'

- project/src/main/career/ui/ProgressBoard.tscn
- project/src/main/career/ui/progress-board-clock-label.gd
- project/src/main/credits/CreditsEndText.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/Score.tscn
- project/src/main/puzzle/milestone-hud.gd
- project/src/main/puzzle/score-value-label.gd
- project/src/main/ui/DiagonalParticles.tscn
- project/src/main/ui/diagonal-particles.gd
The Puzzle, Score, ProgressBoard and Credits all emit clusters of diagonal particles and can all use the same scene.
Puzzle.tscn was slightly different in that it emitted 12 particles instead of 8, so I exposed a 'DiagonalParticles.amount' property.
> Reused DiagonalParticles.tscn where possible.

- project/src/demo/ui/CandyButtonDemo.tscn
- project/src/main/ui/candy-button/CandyButton.tscn
- project/src/main/ui/candy-button/candy-button.gd
- project/src/main/ui/menu/MainMenu.tscn
This prevents the gradient map shader script from being duplicated throughout our project.
> Replaced CandyButton material.duplicate() with resource_local_to_scene

- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/PracticeMenu.tscn
- project/src/main/ui/menu/SplashScreen.tscn
Added title accent, and reusable MenuAccentH2.
> Added accents to main menu

- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/drop-panel.tres
This also affects the appearance of the splash screen and other screens.
> Added white border to main menu drop panel

- project/src/demo/ui/squeak/SqueakThemeDemo.tscn
- project/src/main/ui/squeak/squeak-theme-h4.tres
Created a new 'Squeak theme', a simpler compact UI used in the settings menu. For now, this only applies to Label and Panel but I'll broaden it to include other components as well.
> Squeak theme: Label, Panel

- project/src/demo/ui/squeak/SqueakThemeDemo.tscn
- project/src/demo/ui/squeak/squeak-theme-demo.gd
- project/src/main/ui/squeak/squeak-theme-h4.tres
- project/src/main/ui/tab-input-enabler.gd
Fixed NPE when a tab contains no focusable nodes. Its behavior is still a little unusual in this edge case, but there's no practical scenario where it will happen.
> Squeak theme: TabContainer

- project/src/main/ui/settings/keybind/settings-keybinds-control.gd
These should have been included in #2517.
> Added missing SettingsKeybindControl script updates

- project/assets/main/locale/es.po
Added spanish localization for more phrases, courtesy of Hish from the Turbo Fat discord.
> More spanish localization: credits, cutscenes, etc

- project/src/demo/ui/CandyButtonDemo.tscn
- project/src/main/ui/candy-button/candy-button-h3.gd
- project/src/main/ui/candy-button/candy-button-h4.gd
- project/src/main/ui/candy-button/candy-buttons.gd
- project/src/main/ui/candy-button/gradient-disabled-hover.tres
- project/src/main/ui/candy-button/gradient-disabled.tres
Disabled candybuttons are drawn with a tan color.
> CandyButtons can be disabled.

- project/src/main/editor/creature/creature-color-button.gd
- project/src/main/ui/candy-button/candy-button-c3.gd
- project/src/main/ui/candy-button/candy-button-collapsible.gd
- project/src/main/ui/candy-button/candy-button-h3.gd
- project/src/main/ui/candy-button/candy-button-h4.gd
- project/src/main/ui/candy-button/candy-buttons.gd
The phrases 'color' and 'shape' are unambiguous in context.
> CandyButton button_color/button_shape -> color/shape

- project/src/main/ui/menu/PracticeMenu.tscn
Renamed 'Panel' to 'DropPanel'.
> Refactor: Moved PracticeMenu's VBoxContainer within Panel.

- project/src/main/career/population.gd
- project/src/main/puzzle/box-builder.gd
- project/src/main/ui/candy-button/candy-buttons.gd
- project/src/main/ui/squeak/squeak-option-button-helper.gd
- project/src/test/puzzle/piece/test-piece-kicks-jl.gd
- project/src/test/puzzle/piece/test-piece-kicks-k.gd
- project/src/test/puzzle/piece/test-piece-kicks-sz.gd
- project/src/test/puzzle/piece/test-piece-kicks-v.gd
I experimented with adding a delint script, but honestly after about an hour of messing around with different grep arguments, it just seems it's not meant to work with multiple lines and I'd need to use something entirely different.
> Fix gdscript files containing 3 consecutive lines

- project/assets/main/keybind/default-custom.json
- project/assets/main/keybind/guideline-hold.json
- project/assets/main/keybind/guideline.json
- project/assets/main/keybind/wasd-hold.json
- project/assets/main/keybind/wasd.json
Updated the default keybinds to include 3 keys for next tab/prev tab. Without these 3 keys, KeybindSettings.get_custom_keybind threw an array index out of bounds error
> Bug: 'ResetToDefaults" button caused an error

- delint.sh
Refactored 'import file cleaning' script in some minor ways as well
> Refactor: delint.sh script cleans import files

- delint.sh
This semicolon-delimited style has become more popular recently.
> Refactor: Change delint script from 'if x... then' to 'if x; then'

- project/src/main/world/creature/dna-utils.gd
This method is used in the upcoming creature editor color picker improvements.
> Refactor: Extracted 'darker_line_color' method

- project/project.godot
- project/src/main/data/system-data.gd
- project/src/main/ui/settings/settings-fullscreen.gd
> Added Alt+Enter fullscreen shortcut

- project/src/main/puzzle/rank-calculator.gd
- project/src/test/puzzle/test-rank-calculator.gd
This method is currently only used on the steam branch, but it's generic and could be used for anything
> Added RankCalculator.rank_meets_grade() method

- project/src/main/steam/SteamAchievements.tscn
- project/src/main/steam/chapter-finished-achievement.gd
- project/src/main/steam/chapter-rank-s-achievement.gd
Added 'chapter start', 'chapter rank S', and 'chapter story finish' achievements for all six chapters.
> Achievements: chapter start, rank s, story finish

- project/src/main/puzzle/Puzzle.tscn
This burst was accidentally moved during bcb86e8c
> Fixed level up burst position; was in upper-left corner

- project/src/demo/toolkit/fix-levels-button.gd
- project/src/main/steam/SteamAchievements.tscn
- project/src/main/steam/chapter-rank-s-achievement.gd
- project/src/main/steam/combo-achievement.gd
- project/src/main/steam/consolidated-achievement.gd
- project/src/main/steam/customer-score-achievement.gd
- project/src/main/steam/leftovers-score-achievement.gd
- project/src/main/steam/level-rank-achievement.gd
- project/src/main/steam/rank-m-achievement.gd
- project/src/main/steam/steam-achievement.gd
- project/src/main/steam/steam-achievements.gd
Added achievement validation logic to ReleaseToolkit
> Added score/rank/combo achievements

- project/src/demo/toolkit/fix-levels-button.gd
ReleaseToolkit checks for hyphens in achievement level ids
> Release toolkit hyphens

- project/src/main/ui/HSliderGamepadHelper.tscn
- project/src/main/ui/candy-button/HsvSlider.tscn
- project/src/main/ui/h-slider-gamepad-helper.gd
- project/src/main/ui/menu/TrainingMenu.tscn
- project/src/main/ui/settings/VolumeSetting.tscn
> Gamepads can adjust sliders by holding a direction.

- project/src/main/ui/level-select/level-select-button.gd
These boss levels would usually be pickable because the player would play them to advance. But if the player skips one of these with a cheat code they could never be played, because their unlock criteria was 'play the level' and the criteria for playing them was 'you haven't cleared this area'.
Boss levels now have an additional unlock criteria of 'you've cleared the region'. If the level is skipped, they'll be unlocked anyways.
Closes #2364.
> Fixed 'unpickable boss level' bug.

- project/src/demo/editor/creature-old/LockAlleleButton.tscn
- project/src/demo/editor/creature-old/lock-allele-button.gd
- project/src/demo/toolkit/ReleaseToolkit.tscn
- project/src/demo/toolkit/extract-localizables-button.gd
- project/src/demo/toolkit/fix-chats-button.gd
- project/src/demo/toolkit/fix-creatures-button.gd
- project/src/demo/toolkit/fix-levels-button.gd
- project/src/main/ui/settings/keybind/custom-keybind-button.gd
- project/src/main/ui/settings/reset-gameplay-button.gd
Buttons automatically have a '_pressed' function which is called. It's reundant to connect the button's pressed signal to itself.
> Refactor: _on_pressed -> pressed

- project/project.godot
- project/src/demo/toolkit/extract-localizables-button.gd
- project/src/demo/toolkit/fix-chats-button.gd
- project/src/demo/toolkit/fix-creatures-button.gd
- project/src/demo/toolkit/fix-levels-button.gd
- project/src/demo/toolkit/release-tool-button.gd
- project/src/demo/toolkit/release-toolkit-output.gd
This removes some copy/paste code for stuff like the output label
> Refactor: Extracted 'ReleaseToolButton' for ReleaseToolkit

- project/src/main/editor/creature/NamePickerPopup.tscn
> Creature editor name picker popup is grey

- project/project.godot
- project/src/demo/puzzle/level/level-rank-demo-grade.gd
- project/src/demo/puzzle/level/rank-mode-demo.gd
- project/src/main/career/ui/hookable-region-grade-label.gd
- project/src/main/credits/credits-scroll.gd
- project/src/main/puzzle/duration-calculator.gd
- project/src/main/puzzle/food-items.gd
- project/src/main/puzzle/level/level-history.gd
- project/src/main/puzzle/playfield-fx.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/rank-result.gd
- project/src/main/puzzle/ranks.gd
- project/src/main/puzzle/result/receipt-stamp.gd
- project/src/main/puzzle/result/results-hud-blueprint.gd
- project/src/main/puzzle/step-meter.gd
- project/src/main/ui/high-score-table.gd
- project/src/main/ui/level-select/hookable-level-grade-label.gd
- project/src/main/ui/level-select/level-submenu-info-panel.gd
- project/src/main/ui/menu/region-info-panel.gd
- project/src/test/puzzle/test-rank-calculator.gd
- project/src/test/puzzle/test-rank-target-calculator.gd
- project/src/test/puzzle/test-ranks.gd
In preparation for the rank overhaul, this new 'ranks.gd' script includes some bare bones static scripts and tests to avoid complex dependencies between RankResult and RankCalculator.
> Extracted ranks.gd for constants, utilities

- project/src/demo/puzzle/level/RankOutlierDemo.tscn
- project/src/demo/puzzle/level/rank-outlier-demo-analyze.gd
- project/src/demo/puzzle/level/rank-outlier-demo-import.gd
- project/src/demo/puzzle/level/rank-outlier-dialogs.gd
- project/src/main/data/player-save.gd
This demo can import player data as '.score' files and perform statistical analysis, comparing the player's performance to our expectations and highlighting outliers.
> Added RankOutlierDemo.

- project/project.godot
- project/src/demo/career/ui/progress-board-demo.gd
- project/src/main/career/ui/ProgressBoard.tscn
- project/src/main/career/ui/ProgressBoardSpot.tscn
- project/src/main/career/ui/progress-board-goal.gd
- project/src/main/career/ui/progress-board-lines.gd
- project/src/main/career/ui/progress-board-player.gd
- project/src/main/career/ui/progress-board-splash-message.gd
- project/src/main/career/ui/progress-board-spot.gd
- project/src/main/career/ui/progress-board-spots.gd
- project/src/main/career/ui/progress-board-trail.gd
- project/src/main/career/ui/progress-board.gd
The progress board now has a 'goal' label over the target. The letters bounce and animate when the player reaches the goal.
The progress board now shows the message 'Goal!' in the center when the player reaches the goal.
The progress board flashes rainbow colors when the player reaches the goal, and plays a sound effect.
> Progress board hype enhancements: 'goal' text, rainbows

- project/src/demo/puzzle/result/results-hud-demo.gd
- project/src/main/puzzle/result/results-hud-blueprint.gd
It was supposed to skip empty categories already, but I had a '>= 0' instead of a '> 0'
> ResultsHud skips empty categories.

- project/src/main/career/CareerMap.tscn
- project/src/main/career/career-hint.gd
- project/src/main/career/hint-accent.gd
- project/src/main/career/ui/career-map-level-select.gd
- project/src/main/ui/level-select/LevelSelectButton.tscn
These hints mostly serve as guidance to new players so that they can understand the rules of Career Mode without tutorials. But they also bring back some of the hints from the old ResultsHud which go into details about scoring and advanced piece movement techniques.
> Added hints to career mode.

- project/src/main/career/career-hint.gd
- project/src/main/ui/level-select/level-submenu-description-panel.gd
- project/src/main/ui/menu/BadSaveDataControl.tscn
- project/src/main/ui/menu/region-description-panel.gd
The UI never talls about "Career mode" so mentioning in hints is confusing
> Career mode -> Adventure mode

- project/src/main/career/ui/progress-board-spots.gd
- project/src/main/career/ui/progress-board-trail.gd
Starberry mountain is endless, maybe there will be a goal some day but not for now.
> Starberry Mountain no longer has an ending star.

- project/src/main/puzzle/ranks.gd
- project/src/test/puzzle/test-ranks.gd
The RankCalculator underwent massive changes this past month. I've restored some functionality which was used by our achievement framework. I've added some notes to ensure the functionality is preserved in the future.
> Restored missing rank methods required by steam.

- project/assets/main/creatures/story/beats.json
- project/assets/main/creatures/story/chelle.json
- project/assets/main/creatures/story/dreadhark.json
- project/assets/main/creatures/story/goldfince.json
- project/assets/main/creatures/story/goris.json
- project/assets/main/creatures/story/lisk.json
- project/assets/main/creatures/story/pairet.json
- project/assets/main/creatures/story/pigpog.json
- project/assets/main/creatures/story/raymon.json
- project/assets/main/creatures/story/sandrew.json
- project/assets/main/creatures/story/sleve.json
- project/assets/main/creatures/story/wendrea.json
These 'customer_if' flags prevent story characters from showing up before you've met them.
> Added missing customer_if flags for chocolava canyon, others

- project/assets/main/locale/es.po
Added fixes for the machine-translated spanish phrases, courtesy of Hish from the Turbo Fat discord.
> Translation fixes

- project/src/demo/puzzle/result/ResultsHudDemo.tscn
- project/src/demo/puzzle/result/results-hud-demo.gd
- project/src/main/puzzle/result/ResultsHud.tscn
- project/src/main/puzzle/result/receipt-bar-graph.gd
- project/src/main/puzzle/result/results-hud-blueprint.gd
- project/src/main/puzzle/result/results-hud.gd
The result screen now includes a 'GOAL' marker for boss levels so the player can see how close they are to passing the level. When replaying the levels in training mode, the traditional rank markers are shown.
> Boss levels show 'GOAL' marker on result screen.

- project/src/main/steam/steam-utils.gd
Pause the game when the Steam overlay is toggled
> Steam overlay pause

- project/src/main/puzzle/result/ResultsHud.tscn
This shake was accidentally unhooked when introducing the clipping rectangle in fef9a094
> Restored resultshud 'shake' effect.

- project/src/main/steam/leftovers-score-achievement.gd
- project/src/main/steam/rank-m-achievement.gd
Added missing 'refresh_achievement()' call for these two achievements
> Bug: leftovers, rank m achievements could not be unlocked

- project/assets/main/puzzle/levels/career/a-little-extra.json
- project/assets/main/puzzle/levels/career/a-thousand-moles.json
- project/assets/main/puzzle/levels/career/angle-grinder.json
- project/assets/main/puzzle/levels/career/asparagus-trio.json
- project/assets/main/puzzle/levels/career/block-blockers.json
- project/assets/main/puzzle/levels/career/boss-lava.json
- project/assets/main/puzzle/levels/career/boss-marsh.json
- project/assets/main/puzzle/levels/career/boss-sand.json
- project/assets/main/puzzle/levels/career/cheerleaders.json
- project/assets/main/puzzle/levels/career/chompo-and-bitey.json
- project/assets/main/puzzle/levels/career/curly-queue-2.json
- project/assets/main/puzzle/levels/career/day-night-psycho.json
- project/assets/main/puzzle/levels/career/donuts.json
- project/assets/main/puzzle/levels/career/fat-stacks.json
- project/assets/main/puzzle/levels/career/fruit-salad.json
- project/assets/main/puzzle/levels/career/hungry-moles.json
- project/assets/main/puzzle/levels/career/nowhere-to-turn.json
- project/assets/main/puzzle/levels/career/paranormal-tetrominon.json
- project/assets/main/puzzle/levels/career/snack-box-blitz.json
- project/assets/main/puzzle/levels/career/square-curse.json
- project/assets/main/puzzle/levels/career/traffic-jam-2.json
- project/assets/main/puzzle/levels/career/two-box-buffet.json
- project/assets/main/puzzle/levels/career/up-in-smoke.json
- project/assets/main/puzzle/levels/career/wall-greens.json
- project/assets/main/puzzle/levels/career/wedge.json
Most levels became noticably easier, although I decreased the time limit for a few levels where I was able to significantly exceed the current master time.
> Level rank adjustments

- project/assets/main/creatures/nonstory/ray.json
> New creature: Ray

- project/src/main/steam/create-creature-achievement.gd
- project/src/main/steam/unique-level-achievement.gd
The '--tf-verbose' flag now logs some additional information related to achievements.
> Added achievement logging for --tf-verbose flag.

- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
Replaced 'failed_section' variable with 'failure_count' logic. This allows for more fine-grained logic depending on how many times the player has failed.
Reset 'level_performance.pieces' and 'cakes_built' in one place, instead of specifying it for each tutorial section. This allows all tutorial sections to have fine-grained logic depending on how many pieces the player has placed.
> Streamlined combo tutorial: failure_count, cakes_built

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/assets/main/puzzle/levels/tutorial/combo-0-example.json
- project/assets/main/puzzle/levels/tutorial/combo-2-example.json
- project/assets/main/puzzle/levels/tutorial/combo-5-example.json
- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
The combo tutorial now shows demonstrations for each of the challenges. These demos are shown if the player fails three times.
> Better guidance for combo tutorial.

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/tutorial/tutorial-spins-module.gd
Ordering the logic this way makes it more straightforward to add scenarios for different failure ranges, and mirrors the logic in the combo tutorial.
> Minor reordering of spin move tutorial logic.

- project/src/main/data/player-save.gd
- project/src/main/data/system-save.gd
Before, after upgrading old save data, the old data would remain on disk and need to be upgraded every time the player saved the game. This isn't a big deal, since newer versions are written if the player makes any change or plays any level. But it's possible a player could configure their settings, and not touch their settings for 6 months, in which case the old settings version would stay on their disk until they adjusted the volume or switched their save slot.
Save data is now immediately persisted after it is loaded.
> Persist save data after upgrading it.

- project/src/main/data/system-save.gd
Before, we would upgrade config and save files in memory but not persist them. This resulted in edge cases where, for example, a player could have a config file which was running the newest version, one save slot which was 2 weeks old, and a second save slot which was 2 months old.
This especially introduced complications with the newest release which moves difficulty settings from the config into the save slots. It meant that if we wanted to preserve the player's difficulty settings, we'd need to permanently persist them to the config file just in case 6 months from now they decided to load an old save slot which needed the saved difficulty settings.
We now upgrade all config files and save files on startup, which gets rid of these edge cases and lets us streamline the saved data.
> Upgrade config and save files on startup.

- project/assets/main/puzzle/levels/career/asparagus-vault.json
- project/assets/main/puzzle/levels/career/checkerboard-vault.json
Food disappears faster on Asparagus Vault, Checkerboard Vault
> Updated Asparagus Vault, Checkerboard Vault with food_speed

- project/src/main/ui/difficulty/difficulty-button.gd
- project/src/main/ui/difficulty/difficulty-hold-piece-panel.gd
- project/src/main/ui/difficulty/difficulty-line-piece-panel.gd
- project/src/main/ui/difficulty/difficulty-menu.gd
Difficulty menu was not saving the player's settings. It was saving the system configuration, but the difficulty settings are not in the system configuration anymore.
> Bug: Difficulty menu didn't save settings

- project/assets/demo/puzzle/levels/retired/boxing-day.json
- project/assets/demo/puzzle/levels/retired/muffin-impossible-3.json
- project/assets/demo/puzzle/levels/retired/unfresh-fruits-2.json
- project/assets/main/puzzle/levels/career/500-race.json
- project/assets/main/puzzle/levels/career/angle-grinder.json
- project/assets/main/puzzle/levels/career/asparagus-trio.json
- project/assets/main/puzzle/levels/career/boss-poki.json
- project/assets/main/puzzle/levels/career/cheese-mountain.json
- project/assets/main/puzzle/levels/career/dark/boxing-day.json
- project/assets/main/puzzle/levels/career/dark/its-square-to-be-square.json
- project/assets/main/puzzle/levels/career/dark/secret-brownies.json
- project/assets/main/puzzle/levels/career/destroy-them-with-boxes.json
- project/assets/main/puzzle/levels/career/mozzarella-sticks.json
- project/assets/main/puzzle/levels/career/real-meal.json
- project/assets/main/puzzle/levels/career/shelf.json
- project/assets/main/puzzle/levels/career/traffic-jam-2.json
- project/assets/main/puzzle/levels/practice/ultra-hard.json
- project/assets/main/puzzle/levels/rank/1k.json
- project/assets/main/puzzle/levels/tutorial/basics-4.json
- project/assets/main/puzzle/levels/tutorial/combo-6.json
- project/assets/main/puzzle/levels/tutorial/squish-7.json
- project/src/demo/toolkit/fix-levels-button.gd
- project/src/main/puzzle/rank-criteria.gd
Some levels had overly specific durations like '6:05'. I've also added a check to ensure 'top=...' values are rounded.
> Round level durations and goals.

- project/assets/main/puzzle/levels/career/back-to-back.json
- project/assets/main/puzzle/levels/career/bon-appetit.json
- project/assets/main/puzzle/levels/career/carrot-cake-2.json
- project/assets/main/puzzle/levels/career/serving-on-a-rocket.json
- project/assets/main/puzzle/levels/career/sharky-cheese.json
- project/assets/main/puzzle/levels/career/shoots-and-leaves.json
After more playtesting, these levels were too difficult to reach the target scores so I've loosened their score criteria.
> Adjusted main story rank criteria for a few trouble levels

- project/src/main/career/ui/ProgressBoard.tscn
Animation key order now matches scene tree order.
Changed 'Clock:rect_position' key to 'Clock:rect_position:x'.
> Progress board animation tweaks.

- project/src/main/ui/scene-transition.gd
Triggering a scene change from a signal handler sometimes causes a silent crash, with no errors or logs. We defer the scene change to the next frame to avoid conflicts with signal handling. See Godot #85692 (https://github.com/godotengine/godot/issues/85692).
We previously applied other fixes suggested in the Godot issue, but I saw two silent crashes yesterday in the Steam version of the game, so those fixes were insufficient.
> Defer scene changes until next frame.

- project/assets/main/puzzle/levels/tutorial/cakes-0.json
- project/assets/main/puzzle/levels/tutorial/combo-0.json
- project/assets/main/puzzle/levels/tutorial/spins-0.json
- project/assets/main/puzzle/levels/tutorial/squish-0.json
These durations are estimates, based on my rough guess that each section takes about 30 seconds.
> Updated tutorial durations.

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/main/ui/level-select/level-submenu-info-panel.gd
'Very Easy' refers to the speed that the pieces fall, tutorials aren't necessarily easy.
> 'Difficulty: Tutorial' instead of 'Very Easy'

- project/src/main/ui/scene-transition.gd
Replaced 'call_deferred' with ad-hoc deferred logic
> Tweaked scene transition logic

- project/src/main/data/player-save.gd
- project/src/main/editor/creature/creature-saver.gd
- project/src/main/editor/creature/dialogs.gd
- project/src/main/puzzle/puzzle.gd
PlayerSave.save_player_data() now supports optional threaded saving, reducing lag from 50-100ms to 0ms by moving the operation to a secondary thread.
This improves responsiveness but sacrifices automicity, so it is not used universally.
> Support threaded saving to eliminate lag.
