Poobslag/turbofat

- project/src/main/ui/MusicPopup.tscn
- project/src/main/ui/outline-material-80.tres
This material was broken by 52f08f61, causing the music notes on the music popup to no longer have an outline.
I've fixed it to use the 'Frying Pan Shader' which gives the outlines a smoother look.
> Fixed music note outline material.

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/playfield-fx.gd
The combo strobe was invisible for infinite combo levels. It should always be on. This 'always on' behavior occurs with the current if/else logic, so I've removed the unnecessary conditional.
> Fixed playfield combo strobe for infinite combo levels.

- project/src/main/puzzle/piece/piece-manager.gd
Inserted lines were intended to push pieces above them, but the logic was flipped where they were only pushing pieces below them. (And more importantly, NOT pushing pieces above them resulting in pieces clipping into the playfield.)
> Fixed bug with inserted lines not pushing pieces.

- project/src/demo/puzzle/PuzzleCritterDemo.tscn
- project/src/demo/puzzle/puzzle-critter-demo.gd
- project/src/demo/puzzle/puzzle-demo.gd
I'm about to add a second critter type with several variations i want to test in the editor -- if we have 2 keys for moles, 6 keys for this new critter and so on, we will run out of PuzzleDemo keys very quickly.
I've designed PuzzleCritterDemo to toggle 26 different critters (one for each letter A-Z) with the remaining non-letter keys used to manipulate those critters.
> Split PuzzleCritterDemo from PuzzleDemo.

- project/assets/main/puzzle/levels/career/a-thousand-moles.json
- project/assets/main/puzzle/levels/career/mole-money-mole-problems.json
- project/src/main/puzzle/combo-tracker.gd
- project/src/main/puzzle/level-timer-manager.gd
- project/src/main/puzzle/level/config-string-utils.gd
- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/level/phase-conditions.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/pickups.gd
- project/src/test/puzzle/level/test-config-string-utils.gd
- project/src/test/puzzle/level/test-phase-conditions.gd
Added 'combo_ended' level trigger. This can trigger every time a combo ends, or specifically when a combo of a certain size ends.
Added 'pickup_collected' level trigger. This can trigger every time a pickup is collected, or specifically cake/snack pickups.
line_cleared level trigger now supports 'combo' condition.
Levels now support up to 10 timers, increased from 3.
piece_written and other config strings now accept "1..." as a shorthand for "1,2,3..."
> Level trigger/phase improvements: 'combo_ended', 'pickup_collected'

- license/asset-license.txt
- project/src/main/puzzle/critter/Carrot.tscn
- project/src/main/puzzle/critter/Critters.tscn
- project/src/main/puzzle/critter/carrot.gd
- project/src/main/puzzle/critter/carrots.gd
- project/src/test/puzzle/critter/test-carrots.gd
Added carrot sfx. They make a 'whoosh' sound when they poof in and out, and a cartoon plane sound when they fly by.
Fixed carrot deconflicting algorithm. This algorithm used to swap carrots which were too close together, but this often just moved other carrots which were also too close. The new algorithm is more consistent, as demonstrated with a unit test.
Fixed remove_carrots() performance degradation. When calling it with a large number like 999,999, it would still loop 999,999 times even if it only had to remove 3 carrots. It now terminates the loop prematurely once the last carrot is removed.
> Carrot improvements: sfx, deconflicting

- project/src/demo/puzzle/level/level-rank-demo.gd
Before, when LevelRankDemo was launched it would be blank, and when it loaded a new level it would still display the old level's metadata. This led to mistakes where I'd enter the wrong level's ranking data.
> LevelRankDemo recalculates when launched/loaded

- project/src/main/career/career-flow.gd
- project/src/main/career/ui/career-map-ui.gd
- project/src/main/utils/global.gd
- project/src/main/world/career-map.gd
Career mode's 'end of day' logic was rewritten to redirect to the career map, but in some cases it needs to redirect to the career win screen. I've added some edge cases to cover this.
> Fixed bug where 'give up' button doesn't work

- project/src/main/puzzle/critter/Critters.tscn
- project/src/main/puzzle/critter/carrots.gd
Decreased poof sound volume. I thought I fixed this with 3d7f9dbf but I had adjusted the move sound volume instead.
Increased move sound volume. I inadvertently lowered this to -4 in 3d7f9dbf but after restoring it to full volume, I think it sounds better at -2 instead.
Fixed bug where carrots could be silenced if carrots appeared/disappeared simultaneously. This edge case is now avoided with a 'move_sfx_state' field.
> Carrot sfx fixes; silence, quieter poof sounds

- project/assets/main/puzzle/career-regions.json
- project/src/demo/world/CutsceneDemo.tscn
- project/src/main/chat/chat-library.gd
- project/src/main/world/environment/marsh/MarshEnvironment.tscn
Chat resources changed to three digits awhile ago, but a few references weren't updated.
> Fixed merrymellow marsh unlocks from '20' to '020'

- project/assets/demo/puzzle/levels/experiment.json
- project/src/main/puzzle/line-clear-sfx.gd
- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/tutorial/tutorial-cakes-module.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
The 'make cakes' tutorial clears all cake lines at the end of a tutorial section. This would trigger the all clear message if the player hadn't placed their final piece.
I've added a 'tutorial_section_finished' flag which is assigned/unassigned during tutorials. If it's been set, the all clear message is suppressed.
> Avoid reporting 'All Clear!' between tutorial sections.

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/tutorial/TutorialBasicsModule.tscn
- project/src/main/puzzle/tutorial/TutorialCakesModule.tscn
- project/src/main/puzzle/tutorial/TutorialComboModule.tscn
- project/src/main/puzzle/tutorial/TutorialModule.tscn
- project/src/main/puzzle/tutorial/TutorialSpinsModule.tscn
- project/src/main/puzzle/tutorial/TutorialSquishModule.tscn
- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
- project/src/main/puzzle/tutorial/tutorial-cakes-module.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-diagram.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/puzzle/tutorial/tutorial-squish-module.gd
When restarting tutorials after the 'Good!' message showed up, the piece would never appear, softlocking the tutorial. This is because PieceManager set physics_process to false during the level transition but did not set it back to true. It now sets physics_process to true at the start of a new game.
Tutorials would demonstrate weird behavior when interrupted, because 'yield' statements would continue from the previously run tutorial. These 'yield' statements have been replaced with timers and listeners which are cleaned up when a new tutorial is started.
The choices which appear when the player is watching tutorial diagrams were lingering even if the player gave up on the tutorial. This let them do strange things like choose tutorial options when they weren't playing anymore. The choices …
> Fixed bugs when interrupting/restarting tutorials.

- project/src/main/puzzle/puzzle-tile-map.gd
This fixes a bug where the ghost piece would look like fruit on levels where the player pieces were vegetables.
> Ghost Piece tileset now matches piece type.

- project/src/test/chat/test-tracery.gd
Our tracery unit tests assumed the locale was set to english. They now explicitly set the locale before any locale-specific tests.
> Tracery tests pass in non-english locales.

- project/src/main/chat/chat-tree.gd
- project/src/main/chat/tracery.gd
- project/src/main/chat/ui/chat-frame.gd
- project/src/main/chat/ui/label-typer.gd
- project/src/main/chat/ui/narration-frame.gd
- project/src/main/world/creature/creature-library.gd
- project/src/test/chat/test-tracery.gd
Before, messages like 'I'm #mood#' would fail
to be translated for two reasons.
Firstly, the translation happened when the message was displayed to the user, after all entities were replaced. So even if we had a translation for 'I'm #mood#', the translation engine would instead search for 'I'm angry' which was undefined.
Secondly, the translation engine did not translate replaceable entities like 'angry'.
Both these issues are now fixed.
> Localize chat messages with symbols, 'Hello #player#'

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/tutorial/SkillTallyItem.tscn
- project/src/main/puzzle/tutorial/skill-tally-item.gd
Other languages like Spanish have very long phrases for 'Move Left', so these boxes need to support more characters. They now shrink if the text doesn't fit.
> Tutorial skill tally items support smaller fonts.

- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
Tutorial chimes were playing at the start and end of each section, because the 'before_level_changed' signal was being emitted too frequently. This bug was introduced in 52c1784 when fixing bugs related to interrupting/restarting tutorials.
Closes #1782.
> Fixed redundant tutorial chimes.

- project/src/main/puzzle/restaurant-view.gd
- project/src/main/world/environment/restaurant/RestaurantView.tscn
RestaurantView now adds a listener instead of using a yield statement.
Fixed an incorrect reference to RestaurantView.current_creature_index. This is a virtual property which is only accessible through getters and setters.
> Removed RestaurantView yield statement.

- project/src/main/puzzle/combo-score-value-label.gd
This avoids a scenario where the player gets a -¥100 penalty which persists visually when they restart the level.
> Score label clears when a level is restarted.

- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/step-meter.gd
Various small refactorings encountered while working on the 'retry' button.
PieceManager now updates its state to 'none' when preparing a level. This avoids edge cases if a level is restarted while the piece is in an unusual state.
Fixed a bug where PuzzleState would try to launch a 0.0 second timer when ending a level.
Removed an unnecessary reference from PuzzleState to itself (PuzzleState.customer_scores)
Extracted a Puzzle._save_level_result() function.
Minor refactoring of StepMeter and improved comments. This new code layout makes it easier to rearrange the code later if we decide we want the step meter to become visible/invisible during a puzzle.
> Retry refactorings: 0.0 timers, piece states

- project/src/main/puzzle/piece/piece-dropper.gd
- project/src/main/settings/gameplay-settings.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-gameplay-speed.gd
- project/src/test/data/test-system-save-upgrader.gd
- project/src/test/data/test-system-save.gd
Player can adjust gameplay speed to make pieces fall faster or slower.
This only scales piece speeds by a constant factor, and does not have a meaningful effect on levels with instant gravity speeds. These will be addressed by #1752.
Closes #1751.
> Added 'gameplay speed' cheat to settings.

- project/src/main/puzzle/critter/mole.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-gameplay-speed.gd
Fixed bug where Gameplay Speed setting in settings menu was populated incorrectly. It was populated with the touch settings value instead of the speed settings value.
Fixed bug where Gameplay Speed setting was incorrectly given the label of 'Scheme' instead of 'Speed'.
> Bug: Gameplay speed settings menu.

- project/project.godot
- project/src/main/puzzle/level/gameplay-piece-speeds.gd
- project/src/main/puzzle/piece/piece-speeds.gd
- project/src/main/settings/gameplay-settings.gd
Adjusting the gameplay speed setting now enforces a minimum/maximum piece speed. This eliminates instant gravity speeds for players who enable a cheat code.
Closes #1752.
> Added 'maximum piece speed' setting.

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/settings/gameplay-settings.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-line-piece.gd
- project/src/test/data/test-system-save-upgrader.gd
Player can now toggle line pieces to appear in all levels.
Line pieces are added with their own weird 'nine bag' system. Adding line pieces to the existing piece bag would result in them appearing insanely frequently on levels which use a 2-piece bag. This nine bag system makes them appear as frequently as the eight turbo fat pieces on normal levels, and makes them appear with the same frequency on unusual levels.
This cheat can be toggled before or even during a level, which regenerates the piece queue with line pieces inserted throughout. Because this regenerates the piece queue from scratch, the player can toggle the cheat to reorder their pieces or get duplicates of pieces they already had in their current bag. This is an unintended consequence but I don't think it's worth worrying …
> Added line piece cheat.

- project/src/main/puzzle/level/gameplay-difficulty-adjustments.gd
- project/src/test/puzzle/level/test-gameplay-difficulty-adjustments.gd
Fixed a bug where the progress bar would remain empty even after dropping the first piece or clearing the first line. This is because the initial piece speed is handled as a milestone with value 0, but with the new adjustable difficulty changes this value was increased to 1.
The adjustable difficulty algorithm now uses the ceil() function instead of artificially capping the value at 1.
> Fixed progress bar bug, caused by adjustable difficulty

- project/assets/main/keybind/guideline.json
- project/assets/main/keybind/wasd.json
- project/src/main/ui/settings/keybind/settings-keybinds-control.gd
Keybinds now map joypad's L1/R1 buttons to hard drop. This is analogous to how we remap shift to hard drop as well, and makes sense for the same reasons -- Turbo Fat encourages chord-based play involving holding 2-3 buttons at once, and it is hard to hold multiple face buttons.
Reordered guideline keybinds; Space, Kp 8, Shift with 'Shift' going last. Shift is last because it corresponds to the hold key, so I like the idea of it being removed from the end of the list instead of deleted from the middle.
Improved WASD keybinds. Up and Space no longer hard drop with the WASD preset, but I've added KP Enter. Down no longer soft drops. This seems more consistent with traditional WASD controls for similar games, while enabling pinky hard drop which I find useful for high speed play.
Renamed …
> Improved keybinds. 'Numpad 2' -> 'Kp 2'

- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/states/prespawn.gd
- project/src/main/ui/settings/SettingsMenu.tscn
Extracted PieceManager._initialize_piece() utility method. This avoids bugs from duplicated code; some of these pieces were incorrectly initialized with the piece's tilemap which could cause complications down the road.
Prespawn state no longer explicitly changes to top out state. This simplifies the contract of PieceManager.spawn_piece(). We transition to the top out state anyways, so this logic was redundant.
> PieceManager refactoring: initialize_piece, prespawn top out

- project/src/main/puzzle/piece/piece-queue.gd
Playing part way through the cake tutorial and toggling the line piece cheat could result in an impossible setup. Since the piece order is randomized, regenerating the piece queue could give you the same piece twice and omit other important pieces.
Tutorials no longer regenerate the piece queue if the player toggles the cheat.
> bug: Line pieces could break cake tutorial.

- project/src/main/puzzle/piece-display.gd
Line pieces in the next piece queue were being offset slightly because of a math error.
> Fixed visual bug with line pieces in next queue

- project/src/main/puzzle/puzzle-state.gd
Fixed bug where player loses ¥200 when they lose their last life. This happens because PuzzleState.top_out() and PuzzleState.make_player_lose() both called each other, resulting in an infinite loop which was only avoided because one of them had a precondition. These two methods are no longer codependent.
Added some comments to describe the responsibilities of these two methods.
Closes #1823.
> Bug: Player loses ¥200 for last life. Comments.

- project/src/main/puzzle/piece/piece-queue.gd
Hish of the Turbo Fat discord still says Square Curse crashes on their machine with the line piece cheat enabled. I can't duplicate this or find any obvious reasin it would crash, but I noticed this section of code could, if it had a second bug I'm not seeing, increment piece_index and pieces.size() by one repeatedly causing an infinite loop. I've revised the code so it increments piece_index by 2 in this case which should avoid any potential infinite loop I'm not seeing.
> Minor tweak to line piece code, to resolve square curse crash

- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/VolumeSetting.tscn
- project/src/main/ui/settings/keybind/KeybindCustom.tscn
- project/src/main/ui/settings/keybind/KeybindPreset.tscn
These settings are all one line in English, but in Spanish or other languages they may overrun their boundaries. Settings labels will now wrap to multiple lines as necessary.
Closes #1840.
> Autowrap settings labels.

- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-menu.gd
Before, only a few tall settings items were in scroll containers such as the keybinds. This is currently sufficient, but if the game were localized into German or other languages with especially long words, the settings menu might need to scroll vertically.
> All settings items are in ScrollContainers.

- project/src/main/settings/misc-settings.gd
- project/src/main/ui/FontFitButton.tscn
- project/src/main/ui/font-fit-button.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-language.gd
- project/src/main/ui/theme/h6-font.tres
- project/src/main/ui/theme/h7-font.tres
- project/src/main/ui/theme/h8-font.tres
The 'Open User Folder' and 'Copy To Clipboard' buttons now change their font size depending on the current locale. This lets them use a smaller font for languages like Spanish where the button needs more text on it.
Added a locale_changed signal to MiscSettings. All locale changes now go through MiscSettings instead of TranslationServer.
Closes #1841.
> Smaller settings fonts for spanish. Locale signal.

- pybabel-extract.sh
pybabel-extract now calls msgmerge. Before, developers would need to manually perform this step whenever the .pot file was modified.
Alphabetized pybabel extract keywords.
> pybabel-extract calls msgmerge.

- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle.gd
Decreased scope of PieceQueue.shuffled_piece_types(), it is not referenced outside of this script.
Removed PuzzleMessages.show_buttons(), this method is no longer used.
> shuffled_piece_types() scope. Removed show_buttons().

- project/src/demo/packed-sprite-stress-test.gd
- project/src/main/puzzle/goop-glob.gd
- project/src/main/ui/creature-stress-test.gd
- project/src/main/utils/global.gd
- project/src/main/utils/resource-cache.gd
- project/src/main/utils/sfx-deconflicter.gd
- project/src/main/world/creature/dna-loader.gd
Replaced deprecated OS time calls like 'OS.get_ticks_msec()' with equivalent calls on the singleton Time instance
> Avoid deprecated OS time calls

- project/src/demo/world/free-roam-touch-buttons.gd
- project/src/main/chat/ui/chat-choice-tween.gd
- project/src/main/chat/ui/chat-pop-tween.gd
- project/src/main/editor/puzzle/veg-level-chunk-control.gd
- project/src/main/puzzle/burst-accent.gd
- project/src/main/puzzle/combo-score-value-label.gd
- project/src/main/puzzle/food-item.gd
- project/src/main/puzzle/goop-glob.gd
- project/src/main/puzzle/leaf-poofs.gd
- project/src/main/puzzle/pan/frying-pans-ui.gd
- project/src/main/puzzle/piece-display.gd
- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/puzzle/puzzle-touch-buttons.gd
- project/src/main/puzzle/score-value-label.gd
- project/src/main/puzzle/tutorial/skill-tally-item.gd
- project/src/main/ui/wallpaper/sticker-row.gd
- project/src/main/ui/wallpaper/sticker.gd
- project/src/main/utils/utils.gd
- project/src/main/world/career-camera.gd
- project/src/main/world/creature/creature-shadow.gd
- project/src/main/world/creature/emote-player.gd
- project/src/main/world/cutscene-camera.gd
- project/src/main/world/environment/frame-overworld-obstacle.gd
- project/src/main/world/environment/restaurant/undecorated-floor-tiler.gd
Replaced int(rand_range()) calls with randi_range() calls. According to Godot's documentation, int(rand_rage(3, 6)) has a theoretical (albeit infinitesimally small) chance to return 6. A replacement of randi_range(3, 5) is better. Godot has a built-in
RandomNumberGenerator.randi_range() method, but this is difficult to invoke from a static instance so I've written my own.
Replaced Vector(1, 1) calls with Vector.ONE, and Vector2(0, 0) calls with Vector.ZERO.
> randi_range(). Vector.ONE.

- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/tutorial/tutorial-cakes-module.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/puzzle/tutorial/tutorial-spins-module.gd
- project/src/main/puzzle/tutorial/tutorial-squish-module.gd
- project/src/test/puzzle/level/test-level-trigger-effects.gd
Moved tutorial delay constants from PuzzleState into TutorialModule.
TestLevelTriggerEffects improvements. Renamed 'to_json' tests to 'get_config' tests. Removed redundant tests. Made tests consistently go through LevelTriggerEffects.create() instead of directly calling constructors.
> Moved tutorial delay constants. TestLevelTriggerEffects.

- project/assets/main/puzzle/levels/practice/sandbox-expert.json
- project/assets/main/puzzle/levels/practice/sandbox-master.json
- project/assets/main/puzzle/levels/practice/sandbox-normal.json
- project/src/main/puzzle/level/rank-rules.gd
- project/src/test/puzzle/level/test-rank-rules.gd
The rank algorithm used to decrease the player's rank if they topped out. The decrease amount was configurable with a 'top_out_penalty' property. This is no longer the case, the player's score is now just decreased by ¥100 each time. Sometimes this affects their rank but sometimes it does not.
> Removed top_out_penalty.

- project/src/main/puzzle/puzzle-state.gd
Instead of a player losing after their 3rd top out, they were losing after their 4th top out.
> Fixed bug where player had too many lives.

- project/src/main/career/ui/CareerRegionSelectMenu.tscn
- project/src/main/ui/menu/PagedRegionPanel.tscn
- project/src/main/ui/menu/paged-region-buttons.gd
- project/src/main/ui/menu/region-description-panel.gd
- project/src/main/ui/menu/region-info-panel.gd
This provides symmetry with the PagedLevelPanel. It also simplifies the design of the upcoming 'unlock all regions' cheat.
> Separated locked/unlocked_region_focused signals.

- project/src/main/puzzle/level/phase-conditions.gd
- project/src/test/puzzle/level/test-level-triggers.gd
Exposed PhaseCondition fields to match LevelTriggerEffect. Some of these effects have fields corresponding to their behavior. Exposing these fields enables unit testing, otherwise we'd have to execute the effect and monitor its behavior which is cumbersome for configuration tests.
Renamed LineClearedPhaseCondition. Some names like 'which_lines' were ambiguous and differed from terms used in PieceWrittenPhaseCondition. They now consistently use less ambiguous terms like 'row' for the Y index, and 'index' for the sequential order.
Removed some unnecessary conditionals in LineClearedPhaseCondition's init method.
> PhaseCondition cleanup; LineClearedPhaseCondition

- project/src/main/career/career-region.gd
- project/src/main/career/ui/progress-board.gd
- project/src/main/world/career-map.gd
- project/src/main/world/career-world.gd
Many places were running the same 'region.length == CareerData.MAX_DISTANCE_TRAVELLED' check so it is now a utility method.
> Extracted CareerRegion.has_end() utility method

- project/src/main/puzzle/hold-piece-displays.gd
Before, the hold piece could be used after a tutorial but the window was not visible. The window is now made visible for the last part of a tutorial.
> Hold piece window is visible after tutorials.

- project/project.godot
- project/src/main/puzzle/tutorial/tutorial-cakes-module.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/puzzle/tutorial/tutorial-spins-module.gd
- project/src/main/puzzle/tutorial/tutorial-squish-module.gd
- project/src/main/puzzle/tutorial/tutorials.gd
This fixes a compile error where TutorialModule was referencing itself. But the compile error is sort of a code smell that maybe these constants were not where they were supposed to be. Now they're in a separate class.
> Extracted 'Tutorials' script with constants

- project/src/demo/world/creature/palette-editor-tab.gd
- project/src/main/career/ui/progress-board-trail.gd
- project/src/main/puzzle/chef-view.gd
- project/src/main/puzzle/critter/carrots.gd
- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/customer-view.gd
- project/src/main/puzzle/goop-globs.gd
- project/src/main/puzzle/puzzle-bg-loader.gd
- project/src/main/world/creature-spawner.gd
- project/src/main/world/creature/body.gd
- project/src/main/world/creature/head-sweat-squirts.gd
- project/src/main/world/creature/mouth-player.gd
- project/src/main/world/environment/grass-overworld-tiler.gd
- project/src/main/world/environment/invisible-obstacle-tiler.gd
- project/src/main/world/environment/obstacle-map-shadows.gd
- project/src/main/world/environment/pebble-overworld-tiler.gd
- project/src/main/world/spawn.gd
I modified most of these places to assign the resulting field to 'null' if the node path is null. There were a few areas (especially relating to CreatureVisuals) which already had null handling logic which behaved differently, preserving the field's states if the node path is null. I kept these the way it is, because that code is especially brittle if the underlying CreatureVisuals is null anyways. Assigning a null CreatureVisuals would never do anything helpful.
> Scenes calling get_node() handle nulls better

- project/src/main/career/career-data.gd
is_restaurant_decorated() and is_sensei_turbo() used hardcoded distance constants which introduced bugs when rebalancing the distances in Career Mode. I've replaced them with more complex logic which references the chapter 1 and chapter 2 regions, so that they will adjust automatically.
> Replaced hardcoded 'is restaurant data' 'is turbo' constants

- project/src/demo/toolkit/fix-chats-button.gd
- project/src/main/chat/chat-tree.gd
- project/src/main/chat/chatscript-parser.gd
Instead of the ChatscriptParser pushing warnings directly, it now adds these to the ChatTree's metadata. Usually these are logged to the console, but for some situations such as the ReleaseToolkit's FixChatsButton, these messages are suppressed so they can be collected and reported a different way.
> Added ChatTree warnings.

- project/src/main/puzzle/line-filler.gd
Instead of filling ALL empty lines, LineFiller now only fills the top few.
This opens the possibility for levels which fill in pickups every 3 rows, but leave the other 2 rows empty.
This causes a potential negative interaction with levels like 'above and below' which insert lines in the middle of the playfield as a part of a line clear. Our new LineFiller algorithm will only look at the top 3 rows, so it will ignore empty lines in the middle of the playfield. This seems OK -- if a level like that wanted to have 'filled lines' in the middle of the playfield it could insert them, instead of inserting empty lines.
> LineFiller can now leave empty lines.

- project/src/main/music/music-transition.gd
- project/src/main/ui/scene-transition-cover.gd
- project/src/main/utils/scene-transition.gd
A few places confused fade_in_duration with fade_out_duration, or relied exclusively on the SCREEN_FADE_IN_DURATION constants instead of the customizable 'next_fade_in_duration' fields.
Renamed 'SCREEN_FADE_IN_DURATION' to 'DEFAULT_FADE_IN_DURATION'
> SceneTransition duration bug fixes

- project/src/demo/career/ui/progress-board-demo.gd
- project/src/main/career/ui/progress-board.gd
Fixed bug where ProgressBoard would make it look like the player was progressing through Starberry Mountain even if the player quit.
The player's progress was still updated appropriately, but visually it would show them hopping along the path. Now it only advances then the number of steps they advance according to the 'distance_earned' variable.
> ProgressBoard progress for Starberry Mountain

- project/src/main/ui/settings/settings-menu.gd
- project/src/main/utils/SceneTransition.tscn
Fixed bug where settings menu did not hide itself in some cases.
Moved SceneTransition to layer 10 so that it will cover the settings menu, even if it is not hidden.
> Settings menu always hides itself.

- project/src/main/world/environment/restaurant/TurboFatRestaurant.tscn
This was accidentally removed when adding the undecorated restaurant asset.
> Restored turbo fat restaurant shadow

- project/src/main/world/environment/frame-overworld-obstacle.gd
If FrameOverworldObstacle had its frame or flip_h value assigned, it would throw a null error. This is because the setter would immediately reference a null $Sprite.
FrameOverworldObstacle no longer throws these errors.
> Fixed null error in FrameOverworldObstacle.

- project/src/demo/world/FreeRoam.tscn
- project/src/main/world/creature/ViewportCreatureOutline.tscn
These properties were automatically unassigned when the scenes were opened in the Godot editor; presumably they are redundant or unnecessary
> Removed scene cruft from FreeRoam, ViewportCreatureOutline

- project/src/main/world/environment/poki/PokiCrowd.tscn
- project/src/main/world/environment/poki/Tent.tscn
- project/src/main/world/environment/poki/poki-crowd.gd
Increased size of Poki Desert tents.
Poki desert's crowds no longer animate in the editor. This was polluting .tscn files with unnecessary changes.
> Poki fixes: Tent shadows, crowd editor animations

- project/assets/main/chat/career/lemon-2/boss-level-end-2.chat
This is redundant, but consistent with the 'Lemony Thickets' boss level.
> 'Welcome To Turbofat' boss level advances player to the next region.

- project/src/main/career/career-flow.gd
- project/src/main/data/player-save.gd
The game had a savescum prevention feature which sabotaged the player's save data before starting a new puzzle. However, this was broken in c081854f632d4e26cc1f51c737ac5ab2c6ab7fe2 when the save data was replaced with an asynchronous system which didn't save right away.
I've expanded this code so that it is asynchronous as well, and the player's save data is temporarily sabotaged immediately before being written to disk, and then restored.
> Fixed career savescum bug.

- project/assets/main/chat/career/lemon-2/boss-level.chat
- project/assets/main/chat/career/lemon/010-a.chat
- project/assets/main/chat/career/lemon/020-b.chat
- project/assets/main/chat/career/lemon/030-c.chat
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
Before, the first customer would be served, and the other customers would be seated randomly. They might be served second and third, or they might never be served at all.
Added missing customer tags to some cutscenes with multiple customers.
Closes #1479.
> Priority customers served consecutively. Missing customer tags.

- project/src/demo/toolkit/fix-creatures-button.gd
Lemony Thickets has an invalid creature id 'nest' which snuck by for awhile, and it's taken a lot of work to figure out if this is a creature that was renamed, removed, or just a typo.
> ReleaseToolkit reports bad population data.

- project/src/demo/toolkit/fix-chats-button.gd
- project/src/demo/toolkit/fix-creatures-button.gd
- project/src/main/chat/chat-tree.gd
- project/src/main/chat/chatscript-parser.gd
- project/src/test/chat/test-chat-tree.gd
- project/src/test/chat/test-chatscript-parser.gd
Fixed Chatscript suppress_warnings metadata. This was doing the exact opposite of what it was supposed to do, and only reporting warnings if suppress_warnings was true. I've also fixed many push_warning calls in ChatTree which seemed like they were accidentally sidestepping this mechanism.
Added ChatTree.creature_ids field. In most cases this is redundant with spawn_locations, but the walking cutscenes don't define spawn locations even though they have 2-3 characters (player, sensei, narrator). These walking cutscenes were reporting that they had 0 characters which caused false positive ReleaseToolkit warnings.
Fixed ChatTree.reset() method, which was skipping several newly introduced fields.
> Chatscript fixes: suppress_warnings, creature_ids, reset

- project/src/main/career/population.gd
This prevents customers from showing up in career mode, and later remarking something like "I've never eaten here before!" during a cutscene.
> Population.random_customer() honors the 'customer_if' flag

- project/project.godot
- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/pickups.gd
- project/src/main/puzzle/piece/next-piece-displays.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/squish-fx.gd
- project/src/main/puzzle/playfield-fx.gd
- project/src/main/puzzle/star-seeds.gd
Expanded Pickups.get_pickup() method name to
get_pickup_food_type(). Other scripts want access to the actual pickup nodes so that they can figure out the pickup's state and position.
Exposed SquishFx fields. The upcoming nighttime SquishFx needs access to these fields to copy its state.
New utility methods: Pickups.get_cells_with_pickups(), PieceManager.get_squish_fx(), NextPieceDisplays.get_display()
> Playfield fx/pickup refactoring for night mode.

- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/puzzle.gd
The new onion levels want to start onions in the air, so they want to be able to add an onion immediately when the level starts -- or even when it first loads. These new phases allow for this.
> New level trigger phases: 'before_start', 'start'

- project/src/main/puzzle/level/level-trigger.gd
If a level trigger defines multiple conditions with the same effect, it used to only fire if ALL conditions were met. It now fires if ANY conditions are met.
This allows for more complex combinations of triggers, such as triggers which fire on the 1st, 2nd, 11th, 12th, 21st and 22nd piece, and so on.
> LevelTrigger conditions are now 'any', not 'all'

- project/src/demo/puzzle/critter/onion-demo.gd
- project/src/demo/puzzle/puzzle-critter-demo.gd
- project/src/main/puzzle/critter/Onion.tscn
- project/src/main/puzzle/critter/OnionStateMachine.tres
- project/src/main/puzzle/critter/onion.gd
- project/src/main/puzzle/critter/onions.gd
- project/src/main/puzzle/night-mode-toggler.gd
- project/src/main/puzzle/onion-playfield-tile-map.gd
- project/src/main/puzzle/onion-puzzle-tile-map.gd
- project/src/main/puzzle/puzzle.gd
These bugs especially affected levels that begin at nighttime and toggle to daytime. When restarting in nighttime, sometimes the onion wouldn't launch, or it would launch even though it was already in the sky.
The onion now has the ability to skip to the 'floating in the air' mode which is used when restarting a nighttime level.
> Fixed bugs with onion, nighttime when restarting levels.

- project/src/main/ui/cheat-code-detector.gd
- project/src/main/ui/menu/level-submenu.gd
- project/src/main/ui/menu/paged-level-panel.gd
- project/src/main/ui/menu/practice-menu.gd
The 'unlock' cheat affects both the region and level panel, and was playing a doubled sound effect. The level panel now disables its cheat sound.
> Bug: cheat sfx were playing twice in practice menu

- project/src/main/ui/menu/paged-level-buttons.gd
- project/src/main/ui/menu/paged-region-buttons.gd
Without this yield statement, focus is lost.
> Fixed bug where 'unlock' cheat didn't grab focus correctly.

- project/src/main/puzzle/critter/carrots.gd
- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/piece/puzzle-shadow-map.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/squish-map.gd
For plural cases, I replaced them with 'x_coords' and 'y_coords' because I think is more intuitive than 'xs' or 'ys'. A variable named 'ceiling_xs' seems like it could be referencing 'excess' or 'extra small' whereas 'ceiling_x_coords' is unambiguous.
> Replaced 'row/col' with 'y/x' where appropriate

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/squish-map.gd
A dictionary of 5-10 ints is more efficient than a 2-dimensional array of 200 ints. It also requires less code, as it's a one-liner to clear or initialize it, and it handles out-of-bounds scenarios without crashing.
> Changed SquishMap stretch_pos type from array to dict.

- project/src/main/music/MusicPlayer.tscn
- project/src/main/music/music-player.gd
Alphabetized music player nodes, these nodes were in a random order before. There were about 20 making it hard to find a specific song.
Moved MusicPlayer's all_bgms field; public fields should go before private fields.
Alphabetized MusicPlayer's music fields -- most of these were mostly in order, but '_upbeat_bgms' had some mistakes.
> Reordered MusicPlayer fields/nodes.

- project/src/demo/puzzle/puzzle-demo.gd
- project/src/main/career/career-cutscene-library.gd
- project/src/main/puzzle/critter/critters.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/puzzle/puzzle.gd
- project/src/test/puzzle/level/test-level-trigger-effects.gd
Alphabetized PuzzleDemo's keys.
Reordered carrots/moles/onions in alphabetical order where it made sense. I did not reorder the nodes in the Critters.tscn because carrots should cover everything, it would look strange if they were not in front.
Reordered CareerCutsceneLibrary methods; public methods should precede private methods.
> Reorder: puzzle-demo, critters, CareerCutsceneLibrary

- project/src/demo/world/environment/restaurant/restaurant-puzzle-scene-demo.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/utils/utils.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/environment/restaurant/restaurant-puzzle-scene.gd
- project/src/main/world/obstacle-spawner.gd
A lot of puzzle code allows a customer_index of -1, where -1 either means the current customer or a random customer. This behavior was undocumented and unintuitive. It's now documented.
Removed unnecessarily verbose 'The input arrays are not modified; this code is adapted from Apache Commons' comments. The input arrays not being modified seems implicit, and I'd expect a warning if they WERE modified. The code being adapted from an old version of Apache Commons is also not helpful information -- the code doesn't really resemble Apache Commons anymore, and I had to adapt the algorithms anyways.
Fixed some minor comment typos.
> Improved comments: customer_index, apache commons

- project/src/demo/puzzle/puzzle-demo.gd
- project/src/main/puzzle/OnionHoldPieceDisplays.tscn
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/texture-metaball.shader
This shader parameter dates back to when the shader was authored in June 2020, but the parameter has never done anything.
> Removed goop_texture_offset shader parameter.

- project/src/main/chat/chatscript-parser.gd
Replaced chatscript 'character_name' variable/field names with 'creature_id' which is more accurate. These are usually the same but sometimes creatures with absurd names will have shorter ids.
> Chatscript character_name -> creature_id

- project/src/main/puzzle/piece/NextPieceDisplays.tscn
- project/src/main/puzzle/restaurant-view.gd
Removed unused scroll_to_new_customer() parameter.
Removed unused 'GoopMain' and 'GoopGutter' nodes. These nodes were introduced in bf295952, but according to #186 I decided not to do it because it seemed unnecessary.
> Unused code: GoopMain, GoopGutter, new_customer_index

- project/src/main/career/ui/progress-board-clock.gd
- project/src/main/career/ui/progress-board-player.gd
- project/src/main/chat/ui/chat-choice-tween.gd
- project/src/main/chat/ui/chat-pop-tween.gd
- project/src/main/chat/ui/chat-squish-tween.gd
- project/src/main/music/music-tween.gd
- project/src/main/puzzle/critter/carrot.gd
- project/src/main/puzzle/critter/carrots.gd
- project/src/main/puzzle/goop-glob.gd
- project/src/main/puzzle/hud-flash.gd
- project/src/main/puzzle/leaf-poof.gd
- project/src/main/puzzle/pickup.gd
- project/src/main/puzzle/puzzle-money-hud.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/tutorial/skill-tally-item.gd
- project/src/main/ui/music-popup-tween.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/emote-player.gd
- project/src/main/world/environment/ripple-sprite.gd
Tween's interpolate_property function's 'from' parameter defaults to the current value. Explicitly specifying the from parameter is redundant.
> Removed redundant tween from values.

- project/src/demo/world/environment/lemon/Lemon2FreeRoamEnvironment.tscn
- project/src/demo/world/environment/lemon/LemonFreeRoamEnvironment.tscn
- project/src/demo/world/environment/marsh/MarshFreeRoamEnvironment.tscn
- project/src/demo/world/environment/poki/PokiFreeRoamEnvironment.tscn
- project/src/demo/world/environment/restaurant/TurboFatFreeRoamEnvironment.tscn
- project/src/demo/world/environment/restaurant/UndecoratedTurboFatFreeRoamEnvironment.tscn
- project/src/main/world/OverworldExit.tscn
- project/src/main/world/environment/lemon/Lemon2Environment.tscn
- project/src/main/world/environment/lemon/LemonEnvironment.tscn
- project/src/main/world/environment/marsh/MarshEnvironment.tscn
- project/src/main/world/environment/overworld-environment.gd
- project/src/main/world/environment/poki/PokiEnvironment.tscn
- project/src/main/world/environment/restaurant/TurboFatEnvironment.tscn
- project/src/main/world/environment/restaurant/UndecoratedTurboFatEnvironment.tscn
- project/src/main/world/overworld-exit.gd
OverworldExit is now a sprite. I've removed its hit detection logic and its CollisionShape2D. None of this is necessary since there is no longer the functionality of stepping on the exit to transition to a new area.
Removed spawns from FreeRoam environments. These were originally used because cinematics took place in these environments, but they are now just used for demos and don't need spawns.
> Simplified OverworldExit. Removed unused spawns.

- project/src/demo/world/environment/marsh/MarshFreeRoamEnvironment.tscn
- project/src/demo/world/environment/restaurant/TurboFatFreeRoamEnvironment.tscn
- project/src/main/world/creature-spawner.gd
- project/src/main/world/environment/lemon/BrotSpotStool.tscn
- project/src/main/world/environment/marsh/ButtercupStool.tscn
- project/src/main/world/environment/marsh/ButtercupStoolSpawnerG.tscn
- project/src/main/world/environment/marsh/ButtercupStoolSpawnerW.tscn
- project/src/main/world/environment/marsh/MarshEnvironment.tscn
- project/src/main/world/environment/restaurant/BoxStool1.tscn
- project/src/main/world/environment/restaurant/BoxStool2.tscn
- project/src/main/world/environment/restaurant/BoxStool3.tscn
- project/src/main/world/environment/restaurant/TurboFatEnvironment.tscn
- project/src/main/world/environment/restaurant/TurboFatStool.tscn
- project/src/main/world/environment/restaurant/UndecoratedTurboFatEnvironment.tscn
- project/src/main/world/environment/stool.gd
- project/src/main/world/spawn.gd
Instead of creatures and spawn points needing an explicit 'stool_path' assigned, a corresponding stool is now found by searching for the nearest stool. Stools within a very narrow radius (4 units) are considered 'matching' and will be returned.
> Replace 'stool_path' property with proximity logic

- project/src/main/world/environment/restaurant/RestaurantSpawns.tscn
- project/src/main/world/environment/restaurant/TurboFatEnvironment.tscn
- project/src/main/world/environment/restaurant/UndecoratedTurboFatEnvironment.tscn
TurboFatEnvironment and UndecoratedTurboFatEnvironment had two copies of the same spawns which could cause bugs where cutscenes wouldn't play correctly if the player encountered them too early.
> Extracted 'RestaurantSpawns' scene

- project/src/demo/chat/ui/ChatUiDemo.tscn
- project/src/demo/chat/ui/chat-ui-demo.gd
- project/src/main/chat/ui/chat-ui.gd
The only functionality which ChatUi needs OverworldUi for is assigning nametag sides. If no OverworldUi is present, it just doesn't move the nametags.
> ChatUi functions without OverworldUi.

- project/src/main/puzzle/piece/piece-types.gd
- project/src/test/puzzle/piece/test-piece-kicks-domino.gd
All piece types should be a letter, because they show up to the player as 'T-spin' or 'P-spin'. Showing the player they performed a '--spin' is confusing.
> Chagned domino from '-' to 'd'

- project/src/test/puzzle/level/test-phase-conditions.gd
These had an off-by-one error introduced by recent refactorings.
> Fixed failing piece written phase condition tests.

- project/src/main/puzzle/piece/piece-squisher.gd
Fixed bug with squish drop signals. Before, if you performed squish drop inputs, it would count as a squish move even if no squish was necessary.  Now it only performs a squish drop if the piece could not reach its destination with a regular drop.
> Squish drops only emit signals if squishing is necessary.

- project/src/main/puzzle/critter/mole.gd
- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/foods.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/puzzle-tile-map.gd
The 'Foods' class now not only includes colors for food crumbs, but also pieces and vegetables. These fields are referenced by a new PuzzleTileMap.crumb_colors_for_cell() method.
Refactored some unnecessary duplicate code in mole.gd. Documented an undocumented 'new_state' parameter.
> Shark refactorings; crumb colors, mole comments

- project/src/main/puzzle/piece/piece-types.gd
This is usually unnecessary, but sharks can whittle an O piece down where kicks are helpful. Currently, eaten pieces inherit kicks from the original piece, so eaten O pieces had no kicks at all. They now use the JLSZ kick table.
> Added kicks for O piece.

- project/src/main/puzzle/critter/shark-state-dancing-end.gd
- project/src/main/puzzle/critter/shark-state-dancing.gd
- project/src/main/puzzle/critter/shark-state-eating.gd
- project/src/main/puzzle/critter/shark-state-fed.gd
- project/src/main/puzzle/critter/shark-state-none.gd
- project/src/main/puzzle/critter/shark-state-squished.gd
- project/src/main/puzzle/critter/shark-state-waiting.gd
- project/src/main/puzzle/critter/sharks.gd
When a shark is in the waiting '...' state, they turn invisible if touched by a piece. Before, they'd only turn back visible in certain circumstances. They now turn visible when entering any other state, or when the piece is placed.
Sharks no longer play sound effects when invisible. Before, you'd sometimes hear 'poof sounds' when they entered/exited the none state from the waiting state.
> Fixed invisible shark behavior: permanent invisible bug, sfx

- project/src/main/puzzle/level-timer-manager.gd
Before, timers were sometimes behaving unexpectedly. For example, two timers with intervals of 2s and 4s should fire simultaneously half the time, but they were falling out of sync.
> LevelTimerManager now processes in the physics step; not the idle step

- project/src/main/puzzle/critter/sharks.gd
- project/src/main/puzzle/puzzle-state.gd
Fixed a bug in PuzzleState which caused all sharks to give $20 when eating a piece, instead of giving the displayed reward.
Increased shark payouts; even when the medium sharks were bugged to give out $20, it wasn't enough to compensate for the clumsiness/slowness of playing with this gimmick. Honestly, we could probably double it again.
> Shark scoring bugfix, increases: 20,20,20 -> 10,20,50

- project/src/main/puzzle/critter/Shark.tscn
- project/src/main/puzzle/critter/shark.gd
The 'dance-end' state now shows a '!' bubble instead of a '...' bubble. This helps express the urgency of 'Hurry, you'll miss it!' better, plus we're already using the '...' bubble for a different purpose.
The 'dance-end' animations were using incorrect frames, resulting in a jerky transition from the 'dance' state. Actually, the large shark was using the wrong frames entirely causing it to briefly become a small shark.
> Shark animation fixes: '!', 'dance-end'

- project/src/demo/puzzle/PuzzleCritterDemo.tscn
- project/src/demo/puzzle/puzzle-critter-demo.gd
- project/src/main/puzzle/critter/shark.gd
- project/src/main/puzzle/critter/sharks.gd
Sharks eating wouldn't purge their 'next_states' queue, meaning that after eating, they would go back to normal if the 'advance_sharks' trigger effect occurred. Sharks eating now purge their 'next_states' queue.
Sharks being squished wouldn't pop their next state if the 'advance_sharks' trigger effect had just triggered. Sharks being squished or eating now pop their next state no matter what.
Added a 'shark patience toggle' to the PuzzleCritterDemo to test patience related bugs.
> Bug: Sharks could enter/exit the eating state at unusual times

- project/src/main/puzzle/critter/sharks.gd
Before, mangling a T-piece with small sharks would still report a 'T-spin', but mangling a T-piece with a medium shark would report a 'D-spin' because it is now a domino. ...I've changed it so they will all report a 'T-Spin' for consistency.
Levels can still be created which have dominos, and those will report a 'D-spin'.
> Mangled dominos now keep original piece names.

- project/src/main/puzzle/critter/shark.gd
The shark celebrations are confusing, and players might try to feed a shark that's already eaten. The celebrations are now shorter, but it's possible we should do something else too, like lower their opacity or change their color.
> Shorter shark celebrations.

- project/src/main/puzzle/box-builder.gd
- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/critter/sharks.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/playfield.gd
'sharks for playfield' are now refreshed once after all lines are deleted/inserted, rather than refreshing them for every inserted lines.
Playfield.is_clearing_lines() now returns true throughout LineClearer._delete_lines() method. Before, is_clearing_lines() returned false while triggers were firing, meaning bugs related to inserted/deleted lines were really difficult to work around.
> Fixed bug with sharks deleting during multiline inserts

- project/src/demo/puzzle/puzzle-critter-demo.gd
I noticed a performance hiccup when many sharks were added at once, this demo now lets us show that more easily. We can also test similar scenarios with many moles or many carrots.
> Added performance test keys to PuzzleCritterDemo

- project/project.godot
- project/src/main/puzzle/critter/Critters.tscn
- project/src/main/puzzle/critter/Shark.tscn
- project/src/main/puzzle/critter/shark-clouds.gd
- project/src/main/puzzle/critter/shark-crumbs.gd
- project/src/main/puzzle/critter/shark-tile-map-pool.gd
- project/src/main/puzzle/critter/shark-tooth-cloud.gd
- project/src/main/puzzle/critter/sharks.gd
- project/src/main/puzzle/level/level-triggers.gd
- project/src/test/puzzle/level/test-level-triggers.gd
Sharks were taking about 40 ms to instance. This meant levels which spawned many sharks at once could have a half second of lag while all of the sharks were created. This stemmed from the fact that PuzzleTileMaps are expensive to create.
Shark PuzzleTileMap instances are now pooled in SharkTileMapPool. This lets us instance them at the start of the level and reduce lag. They're only instanced for levels with sharks. They're also instanced in a thread which reduces lag even further.
> Enable object pooling for Shark PuzzleTileMaps

- project/src/main/puzzle/line-clearer.gd
Before, float_fall levels would not emit line_cleared triggers properly because the index of the deleted line did not match the index of the cleared line. Now, line_cleraed triggers are emitted as long as ANY lines are being cleared. This means it'll trigger properly for float_fall, but still won't trigger during a top out.
> Fixed line_cleared triggers for float_fall levels

- project/src/main/puzzle/puzzle-tile-map.gd
This doesn't have any noticable gameplay effect, but it's consistent with other similar code.
> PuzzleTileMap uses preload() instead of load()

- project/src/main/puzzle/piece/piece-manager.gd
If a shark ate pieces as a result of initial movement/rotation, the piece manager would incorrectly think the next queue was empty. It now caches this fact before initial movement to prevent the level from eating.
> Bug: Level immediately ends if a shark eats a piece immediately

- project/project.godot
- project/src/main/puzzle/critter/call-queue.gd
- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/critter/sharks.gd
Critters being added/removed during line clears is messy for multiline clears. For example, critters might spawn as a result of a top line being cleared, be placed on the bottom line, which is then cleared as well. This might result in a level which is supposed to spawn 5 critters only spawning 3, because the other 2 spawned in strange places.
This scenario is now handled by a new "CallQueue". Critters spawning/advancing is now delayed until after all lines are cleared. Critters removing is still handled immediately -- this removal occurs in a specific cell, so if we didn't handle it immediately those coordinates wouldn't track to the critter's new location without a lot of work.
Fixed some shark/mole comments referencing the wrong critter.
> Avoid adding/removing critters during line clears.

- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/critter/sharks.gd
Shifting rows could result an _moles_by_cell entry being overwritten. The result was that a critter would remain on the playfield, but would be inaccessible and never advance or be affected by pieces.
Shifting rows now remove conflicting critters. This shouldn't happen often, and only in weird scenarios where multiple critters are spawning in the same column multiple times during a line clear. But it should now work properly.
> Fixed orphaned critters when shifting rows.

- project/src/main/puzzle/line-clearer.gd
These line clear triggers were tweaked on 940c3d4e2 but they inadvertently started firing during level finishes. This results in weird things happening like the player finishing a level, and 15 carrots launching or 10 sharks appearing.
> Fixed bug where line clear triggers happened on finish

- project/src/main/puzzle/level-timer-manager.gd
Before, puzzles would sometimes start and critters would already be appearing before the player had control.
> Puzzle timers reset on puzzle start.

- project/src/main/puzzle/critter/sharks.gd
Sharks have a 'patience' meter which counts down, and then they disappear. If a shark is triggered where their patience decreases when a piece is placed, and then they eat a piece, the game would crash. The game crashed because the piece would be eaten (counting as a placed piece) making the shark disappear before they ate.
Sharks now transition to the 'eating state' before the piece is eaten.
> Bug: Sharks crash eating on their last 'patience' turn

- project/src/main/chat/chat-event.gd
- project/src/main/data/player-save.gd
- project/src/main/editor/puzzle/playfield-editor-control.gd
- project/src/main/puzzle/critter/mole.gd
- project/src/main/puzzle/critter/onion-config.gd
- project/src/main/puzzle/critter/onion.gd
- project/src/main/puzzle/critter/shark.gd
- project/src/main/puzzle/line-filler.gd
- project/src/main/puzzle/line-inserter.gd
- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/settings/keybind-settings.gd
- project/src/main/ui/wallpaper/sticker-row.gd
- project/src/main/utils/packed-sprite.gd
- project/src/main/utils/utils.gd
- project/src/main/world/chat-key-pair.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/walking-buddy.gd
- project/src/main/world/overworld-ui.gd
Godot 3.x let us treat integers/arrays/dictionaries as boolean values, but Godot 4.x doesn't let us do that anymore. In preparation for the Godot 4 upgrade, I'm replacing these boolean evaluations.
> Replace 'if foo' with 'if not foo.empty()'

- project/src/demo/world/FreeRoamTouchButtons.tscn
- project/src/demo/world/free-roam-touch-buttons.gd
Overriding native methods causes an error in Godot 4. Rather than overriding show/hide, we now react to shown/hidden signals.
> Rewrote FreeRoamTouchButtons to avoid overridding show/hide

- project/src/demo/music/music-player-demo.gd
MusicPlayerDemo allows toggling of night filter with 'N'.
Fixed bug where fading in MusicPlayerDemo would usually cause a crash, because no song was playing.
> MusicPlayerDemo night filter, fade in error

- project/src/main/puzzle/line-clearer.gd
LineClearer had a slice call which, for most levels, resulted in Array.slice(0, -1) which actually has no effect. In Godot 4.x, the slice function is exclusive instead of inclusive, meaning the code translates to Array.slice(0, 0) which empties the array, introducing a bug.
It's better just to preempt this bug by avoiding this cheeky code.
> Fix cheeky LineClearer slice call.

- project/src/main/world/creature/creature-sfx.gd
- project/src/main/world/creature/creature.gd
Removed call to `mouth_hook.set_elevation` in editor
> Fixing creature tool script errors

- project/src/main/world/environment/IndoorShadows.tscn
- project/src/main/world/environment/OutdoorShadows.tscn
Godot 3.x has no way to render translucent groups of nodes. We originally thought it would be feasible to upgrade to Godot 4.x and leverage Godot 4.x CanvasGroups, but we cannot migrate to Godot 4 due to critical missing features. More information is available on the godot-4-transition page in the wiki.
Closes #2060.
> Opaque indoor/outdoor shadows.

- project/src/main/puzzle/critter/Onion.tscn
Fixed bug where onion monster's dirt patch would appear at the end of night time, only to immediately disappear and reappear again.
Closes #2057.
> Fixed onion monster dirt patch visibility

- project/src/main/puzzle/piece/piece-physics.gd
When flipping a U piece with initial rotation, if the player topped out, the piece would spawn one row too low. This could also happen with S and Z pieces, or any other piece which is in a lower position when flipped.
Closes #1980.
> Fixed initial flipped U-piece top out bug

- project/src/demo/InputMapDemo.tscn
- project/src/demo/input-map-demo.gd
This demo was useful on the godot-4 branch for diagnosing bugs introduced by keybind-manager.gd. These bugs were caused by mismatches between the scancodes in our code and Godot 4's scancodes, but there could be similar bugs in the input map in the future if Godot updates.
> Added InputMapDemo.

- project/src/main/editor/puzzle/editor-playfield.gd
- project/src/main/puzzle/critter/shark-clouds.gd
- project/src/main/puzzle/critter/shark-crumbs.gd
- project/src/main/puzzle/critter/shark-tooth-cloud.gd
- project/src/main/puzzle/critter/sharks.gd
- project/src/main/puzzle/night/night-playfield-tile-map.gd
- project/src/main/puzzle/piece/piece-dropper.gd
- project/src/main/puzzle/playfield-fx.gd
- project/src/main/puzzle/squish-map.gd
- project/src/main/settings/graphics-settings.gd
Changed 'tile map' to 'tilemap' in code comments. The godot documentation is inconsistent, but it usually refers to it as 'tilemap' or 'TileMap' and rarely as 'tile map'.
Changed some code to use Vector2 constants instead of hardcoding 'Vector2(0, -1)'
Added parameters to PieceDropper signals.
Removed unnecessary set_feeding_animation method.
Changed PlayfieldFx._color_tile_indexes field to conform to our conventions for dictionaries.
> Refactor: 'tile map', Vector2.UP, PieceDropper signals

- project/src/main/career/career-data.gd
- project/src/main/career/ui/career-time-label.gd
- project/src/main/career/ui/progress-board-clock.gd
- project/src/main/editor/puzzle/editor-pickups.gd
- project/src/main/editor/puzzle/pickup-level-chunk-control.gd
- project/src/main/puzzle/critter/mole.gd
- project/src/main/puzzle/critter/shark.gd
- project/src/main/puzzle/foods.gd
- project/src/main/puzzle/night/night-pickup.gd
- project/src/main/puzzle/pickup.gd
- project/src/main/puzzle/pickups.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/puzzle/star-seed.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/main/world/environment/goop-overworld-tiler.gd
Fixed dictionaries to be consistently named '_foos_by_bar', with the first noun plural and the second noun singular. There are a few exceptions where the dictionary's key is actually a hybrid key with several different parts, in which case it actually should be plural.
Fixed enums to be consistently singular with names like 'State' and 'TileType' instead of 'States' and 'TileTypes'
> Refactor: Plural enums, dictionaries

- project/src/main/puzzle/critter/moles.gd
Moles no longer implicitly disappear when their state queue is exhausted. It seems more intuitive that they should just remain in their final state, similar to how sharks behave.
Moles now explicitly enter the 'none' state after finding a shark; a 'Mole.NONE' state is appended to the end of their state queue.
> Refactor: Mole 'final state' logic mirrors shark logic

- project/src/main/career/career-rewinder.gd
- project/src/main/chat/chat-history.gd
- project/src/main/chat/chatscript-parser.gd
- project/src/main/editor/creature/creature-editor-nametags.gd
- project/src/main/utils/resource-cache.gd
- project/src/main/world/creature/creature-library.gd
- project/src/test/career/test-career-rewinder.gd
- project/src/test/data/test-player-save-upgrader.gd
A few dictionaries had comments saying things like 'mapping from creatures to nametag panels' which is implied by our naming convention. A few dictionaries had comments like 'creature_to_nametag' which oppose our dictionary conventions. I've changed some of these places to be consistent.
> Refactor: dictionary names include '_by_'

- project/src/demo/chat/ui/chat-frame-demo.gd
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/puzzle/bursts.gd
- project/src/main/puzzle/critter/carrot.gd
- project/src/main/puzzle/critter/shark-clouds.gd
- project/src/main/puzzle/critter/shark-tooth-cloud.gd
- project/src/main/puzzle/goop-glob.gd
- project/src/main/puzzle/leaf-poofs.gd
- project/src/main/puzzle/night/night-sky.gd
- project/src/main/ui/menu/loading-orb.gd
- project/src/main/ui/wallpaper/sticker-row.gd
- project/src/main/utils/markov-model.gd
- project/src/main/world/career-world.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/environment/frame-overworld-obstacle.gd
- project/src/main/world/environment/grass-overworld-tiler.gd
- project/src/main/world/environment/lemon/lemon-tree.gd
- project/src/main/world/environment/mile-marker.gd
- project/src/main/world/environment/pebble-overworld-tiler.gd
- project/src/main/world/environment/poki/poki-crowd.gd
- project/src/main/world/environment/poki/puddle-overworld-tiler.gd
- project/src/main/world/environment/poki/tent-spawner.gd
- project/src/main/world/environment/restaurant/carpet-tiler.gd
- project/src/main/world/environment/restaurant/hello-timer.gd
- project/src/main/world/environment/restaurant/kitchen-floor-tiler.gd
- project/src/main/world/environment/restaurant/undecorated-floor-tiler.gd
At a glance, stuff like 'randf() > 0.35' looks like a 35% chance and 'randf() < 1.0' looks like a 100% chance. It takes a little more thought and mental arithmetic to figure out what it's actually doing. 'randf() <= 0.65' is easier to read.
> Refactoring: Remove 'randf() >' calls

- project/src/main/music/music-tween-manager.gd
- project/src/main/puzzle/critter/carrots.gd
- project/src/main/world/creature/emote-player.gd
Made min_volume check consistent; instead of checking if two flats are equal or if their difference is within a threshold, we now use Godot's built-in 'is_equal_approx'
EmotePlayer no longer uses 'yield' to wait for a tween to finish. It now uses tween's tween_callback functionality. This avoids an error if the scene is disposed while yielding.
> Refactor: min_volume check, post_unemote

- project/src/demo/ui/menu/BadSaveDataControlDemo.tscn
- project/src/demo/ui/menu/bad-save-data-control-demo.gd
- project/src/main/ui/menu/BadSaveDataControl.tscn
- project/src/main/ui/menu/SplashScreen.tscn
- project/src/main/ui/menu/bad-save-data-control.gd
Extracted BadSaveDataControl from SplashScreen into its own scene file. Added a BadSaveDataControlDemo. It was tedious repeatedly corrupting my own save data to test this dialog in different languages.
> Refactor: Extracted BadSaveDataControl, added demo

- project/src/main/editor/puzzle/BlockLevelChunkControl.tscn
- project/src/main/editor/puzzle/PlayfieldEditor.tscn
- project/src/main/editor/puzzle/box-level-chunk-control.gd
- project/src/main/editor/puzzle/pickup-level-chunk-control.gd
- project/src/main/editor/puzzle/piece-level-chunk-control.gd
- project/src/main/editor/puzzle/playfield-editor-control.gd
- project/src/main/editor/puzzle/veg-level-chunk-control.gd
Before, level editor chunk controls included ugly parent references like '../../Button/RotateButton'. These were bad because they were dependent on hard-coded path names, they were used in several sections of code, and if the level editor chunk controls changed their location in the scene tree everything would break.
PlayfieldEditorControl now connects its child listeners. Chunk controls are all in a node group so that PlayfieldEditorControl can easily find them all.
> Refactor: Level editor chunk control parent references

- delint.sh
- project/project.godot
- project/src/main/puzzle/critter/Critters.tscn
- project/src/main/puzzle/critter/critter-manager.gd
- project/src/main/puzzle/critter/critters.gd
- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/critter/sharks.gd
Moles/sharks had a lot of copy/paste code centered around keeping track of which critters were in each cell. Additionally, if a level had both kinds of critters they could overlap.
I've extracted a CritterManager class which keeps track of which critters are in each cell, shifts them up and down as lines are cleared/inserted, and provides utility methods like 'does this cell have a floor'.
> Refactor: Extracted CritterManager from moles/sharks

- delint.sh
- project/src/main/utils/packed-sprite.gd
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/ViewportCreatureOutline.tscn
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/dna-loader.gd
- project/src/main/world/creature/viewport-creature-outline.gd
Added Godot #27790 workaround. Assigning a ViewportTexture results in an editor error, '(Node not found: "Viewport" (relative to "/root/EditorNode/@@596/@@597/@@605/@@607/@@611/@@615/@@616/@@617/@@633/@@634/@@643/@@644/@@6618/@@6450/@@6451/@@6452/@@6453/@@6454/@@6455/Creature").)' Leaving this texture null and assigning it in the _ready() function eliminates the error.
Added PackedSprite null texture check. Without this check, PackedSprite was throwing an error 'godot condition p_texture.is_null() is true'
DnaLoader.reset() unsets mouth z_index. This property is set by some animations, which caused the property to flip back and forth when saving CreatureVisuals.tscn even when resetting.
> Refactor: Creature editor errors, mouth z_index

- project/src/demo/puzzle/critter/shark-demo.gd
- project/src/main/puzzle/critter/sharks.gd
Shark food (size, shape, color, duration) is now configured before the shark eats. Before, half of the properties (duration, color) were assigned before the shark ate, and the other half (size, shape) were assigned after the shark ate.
Simplified shark demo keys.
> Refactor: Configure shark food before eating

- project/src/main/world/overworld-ui.gd
For chatters sitting on stools, the camera would still zoom in on the bottom of the stool.
> Fixed camera for elevated chatters.

- project/src/demo/chat/ui/chat-frame-demo.gd
- project/src/main/chat/ui/chat-frame.gd
This lets cutscenes change a creature's name temporarily, such as if you don't know their name or if they joke about wanting you to call them a different name
> Added 'nametag_text' meta item override

- project/src/main/world/creature/emote-player.gd
Fixed a bug where the ambient animation would play for a few frames during mood transitions, such as when transitioning from laugh1 to laugh0. EmotePlayer no longer plays the ambient animation if the reset tween is active.
Increased the 'transition mood advancement' value by a tiny, tiny amount. Otherwise, the creature's eyes would open for 1 frame about 10%-20% of the time. It wasn't very consistent, but nudging the value up fixes it.
> Fixed emote bugs where eyes would flash for a few frames

- project/src/main/chat/chat-tree.gd
- project/src/main/chat/ui/chat-frame.gd
If a chatscript file specified an invalid name like 'p' instead of 'p1' the game would crash with an NPE, because creature_def.creature_name could not resolve with a null CreatureDef. I've added a null check which assigns the nametag_text to null.
Added missing 'filming' chat location.
> Added 'filming' chat location. Fixed nametag NPE.

- project/src/main/world/creature/walking-buddy.gd
Creatures in walking scenes would sometimes alternate stopping and starting, if they hit a magic distance where the front one took too long to stop running and the back one took too long to start running. I've tweaked the WalkingBuddy thresholds to hopefully fix this.
> Bug: Creatures in walking scenes sometimes start/stop repeatedly

- project/assets/main/chat/career/poki/010-b-end.chat
- project/assets/main/chat/career/poki/010-b.chat
- project/assets/main/chat/career/poki/120.chat
- project/src/main/world/environment/restaurant/RestaurantSpawns.tscn
Some scenes want creatures to sit on other barstools, so I've replaced 'bar_stool' with 'barstool_middle' and 'barstool_down'. These names mirror 'table_seat_left' which use directions
> Added multiple bar_stool spawns for cutscenes

- project/src/main/career/population.gd
- project/src/main/editor/creature/dialogs.gd
- project/src/main/world/creature/creature-def.gd
The 'chef_if' flag is similar to the 'customer_if' flag and prevents a creature from appearing as a random chef until a condition is met. It's used for the upcoming Cannoli Sandbar cutscenes.
> Added support for 'chef_if' flag.

- project/src/main/world/career-map.gd
- project/src/main/world/career-world.gd
There are some cutscenes where it doesn't make sense for a random chef to step in. Before, we could tag '(chef) player' but it would result in oddities like two players appearing on the career map.
Cutscenes defining '(chef) player' and '(chef) sensei' should now work correctly.
> Added support for '(chef) player' metadata

- project/assets/main/chat/career/marsh/prologue.chat
Merrymellow Marsh is the fifth chapter, and they've been to two other locations (Poki Desert, Cannoli Sandbar) which all had problems attracting customers too. I've tweaked the dialogue to contrast this chapter with the previous ones to avoid 'saminess' (or at least, to acknowledge it)
> Changed Merrymellow Marsh prologue for consistency

- project/src/demo/chat/ui/mood-demo.gd
- project/src/main/world/creature/creature-animations.gd
- project/src/main/world/creature/creature-visuals.gd
Instead of interrupting the movement animations, moving just resets the creature's "emote arm frame". This is the same mechanism that happens when you launch an emote while the creature is running.
Creatures will no longer emote when facing north. This was resulting in some buggy behavior like eyes on the back of their head.
Closes #1905.
Added movement options to MoodDemo.
> Moving no longer interrupts mood. Disabled north-facing emotes.

- project/src/main/data/player-save-upgrader.gd
- project/src/main/puzzle/box-builder.gd
- project/src/main/world/creature/name-generator.gd
- project/src/main/world/environment/invisible-obstacle-tiler.gd
Updated InvisibleObstacleTiler to reuse its 'neighbor_cell' Vector2 to avoid repetition
Changed 'string' to 'String' in a few code comments. This type is capitalized in GDScript.
Updated NameGenerator to use 'Array.duplicate()' instead of looping through the source array to add items one at a time.
> Vector2 reuse, NameGenerator tweaks

- project/src/main/world/environment/goop-overworld-tiler.gd
- project/src/main/world/environment/grass-overworld-tiler.gd
- project/src/main/world/environment/invisible-obstacle-tiler.gd
- project/src/main/world/environment/pebble-overworld-tiler.gd
- project/src/main/world/environment/poki/puddle-overworld-tiler.gd
- project/src/main/world/environment/restaurant/carpet-tiler.gd
- project/src/main/world/environment/restaurant/kitchen-floor-tiler.gd
- project/src/main/world/environment/restaurant/kitchen-obstacle-tiler.gd
- project/src/main/world/environment/restaurant/undecorated-floor-tiler.gd
- project/src/main/world/environment/sand/chip-overworld-tiler.gd
- project/src/main/world/environment/sand/sand-tiler.gd
- project/src/main/world/environment/sand/water-overworld-tiler.gd
- project/src/main/world/environment/sand/water-ripple-overworld-tiler.gd
Some autotiler scripts such as 'carpet-tiler.gd' and 'kitchen-floor-tiler.gd' did not check the value of the 'value' property, and did not initialize onready variables in the autotile function. This can result in unnecessary autotiling, unnecessary .tscn file changes, and nil reference errors.
Changed 'Autotile' property to 'autotile' property in comments (lower case)
> Unify autotile syntax: 'not value', initialize_onready

- project/src/main/world/environment/grass-overworld-tiler.gd
- project/src/main/world/environment/invisible-obstacle-tiler.gd
- project/src/main/world/environment/pebble-overworld-tiler.gd
- project/src/main/world/environment/poki/puddle-overworld-tiler.gd
- project/src/main/world/environment/restaurant/carpet-tiler.gd
- project/src/main/world/environment/restaurant/kitchen-floor-tiler.gd
- project/src/main/world/environment/restaurant/undecorated-floor-tiler.gd
- project/src/main/world/environment/sand/chip-overworld-tiler.gd
- project/src/main/world/environment/sand/sand-tiler.gd
- project/src/main/world/environment/sand/water-overworld-tiler.gd
- project/src/main/world/environment/sand/water-ripple-overworld-tiler.gd
Autotilers often do things like randomize water tiles or randomly place chocolate chips which are difficult to reverse. Autotilers now include an 'unautotile' editor flag which can be flipped to reverse or remove all randomized tiles.
> Added 'unautotile' to tilers

- project/src/main/utils/bool-expression-parser.gd
- project/src/test/utils/test-bool-expression-parser.gd
I entered some chatscript which evaluated "is_flag foo" and it errored out in a confusing way. The chatscript parser now reports this kind of error in a graceful way.
> Added check for BoolExpression argument count

- project/src/main/world/creature/creature-visuals.gd
When pressing left and right in free roam mode, the player would often face away from the screen. They now face toward the screen instead.
> Bias horizontally-running creatures to face the screen

- project/src/main/puzzle/critter/Critters.tscn
- project/src/main/puzzle/critter/critter-manager.gd
- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/critter/sharks.gd
This bug was introduced by the CritterManager refactoring in 2a7c921d. Before, sharks would be shifted and then their positions would be evaluated. But after, sharks would be evaluated before being shifted because the signal methods were called in the wrong order.
I've added a CritterManager.line_inserted signal to ensure these calls are ordered appropriately.
> Bug: sharky cheese sharks were disappearing

- project/src/main/puzzle/line-clear-sfx.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/star-seeds.gd
Some critters destroy boxes, but we still want to award the player points. This 'cells_consumed' event gives StarSeeds a hook where it can emit food and play sound effects when a cake is destroyed by a critter.
> Added new 'cells_consumed' functionality.

- project/src/main/puzzle/level-timer-manager.gd
- project/src/main/puzzle/level/level-settings-upgrader.gd
- project/src/main/puzzle/level/level-timers.gd
- project/src/main/puzzle/level/levels.gd
Level timers used to have an optional 'initial_interval' property to define when the timer started, but there was no way to stop a level timer. I've replaced this 'initial_interval' property with a 'start' property, which is more intuitive and matches the naming conventions of Godot's timers. I've also added a new 'end' property.
> Replaced level timer 'initial_interval' with 'start/end'

- project/src/main/puzzle/critter/spear-config.gd
- project/src/main/puzzle/critter/spear-sfx.gd
- project/src/main/puzzle/critter/spear.gd
- project/src/main/puzzle/critter/spears.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/test/puzzle/critter/test-spears.gd
Added 'spear.wait' parameter to define how many cycles the spear should wait before popping out.
Spear supports spear size strings with two xs, like 'x3x5'.
Removed unused 'pop_anim_duration' parameter from
SpearSfx.play_pop_sound.
Fixed bug where spear would sometimes suddenly appear, instead of popping out.
> Spear improvements: 'wait', 'x3x5', already_popped_state

- project/src/main/puzzle/critter/critter-manager.gd
If spears eliminated a player's piece when clearing a line, there was an unnecessarily long piece because this 'add misc_delay_frames' logic was caused, even though there were already delay frames caused by the line clear.
These 'add misc delay frames' and other steps now only occur if the piece is obliterated while still moving.
> Fixed spear timing bug when obliterating a piece.

- project/src/main/world/environment/frame-overworld-obstacle.gd
Some upcoming obstacles have animations and static images in the same sprite sheet, so we might only want to allow an arbitray set of frames when shuffling.
FrameOverworldObstacle now initializes its onready variables if it detects its sprite is null in the editor. This happens sometimes when editing a tool script.
> FrameOverworldObstacle improvements: shuffle_frames, initialize

- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/critter/sharks.gd
- project/src/main/puzzle/critter/spears.gd
- project/src/main/puzzle/puzzle-tile-set-onion.tres
- project/src/main/puzzle/puzzle-tile-set-veggies.tres
- project/src/main/world/environment/sand/banana-hq-floor-library.tres
A few scripts had names like 'blocks.png' for resources like 'blocks-veggies.png'.
A few critter scripts had nonsensical comments like 'We don't add moles during line clear events -- the playfield'
> Fixed .tres resource names, malformed critter comments.

- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/critter/Mole.tscn
- project/src/main/puzzle/critter/Shark.tscn
- project/src/main/puzzle/critter/SpearWide.tscn
- project/src/main/puzzle/piece/PieceManager.tscn
- project/src/main/utils/SceneTransition.tscn
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/environment/restaurant/TurboFatRestaurant.tscn
Added missing sound bus settings for things like pickups, level editors, and creature 'poofs'. These were going directly to the master bus instead of the sfx bus.
Changed creature 'eat' sound from voice bus to sfx bus. I'm not sure whether anybody would just want to mute voice sounds -- but if they did, I think it would be because they don't like the silly voices. So I'm using the voice bus just for the silly voices, and sound effects go to the sfx bus -- even things like bite/chew noises, and voices for the little puzzle critters (which often have a gameplay effect.)
> Sfx bus fixes: master bus mistakes, voice/sfx

- project/src/main/world/chat-letters.gd
Creatures which aren't visible will no longer spew chat letters while invisible. This helps with the intro cutscene, where Fat Sensei has a line before sitting in the chair.
This is useful for an upcoming cutscene where Fat Sensei says something before appearing in the cutscene.
> Invisible creatures no longer spew chat letters.

- project/src/main/career/career-cutscene-library.gd
- project/src/main/utils/resource-cache.gd
I'd like to write some test scenarios which have empty folders, but this is impossible because of limitations of Git. I'm modifying our path traversal logic to ignore gitkeep files, so that our test scenarios will work even if they have a '.gitkeep' folder and won't do something silly like look for a '.gitkeep cutscene'
> Path traversal logic now ignores .gitkeep

- project/assets/test/career/career-regions-kpecz.json
- project/project.godot
- project/src/main/career/career-cutscene-librarian.gd
- project/src/main/career/career-cutscene-library.gd
- project/src/main/career/careers.gd
- project/src/main/career/ui/career-map-ui.gd
- project/src/main/world/career-map.gd
- project/src/test/career/test-career-cutscene-librarian.gd
Extracted CareerCutsceneLibrarian from CareerMap. CareerMap is a node and interacts with UI elements such as buttons, making it difficult to unit test. CareerCutsceneLibrarian only decides which cutscenes to play for levels, so it's more testable.
Moved Careers.GENERAL_CHAT_KEY_ROOT into CareerCutsceneLibrary. It can now be changed for tests.
> CareerCutsceneLibrarian, testability, tests

- project/src/main/puzzle/box-builder.gd
- project/src/test/puzzle/piece/test-piece-kicks-v.gd
Fixed some buggy piece kick tests which had different obstructions in the before/after. We ignore the obstructions in the 'after' state, but it's still confusing if they're not consistent.
> Box builder comment tweaks, V kick test fixes

- project/assets/demo/puzzle/levels/experiment.json
- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/critter/critter-manager.gd
- project/src/main/puzzle/critter/sharks.gd
- project/src/main/puzzle/critter/spears.gd
The PieceWritten trigger fires when a shark eats a piece. This trigger can cause level effects like inserting lines, and moving sharks, which then was causing crashes (for sharks that could not be found) or graphical oddities (for sharks that moved)
The PieceWritten trigger now only fires after all sharks eat.
Eating a piece with a non-zero orientation was causing crashes in some cases. I've moved the check to 'UpdatePieceManagerPiece' so that a null piece will never have a non-zero orientation.
> Fixed shark crashes related to PieceWritten trigger, piece orientation

- project/src/main/puzzle/critter/spears.gd
Spears shadows were accidentally made visible when adding cheese tiles to the sprite sheets.
> Fixed bug with spears shadows.

- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle.gd
CurrentLevel.attempt_count is now incremented at the start of a puzzle, not at the end. Before, attempt_count was '1' after finishing a puzzle which made it more difficult to code in the 'persistent lives' logic.
> Increment attempt count at start; not end

- project/assets/main/puzzle/levels/career/creeping-crevice-2.json
- project/src/main/career/career-calendar.gd
- project/src/main/career/career-data.gd
- project/src/main/career/career-flow.gd
- project/src/main/puzzle/pan/puzzle-frying-pans-ui.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/puzzle.gd
- project/src/test/world/test-career-data.gd
If the player tops out, they'll have one less life for the rest of the career session. If they lose all their lives, the session ends. They always start with at least one life, even if they've previously lost more lives than the current level allows.
The penalty for save scumming is now that the career day immediately ends, instead of skipping forward an hour.
> Career mode preserves lives lost.

- project/assets/main/puzzle/career-regions.json
- project/src/main/career/career-level.gd
- project/src/main/chat/chat-tree.gd
- project/src/main/world/career-map.gd
- project/src/main/world/environment/restaurant/RestaurantPuzzleScene.tscn
- project/src/main/world/level-posse.gd
- project/src/main/world/puzzle-world.gd
Zagma levels now take place in the appropriate puzzle environment. This is controlled by a new 'puzzle_environment' json flag, which works just like the customer flags. It can be set on cutscenes, levels or regions. We currently only set it on levels.
Closes #2264 .
> 'puzzle_environment' flag; Zagma puzzle environment

- project/src/main/world/career-map.gd
The old algorithm had a bug which could result in the level select offering the same level twice, side-by-side.
The new algorithm seems simpler and more robust.
> Changed 'avoid duplicate levels' algorithm

- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/ui/menu/paged-level-buttons.gd
LevelSelectButton was modified in b21415d9 to include new visual effects, but this affected how it grabbed focus in different situations. It wouldn't grab initial focus, and the "UNLOCK" cheat caused it to lose focus as well.
Both of these bugs have been fixed, the LevelSelectButton should grab focus appropriately again.
> Fixed new LevelSelectButton focus bugs

- project/src/main/ui/menu/paged-level-buttons.gd
There's no need to continue looping once we find the focus owner.
> PagedLevelButtons breaks for loop.

- project/src/main/puzzle/playfield-fx.gd
Clearing a cake box results in rainbow lights appearing, but the rainbow included an olive green vegetable color when all the tile indexes were shifted in 86fed88a.
I've fixed the index problem and refactored the code so that further changes to the FOOD_LIGHT_COLORS array will not break this code.
> Fixed rainbow lights for cake clears.

- project/src/main/ui/menu/practice-menu.gd
Before, the practice menu button sometimes displayed long level names like 'Vega Churn Twelve: Grand Opening: Chocolava Canyon'. This made the button grow wider and made the UI a little uglier. This button is now truncated as 'Vega Churn Twelve: Grand Open...'
Strictly speaking, this would still break if we maliciously named a level something like 'WWWWW' and a real solution would invoke font width. But this is good enough, and these buttons don't accept user-submitted content.
> Long level names are truncated in practice menu.

- project/assets/main/puzzle/levels/career/dark/sharky-cheese-2.json
- project/src/main/ui/menu/paged-level-panel.gd
Boss levels and intro levels now show up in the practice menu.
Added missing 'show_pickups_rank' flag for Sharky Cheese 2.
> Practice boss levels. Sharky cheese 2 pickups rank.

- project/src/main/puzzle/playfield-fx.gd
This method threw an NPE because _rainbow_tile_indexes wasn't initialized before _refresh_tile_maps was called.
> Fixed PlayfieldFX NPE

- project/src/main/editor/puzzle/dialogs.gd
Our dialog popups used to default to game directories, but this was broken in Godot 3.5 by the fix for Godot #29674
(https://github.com/godotengine/godot/issues/29674)
I've restored these paths.
> Restore level editor default dialog paths.

- project/src/main/editor/puzzle/level-editor.gd
This duplicate code caused a bug when we made the level editor upgrade level files when loading them. The code is now the same in both places.
> Avoid duplicate code in LevelEditor ready, load

- project/src/main/chat/chat-history.gd
- project/src/main/utils/utils.gd
- project/src/test/utils/test-utils.gd
These utilities are useful for other JSON saving/loading code, so they shouldn't be private to ChatHistory.
convert_floats_to_ints_in_dict has been improved. It no longer modifies the source dictionary, and is able to convert both keys and values. I've also added unit tests.
> Extracted, improved convert_floats_to_ints json utils.

- project/assets/test/data/turbofat-512b.json
- project/src/main/career/career-calendar.gd
- project/src/main/career/career-data.gd
- project/src/main/career/ui/career-map-ui.gd
- project/src/main/career/ui/career-win-world.gd
- project/src/main/career/ui/career-win.gd
- project/src/main/career/ui/chalkboard-earned.gd
- project/src/main/career/ui/chalkboard-served.gd
- project/src/main/career/ui/chalkboard-steps.gd
- project/src/main/career/ui/chalkboard-time.gd
- project/src/main/career/ui/chalkboard-title.gd
- project/src/main/data/player-save-upgrader.gd
- project/src/main/data/player-save.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/world/career-map.gd
- project/src/test/data/test-player-save-upgrader.gd
- project/src/test/world/test-career-data.gd
This was haphazardly applied. Some fields like 'distance_travelled' were not called 'daily_distance_travelled' even though they were properties of the current career day. Other fields like 'daily_steps' had the word 'daily'.
I've removed the word 'daily' from all career fields, and updated our backwards compatibility logic to remove it from the player's saves as well.
> Remove 'daily' from career fields.

- project/src/main/career/career-level.gd
- project/src/main/career/career-region.gd
- project/src/main/career/ui/career-win-world.gd
- project/src/main/chat/chat-tree.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/other-region.gd
- project/src/main/puzzle/puzzle-bg-loader.gd
- project/src/main/ui/menu/paged-region-buttons.gd
- project/src/main/world/career-map.gd
- project/src/main/world/career-world.gd
- project/src/main/world/cutscene-queue.gd
- project/src/main/world/level-posse.gd
- project/src/main/world/puzzle-world.gd
Fields like 'overworld_environment_name' are now called 'overworld_environment_id' instead. I think this makes more sense because these are unique identifiers like 'lava/zagma' and not names like 'Chocolava Canyon'.
> *_environment_name -> *_environment_id

- project/src/main/career/ui/career-map-level-select.gd
- project/src/main/career/ui/progress-board-spots.gd
- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/ui/menu/paged-level-buttons.gd
Converting the LevelSelectButton from a Button to Control to add the nice graphics in b21415d9 broke 'focus_entered' events from being propagated correctly. This meant the distance indicators in Career mode were broken.
Changed 'get_children().size()' calls to 'get_child_count()'
> Fixed career map level select button focus_entered bug

- project/src/main/puzzle/tutorial/tutorial-messages.gd
This was broken in a37e117d when renaming the 'Tween' node. Most references were updated, but we missed this one.
> Fixed tutorial message bug.

- license/asset-license.txt
Soniss was misspelled as Coniss in the license.
One sound effect was misattributed to 'doctorphil at Defelozedd94' instead of 'Defelozedd94 at FreeSound.org'.
The cartoon bite sound effect was misattributed to 'Sound effects for youtubers' instead of 'Hanna-Barbera SoundFX Library'. I have paid for a license for this library.
> Fixed license typos: 'Coniss', 'Defelozedd94', 'youtubers'

- project/src/main/music/checkpoint-song.gd
This occurred when fast-forwarding the credits song. I don't think it would ever happen in game, but this array bounds check seems harmless.
> Fixed array out of bounds in CheckpointSong

- project/assets/main/creatures/nonstory/kylie.json
- project/assets/main/creatures/story/jaco.json
- project/assets/main/creatures/story/unknown.json
Jaco will appear during the credits sequence.
'unknown' is used for cutscenes which need things like anonymous voices. A nametag is not shown for this creature, and the creature themselves should never really be spawned anywhere. We just need them for their chat theme.
Kylie is just a random customer.
> New customers: Kylie, Jaco, unknown

- project/src/main/credits/credits-scroll.gd
Extracted '_shift_credits' method.
Renamed '_horizontal_tween' to '_lines_tween_x' to disambiguate it from other similar tweens which we will add soon.
> Credits scroll refactoring; lines_tween_x, shift_credits

- project/src/main/credits/CreditsScroll.tscn
- project/src/main/world/creature/ViewportCreatureOutline.tscn
- project/src/main/world/environment/restaurant/RestaurantView.tscn
Some of our viewports use subtly different settings, so I'm making them more consistent. I also notice a few use different sound settings, but I'm leaving this alone for now. I think they do it to avoid having sound effects play in the left or right channel in weird ways.
> Viewport: size_override_stretch=true, hdr=false

- project/src/main/credits/CreditsScroll.tscn
The credits movie looked OK at 100% zoom, but if the player made the window bigger the movie looked pixelly. I've changed it to use the same 'stretch_shrink' workaround that we use in our puzzles.
> Fixed pixelly credits movie.

- project/src/main/credits/credits-scroll.gd
- project/src/main/world/cutscene-camera.gd
Fixed 'unused parameter' warning in credits-scroll.gd.
CutsceneCamera now iterates over _overworld_ui.chatters instead of all creatures. This makes it consistent with similar methods in OverworldUi.
> credits-scroll.gd warning. CutsceneCamera refactoring.

- project/src/demo/world/environment/lava/lava-crowd-demo.gd
- project/src/main/world/environment/lava/lava-crowd.gd
LavaCrowd 'export' property is exported so it can be toggled in the Godot editor. This lets us have scenes with creatures who are always bouncing, like for the upcoming crowd surf cutscene.
> LavaCrowd 'bouncing' toggle

- project/src/main/world/environment/lava/crowd-recycler.gd
A bug in CrowdRecycler causes it to move creatures which are already moved by CrowdWalkDirector. We had a fix for this bug, but I accidentally removed it when delinting our code and deleting all of the print statements.
> bug: duplicate CrowdRecycler collisions

- project/src/demo/world/environment/lava/crowd-walk-cutscene-demo.gd
- project/src/main/world/environment/lava/crowd-walk-cutscene.gd
- project/src/main/world/environment/lava/crowd-walk-director.gd
- project/src/main/world/environment/lava/crowd-walking-buddy.gd
Crowd walk cutscene creature initial positions are now cached. Before, we'd just move the player, and move all creatures the same amount. This caused some bugs which we worked around by just having the creature always move in a perfectly straight line, but it's better to just store the creature's initial positions and always reset them to where they started.
Player and Fat Sensei remain stationary until the cutscene starts.
Changed 'prepare launch timer' method to 'play'. This is less descriptive, but all of our credits cutscenes can use the method name 'play' which will give them a more intuitive API.
> Crowd walk tweaks: initial positions, naming, sit still

- project/src/demo/chat/ui/mood-demo.gd
- project/src/main/utils/dynamic-viewport-container.gd
Changed DynamicViewportContainer to leave the world2d intact instead of overwriting it with null. Null is not a valid value for the world2d, and causes errors.
Removed an unnecessary line from MoodDemo which assigned the creature's dna redundantly.
> DynamicViewportContainer null case. MoodDemo line.

- project/src/demo/world/environment/lava/CrowdSurfCutsceneDemo.tscn
- project/src/demo/world/environment/lava/CrowdWalkCutsceneDemo.tscn
- project/src/main/credits/CreditsScroll.tscn
- project/src/main/puzzle/customer-view.gd
- project/src/main/utils/dynamic-viewport-container.gd
- project/src/main/world/environment/restaurant/RestaurantView.tscn
Renamed DynamicViewportContainer's restaurant_viewport_path to world_viewport_path. This is now being reused and does not always point to a restaurant.
Replaced customer-view.gd with dynamic-viewport-container.gd. This script seemed redundant and did not do anything to justify being unique.
> Refactor: restaurant_viewport_path, customer-view

- project/src/main/credits/Pinup.tscn
- project/src/main/world/creature/ViewportCreatureOutline.tscn
- project/src/main/world/environment/restaurant/RestaurantView.tscn
I don't know why we set this originally, or if it had an effect in older versions of godot, or older versions of our viewport logic. It doesn't do anything now.
> Disabled 'size_override_stretch' flag

- project/src/main/world/environment/environment-shadows.gd
EnvironmentShadows having a null obstacles_path subtly makes all creatures in the environment not have shadows, and it's something that slipped through the cracks previously.
> Added EnvironmentShadows warning.

- project/src/main/world/creature/creature-visuals.gd
When using pinup-demo.gd and changing the creature size from 10 to 1 abruptly, an error is logged.
E 0:00:05.836   canvas_item_add_polygon: Invalid polygon data, triangulation failed.
<C++ Error>   Condition "indices.empty()" is true.
<C++ Source>  servers/visual/visual_server_canvas.cpp:768 @ canvas_item_add_polygon()
This specific error was because CreatureCurve lerps its polygon geometry based on the VisualFatness value. When it goes outside a specific range, it continues extrapolating in that direction but this eventually results in self-intersecting polygons.
We could fix CreatureCurve to avoid this use case, but even so -- values higher than 10.0 will result in oddities because the heads and arms are not lerped in the same way curves are, so they will stay constrained while the body …
> Bug: Polygon error with unusual fatness values

- project/src/demo/chat/ui/mood-demo.gd
- project/src/demo/credits/pinup-demo.gd
- project/src/demo/world/environment/restaurant/restaurant-puzzle-scene-demo.gd
- project/src/demo/world/environment/restaurant/restaurant-view-demo.gd
- project/src/main/credits/pinup-camera-mover.gd
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/editor/creature/tweak-size-row.gd
- project/src/main/puzzle/food-items.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/world/creature-spawner.gd
- project/src/main/world/creature/body-sweat.gd
- project/src/main/world/creature/creature-shadow.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/cutscene-camera.gd
- project/src/main/world/environment/lava/crowd-surf-camera.gd
- project/src/main/world/environment/lava/crowd-walk-camera.gd
- project/src/main/world/environment/restaurant/chef-camera-mover.gd
- project/src/main/world/environment/restaurant/customer-camera-mover.gd
Exposed 'fatness', 'visual_fatness' fields on Creature and CreatureVisuals. Other similar properties like 'dna' had fields with setters and setters, so it was inconsistent to see most of these properties assigned directly but just these two special fatness fields assigned with a method.
> Refactor: get_fatness() -> fatness

- project/src/main/puzzle/critter/Critters.tscn
- project/src/main/puzzle/critter/Mole.tscn
- project/src/main/puzzle/critter/Onion.tscn
- project/src/main/puzzle/critter/Shark.tscn
- project/src/main/puzzle/critter/Spear.tscn
- project/src/main/puzzle/critter/carrots.gd
- project/src/main/puzzle/critter/mole-sfx.gd
- project/src/main/puzzle/critter/onion-sfx.gd
- project/src/main/puzzle/critter/shark-sfx.gd
- project/src/main/puzzle/critter/spear-sfx.gd
- project/src/main/utils/DeconflictedAudioStreamPlayer2D.tscn
- project/src/main/utils/deconflicted-audio-stream-player-2d.gd
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/creature-sfx.gd
Replaced calls to 'SfxDeconflicter.play()' with DeconflictedAudioStreamPlayer, and a new DeconflictedAudioStreamPlayer2D. This slightly reduces code and repetition.
> Refactor: More use of DeconflictedAudioStreamPlayer

- project/src/demo/world/environment/lava/LavaFreeRoamEnvironment.tscn
- project/src/demo/world/environment/lava/ZagmaFreeRoamEnvironment.tscn
- project/src/demo/world/environment/lemon/Lemon2FreeRoamEnvironment.tscn
- project/src/demo/world/environment/lemon/LemonFreeRoamEnvironment.tscn
- project/src/demo/world/environment/marsh/MarshFreeRoamEnvironment.tscn
- project/src/demo/world/environment/poki/PokiFreeRoamEnvironment.tscn
- project/src/demo/world/environment/restaurant/TurboFatFreeRoamEnvironment.tscn
- project/src/demo/world/environment/restaurant/UndecoratedTurboFatFreeRoamEnvironment.tscn
- project/src/demo/world/environment/sand/BananaHqFreeRoamEnvironment.tscn
- project/src/demo/world/environment/sand/FilmingFreeRoamEnvironment.tscn
- project/src/demo/world/environment/sand/SandFreeRoamEnvironment.tscn
- project/src/main/world/creature/Player.tscn
- project/src/main/world/creature/Sensei.tscn
- project/src/main/world/creature/player.gd
- project/src/main/world/creature/sensei.gd
Having these extracted into their own scenes eliminates redundant timers and property settings.
> Extracted Player.tscn, Sensei.tscn

- project/src/main/world/environment/lava/lava-crowdie.gd
- project/src/main/world/environment/poki/poki-crowdie.gd
These colors are similar enough that any difference seems like an oversight.
> Replaced brown '3d291f' with '41281e'

- project/src/demo/credits/credits-scroll-demo.gd
- project/src/main/credits/credits-director.gd
Tightened credits desync threshold. 100 ms results in a very noticable audio delay for some of the sound effect cues.
Changed CreditsDemo speed up key from shift to space. Shift is a useful modifier key, and it's awkward to not be able to press it without speeding up the credits.
> Tighter credits desync threshold. CreditsDemo shift -> space

- project/src/main/credits/credits-movie.gd
- project/src/main/credits/pinup-scrollers.gd
- project/src/main/world/environment/lava/crowd-surf-cutscene.gd
- project/src/main/world/environment/lava/crowd-walk-cutscene.gd
Our initial version of the credits only loaded the cutscenes as needed, which uses about 5.1% less memory but introduces some ugly hiccups as the scenes load. The new credits sequence is smoother.
Decreased pinup scroller pool size from 5 to 4. Only 4 are visible at once.
> Preload credits cutscenes. Pinup scroller pool size.

- project/src/main/world/environment/lava/CrowdSurfEnvironment.tscn
- project/src/main/world/environment/lava/CrowdWalkEnvironment.tscn
- project/src/main/world/environment/lava/crowd-recycler.gd
- project/src/main/world/environment/lava/crowd-surf-director.gd
- project/src/main/world/environment/lava/crowd-walk-director.gd
- project/src/main/world/environment/lava/crowd-walk-environment.gd
Renamed 'creatures_arranged' signal to more generic 'played'. A future expansion of this method will add new methods and signals named 'stop' and 'stopped', so this is more consistent and simple.
Renamed '_on_CrowdWalkDirector_creatures_arranged' signal to '_on_Director_creatures_arranged'. This signal method is used for the CrowdSurfDirector as well, so the name should be generic.
Removed unused CrowdSurfDirector._tween field.
> Crowd cutscene refactoring: played, _on_Director, unused tween

- project/src/main/music/music-transition.gd
- project/src/main/ui/scene-transition.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/free-roam-player.gd
MusicTransition needs to know the duration of the scene transition on web targets so that it can fade out the music. It was still relying on SceneTransition.next_fade_out_duration, but this property was removed in 74b790ec.
> Added 'duration' parameter for SceneTransition signals.

- project/src/demo/world/environment/lava/crowd-surf-cutscene-demo.gd
- project/src/demo/world/environment/lava/crowd-walk-cutscene-demo.gd
- project/src/main/credits/crowd-surfing-buddy.gd
- project/src/main/world/environment/lava/CrowdSurfEnvironment.tscn
- project/src/main/world/environment/lava/CrowdWalkEnvironment.tscn
- project/src/main/world/environment/lava/crowd-recycler.gd
- project/src/main/world/environment/lava/crowd-surf-cutscene.gd
- project/src/main/world/environment/lava/crowd-surf-director.gd
- project/src/main/world/environment/lava/crowd-walk-cutscene.gd
- project/src/main/world/environment/lava/crowd-walk-director.gd
Fixed crowd cutscene collision bugs. CrowdSurfEnvironment and CrowdWalkEnvironment both use a CrowdRecycler to shuffle creatures around when they collide with an Area2D. However in fabd4cc8 we started loading both these environments simultaneously to reduce lag. This had the unintended side effect of these two Area2Ds interacting with creatures in the other environment.
I've fixed the bug by disabling these Area2D collision areas when they are not in use. Cutscenes are now considered active when 'play' is called, and they are considered inactive when a new 'stop' method is called. Inactive cutscenes have all their animations stopped and their CrowdRecyclers disabled.
This new 'stop' method is also available in CrowdWalkCutsceneDemo and CrowdSurfCutsceneDemo.
> Crowd cutscene collision bugs. Added 'stop'.

- project/src/main/credits/CreditsScroll.tscn
- project/src/main/credits/credits-movie.gd
- project/src/main/credits/credits-scroll.gd
If the window was taller than 1024x600, the movies which played alongside the credits would appear at the top of the credits window instead of the center. I've moved the credits movies inside the 'fixed container' so that they'll be aligned with everything else.
> Bug: credits movies were at top, not center

- project/src/main/credits/pinup-scroller.gd
- project/src/main/credits/pinup-scrollers.gd
One especially large pinup 'chelle' was blinking out of view unpleasantly. Pinups now slowly fade out after they're above a certain height. This also improves the appearance when the window is very tall, as the pinups fade in from the bottom and fade out at the top, so it's symmetrical. Before, the pinups kept scrolling up all the way offscreen and it looked a bit strange.
> Improved pinups scrolling offscreen during credits.

- project/src/demo/chat/ui/mood-demo.gd
I've made a lot of creatures very fat through gameplay, but I still want to draw them at their canon sizes. Having MoodDemo reset their fatnesses makes this simpler
> MoodDemo uses canon appearances, not player's custom fatness

- package.sh
- project/export_presets.cfg.template
Changed windows, linux export presets from .exe/.x86_64 to .zip. This lets us get rid of our custom packaging code and automatically sets the executable flag for linux systems, so that players don't need chmod +x the executable before running it.
I could not change the html export to use a '.zip' -- this is not supported, and instead exports the game into a 'turbofat.zip.html' html file.
Renamed 'turbofat.html' to 'index.html' to avoid unnecessary packaging step.
> Changed export presets to zips. Linux +x flag.

- project/src/main/ui/VersionLabel.tscn
- project/src/main/ui/version-label.gd
Before, the version label was always at position (956, 570) which was usually OK but would look strange if the version number was very long or very short.
The version label now stays locked in the bottom right corner regardless of the version text.
> Fixed version label layout, stays in bottom-right

- package.sh
We want to show the user a version like '1.2.3-steam' for steam, but we don't want this suffix to pollute places like the Android Play store. This suffix would probably violate the syntax of some platforms.
> package.sh can now handle version suffixes

- generate-export-presets.sh
- project/project.godot
generate-export-presets.sh now suffixes the version number with '-steam'. The steam version is likely to diverge slightly as we add things like achievement support. It could have its own bugs, so it's good to keep the version numbers separate so we can differentiate them when users report problems.
> Update version to '0.8416-steam'.

- project/src/main/world/career-map.gd
The 'don't repeat levels' logic was broken, and was always replacing the first level instead of replacing the repeated level.
> Bug: Repeat levels showing up in career mode

- project/src/main/career/career-data.gd
It was strange to unlock Chapter 2 and after viewing a few cutscenes in chapter 1, the player was still told the chapter's story was 0% complete. It will now show up as 10%-20% even if the player just views the mandatory intro/boss cutscenes.
> Story completion percent now includes epilogue, prologue, etc

- project/assets/main/chat/career/marsh/050-b-end.chat
The old dialog made the assumption that the player would read 'what about us?' and assume Skins was asking about a relationship. This is possible, but I think it's better to spell it out.
> Skins cutscene dialog, 'our relationship?'

- project/src/main/editor/creature/creature-editor.gd
- project/src/main/editor/creature/tweak-name-row.gd
- project/src/main/editor/puzzle/level-editor.gd
Level Editor, Creature Editor grab initial focus so that the player can navigate with keyboard or controllers. They still don't work well with keyboard or controllers overall, but they at least have focus initially
> Initial focus for Level Editor, Creature Editor

- project/src/main/ui/TabInputEnabler.tscn
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/tab-input-enabler.gd
Added controller support for SettingsMenu.
Disabled 'FocusMode=ALL' for the SaveSlot control, which caused a bug where the player could arrow up toward the save slot and their 'cursor' would disappear.
The player can now control the Settings Menu tab by arrowing up to the top, and pressing left/right.
> Settings menu controller support. TabInputEnabler.

- project/project.godot
- project/src/main/ui/exit-credits-popup.gd
Added new 'ui_click' event. This seems like a cleaner way to handle mouse events rather than manually checking the mouse mask. The existing 'mouse mask' code has some bugs. I've created #2433 to capture these.
> Can click to exit credits. 'ui_click'

- project/src/main/data/system-save.gd
- project/src/main/settings/misc-settings.gd
Most 'from_json_dict' methods emit corresponding signals, but there was a blind spot for this one property.
Reordered SystemSave initialization to prevent the save slot from being set twice.
> MiscSettings.save_slot_changed signal emitted by from_json_dict

- project/src/main/data/system-data.gd
- project/src/test/pre-run-hook.gd
Added 'SystemData.disallow_graphics_customization' method which unhooks the player's settings from triggering graphics updates. This is called by a GutHookScript so that running the Gut tests does not enter fullscreen mode.
> Gut no longer triggers fullscreen mode.

- project/src/demo/credits/CreditsScrollDemo.tscn
- project/src/main/credits/credits-director.gd
Credits orb timing was being synchronized one idle frame after the music and animationplayer, which in some cases was extremely noticable and resulted in the piece particles popping before the piece hit their target.
> Fixed credits orb sync issue

- project/src/demo/world/FreeRoamUi.tscn
- project/src/main/world/CutsceneUi.tscn
- project/src/main/world/creature/free-roam-player.gd
- project/src/main/world/overworld-ui.gd
This was used in FreeRoam mode when the player could move with the arrow keys and talk to other creatures. When the dialog boxes popped up, we didn't want them moving around when trying to select chat choices. This functionality is no longer in the game, not even in demos, so we don't need this property anymore.
> Removed unused 'ui_has_focus' property.

- project/src/main/puzzle/Puzzle.tscn
DiagonalParticles.tscn was being reused in Puzzle.tscn, but Puzzle.tscn changes the color and speed of the process_material, affecting places like the credits. Puzzle.tscn now uses its own localized instance of DiagonalParticles.tscn to avoid polluting the material for others.
> Fixed bug where credits particles were green

- project/src/main/puzzle/critter/shark.gd
Added workaround for Godot #56576
(https://github.com/godotengine/godot/issues/56576). Referencing the Shark type from within the shark script causes a memory leak causing several 'Resources still in use at exit' errors when exiting the game. Changing the variable to a 'Node2D' type resolves this issue.
> Shark script no longer references itself.

- license/asset-license.txt
Added missing license info. The Gradient Map is a part of a GDQuest tutorial which does not have a license, but from context it seems the intended license is the MIT license.
> Added missing license info: GDQuest, icon-play.png

- project/src/main/ui/candy-button/CandyButtonH3.tscn
- project/src/main/ui/candy-button/CandyButtonH4.tscn
- project/src/main/ui/candy-button/candy-button-h3.gd
- project/src/main/ui/candy-button/candy-button-h4.gd
Moved CandyButton signals so they no longer appear in the editor. This is a generic button used in many places, we want to be able to quickly see the unique signals connected to each button instance, not the generic signals connected to all button instances.
Assigned more suitable default textures/color to CandyButtonH4.
> Move CandyButton signals from .tscn to script.

- project/assets/main/puzzle/career-regions.json
- project/src/main/career/career-region.gd
- project/src/main/ui/menu/paged-region-buttons.gd
Added 'new_page' flag to force Starberry Mountain to appear on its own page. Currently, the number of regions is coincidentally the maximum page count of the PagedRegionPanel, but we plan to remove Vega Churn Twelve shortly.
> Added 'new_page' flag for Starberry Mountain

- project/src/main/puzzle/level/phase-conditions.gd
Levels can now have behaviors which trigger on specific types of boxes, like cheesecake or chocolate snack boxes.
> Added 'box_built pink' level functionality

- project/src/main/ui/candy-button/CandyButtonH3.tscn
- project/src/main/ui/candy-button/CandyButtonH4.tscn
Disabled 'shortcut_in_tooltip'. This baffling default Godot functionality makes it so that hovering any button results in a cryptic message like '(InputEventAction : action=ui_cancel, pressed=(false) My Tooltip)'.
There is luckily a workaround, but it's honestly baffling that a workaround is necessary in the first place.
Changed 'pauze_mode' for button sound effects. Otherwise when clicking the Settings button, no sounds will play because the sound effect nodes are paused.
> CandyButton tweaks: shortcut_in_tooltip, pause_mode

- project/src/main/ui/menu/SystemButtons.tscn
These shortcuts were accidentally removed when changing the buttons to CandyButtons.
> Restored removed Quit/Settings shortcuts.

- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/SystemButtons.tscn
Adding a CandyButton instance automatically adds a bunch of unnecessary GradientTexture2D and ShaderMaterial instances.
> Removed CandyButtons cruft from MainMenu, SystemButtons

- project/src/main/ui/settings/volume-setting-control.gd
At a glance, seeing just the word 'Master' and a slider is confusing. Other games I looked at (Balatro, Risk Of Rain Returns) used the full term 'Master Volume'.
> Settings volume words: 'Sounds -> SFX Volume'

- project/src/main/ui/settings/SettingsMenu.tscn
The keybinds used to be flush with the left side of the window, but they're now centered. This was a subtle issue as the window was almost the same size as the keybinds, but it will become more prominent when the window is enlarged.
> SettingsMenu: Keybinds are now centered

- project/src/main/ui/settings/SettingsMenu.tscn
Enabled follow_focus for keybind presets scroll container. This somehow got left behind in 34b57ceed59176f9f1527177d767464aa2aef4ea
Made all SettingsMenu dialogs invisible for consistency.
> SettingsMenu: follow_focus, dialog visibility

- project/assets/main/keybind/guideline-hold.json
- project/assets/main/keybind/guideline.json
- project/assets/main/keybind/wasd-hold.json
- project/assets/main/keybind/wasd.json
- project/project.godot
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/tab-input-enabler.gd
Tab navigation is now supported with Z, X, or the gamepad bumpers. We also continue to support arrowing up into the TabContainer, but the gamepad bumpers are a bit faster.
The real reason for implementing this is that the Creature Editor redesign will use a similar tabbed approach, and I'd like to streamline it with bumpers.
Closes #2526.
> Support tab navigation with gamepad bumpers.

- project/src/main/ui/candy-button/candy-button-h3.gd
- project/src/main/ui/candy-button/candy-button-h4.gd
- project/src/main/ui/candy-button/gradient-none-hover.tres
We might use undecorated CandyButtons in our upcoming creature editor. It makes sense for them to have the same UI feedback when hovered.
> Added CandyButton 'gradient none hover'

- project/src/main/ui/candy-button/candy-button-h3.gd
- project/src/main/ui/candy-button/candy-button-h4.gd
- project/src/main/ui/candy-button/candy-buttons.gd
These gradients constants are currently used in two places, but the CreatureEditor will introduce several more. It's helpful to avoid the repetition. We have some proposed refactorings that will handle this in a cleaner way.
> Extracted redundant gradient constants

- project/assets/main/keybind/guideline-hold.json
- project/assets/main/keybind/guideline.json
- project/assets/main/keybind/wasd-hold.json
- project/assets/main/keybind/wasd.json
- project/project.godot
This was originally done back when the game had an interactive overworld, where it felt intuitive that the player would talk with people using the same keys they play with the game with. But it now causes a conflict with the tab navigation buttons, which are also Z/X.
> Z no longer activates 'ui_accept'.

- project/src/demo/chat/ui/chatscript-table-demo.gd
- project/src/demo/editor/creature-old/creature-editor-old.gd
- project/src/demo/puzzle/level/rank-mode-demo.gd
- project/src/main/career/career-cutscene-library.gd
- project/src/main/credits/pinup-scrollers.gd
- project/src/main/puzzle/critter/shark.gd
- project/src/main/puzzle/foods.gd
- project/src/main/puzzle/level/level-triggers.gd
- project/src/main/puzzle/level/phase-conditions.gd
- project/src/main/ui/candy-button/candy-button-collapsible.gd
- project/src/main/ui/candy-button/candy-button-h3.gd
- project/src/main/ui/candy-button/candy-button-h4.gd
- project/src/main/ui/candy-button/candy-buttons.gd
- project/src/main/ui/candy-button/gradient-map.shader
- project/src/main/ui/region-select-button.gd
- project/src/main/ui/transition-mask.shader
- project/src/main/utils/icon-outline.shader
- project/src/main/utils/outline.shader
- project/src/main/utils/sfx-deconflicter.gd
- project/src/main/world/creature/creature-curve.gd
- project/src/main/world/creature/name-generator-library.gd
- project/src/main/world/environment/goop-overworld-tiler.gd
- project/src/main/world/environment/restaurant/kitchen-obstacle-tiler.gd
- project/src/main/world/environment/ripples.gd
- project/src/main/world/rgb-palette.shader
'## key: (Creatures.Mood)' -> '## key: (int) Enum from Creatures.Mood)'
Moved shader comments below 'shader_type' declaration. Reformatted as '/**' block comments.
'value: (Array)' -> 'value: (Array, String)
> Refactor: Enum comments, shader comments, array type comments

- project/src/main/career/ui/progress-board-clock-label.gd
- project/src/main/career/ui/progress-board-clock.gd
- project/src/main/career/ui/progress-board-player.gd
- project/src/main/music/music-player.gd
- project/src/main/puzzle/critter/carrot.gd
- project/src/main/puzzle/critter/carrots.gd
- project/src/main/puzzle/critter/onion.gd
- project/src/main/puzzle/critter/shark-sfx.gd
- project/src/main/puzzle/critter/shark-tooth-cloud.gd
- project/src/main/puzzle/goop-glob.gd
- project/src/main/puzzle/leaf-poof.gd
- project/src/main/puzzle/night/night-mode-toggler.gd
- project/src/main/puzzle/night/night-sky-glow.gd
- project/src/main/puzzle/night/night-sky.gd
- project/src/main/puzzle/pickup.gd
- project/src/main/puzzle/playfield-fx.gd
- project/src/main/puzzle/puzzle-money-hud.gd
- project/src/main/world/creature/creature-animations.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/emote-player.gd
- project/src/main/world/environment/credits/crowd-surfing-buddy.gd
- project/src/main/world/environment/ripple-sprite.gd
These were previously onready variables because they were being assigned to a node in the scene tree. Now, they're just created at runtime.
> Refactor: Remove 'onready' from tweens.

- project/src/demo/editor/creature-old/dialogs.gd
- project/src/main/editor/creature/dialogs.gd
- project/src/main/editor/puzzle/dialogs.gd
- project/src/main/utils/utils.gd
Eliminated 'assign_default_dialog_path' method. The purpose of this method was to detect whether a dialog had been launched or not, and if not, to assign it a default path. It is much simpler to instead assign the default path in the _ready() function. It no longer requires a specialized function or weird UUID path.
Changed level editor and old creature editor from defaulting to 'C:\' or '<snip>/AppData/Roaming/Godot/app_userdata/Turbo Fat' to 'Documents'
Removed redundant level editor 'OpenResourceDialog.popup_centered' call. This was being called twice by mistake.
> Refactor: Simplified default dialog path behavior.

- project/src/main/world/creature/dna-loader.gd
These warnings occurred when trying to add a mouth animation player for a non-existent mouth. THis would happen if the player created a creature with no mouth.
> Fix 'invalid mouth: 0' warnings

- project/src/main/editor/creature/AlleleButton.tscn
- project/src/main/editor/creature/CreatureColorButton.tscn
- project/src/main/editor/creature/CreatureNameButton.tscn
- project/src/main/editor/creature/OperationButton.tscn
- project/src/main/editor/creature/creature-color-button.gd
- project/src/main/ui/candy-button/CandyButtonC3.tscn
- project/src/main/ui/candy-button/CandyButtonCollapsible.tscn
- project/src/main/ui/candy-button/CandyButtonH3.tscn
- project/src/main/ui/candy-button/CandyButtonH4.tscn
- project/src/main/ui/candy-button/ShineTextureRect.tscn
- project/src/main/ui/candy-button/candy-button-c3.gd
- project/src/main/ui/candy-button/candy-button-collapsible.gd
- project/src/main/ui/candy-button/candy-button-h3.gd
- project/src/main/ui/candy-button/candy-button-h4.gd
- project/src/main/ui/candy-button/candy-button-shine.gd
All candy buttons had the concept of "Toggle the Shine Texture between
these two textures based on whether the button is pressed or not". I've
extracted a common ShineTextureRect scene to unify this logic.
> Extracted 'ShineTextureRect' for CandyButtons

- project/src/main/ui/candy-button/candy-button-shine.gd
When toggling a CandyButton into the pressed state, the button appeared unpressd until releasing the mouse button. This is because the 'button_down' signal is called before the button's 'pressed' state is updated. I've changed the signal methods to not rely on the button's 'pressed' state.
> Bug: CandyButton ToggleButton shine behavior

- project/project.godot
- project/src/main/editor/creature/AlleleButton.tscn
- project/src/main/editor/creature/CreatureNameButton.tscn
- project/src/main/editor/creature/OperationButton.tscn
- project/src/main/ui/candy-button/CandyButtonC3.tscn
- project/src/main/ui/candy-button/CandyButtonCollapsible.tscn
- project/src/main/ui/candy-button/CandyButtonH3.tscn
- project/src/main/ui/candy-button/CandyButtonH4.tscn
- project/src/main/ui/candy-button/candy-button-c3.gd
- project/src/main/ui/candy-button/candy-button-collapsible.gd
- project/src/main/ui/candy-button/candy-button-h3.gd
- project/src/main/ui/candy-button/candy-button-h4.gd
- project/src/main/ui/candy-button/gradient-helper.gd
This avoids some copy/paste code for calculating which color to use as the button becomes hovered, focused, etc.
This GradientHelper could not be reused for CreatureColorButton because its behavior is slightly specialized and it does not use gradients in the same way.
> Refactor: Extracted 'GradientHelper' from CandyButton

- project/src/main/puzzle/piece/piece-type.gd
- project/src/test/career/test-career-rewinder.gd
- project/src/test/data/test-player-save-upgrader.gd
- project/src/test/puzzle/test-line-clearer.gd
- project/src/test/world/test-career-data.gd
Fixed some int/float comparison warnings in Gut tests. One of these affected the actual game too, PieceType.get_box_type() was returning a float.
Fixed some orphan node warnings in Gut tests. These were false positives, as the nodes were being cleaned up in after_all. But I've updated the tests to use Gut's new 'autofree' functionality anyway.
> Refactor: Gut warnings, orphans

- project/project.godot
- project/src/demo/toolkit/ReleaseToolkit.tscn
- project/src/demo/toolkit/extract-localizables-button.gd
- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/editor/creature/CreatureEditorLibrary.tscn
- project/src/main/editor/creature/allele-buttons.gd
- project/src/main/editor/creature/category-label.gd
- project/src/main/editor/creature/creature-editor-library.gd
- project/src/main/utils/global.gd
This node is only used in the creature editor, so I've changed it into a regular node accessible through Global.get_creature_editor_library()
> Refactor: Removed CreatureEditorLibrary autoload singleton

- project/src/main/data/system-save.gd
This avoids conflicts with Godot's 'Node.filename' property.
> Refactor: 'filename' -> 'save_slot_filename'

- project/src/test/data/test-player-save-upgrader.gd
- project/src/test/data/test-player-save.gd
- project/src/test/data/test-rolling-backups.gd
- project/src/test/data/test-system-save-upgrader.gd
- project/src/test/data/test-system-save.gd
Filenames elsewhere were prefixed with 'user://' but test filenames followed a different convention. This led to extra code as we had to prefix the 'user://' throughout the test instead of just applying it to the constant.
> Refactor: Prefix test filenames with 'user://'

- project/src/main/data/rolling-backups.gd
- project/src/main/data/system-save.gd
- project/src/test/data/test-player-save.gd
- project/src/test/data/test-rolling-backups.gd
- project/src/test/data/test-system-save.gd
Extracted RollingBackups.delete_all_backups() method which is used by the 'delete save slot' functionality and by certain tests.
This partially addresses a bug where running the Gut tests would occasionally delete the user's save slot. This bug occurred because the SystemData.reset() method would change the active save slot, resetting the PlayerSave.data_filename which had been overridden for the tests. Howveer, with this change the cleanup logic will still delete the data from the temporary location, and not the player's user data.
> Extract 'delete_all_backups'. Fix tests removing user data.

- project/src/main/data/system-save.gd
- project/src/test/pre-run-hook.gd
Gut tests had logic to override the player's data_filename, but this was then being reverted when the SystemSave reacted to the 'save_slot_changed' signal, setting the filename back to the user's save slots. The result was that some tests would delete the user's data instead of deleting the test's data.
I've added two protections for the Gut tests:
1. SystemSave no longer assigns the filenames during tests.
2. Gut tests override the filenames by default in a pre-run hook.
> Bug: Gut tests were deleting user data.

- project/src/main/editor/creature/CreatureEditor.tscn
Disabled the Creature Editor 'ui_back' shortcut. Using the back button to quit the creature editor would be surprisingly destructive for the player, and also interfered with closing the color popups.
Changed CreatureEditor's SystemButtons to appear behind the color pickers.
> Creature Editor system buttons tweaks: shortcuts, layer

- project/project.godot
- project/src/demo/editor/creature/CreatureColorButtonDemo.tscn
- project/src/demo/editor/creature/creature-color-button-demo.gd
- project/src/demo/ui/candy-button/CandyColorPickerDemo.tscn
- project/src/demo/ui/candy-button/candy-color-picker-demo.gd
- project/src/main/editor/creature/ColorPickerPopup.tscn
- project/src/main/editor/creature/CreatureColorButton.tscn
- project/src/main/editor/creature/allele-buttons.gd
- project/src/main/editor/creature/color-picker-popup.gd
- project/src/main/editor/creature/creature-color-button.gd
- project/src/main/editor/creature/creature-editor-library.gd
- project/src/main/ui/candy-button/CandyColorPicker.tscn
- project/src/main/ui/candy-button/CandyColorPickerButton.tscn
- project/src/main/ui/candy-button/HsvSlider.tscn
- project/src/main/ui/candy-button/candy-color-picker-button.gd
- project/src/main/ui/candy-button/candy-color-picker.gd
- project/src/main/ui/candy-button/hsv-slider.gd
- project/src/main/utils/utils.gd
- project/src/main/world/creature/dna-utils.gd
- project/src/test/utils/test-utils.gd
Created 'CandyColorPicker', a color picker which supports gamepads. It includes a context-sensitive set of color presets as well as HSV sliders for fully custom colors. It can be navigated well using a gamepad or keyboard.
The presets were collected from both the presets from DnaUtils as well as the creature colors for creatures in the game (e.g Rhonk, Skins). Utilities for repeating this process are in CreatureColorButtonDemo.
> CreatureEditor's color picker supports gamepads

- project/src/main/editor/creature/CreatureEditor.tscn
The VBoxContainer with the allele buttons and main UI for the screen had its mouse mode set incorrectly, blocking mouse inputs for the system buttons
> Bug: CreatureEditor settings button couldn't be clicked

- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/editor/creature/creature-saver.gd
When repeatedly importing different creatures, the CreatureEditor would prompt to save each time. It no longer prompts if the current creature definition matches the most recently imported one.
> Avoid creature editor save prompts when reimporting

- project/src/main/data/system-data.gd
Without saving, the player would need to keep hitting Alt+Enter every time they launch the game.
> Alt+Enter fullscreen shortcut saves system data.

- project/src/main/settings/keybind-settings.gd
Having these omitted from the list of menu actions meant they could potentially have UI-breaking conflicts with other UI controls.
> Added missing menu actions: 'next_tab', 'prev_tab'

- project/src/main/settings/keybind-settings.gd
- project/src/main/ui/settings/keybind/custom-keybind-row.gd
UI controls can no longer be unassigned. If a control is unassigned, it is swapped with the input currently being rebound.
Added missing 'next_tab', 'prev_tab' ui actions
> Prevent unbinding UI controls.

- project/src/main/ui/candy-button/candy-button-c3.gd
- project/src/main/ui/candy-button/candy-button-collapsible.gd
- project/src/main/ui/candy-button/candy-button-h3.gd
- project/src/main/ui/candy-button/candy-button-h4.gd
Toggling a candy button's 'disabled' property didn't change its appearance. I've added a '_refresh_color()' call to the candy button's set_disabled function.
> Bug: Toggling candy button 'disabled' didn't update color

- project/src/main/utils/ResourceCache.tscn
The following warning was appearing on startup in the Godot console:
```
set_path: Another resource is loaded from path 'res://assets/main/credits/pinup-namory.png' (possible cyclic resource inclusion).
```
I think this is because the pinup scene was being loaded at the same time as the pinup resource. I've made the pinup and credits scroll scenes 'low priority resources' which should have probably been done before -- they both point to a lot of big resources.
> Tweaked resource cache to avoid 'namory set_path warning'

- project/src/main/career/ui/career-map-level-select.gd
- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/ui/menu/paged-level-buttons.gd
Assignment of the level name, id, duration and color was behavior partially shared between PagedLevelButtons and CareerMapLevelSelect. With the upcoming TrainingMenu improvements, it's convenient to have this code in one place.
> Refactor: Extract 'LevelSelectButton.decorate_for_level'

- project/project.godot
- project/src/demo/ui/level-select/LevelButtonScrollerDemo.tscn
- project/src/demo/ui/level-select/level-button-scroller-demo.gd
- project/src/main/ui/HighScoreTable.tscn
- project/src/main/ui/level-select/LevelButtonScroller.tscn
- project/src/main/ui/level-select/LevelSelectButton.tscn
- project/src/main/ui/level-select/hookable-level-grade-label.gd
- project/src/main/ui/level-select/level-button-scroller.gd
- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/ui/menu/TrainingMenu.tscn
- project/src/main/ui/menu/training-menu.gd
- project/src/main/ui/menu/training-speed-selector.gd
The training menu previously used an undecorated button which was very wide, and would have been difficult to reskin as a candy button given its width.
The training menu now uses a 'LevelButtonScroller' which uses the same button style as the career mode and level picker. We'd like to eventually amp up these buttons to include some icons or fancy graphics, so that will help this screen look a bit prettier too.
The training menu's high score table now uses the 'squeak-theme-gy' variant, instead of an undecorated 'h4' theme.
> Redesigned TrainingMenu with LevelButtonScroller

- project/src/main/career/ui/CareerRegionSelectMenu.tscn
- project/src/main/ui/menu/PagedLevelPanel.tscn
- project/src/main/ui/menu/PagedRegionPanel.tscn
- project/src/main/ui/menu/paged-level-buttons.gd
- project/src/main/ui/menu/paged-region-buttons.gd
- project/src/main/ui/region-select-button.gd
Level/chapter next/prev buttons no longer use default UI, and instead use 'gy/squeak-theme-h4'
Keyboard/gamepad now work better in level/chapter select. Instead of navigating to the 'next' button and pressing it, navigating off the page automatically selects the next page.
> Improved level/chapter next/prev buttons

- project/assets/main/puzzle/career-regions.json
- project/project.godot
- project/src/demo/toolkit/fix-levels-button.gd
- project/src/main/career/career-region.gd
- project/src/main/career/region-music.gd
- project/src/main/data/player-data.gd
- project/src/main/data/player-save.gd
- project/src/main/music/MusicPlayer.tscn
- project/src/main/music/checkpoint-song.gd
- project/src/main/music/music-player.gd
- project/src/main/ui/menu/career-region-select-menu.gd
- project/src/main/ui/menu/training-menu.gd
Career regions define their own menu music and puzzle music. This music is validated by the Release Toolkit. The menu music and puzzle music is controlled by a new 'PlayerData.menu_region' field. This field is updated when the player selects a new career region in Career Mode or Training Mode.
Puzzle music defines multiple songs for each region. Each region has a 'main song' which plays at the start of each career data and during boss levels. Each region can also define songs which play more frequently.
The twelve songs are arranged such that some songs play twice as frequently in a single area, while others play half as frequently in two areas. Overall, they should all play about the same amount of time.
> Each career region has its own music.

- project/src/main/puzzle/combo-burst.gd
This was intended for inclusion in a28773ef but was left out.
> Mirror combo accents.

- project/src/main/ui/menu/tutorial-menu.gd
This already had a utility method in OtherLevelLibrary.region_for_id, it doesn't make sense to reimplement it here
> Simplify TutorialMenu's 'find_tutorial_region' technique

- project/src/main/ui/CheatCodeDetector.tscn
The LevelButtonScroller and PagedLevelButtons both tried to play the same sound effect, resulting in an unpleasant sfx overlap when entering the cheat code
> Fixed overlapping cheat sfx for 'unlock' cheat in training menu

- project/src/main/puzzle/critter/carrots.gd
- project/src/main/puzzle/critter/sharks.gd
- project/src/main/utils/breadcrumb.gd
Steam achievements want to receive signals for a few specific arbitrary events like 'there are 6 carrots visible' or 'the player squished a shark' so I've added signal support for these events.
Added Breadcrumb.after_scene_changed signal.
> Signals for achievements: after_scene_changed, creature_saved, etc

- project/src/main/career/career-level-library.gd
- project/src/main/steam/chapter-rank-s-achievement.gd
- project/src/main/steam/chapter-story-finished-achievement.gd
- project/src/test/career/test-career-level-library.gd
The 'Chapter Rank S' and 'Chapter story completion' achievements were especially sluggish, taking 0.2 ms and 1.5 ms respectively. This doesn't seem impactful but there are twelve of these achievements so it adds up to 10 ms every save.
These achievements are now only calculated when a corresponding chapter's level or cutscene is played.
> Improve steam achievement performance

- project/src/main/editor/creature/dialogs.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-dialogs.gd
- project/src/main/ui/settings/settings-menu-bottom.gd
'ui_cancel' now closes modal dialogs.
'ui_cancel' no longer closes the settings menu if a modal dialog is visible.
Closes #1787.
> Improve 'ui_cancel' behavior with modal dialogs.

- project/src/main/ui/level-select/HardcoreLevelSelectButton.tscn
- project/src/main/ui/level-select/LevelSelectButton.tscn
- project/src/main/ui/level-select/LevelSelectButtonControlHolder.tscn
- project/src/main/ui/level-select/LevelSelectButtonFont.tres
- project/src/main/ui/level-select/level-select-button.gd
Updated LevelSelectButtonFont 'extra_spacing' property to vertically condense the text.
Extracted 'LevelSelectButtonControlHolder' to reduce repetition between LevelSelectButton and HardcoreLevelSelectButton.
Changed LevelSelectButton heights from 60/93/126 to 80/100/120. They still get taller for longer levels, but the calculations are simpler and the heights are less variable. This makes it easier to accommodate button icons in an upcoming commit.
> Level button tweaks: extra_spacing, ButtonControlHolder

- project/src/demo/ui/candy-button/CandyColorPickerDemo.tscn
- project/src/demo/ui/candy-button/candy-color-picker-demo.gd
Restored CandyColorPickerDemo 'color_changed' signal
Fixed 'rect_position' calculation which moved the panel too far to the bottom right if the window was resized
> CandyColorPickerDemo: signals, position

- project/src/main/ui/h-slider-gamepad-helper.gd
HSliderGamepadHelper now stops sliding when it loses focus. Otherwise the gamepad kept sliding forever if you pressed "up" while sliding.
HSliderGamepadHelper now stops its 'delay timer' when it loses focus. Otherwise, repeated gamepad taps were resulting in large changes in the timer.
> HSliderGamepadHelper fixes: focus, timer

- project/src/main/steam/chapter-rank-s-achievement.gd
- project/src/main/steam/chapter-story-finished-achievement.gd
- project/src/main/steam/combo-achievement.gd
- project/src/main/steam/create-creature-achievement.gd
- project/src/main/steam/customer-score-achievement.gd
- project/src/main/steam/leftovers-score-achievement.gd
- project/src/main/steam/rank-m-achievement.gd
- project/src/main/steam/shark-smush-achievement.gd
- project/src/main/steam/steam-achievement.gd
- project/src/main/steam/unique-level-achievement.gd
Steam Achievements now connect their signals 3 seconds after startup. This prevents us from immediately flooding the Steam API with calls on startup, which was causing the game to crash.
> Updating achievement timing

- project/project.godot
- project/src/demo/ui/level-select/LevelSelectButtonDemo.tscn
- project/src/main/career/CareerMap.tscn
- project/src/main/ui/level-select/GradeLabels.tscn
- project/src/main/ui/level-select/LevelButtonScroller.tscn
- project/src/main/ui/level-select/level-grade-labels.gd
- project/src/main/ui/menu/PagedLevelPanel.tscn
- project/src/main/ui/menu/paged-level-buttons.gd
Extracted GradeLabels node. The script was already reused, but the node encapsulates the 'HookableLevelGradeLabel' packed scene, mouse filter, anchors and other node properties.
Removed LevelGradeLabels 'button_added' signal receiver. This was a bit of a 'gotcha' when extracting this scene, and I don't like the design. This signal method is only used by PagedLevelPanel, and it makes more sense to be on one of PagedLevelPanel's scripts instead.
> Refactor: Extracted GradeLabels.tscn

- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/editor/creature/creature-saver.gd
- project/src/main/editor/creature/save-message.gd
The signal 'creature_saved' is a little misleading as it doesn't apply when the creature is saved due to the player answering a dialog prompt.
> Refactor: CreatureSaver.creature_saved -> save_button_pressed

- project/project.godot
- project/src/demo/toolkit/ReleaseToolkit.tscn
- project/src/demo/toolkit/extract-localizables-button.gd
- project/src/demo/toolkit/fix-chats-button.gd
- project/src/demo/toolkit/fix-creatures-button.gd
- project/src/demo/toolkit/fix-levels-button.gd
- project/src/demo/toolkit/release-tool-button.gd
- project/src/demo/toolkit/release-toolkit-output.gd
- project/src/demo/toolkit/run-all-button.gd
Instead of clicking the buttons sequentially and monitoring the output, the user can now just click the "Run All" button and monitor the result.
> Added 'run all' functionality for ReleaseToolkit.

- project/src/main/world/creature/creature-loader.gd
CreatureLoader treated 'black' as 'null' when assigning shader colors. Black is a pickable eye color in the creature editor, and the player can also pick it with the sliders.
'Transparent' is now treated as null instead. The player can't pick this with the creature editor, so it's more suitable as a 'null' value.
> Bug: Black (#000000) creature colors caused texture issues

- project/src/demo/puzzle/level/level-rank-demo.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/rank-calculator.gd
The name 'rank' was ambiguous, and a reasonable misinterpretation of the function is that it would convert a grade like 'A' to the minimum requirement such as '44.0'.
I've renamed the method to 'average_rank_per_grade' and added a new method 'required_rank_for_grade' to provide the utility I needed.
> RankCalculator.rank() -> average_rank_for_grade()

- project/src/main/puzzle/result/BarGraphGoal.tscn
Apparently this is a prank the Godot editor enjoys playing on developers as retribution for violating unwritten Godot etiquiette -- perhaps introducing a cyclic reference, triggering a runtime error, or working overtime on Friday the 13th.
> Restored baffling 'BarGraphGoal' change instigated by the Godot editor

- project/src/main/career/ui/ProgressBoard.tscn
The shadow was overlapping the wooden edges of the progress board in a strange way, particularly when maximized.
> Adjusted ProgressBoard shadows.

- project/src/main/puzzle/playfield-fx.gd
The light map/glow map tilesets used to remain populated when the Puzzle.tscn scene was reused, however, the tile instances now appear to become ruined. I've replaced the old logic for caching the tile sets with new logic for purging the garbage tilesets.
> Bug: Combo lights didn't show up

- project/src/main/puzzle/result/results-hud.gd
After finishing a level, if the player hit 'R' to restart the level while the animation was playing, the ResultsHud BarGraph would continue playing sounds.
ResultsHud now resets all of its child components when it scrolls offscreen.
> Bug: ResultsHud BarGraph sfx kept playing on restart

- project/src/main/ui/CheatCodeDetector.tscn
- project/src/main/utils/DeconflictedAudioStreamPlayer.tscn
- project/src/main/utils/deconflicted-audio-stream-player-2d.gd
- project/src/main/utils/deconflicted-audio-stream-player.gd
- project/src/main/utils/sfx-deconflicter.gd
DeconflictedAudioStreamPlayer now accepts an optional 'threshold_msec' parameter.
> Fixed overlapping audio for Training Menu 'unlock' cheat

- project/src/main/ui/level-select/level-button-scroller.gd
If the leftmost level were selected in the Training menu, the 'unlock' cheat would reposition the button incorrectly
> Fixed bug where 'unlock' cheat moved central button incorrectly

- project/src/main/chat/ui/chat-ui.gd
- project/src/main/editor/creature/color-picker-popup.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/button-shortcut-helper.gd
- project/src/main/ui/level-select/level-button-scroller.gd
- project/src/main/ui/menu/paged-level-buttons.gd
- project/src/main/ui/menu/paged-region-buttons.gd
Before, it was impossible to toggle fullscreen with alt+enter while a cutscene was playing, because chat-ui.gd's get_tree().set_input_as_handled() would prevent system-data.gd from receiving the "fullscreen" input.
> 'Fullscreen' input overrides other inputs.

- project/assets/main/chat/career/lava/boss-level-end.chat
- project/assets/main/chat/career/lava/boss-level-reretry.chat
- project/assets/main/chat/career/lava/boss-level-retry.chat
- project/assets/main/chat/career/lava/boss-level.chat
- project/assets/main/chat/career/lava/intro-level-end.chat
- project/assets/main/chat/career/lava/intro-level.chat
These cutscenes had a lot of dead space on the left and bottom of the screen.
> Zoom in camera for 'Zagma HQ' cutscenes

- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/result/results-hud-blueprint.gd
Toggling the "winish" or "finish" cheats adjusts the player's score, but didn't adjust their score components. The result is that the ResultsHud would count up a total of $0 and then award an SS+ grade, which makes no sense.
The "winish" and "finish" cheats now make up arbitrary values for the combined scores.
Also made a minor adjustment to ResultsHudBlueprint to explicitly calculate the 'extra' value as 'everything but boxes and combos'. This helps handle edge cases where they don't add up otherwise. It also helps future-proof the code in case the score calculation changes in the future.
> Bug: "winish" cheat caused bizarre output for ResultsHud

- project/project.godot
- project/src/demo/world/FreeRoamDemo.tscn
- project/src/main/career/CareerMap.tscn
- project/src/main/chat/chat-tree.gd
- project/src/main/world/Cutscene.tscn
- project/src/main/world/OverworldBg.tscn
- project/src/main/world/cutscene-world.gd
- project/src/main/world/environment/credits/CrowdSurfCutscene.tscn
- project/src/main/world/environment/credits/CrowdWalkCutscene.tscn
- project/src/main/world/environment/restaurant/RestaurantPuzzleScene.tscn
- project/src/main/world/overworld-bg.gd
The outer space background was especially distracting during the 'Zagma HQ' cutscenes, but in indoor cutscenes it just too strange and distracting.
> Disable outer space background for indoor scenes

- project/src/main/music/music-player.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/result/receipt-header.gd
- project/src/main/world/career-map.gd
- project/src/main/world/cutscene-queue.gd
ResultsHud now shows 'Level Failed...' when failing to meet the success criteria for a boss level. Before, it only showed a failure message if you quit or lost all your lives.
Added 'CurrentLevel.boss_level' flag. This is necessary because the CareerData.is_boss_level() method is based purely on the player's distance, but this distance is unreliable during a level, as it is adjusted when the player plays or finishes a level
> 'Level failed...' when not scoring enough for a boss level.

- project/src/main/puzzle/result/receipt-bar-graph.gd
The old scroll speed meant the bad graph was often still scrolling when the stamp got applied to the paper, breaking the illusion that the stamp was on the page.
> Increased ResultsHud bar graph scroll speed.

- project/src/main/editor/creature/fatness-changer.gd
When importing a creature, this code occasionally crashed complaining that a method was being called on a null instance. The instance wasn't actually null, but was not a valid instance. This check seems to prevent the error.
The error didn't happen very consistently, but seemed to happen if you played the game for awhile and then launched the creature editor and imported a creature.
> Added instance_valid check to avoid NPE in fatness changer

- project/src/main/career/ui/ProgressBoard.tscn
- project/src/main/career/ui/animation-player-unscrewerupper.gd
- project/src/main/ui/AnimationPlayerUnscrewerupper.tscn
Workaround for Godot #90079 (https://github.com/godotengine/godot/issues/90079).
Godot has an exciting feature where Controls animated by an AnimationPlayer randomly change their position or size. This only affects the editor, and results an exciting and fun surprise for developers.
I've added a workaround to prevent controls from randomly changing their position and size.
> Godot #90079 workaround (wandering controls)

- project/assets/main/puzzle/career-regions.json
- project/src/main/career/region-music.gd
- project/src/main/career/ui/ProgressBoard.tscn
- project/src/main/career/ui/progress-board.gd
- project/src/main/music/music-player.gd
- project/src/main/puzzle/puzzle-music-manager.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/world/career-map.gd
- project/src/main/world/career-world.gd
- project/src/main/world/cutscene-world.gd
'Extra sprinkles' plays for boss levels. It plays once the player reaches the boss level, and under certain other edge cases like if the player quits and re-enters career mode when they're at a boss level.
Removed 'Extra Sprinkles' as Chocolava Canyon's signature song. Sugar Crash is now the signature song for the first two regions, and Pressure Cooker is the signature song for Chocolava Canyon. This is good for a few reasons imho: Sugar Crash shows up in the credits, so it's good to cement it in the player's head a little more. Also Extra Sprinkles is a really good song so it's good for the player to hear it early, as opposed to saving it for levels which only a few players will reach.
> Added goal hype music: 'Extra Sprinkles'

- project/src/main/editor/creature/creature-editor.gd
- project/src/main/ui/menu/main-menu-adventure.gd
Added a missing substitute singletons call to the CreatureEditor. To my knowledge, this mostly affects the wallpaper in a very subtle way, but it's more future-proofing for other singletons I may have forgotten about.
> Creature editor plays music. Substitute singletons call.

- project/src/main/steam/carrot-count-achievement.gd
- project/src/main/steam/chapter-rank-s-achievement.gd
- project/src/main/steam/level-rank-achievement.gd
- project/src/main/steam/rank-m-achievement.gd
- project/src/test/steam/test-steam-achievements.gd
Some recent changes in the rank algorithm resulted in runtime errors.
> Added tests to ensure achievements don't crash.

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/piece/frame-input.gd
If the player held an input before a level transition, the tutorial replays would break. It would ignore all player input, but this ignored the "releasing the input" input so the entire replay would play as though the key were held.
All keys are now released at the start of a level transition.
> Bug: Tutorial replays broke if player held a key

- project/src/main/steam/chapter-rank-s-achievement.gd
- project/src/main/steam/chapter-story-finished-achievement.gd
A playtester reported the 'achieve an S- rank on all levels' achievement unlocked prematurely, and looking at their logs revealed some baffing responses from Steam:
[STEAM] Setting Steam stat: CHAPTER_3_RANK_S_PERCENT -> 6.25
[STEAM] Getting Steam stat: CHAPTER_3_RANK_S_PERCENT
[STEAM] get_stat_float(CHAPTER_3_RANK_S_PERCENT) response: 728754765532960332447744
[STEAM] setStatFloat(CHAPTER_3_RANK_S_PERCENT, 6.25) response: False
While these responses wouldn't cause the achievement to unlock, it still seems like we should perform some data validation on our 'set_stat_float' calls. I'm guessing at some point a division by zero error or data issue may have resulted us setting this stat to 'INF' or something. I can't reproduce it, but we should still guard against it
> set_stat_float sanity checks, error logging

- project/assets/test/data/config-37b3.json
- project/src/main/data/system-save-upgrader.gd
- project/src/main/data/system-save.gd
- project/src/main/settings/keybind-settings.gd
- project/src/test/data/test-system-save-upgrader.gd
- project/src/test/settings/test-keybind-settings.gd
Older versions of the save data did not include custom keybinds for 'next_tab' or 'prev_tab', causing crashes when keybinds-settings.gd tried to verify that all UI keybinds had keys assigned. I've fixed this bug in several different ways for redundancy:
1. SystemSaveUpgrader now adds the 'next_tab' and 'prev_tab' keybinds
2. On load, KeybindSettings checks whether any custom UI keybinds are absent or duplicated and if so, restores the default custom keybinds
3. KeybindSettings checks for the absence of a custom keybind to avoid an NPE
4. A Gut test verifies that older keybinds are preserved during the upgrade -- so if a new keybind is added or this logic is broken, this test will fail as the default custom keybinds are restored
> Bug: Crashes editing keybinds from older save data

- project/src/main/steam/steam-utils.gd
Before, we logged even on suppressed/redundant calls which never went out to Steam. Now, we only log when calling the Steam API.
> Tweaked GodotSteam logging to occur less frequently

- project/src/main/chat/ui/chat-choices.gd
- project/src/main/chat/ui/chat-ui.gd
- project/src/main/world/Cutscene.tscn
- project/src/main/world/CutsceneUi.tscn
- project/src/main/world/cutscene-ui.gd
- project/src/main/world/overworld-buttons.gd
Added a 'quit' button to the CutsceneUI. The player can quit by pressing the button or hitting escape.
ChatChoices no longer suppresses player input; this was vestigial behavior from when the player could run around in free roam mode and talk to people.
> Player can exit cutscenes.

- project/src/main/data/system-data.gd
- project/src/main/data/system-save.gd
- project/src/main/settings/misc-settings.gd
- project/src/main/ui/settings/keybind/custom-keybind-button.gd
- project/src/main/ui/settings/keybind/custom-keybind-row.gd
- project/src/main/ui/settings/keybind/settings-keybinds-control.gd
- project/src/main/ui/settings/reset-gameplay-button.gd
- project/src/main/ui/settings/settings-creature-detail.gd
- project/src/main/ui/settings/settings-feeding-animation.gd
- project/src/main/ui/settings/settings-fullscreen.gd
- project/src/main/ui/settings/settings-gameplay-speed.gd
- project/src/main/ui/settings/settings-ghost-piece.gd
- project/src/main/ui/settings/settings-hold-piece.gd
- project/src/main/ui/settings/settings-language.gd
- project/src/main/ui/settings/settings-line-piece.gd
- project/src/main/ui/settings/settings-lock-cancel.gd
- project/src/main/ui/settings/settings-menu.gd
- project/src/main/ui/settings/settings-touch-fat-finger.gd
- project/src/main/ui/settings/settings-touch-scheme.gd
- project/src/main/ui/settings/settings-touch-size.gd
- project/src/main/ui/settings/settings-use-vsync.gd
- project/src/main/ui/settings/volume-setting-control.gd
The settings menu always saved the player's data and displayed the little spinning disk, even if the player just opened the settings menu to end a puzzle or quit career mode.
The settings menu now only saves the player's data if the player makes changes to their settings.
> Bug: Settings menu always resulted in save confirmation

- project/src/main/puzzle/puzzle.gd
Before, going into the settings menu and choosing "Quit" from a Career Mode puzzle would abort the puzzle, incurring a penalty and leaving the player in career mode.
Now, going into the settings menu and choosing "Quit" will exit Career mode. The player may still incur a penalty if they've already played and lost the level, but they can quit and play the same level again later or even pick a different level.
> Improve career mode's puzzle quit behavior.

- project/assets/main/chat/career/credits/precredits-1.chat
- project/assets/main/chat/career/credits/precredits-2.chat
- project/assets/main/chat/career/lava/boss-level-end.chat
- project/src/main/world/overworld-ui.gd
Before, watching the final cutscene would end the career day, but if you exited the previous cutscenes, the player would continue into Starberry Mountain.
This isn't a big deal, but it's a little inconsistent and odd. The gameplay behavior should stay the same regardless of whether the player watches the credits or the preceding cutscenes.
I also closed a small issue where watching the cutscenes in the CutsceneDemo (or perhaps some future gallery mode) would end the current career day. The career day is now only ended if the player is watching the cutscenes from career mode.
> Improve quit behavior during credits

- project/src/main/ui/input-manager.gd
InputManager is supposed to toggle the mouse visible/invisible, but it was disabled when the game was paused, causing the mouse to remain invisible in the settings menu
> Fixed bug where mouse remained invisible in settings menu

- project/src/main/ui/settings/SettingsMenu.tscn
This button was unhooked in 8699bb67 when changing the settings menu's UI.
> Reconnected 'Reset to Default' gameplay settings button

- project/src/main/ui/level-select/LevelSelectButtonPressed.tres
LevelSelectButton was briefly translucent when pressed. This looks kind of cool but it was accidental, and I've fixed it
> Fixed translucent level select buttons

- project/src/main/puzzle/puzzle.gd
For levels with a goal like 'finish in 3 minutes', the "winish" cheat was setting the clock to 3:00 minutes, which meant the player would fail after dropping the current piece with a time of 3:01.
The "winish" cheat now sets the clock to 10 seconds before the target time.
> "winish" cheat works better for levels with time criteria

- project/src/main/ui/level-select/level-button-scroller.gd
Replaced 'yield idle frame' with 'call_deferred'
This 'call_deferred' appears to be Godot's intended way of waiting until the end of a physics/process frame, and the behavior seems more consistent across different PCs.
> LevelButtonScroller 'disappearing buttons' bug

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/main/puzzle/tutorial-keybinds-label.gd
- project/src/main/ui/settings/keybind/custom-keybind-button.gd
Changed the custom controller prompt from 'enter key' to 'press...' Enter key is nonsensical for players using a controller.
Changed the tutorial prompt for players who unbind their controls from 'Click...' to 'Go into...'. Click is specifically for mouse and keyboard players, it doesn't make sense for a controller
> Controller game prompts; 'enter/click' -> 'press'

- project/src/main/puzzle/ranks.gd
- project/src/test/puzzle/test-ranks.gd
Times over 20:00 are now rounded to the nearest minute. This is not likely to ever matter, but cosmetically I think it's better to tell the player "Finish this level in 22:00" instead of "Finish this level in 22:20"
> Tweak time rounding: 20:33 -> 21:00

- project/src/main/puzzle/intro/intro-receipt.gd
This listener caused a warning, and the absence of a 'game started' listener could have caused the intro receipt to pop up in some edge cases, probably.
> Fixed bogus intro receit listener.

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/main/settings/gameplay-settings.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-lock-cancel.gd
Disabled Soft Drop Lock Cancel by default. Two high-level Tetris players complained about the setting, and I think it's something Turbo Fat experts can seek out and enable if they like it. It's better for the default settings to cater to new players.
Added a description field for the Soft Drop Lock Cancel property.
> Soft Drop Lock Cancel tweaks: default off, description field.

- project/assets/main/keybind/guideline-hold.json
- project/assets/main/keybind/guideline.json
- project/src/main/ui/settings/keybind/settings-keybinds-control.gd
Guideline controller keybinds now use X/A to rotate instead of A/B. This seems more comfortable as it's where your thumb rests naturally on the controller.
The old guideline controller keybinds are still accessible as WASD. Since WASD and Guideline controller keybinds are now distinct, I added logic to the Settings menu to swap between them.
> Guideline controller keybind tweaks: A/B -> X/Y

- project/src/main/ui/input-manager.gd
The InputManager was only responding to button inputs, which meant the player had to clumsily use the D-Pad or press a button before it would accept analog input.
> Analog input now toggles InputManager input mode.

- project/src/main/ui/analog-event-translator.gd
The UI sliders have some specific logic for processing JoypadButton events, but this logic was being sidestepped because our AnalogEventTranslator generated InputEventActions instead. I've rewritten the translator to use InputEventJoypadButtons instead, which also makes the code much simpler.
> Analog sticks now work for UI sliders.

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/main/ui/menu/region-info-panel.gd
Replaced the 'Replay this chapter to continue your adventure' message in Career mode with new messages, 'Start this chapter...' and 'Play this chapter...' which make more sense for players who haven't beaten the game.
Removed 'star count' message from chapter descriptions. I was originally thinking I'd have 'stars' instead of letter grades, so players wouldn't be discouraged by seeing they got a 'B-' or something like that. But I've decided letter grades are OK, the grade scale is just shifted so everybody gets an A or better.
> 'Replay to continue adventure', star count

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/main/career/career-hint.gd
Added hint messages for turning on cheats. Some players are going to be discouraged at the game's difficulty, so it would be nice to occasionally remind them about the cheats they can turn on.
Changed 'soft drop lock cancel' hint to tell players where to enable this functionality. It's off by default, they'll have to turn it on.
> Improved hint messages: cheats, soft drop lock cancel

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/unplugged-controller-detector.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/controller-unplugged-message.gd
- project/src/main/ui/settings/settings-menu.gd
If the player's controller disconnects during gameplay, we pop up the settings menu with a message.
We don't pop up the settings menu in the creature editor, during cutscenes, or in other parts of the game.
> Add a 'controller disconnected' message during puzzles

- project/src/main/ui/settings/settings-menu.gd
- project/src/main/utils/pauser.gd
Deleting/changing the save left the game paused, causing the game to softlock because the SceneTransition couldn't play.
Deleting/changing the save now purges all "pausers".
> Fixed softlock when deleting/changing save

- project/src/main/career/career-calendar.gd
When new players play the game, they will get past the first boss level or maybe even the first two, but they will inevitably end up in a region with only 1 or 2 levels remaining, get part way to the boss level, and be told "Let's stop and try again"
The intent of Career mode is more or less a six-level time limit to reach a goal. It has a side effect of portioning out the gameplay into bite-size sections, but that's not strictly the intent, and I definitely don't want to frustrate the player by forcing them to restart when they haven't even had a chance to progress yet
> Clearing a boss level now resets the career day.

- project/src/demo/editor/creature-old/CreatureEditorOld.tscn
- project/src/demo/editor/puzzle/LevelEditor.tscn
- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/ui/CreatureStressTest.tscn
- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/SplashScreen.tscn
- project/src/main/ui/menu/SystemButtons.tscn
- project/src/main/ui/menu/TrainingMenu.tscn
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-menu-bottom.gd
- project/src/main/ui/settings/settings-menu.gd
Changed 'quit' to 'back' and 'main menu' appropriately, for places where the button does not quit the game.
Hopefully this makes it less ambiguous what the button does.
> Quit -> Back, Main Menu

- project/assets/test/puzzle/levels/level-59c3.json
- project/src/main/puzzle/level/blocks-during-rules.gd
- project/src/main/puzzle/level/level-settings-upgrader.gd
- project/src/main/puzzle/level/levels.gd
- project/src/main/puzzle/line-filler.gd
- project/src/main/puzzle/pan/puzzle-frying-pans-ui.gd
- project/src/main/puzzle/top-out-tracker.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/test/puzzle/level/test-blocks-during-rules.gd
- project/src/test/puzzle/level/test-level-settings.gd
Combined 'clear_on_top_out' and 'refresh_on_top_out' into a single 'top_out_effect' field. These two fields shouldn't have been separated, since otherwise it's ambiguous what should happen if both are set to true.
Added a new 'top_out_effect none'. Some tutorials don't want to alter the playfield when the player tops out, and just want to restart the tutorial section.
> Added BlocksDuringRules.top_out_effect. Added 'none' top out effect.

- project/src/main/puzzle/piece/frame-input.gd
If the player mashed the rotate keys when a replay was starting, their buffered input would be applied to the replay. For example, during the 'squish and recover' tutorial, they could mash the rotate buttons during the two replays of the tutorial, causing Fat Sensei to clear a line or to block the well entirely.
Buffered inputs no longer impact replays.
> Bug: buffered player inputs impacted replays

- project/src/main/puzzle/critter/critter-manager.gd
Before, eaten pieces emitted PIECE_WRITTEN trigger but not the corresponding signals. Most notably, these signals advance the ComboTracker so it meant sharks eating your piece let you place too many pieces.
> Eaten pieces emit piece_written signals

- project/src/main/puzzle/result/ResultsHud.tscn
- project/src/main/puzzle/result/results-hud.gd
The results hud receipt is now clipped. Its boundaries extend 84 pixels below the bottom of the screen. This distance means it will remain unclipped for users playing the game at a 4:3 aspect ratio, but also means it won't extend so far as to look too weird on a vertical monitor.
> Clip results hud receipt vertically.

- project/src/main/puzzle/Puzzle.tscn
This chalk dust texture didn't have the 'night_mode_dark_self' group assigned, so the onion didn't darken it, resulting in weird brown dust.
> Night mode affects 'chalk dust'

- project/src/main/career/ui/ProgressBoard.tscn
- project/src/main/chat/ui/ChatUi.tscn
- project/src/main/ui/menu/TrainingMenu.tscn
Cutscene/chat UI now extends all the way to bottom of the screen. Before, chat choices and chat messages were appearing in the middle of the screen.
Progress board is now centered, instead of appearing at the top of the career map window.
Training menu speed slider is now centered.
> Minor display issues with vertical screens.

- project/src/main/ui/menu/training-menu.gd
Training menu was always initially showing 'Earn $200...!' message regardless of which level was selected.
> Fixed training menu initial description

- project/src/main/puzzle/puzzle-music-manager.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/puzzle.gd
Fixed a bug where the puzzle music stopped in career mode if the player restarted the puzzle.
> Bug: Music stops on retry

- project/src/main/career/career-data.gd
If the player skips a cutscene or quits at an unusual time, they might never view certain cutscenes, locking them out of 100%.
We now mark those cutscenes as viewed for the purposes of region completion.
> Added workaround for unfinishable regions

- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
When restarting a puzzle with a priority customer, the camera would often stay focused on that customer when the player broke their combo. This meant instead of swinging to a new customer and having the old customer change in the background, the camera would stay focused on the current customer and the customer would change in the foreground.
I've changed the 'puzzle preparation' code to always purge the current customer from the queue to ensure it will always focus on a new customer.
I also changed RestaurantView.reset() to kill all the summon_customer_timers. If the timers stayed running, there were some edge cases where the camera would end up on a random customer instead of the intended priority customer.
> Bug: Restarting sometimes kept focus on current 'morphing' creature

- project/src/main/data/player-save.gd
- project/src/main/puzzle/rank-result.gd
Rank data is calculated at runtime instead of being stored. Storing rank data had one major design problem, which is that if we want to make a level easier, the store rank data will still give the player a worse grade
We also purge all non-existent levels.
Calculating all rank data takes about 400 ms on my computer, and it's only done at startup.
If we decide the 400 ms delay on startup is undesirable, we could adopt a 'best of both worlds' approach where rank data is stored, but conditionally refreshed (perhaps the player's save data can have a 'level_version', which causes us to recalculate all ranks when it's out of date, or something like that.)
> Calculate rank data at runtime, instead of storing it

- project/src/main/steam/steam-achievement.gd
GodotSteam's native version crashed when checking achievements, but the standalone version does not crash.
Not checking achievements on load resulted in some edge cases where story achievements (finish the story for chapter 2) could never unlock, because the player could never view another cutscene in that chapter
> Steam achievements are checked on load again

- project/src/demo/puzzle/level/rank-outlier-demo-analyze.gd
Filtering for each region's level by itself is too narrow and generates very erratic results. Filtering for the main story levels and excluding the bonus levels gives a more balanced result
> RankOutlierDemo can filter for main story levels

- project/src/main/data/player-save.gd
- project/src/test/data/test-player-save-upgrader.gd
- project/src/test/pre-run-hook.gd
Now that ranks are populated on startup, it takes about 300 ms to load a save. This is fine for the player starting the game, but it's too slow for unit tests since they need to load 20-30 saves to test backwards compatibility. I've added a 'pre-run hook' which disables this functionality. It invalidates 2 tests.
> Fixed gut tests for rank change

- project/src/main/credits/credits-scroll.gd
Fixed bug where credits end text stopped at 83%. max_completion_value was including the non-completable 'Starberry Mountain' region
> Bug: Credits end text did not reach 100%

- project/src/main/steam/steam-utils.gd
We're trying to diagnose achievement bugs which only affect some users. On the basis that it might be a timing or race condition issue, I've added a timestamp to the steam logs.
> Added timestamp to steam logs.

- project/src/main/steam/chapter-rank-s-achievement.gd
- project/src/main/steam/chapter-story-finished-achievement.gd
I'm still unable to duplicate #2720 locally, but we've seen similar bugs affect other Godot projects when Godot randomly swaps certain values between being ints and floats. While I can't understand how that bug could cause this behavior for this section of code, particularly with the values we're seeing logged, it still feels like a meaningful precaution.
> Explicitly type 'percent' achievements as floats

- project/src/main/steam/steam-utils.gd
We're seeing crashes seemingly centered around calls to `getAchievement`. It's unclear what's causing this, but one possibility is that getAchievement is not returning a Dictionary with a boolean 'achieved' key -- if any of those weren't true, this method would crash.
I've added some logging and checks to protect against unusual responses.
> Protect against unusual 'getAchievement' responses

- project/src/main/editor/creature/fatness-changer.gd
Fixed bug where Creature Editor did not save the player's fatness; the player's avatar was always slim
> Bug: Creature Editor did not save fatness

- project/src/main/steam/shark-smush-achievement.gd
- project/src/main/steam/unique-level-achievement.gd
- project/src/main/ui/scene-transition.gd
- project/src/main/utils/breadcrumb.gd
Made some changes to the scene change logic to try and avoid crashes. These crashes are unpredictable and difficult to pin down, so we're trying many different things.
Replaced 'after_scene_change' listeners with 'game_prepared' listeners. One possible vector for crashes is these 'after_scene_changed' listeners firing at unusual times, possibly before the new scene is loaded.
Defer SceneTransition 'fade_in' effect until next available idle frame. One possible vector for crashes is firing these 'fade_in_started' signals being fired at an unusual time, possibly before the old scene is unloaded.
> Scene change tweaks: after_scene_changed, fade_in

- project/src/main/ui/settings/SettingsMenu.tscn
These warning boundaries were too narrow, causing text to get cut off in Spanish.
> Change Settings '...on next scene' warning boundaries

- project/src/main/career/career-region.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/puzzle/other-region.gd
Our data objects such as 'CareerRegion' and 'LevelSettings' translated their name and description on initialization. This was a flawed idea for many reasons:
1. These models are only initialized on startup, which means if the objects were translated into Spanish on startup, the player would not be able to change their language as our translation framework has no way of translating from Spanish to other languages
2. These models are initialized before PlayerSave is loaded, so they were always translating into English anyways, even if the player selected a different language
Overall it seems better for the models to remain in English, and for language translation to occur on the UI side. I've verified that career regions and levels still show up in Spanish, even removing this translation …
> Removed redundant spanish translation of data objects

- project/src/main/steam/carrot-count-achievement.gd
- project/src/main/steam/first-customer-score-achievement.gd
- project/src/main/steam/level-pickup-achievement.gd
- project/src/main/steam/unique-level-achievement.gd
UniqueLevelAchievements like 'get $250 in pickups on this level' did not disconnect their listeners. This resulted in a few undesirable effects:
1. An console error if you played an achievement level such as 'Cheerleaders' multiple times
2. The achievements could unlock for unrelated levels. For example, playing 'Cheerleaders' and then 'Serving On A Rocket' could unlock the achievement for onscreen carrots.
> UniqueLevelAchievements disconnect their listeners

- project/src/main/steam/carrot-count-achievement.gd
- project/src/main/steam/chapter-rank-s-achievement.gd
- project/src/main/steam/chapter-story-finished-achievement.gd
- project/src/main/steam/combo-achievement.gd
- project/src/main/steam/create-creature-achievement.gd
- project/src/main/steam/customer-score-achievement.gd
- project/src/main/steam/first-customer-score-achievement.gd
- project/src/main/steam/leftovers-score-achievement.gd
- project/src/main/steam/level-pickup-achievement.gd
- project/src/main/steam/rank-m-achievement.gd
- project/src/main/steam/steam-achievement.gd
Achievement conditions do not need to be checked if the achievement has already been achieved. We used to avoid calls to
Steam.is_achievement_achieved because API calls were expensive, resulting in internet calls and sometimes crashing the game. However these calls are now cheap and go to our facade, so it's better to avoid checking the achievement conditions for completed achievements. These achievement checks in some cases are a little expensive, such as for the 'Create Creature Achievement'.
> Streamline achievement checks.

- project/src/main/puzzle/critter/onions.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/utils/breadcrumb.gd
If certain signals were fired while no puzzle was active, a null pointer exception could cause a crash. I never saw this myself, as it would require something nonsensical like "a shark is smushed on the main menu screen," but it could potentially explain some of the crashes we're seeing on steam versions of the game.
Also added a null check for get_tree().current_scene. This method is only used in a demo, but we may as well check.
> Added null checks for CurrentLevel.puzzle.

- bin/troubleshoot_bat/turbofat-troubleshoot.bat.template
- package.sh
- project/src/main/data/player-save.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/ui/save-indicator.gd
- project/src/main/ui/scene-transition.gd
- project/src/main/utils/breadcrumb.gd
- project/src/main/utils/global.gd
- project/src/main/utils/resource-cache.gd
- project/src/main/world/creature/creature.gd
Turbo Fat now includes a 'turbofat-troubleshoot.bat' file which enables Godot's '--verbose' flag as well as a Turbo-Fat-specific '--tf-verbose' flag. These enable enhanced logging for scene transitions, singletons and resource loading. The intent is to give players a tool to share detailed crash information with developers, to try and root out the cause of the game crashing after puzzles.
> Added 'troubleshoot.bat' file, verbose logging

- project/export_presets.cfg.template
From https://godotsteam.com/tutorials/exporting_shipping/:
> Since the pre-compiles are never debug-release versions, you must make sure
> that only the release field contains a template and that the debug field is
> empty... ...If you have the debug field filled in, especially while using the
> pre-compiled templates, the export process will fail.
In contradiction with this advice, I experimented with the debug templates to diagnose some crashes. They seemed helpful, and it does not cause the export process to fail. I'm unsure whether this documentation is out of date, or only applies to the GodotSteam plugin, but either way I'll leave the debug templates in place unless we start seeing issues.
> Restored GodotSteam windows debug templates.

- project/src/main/data/player-save.gd
- project/src/main/ui/save-indicator.gd
We used to show the save indicator at the start of the save operation. However because our save logic is non-threaded, this meant the save indicator would not be shown until the save operation was complete.
I've added a new signal so the save indicator is shown before the scene transition if a save is scheduled.
> Save indicator appears sooner.

- project/src/main/data/player-save.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/ui/menu/training-menu.gd
When switching saves during a puzzle, there were a lot of unusual side-effects including asparagus sounds playing. This occurred because the new rank system recalculates all ranks on startup, which requires loading all levels into memory briefly. However, this was also triggering the Puzzle scene to do things like initialize tilemaps, load puzzle gimmicks and play sound effects.
I've changed the 'load level' logic to include an optional flag which will prevent these kinds of events from triggering, so that we can recalculate the player's rank data without asparagus sounds playing. This is also more performant; switching saves during a puzzle took 0.5-1.2 seconds, but now only takes 0.2-0.5 seconds.
Also fixed TrainingMenu's 'LevelSettings.load_from_resource' call to explicitly initialize …
> Fixed 'phantom asparagus' bug

- project/assets/main/puzzle/levels/tutorial/cakes-2.json
- project/assets/main/puzzle/levels/tutorial/cakes-3.json
- project/assets/main/puzzle/levels/tutorial/cakes-4.json
- project/assets/main/puzzle/levels/tutorial/cakes-6.json
- project/assets/main/puzzle/levels/tutorial/cakes-7.json
- project/assets/main/puzzle/levels/tutorial/cakes-8.json
I personally thought it was cute how the cake tutorial shuffled the pieces every time, and how it was always possible to complete regardless of the piece order. However based on player feedback, this tutorial was too difficult and the shuffling confused some people, or they were frustrated that they had to use techniques such as spin moves or squish moves to complete it.
> 'Cake tutorial' no longer requires squishes/spins.

- project/src/demo/ui/settings/SettingsMenuDemo.tscn
- project/src/demo/ui/settings/settings-menu-demo.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/keybind/settings-keybinds-control.gd
- project/src/main/ui/settings/settings-menu-bottom.gd
- project/src/main/ui/tab-input-enabler.gd
The SettingsMenu has up to two quit buttons. Before, only the top 'quit' button had its focus neighbours set. Now, the focus neighbours are set for the topmost node which is visible in the tree, and the focus neighbours are unset for the other node.
The 'Customize Controls' tab has three topmost buttons. Before, focus neighbors were only configured for an arbitrary one of the three. Now, focus neighbors are configured for all three. Navigating down from the TabContainer selects the currently pressed button.
> Fixed SettingsMenu focus neighbours.

- project/project.godot
- project/src/demo/career/ui/CareerWinDemo.tscn
- project/src/demo/credits/CreditsScrollDemo.tscn
- project/src/main/career/CareerMap.tscn
- project/src/main/career/ui/CareerRegionSelectMenu.tscn
- project/src/main/career/ui/CareerWin.tscn
- project/src/main/credits/CreditsScroll.tscn
- project/src/main/credits/credits-orb.gd
- project/src/main/credits/transformation-target.gd
- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/ui/menu/LoadingScreen.tscn
- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/SplashScreen.tscn
- project/src/main/ui/menu/TrainingMenu.tscn
- project/src/main/ui/menu/TutorialMenu.tscn
- project/src/main/ui/menu/loading-screen.gd
- project/src/main/ui/wallpaper/Wallpaper.tscn
- project/src/main/ui/wallpaper/wallpaper.gd
Scenes used to manage their own wallpaper nodes. I'm replacing this with a Wallpaper autoload singleton to remove our dependency on ResourceCache's singleton management, to hopefully prevent game crashes.
I have a hunch ResourceCache's singleton management is the source of the game's crashes during scene changes. I think our code for rescuing these singletons from Godot's node freeing logic is failing, and these nodes get cleaned up sometimes, causing errors when they're reintroduced to the scene tree.
> Convert Wallpaper to autoload singleton.

- project/src/main/career/ui/career-win.gd
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/menu/career-region-select-menu.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/menu/splash-screen.gd
- project/src/main/ui/menu/training-menu.gd
- project/src/main/ui/menu/tutorial-menu.gd
- project/src/main/utils/resource-cache.gd
- project/src/main/world/career-map.gd
- project/src/main/world/overworld-ui.gd
Nodes formerly managed by ResourceCache's singleton logic are now traditional autoload singletons.
I have a hunch ResourceCache's singleton management is the source of the game's crashes during scene changes. I think our code for rescuing these singletons from Godot's node freeing logic is failing, and these nodes get cleaned up sometimes, causing errors when they're reintroduced to the scene tree.
> Removed ResourceCache singleton logic.

- project/src/main/ui/settings/settings-menu.gd
The settings menu is already unpaused when it is hidden. I'm unsure what the logic was initially for pausing it; possibly to avoid bugs with scene transitions or something like that. I've verified the scene transition logic works fine with the new code.
> Don't unpause Settings Menu when showing dialogs.

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/puzzle.gd
- project/src/main/settings/misc-settings.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/reenable-tips.gd
- project/src/main/ui/settings/settings-dialogs.gd
- project/src/main/ui/settings/settings-menu.gd
Before, hitting 'restart' or 'give up' would surprise or frustrate players, because Adventure mode would suddenly end and they might not realize what they had done wrong.
Now, the player is prompted '...will end the adventure day, do you really give up?'. This prompt can be restored with a button in the settings menu.
Closes #2847.
> Added 'give up' confirmation for Adventure mode

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/demo/ui/settings/settings-menu-demo.gd
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/SplashScreen.tscn
- project/src/main/ui/settings/settings-menu-bottom.gd
- project/src/main/ui/settings/settings-menu.gd
This 'restart' option only appears while a puzzle is active. It does all the same things as restarting with the 'R' key: prompting the player in adventure mode and recording the level's score.
Closes #2859.
> Added 'restart' button to puzzle menu.

- project/src/main/puzzle/result/ResultsHud.tscn
ResultsHud was blocking mouse clicks, specifically for the right side of the 'Start' or 'Retry' button.
Closes #2878.
> Bug: ResultsHud was blocking mouse clicks

- project/src/main/career/career-calendar.gd
Yesterday while testing some edge cases and working on some new career mode logic, I encountered a bug where hours_passed was incremented to 7. I can't find a way to duplicate this bug this morning, but it's easy to imagine calling 'advance_clock' one too many times resulting in hours_passed exceeding the maximum.
> Added boundary check for 'hours_passed' in career mode

- project/src/main/puzzle/puzzle-tile-set-diagram.tres
This unique tile set is used for drawing diagrams for tutorials, and never used in the game. However, its dimensions are too short making some tiles inaccessible through the UI.
> Fixed dimensions for 'puzzle tile set diagram'

- pybabel-extract.sh
We use a custom 'needs-review' flag to track machine translations which need to be reviewed by a human. Previously, these flags were automatically removed every time the POT update script was run, and needed to be manually reapplied.
> POT update script preserves 'needs-review' flags

- project/src/demo/career/ui/ProgressBoardDemo.tscn
- project/src/demo/career/ui/progress-board-demo.gd
- project/src/main/career/career-calendar.gd
- project/src/main/career/career-data.gd
- project/src/main/career/career-flow.gd
- project/src/main/career/ui/career-map-level-select.gd
- project/src/main/career/ui/career-time-label.gd
- project/src/main/career/ui/progress-board-clock.gd
- project/src/main/career/ui/progress-board-goal.gd
- project/src/main/career/ui/progress-board-splash-message.gd
- project/src/main/career/ui/progress-board-trail.gd
- project/src/main/career/ui/progress-board.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/menu/main-menu-adventure.gd
- project/src/main/world/career-map.gd
- project/src/test/world/test-career-data.gd
Before, if you reached the boss level on your sixth level, there would be a big fanfare but you wouldn't get to play it.
Now, you are always allowed to play the boss level even if you are out of time.
I've also fixed it where the fanfare does not play if you are not able to play the boss level -- for example, if you lose all your lives, but advance two spaces and land on a boss level. Before, this would result in a big fanfare with boss music and then the day would end. Now, there is no fanfare or special music.
Closes #2873.
> Let player boss level, even if time is up

- project/src/main/puzzle/puzzle.gd
In Career Mode, restarting a level would record the loss to your level history twice. One save was caused by PuzzleState's end game triggers, and one save was directly embedded in the 'restart' logic.
I've added a conditional so that the 'restart' logic does not record the loss during the first level in Career mode. It is a little kludgy but I can't think of a better fix at the moment.
> Bug: Some level results were being saved twice

- project/src/demo/puzzle/result/results-hud-demo.gd
- project/src/main/career/career-flow.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/result/results-hud-blueprint.gd
In Adventure mode, retrying a level counts as a failure and shouldn't display cutscenes. However, our logic for 'do we play a cutscene' was keying off of the player's best performance, not their first performance.
While it's not necessarily a bad thing to be lenient and say, 'oh it took you a few tries, but here is a cutscene', it was inconsistent with how Adventure mode works. It meant a player could lose a boss level, retry, beat it, see a cutscene, and then get sent backwards on the map screen and told 'try again tomorrow!'
Retrying a level now prevents cutscenes from playing. The cutscene logic cares about your first performance, not your best performance
> Bug: Don't show ending cutscenes when retrying levels

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/messages.pot
- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/settings/misc-settings.gd
- project/src/main/ui/difficulty/DifficultyMenu.tscn
- project/src/main/ui/difficulty/difficulty-menu.gd
- project/src/main/ui/menu/splash-screen.gd
- project/src/main/ui/settings/reenable-tips.gd
After completing the tutorial, the player is forcibly shown the difficulty menu. This ensures all players have the option to select an easier difficulty, even if they don't notice the main menu button. This also ensures that if they later encounter trouble, they'll hopefully remember 'Oh, I chose my difficulty earlier, I should lower it.'
If the player clicks 'Re-enable tips', the player is also shown the tutorial after the splash screen.
> Difficulty menu is forced on the player once.

- project/src/main/data/save-item-upgrader.gd
Some comments were vague or inaccurate. The upgrade methods don't just provide 'version-specific updates', but they provide granular version-specific updates on a single save item. Additionally, the signature does not accept a 'SaveData' object but rather a 'SaveItem' object. There is no such thing as a SaveData object.
> Improve SaveItemUpgrader comments.

- project/assets/test/data/config-5a24-default.json
- project/assets/test/data/config-5a24.json
- project/assets/test/data/turbofat-59c3.json
- project/project.godot
- project/src/main/data/difficulty-data.gd
- project/src/main/data/player-data.gd
- project/src/main/data/player-save-upgrader.gd
- project/src/main/data/player-save.gd
- project/src/main/data/system-save-upgrader.gd
- project/src/main/data/system-save.gd
- project/src/main/puzzle/hold-piece-displays.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/level/gameplay-difficulty-adjustments.gd
- project/src/main/puzzle/piece/piece-dropper.gd
- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/puzzle/piece/piece-speeds.gd
- project/src/main/puzzle/playfield-shadow.gd
- project/src/main/settings/gameplay-settings.gd
- project/src/main/settings/keybind-manager.gd
- project/src/main/ui/difficulty/difficulty-button.gd
- project/src/main/ui/difficulty/difficulty-hold-piece-panel.gd
- project/src/main/ui/difficulty/difficulty-line-piece-panel.gd
- project/src/main/ui/difficulty/difficulty-menu-description.gd
- project/src/main/ui/difficulty/difficulty-menu.gd
- project/src/main/ui/settings/keybind/settings-keybinds-control.gd
- project/src/test/data/test-player-save.gd
- project/src/test/data/test-system-save-upgrader.gd
- project/src/test/data/test-system-save.gd
- project/src/test/puzzle/level/test-gameplay-difficulty-adjustments.gd
Difficulty data used to be in the system data, alongside settings like 'Ghost Piece' and 'Soft Drop Lock Cancel' and keybinds. I've moved it into the player data. I think it's common that players will want to have different save slots for different difficulties, and unusual that all save slots would need to share a difficulty
> Save slots now have independent difficulties.

- project/assets/test/data/config-5a24-slowest.json
- project/src/main/data/player-save-upgrader.gd
- project/src/test/data/test-system-save-upgrader.gd
Difficulties such as 'fast' and 'sloweset' can not be picked in the new difficulty interface. Before, players who selected these difficulties would be able to continue using them, although the UI would make it look like they had no difficulty selected.
Now, when upgrading to the newest version, the player's difficulty is adjusted to one of the four standard difficulties. They can still hack into their save files and assign a non-standard difficulty, and the old behavior will persist. This might be construed as a feature and not a bug, it doesn't break anything and lets them try the super silly 'fastestest' difficulty if they really want.
> Fix difficulty upgrade edge cases: slowest, fast, etc

- project/src/main/settings/gameplay-settings.gd
We no longer need to persist the SystemData 'legacy_properties' field. We still need the field to exist temporarily so that the difficulty settings can be moved into PlayerData. But we do not need to save the field, since #2912 changed PlayerData to be upgraded immediately on startup.
> Don't persist legacy difficulty properties.

- project/src/main/puzzle/food-items.gd
- project/src/main/puzzle/level/other-rules.gd
- project/src/test/puzzle/level/test-other-rules.gd
Levels can now define a 'food_speed' if they want food to disappear faster.
> Added food_speed level setting.

- project/src/demo/toolkit/fix-levels-button.gd
- project/src/main/puzzle/level/other-rules.gd
- project/src/main/puzzle/piece/piece-queue.gd
Some levels like 'Carrot Alley' top the player out if they are using the line piece cheat. This new setting causes specific levels to automatically rotate line pieces to prevent a top out.
> Added 'vertical_line_pieces' setting.

- bin/troubleshoot_bat/turbofat-troubleshoot.bat.template
- project/project.godot
Enable flush_stdout_on_print setting. This allows us to view logged messages, even when the game crashes.
Disable immediate console printing while the game is running. Immediately printing messages causes unusual behavior if the player interacts with the console window. It reliably causes the game to freeze temporarily, but other users have reported the window turning transparent or crashing as well.
Messages are still logged after the game closes, by echoing the 'godot.log' file.
> Fixed freeze when interacting with console window

- project/src/main/puzzle/critter/tomatoes.gd
Specifically, levels with asparagus often have full rows when the asparagus pop out. They were triggering tomatoes, but they shouldn't.
> Removed tomatoes from non-tomato levels

- project/src/main/ui/scene-transition.gd
https://github.com/Poobslag/turbofat/issues/2821#issuecomment-2504282569
I encountered a crash within the Godot editor today, which seems to narrow the crash to something around calling the breadcrumb method or disconnecting the listeners. I've added some additional log statements to help narrow it down.
> Added additional scene transition/breadcrumb logging

- project/assets/main/locale/en.po
- project/assets/main/locale/es.po
- project/assets/main/locale/localizables-extracted.py
- project/assets/main/locale/messages.pot
- project/src/demo/toolkit/extract-localizables-button.gd
Before, locale names were output in a random order resulting in unnecessary churn in our .po files.
> Output locale names in predictable order.

- project/src/main/utils/breadcrumb.gd
https://github.com/godotengine/godot/issues/85692
`get_tree().unload_current_scene()` sometimes causes a silent crash with no errors or logs. Apparently this can be worked around by manually removing the children from the tree. This bug is infrequent enough that I can't be certain this changes anything.
> Experimenting with 'unload_current_scene' workaround

- project/src/main/chat/ui/chat-ui.gd
- project/src/main/chat/ui/touch-translator.gd
I don't think people would usually skip the dialog but then care about making a specific choice. It's a little tedious having to hold a key to skip dialog, then let go and repress it during a dialogue choice, sometimes multiple times if you trigger the "don't mash through dialog choices" prevention code.
Closes #1007.
> Skipping dialog skips choices as well.

- project/src/main/chat/ui/ChatUi.tscn
- project/src/main/chat/ui/click-translator.gd
Replaced 'touch advances cutscenes' logic with 'click advances cutscenes' logic. The emulate_mouse_from_touch setting automatically allows touch input as well for cutscenes.
Closes #2942.
> Clicking advances cutscenes.

- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/creature.gd
Scripts don't need to listen for their own 'tree_exited' signals; they have an '_exit_tree' callback for this
> Replace 'creature.on_tree_exited' with 'exit_tree'

- project/src/main/career/ui/career-win-world.gd
- project/src/main/editor/creature/allele-buttons.gd
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/editor/creature/creature-saver.gd
- project/src/main/editor/creature/dialogs.gd
- project/src/main/editor/creature/fatness-changer.gd
- project/src/main/world/career-map.gd
- project/src/main/world/career-world.gd
- project/src/main/world/environment/overworld-environment.gd
While the root cause of 45b49cd was caused by a lingering listener connected to a node outside of the scene tree, the lines causing the crash were related to OverworldEnvironment.get_creature_by_id not handling the case where it is not in a scene tree.
I've changed OverworldEnvironment.get_creature_by_id to return null in this case, and changed many of its callers to handle this case more gracefully. This doesn't fix any crash that I know of, but it makes this code more resilient to future crashes I don't know about yet.
> Additional 'null player checks' for 45b49cd

- project/assets/test/puzzle/levels/level-5a6b.json
- project/src/main/puzzle/level/level-settings-upgrader.gd
- project/src/main/puzzle/level/levels.gd
- project/src/main/puzzle/rank-criteria.gd
- project/src/test/puzzle/level/test-level-settings.gd
- project/src/test/puzzle/test-rank-calculator.gd
- project/src/test/puzzle/test-rank-criteria.gd
RankCriteria now defines a distinct 'TOP' grade. Currently this is the exact same as the 'M' grade, but we can now decrease the score/time requirements for 'M' grades to make the grade more achieveable.
Since levels define their own arbitrary values for what constitutes an 'M' rank, this might be counterintuitive. Why define an arbitrary value of what a 'TOP' grade is, only to have master grades be an arbitrary fraction of it? However, keeping these separate allows us to more easily make sweeping changes such as deciding a master grades is 99% or 80% of a perfect grade. Otherwise, we'd need to make those changes in 200 different level definitions.
> Separate 'M' and 'TOP' grades, to allow for lenient master grade

- project/assets/main/puzzle/levels/career/200-race.json
- project/assets/main/puzzle/levels/practice/ultra-normal.json
- project/assets/main/puzzle/levels/rank/7k.json
"Ultra Normal", "7 Kyu" and "200 Race" are all identical, and should have similar grading criteria/duration. (200 Race is graded more leniently because it is an introductory level.)
> Tweaked grades for "Ultra Normal" and its clones

- project/assets/main/puzzle/levels/career/dark/a-little-extra.json
- project/assets/main/puzzle/levels/career/dark/cheddarbox-blitz.json
- project/assets/main/puzzle/levels/career/dark/no-smoking-section-2.json
- project/assets/main/puzzle/levels/career/dark/strawberry-shortcut.json
- project/assets/main/puzzle/levels/career/dark/sweet-dreams.json
- project/assets/main/puzzle/levels/career/dark/three-minute-sprint.json
After more playtesting, these levels were too difficult to reach the target scores even for expert-level players, so I've loosened their score criteria.
The level 'No Smoking Section 2' was difficult to complete even for expert-level players. I've decreased the scoring requirements, but left the grading criteria at its old values. It's still quite challenging to clear in under 2 minutes with the decreased scoring requirements. My personal best is 1:41.
> Adjusted Starberry Mountain rank criteria for a few trouble levels

- project/assets/main/puzzle/levels/practice/marathon-expert.json
- project/assets/main/puzzle/levels/practice/marathon-hard.json
- project/assets/main/puzzle/levels/practice/marathon-master.json
- project/assets/main/puzzle/levels/practice/marathon-normal.json
- project/assets/main/puzzle/levels/practice/sprint-expert.json
- project/assets/main/puzzle/levels/practice/sprint-normal.json
- project/assets/main/puzzle/levels/practice/ultra-expert.json
- project/assets/main/puzzle/levels/practice/ultra-hard.json
- project/assets/main/puzzle/levels/rank/10d.json
- project/assets/main/puzzle/levels/rank/1d.json
- project/assets/main/puzzle/levels/rank/1k.json
- project/assets/main/puzzle/levels/rank/2d.json
- project/assets/main/puzzle/levels/rank/2k.json
- project/assets/main/puzzle/levels/rank/3d.json
- project/assets/main/puzzle/levels/rank/3k.json
- project/assets/main/puzzle/levels/rank/4d.json
- project/assets/main/puzzle/levels/rank/4k.json
- project/assets/main/puzzle/levels/rank/5d.json
- project/assets/main/puzzle/levels/rank/5k.json
- project/assets/main/puzzle/levels/rank/6d.json
- project/assets/main/puzzle/levels/rank/6k.json
- project/assets/main/puzzle/levels/rank/7d.json
- project/assets/main/puzzle/levels/rank/8d.json
- project/assets/main/puzzle/levels/rank/9d.json
- project/assets/main/puzzle/levels/rank/m.json
The training/rank level grading criteria were still based on a mathematical model and not player data. I decreased the criteria for slower levels ('AF' and slower) by about 20%. I sharply decreased the criteria for faster levels ('FA' and faster) by about 40%.
Slightly reduced the clear requirements for 9-dan and Master Rank courses. Nobody in the Turbo Fat community has ever cleared anything past 8-dan, and even with the decreased 9-dan scoring requirements I think it will remain an insurmountable challenge. My best score for 9-dan is $1,879 and 179 lines.
> Adjusted grading criteria for training/rank levels

- project/src/demo/career/ui/progress-board-demo.gd
- project/src/main/career/ui/ProgressBoard.tscn
- project/src/main/career/ui/progress-board-clock.gd
- project/src/main/career/ui/progress-board.gd
The progress board animations hard-coded x-coordinates like "422" but these x-coordinates were only valid for a specific resolution. As a result, the animations would animate the progress board into an uncentered position for most resolutions.
I've introduced a new 'swoosher' node in the ProgressBoard which has an X-coordinate of 0,0, and will appear centered regardless of the resolution.
Closes #2937.
> Bug: Progress board was not centered.

- project/src/main/settings/touch-settings.gd
Subjectively, I think a more forgiving fat-finger setting makes the game more enjoyable. Objectively, the fat-finger setting of 'None' makes the Meet Spins tutorial impossible.
> Changed default fat finger setting from 'none' to 'pudge'

- project/src/main/ui/settings/settings-touch-fat-finger.gd
The 'Fat Finger' setting had a typo where it was loading the 'scheme' setting to initialize its value.
> Fixed bug where 'Fat Finger' setting showed an incorrect value

- project/src/demo/editor/creature/creature-color-button-demo.gd
- project/src/main/editor/creature/CreatureColorButton.tscn
- project/src/main/editor/creature/creature-color-button.gd
Pressing a Creature Editor color button and then closing the popup lost focus. The focus was not returned to the color button afterward.
This bug was confusing to track down, but it only happens if the ColorPickerPopup has at least one preset, and if the resulting preset button grabs focus.
Updated CreatureColorButtonDemo to include multiple palettes.
> Bug: Creature editor color buttons didn't return focus

- project/src/main/editor/creature/allele-buttons.gd
Creature editor allows player to select conflicting creature parts, and updates the creature's appearance to resolve the conflicts. For example, selecting a beak will unselect the creature's nose.
> Creature editor no longer disables conflicting buttons.

- project/src/demo/world/environment/restaurant/restaurant-view-demo.gd
- project/src/main/world/creature/creature-visuals.gd
Creatures with a fatness value greater than 10.0 appeared glitchy and stretched out.
> Bug: Glitched creature appearance past fatness=10

- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/piece-rotator.gd
- project/src/main/puzzle/tutorial/tutorial-spins-module.gd
180 flips used to require frame perfect inputs in some cases, as pressing the first rotate button would flip the piece out of a nook, and then the piece would flip from the wrong position.
The game now stores the piece's position before the rotate inputs, and if the player hits both buttons quickly enough, the piece will flip from its previous position.
> More leniency for 180 flips.

- project/src/main/puzzle/puzzle.gd
I'm not sure what this intended, but I couldn't really notice when I disabled it. Keeping it enabled resulted in an unusual bug when introducing the 'restart tutorials' logic, where restarting a tutorial over and over and over would result in a very long delay for the next piece.
It was introduced during 914ef298 when refactoring the tutorial logic.
> Disable 'brief pause during level transitions'.

- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/utils/timer-group.gd
Some of these methods were called to start/free timers after a delay, but the timer could be cleared by another process. I triggered this once when testing my 'restart tutorial section' logic while some tutorial messages were playing.
> Added null checks for timer signal methods

- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/start-end-sfx.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
Particularly during the combo and cakes, it's possible a player might reflexively hit 'R' when they misdrop a piece. Previously this restarted the entire tutorial, which is definitely not what the player would want.
They can still restart the entire tutorial if they go into the menu.
> 'R' restarts only one tutorial section, not the whole tutorial.

- project/src/main/puzzle/piece/piece-rotator.gd
The logic for caching a piece's previous location for flip inputs did not check whether the cached piece was the same as the flipped piece. This meant you could execute some very specific and strange inputs to warp a the flipped piece to the previous piece's location.
> Fixed unusual bug which let pieces warp with flip inputs

- project/src/main/ui/CheatCodeDetector.tscn
- project/src/main/utils/DeconflictedAudioStreamPlayer.tscn
The high threshold was making the hover sound effects a little strange and sparse during the menus. Circling the mouse quickly would not play very many hover sounds.
This threshold was accidentally increased in a099b976 when fixing overlapping audio for the training menu unlock cheat. This change affected the entire game, not just the cheat sound effect, and increased the threshold very high.
> Decreased 'avoid repeated sfx' threshold from 200 ms to 20 ms

- project/src/main/editor/creature/allele-buttons.gd
Calling 'disabled = true' on candybuttons does not update their appearance, so callers should always call 'set_disabled' explicitly.
This did not have any visual effects, but can introduce bugs when this code is reused elsewhere.
> Fixed Creature Editor 'disabled=' assignments

- project/src/main/world/creature/creature-shadow.gd
- project/src/main/world/creature/dna-loader.gd
Before, the dna_loaded signal was called immediately after the creature's fields were set, even if the shaders hadn't been updated. There was no signal to indicate "the creature is ready to display."
Rather than having two granular signals for "the creature's fields have been populated" and "their shaders have been updated", I've merged these into a single signal.
> dna_loaded signal now fires after all shaders are assigned.

- project/src/main/editor/creature/allele-buttons.gd
- project/src/main/editor/creature/creature-editor-library.gd
- project/src/main/editor/creature/creature-editor-nametag.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/environment/CreatureEditorEnvironment.tscn
When changing the creature's appearance in the creature editor, parts of the creature blink black as the creature is redrawn.
To avoid this, I've introduced an offscreen creature where we apply the changes, and then we swap them in once their apperance is updated.
Closes #2531.
> Bug: Creature editor shows black pixels when selecting feature

- project/src/test/utils/Autopilot.tscn
- project/src/test/utils/autopilot.gd
If enabled, this script will quickly launch a puzzle, drop 6 pieces, and exit the puzzle over and over again. This is useful for verifying whether the game can handle someone playing hundreds of puzzles in a row.
> Added 'autopilot' automation script.

- project/src/main/utils/ViewportPurger.tscn
- project/src/main/utils/viewport-purger.gd
Godot crashes sometimes when freeing a node with a ViewportTexture property. To prevent this, we manually set any ViewportTexture properties to null before the node is freed. ViewportPurger accepts a list of viewport path properties relative to a particular root node. The string syntax is a NodePath followed by one or more colon-delimited properties.
> Added 'ViewportPurger' script to avoid crashes.

- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/night/NightPlayfield.tscn
- project/src/main/world/creature/ViewportCreatureOutline.tscn
NightPlayfield, Playfield, Puzzle and ViewportCreatureOutline now use ViewportPurger to unassign their ViewportTextures. This prevents occasional crashes when exiting a puzzle.
> Add and configure ViewportPurgers to prevent crashes

- project/src/main/data/rolling-backups.gd
Copy operations are more expensive than renames. This change optimizes the backup process by deleting/renaming files instead of copying them.
> RollingBackups: Use rename instead of copy to reduce overhead

- project/src/main/puzzle/puzzle.gd
Previously, saving was scheduled to avoid 50-100 ms of lag, but this led to a frustrating issue where high scores were lost if players quit before the save occurred. Now, scores are saved immediately.
We plan to mitigate lag with threading in a future update.
> Save scores immediately instead of scheduling a save

- project/src/main/settings/touch-settings.gd
The SettingsTouchScheme UI called 'Easy Console' the first item in the list, but the ControlScheme enum sorted them alphabetically.
I've rearranged the enum to match the display order. Easy Console should be the first one in the list, because I think it's the most intuitive.
> Fix 'Ambi Console' / 'Easy Console' name mixup

- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-touch-size.gd
Decreased the maximum touch size from 1.69 to 1.40. In an upcoming change which introduces the hold piece, a scale of 1.69 is too large and causes the buttons to overlap.
Settings menu no longer hard-codes the max value and tick count, these values are derived from the SettingsTouchSize.VALUES constant.
> Touch size settings: tick count, limits

- project/src/main/settings/keybind-settings.gd
Our code looks up xbox glyphs based on button index, but Godot stores json button indexes as floats, not ints. So these glyphs were often coming back as null.
We now cast the button indexes to an int.
> XBOX glyphs were sometimes missing for custom controls.

- project/src/main/chat/ui/click-translator.gd
- project/src/main/world/CutsceneUi.tscn
The cutscene settings button could not be clicked, except for when a dialog choice was being presented. This was broken by c0a8e988b which allowed clicking to advance cutscenes. The logic also consumed mouse events directed towards buttons in the scene.
The chat ui logic now ignores mouse click events near any buttons in the 'cutscene_buttons' group, which currently only includes the settings button.
> Bug: Cutscene settings button could not be clicked.

- project/src/main/chat/ui/ChatUi.tscn
- project/src/main/chat/ui/gamepad-accept-echo-generator.gd
Gamepads do not generate echo events. Our fast-forward logic relies on receiving echo events, so I've added a special handler which can enable echo events for a specific gamepad input. This handler is used in ChatUi to enable 'ui_accept' to generate echo events.
Closes #730.
> Players can fast-forward text with gamepads.

- project/src/main/puzzle/piece/piece-manager.gd
Players could stall infinitely if they moved the piece back and forth without rotating it, as piece movement did not consume a lock reset.
Piece movement now consumes a lock reset.
> Fixed infinite stall exploit

- project/src/main/editor/creature/allele-buttons.gd
- project/src/main/ui/settings/settings-open-user-folder.gd
Android is case sensitive, so has_feature("android") always returned false causing these buttons to stay visible. Since Android doesn't provide file access in the same way PCs do, this would crash the game.
I've fixed these checks to use has_feature("mobile") so that the options stay disabled on Android.
> has_feature("android") -> has_feature("mobile")

- project/src/main/data/player-save.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/level/gameplay-difficulty-adjustments.gd
- project/src/main/puzzle/level/milestone.gd
- project/src/main/puzzle/milestone-hud.gd
- project/src/main/puzzle/milestone-manager.gd
- project/src/main/puzzle/piece-sfx.gd
- project/src/main/puzzle/piece/piece-speeds.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/level-select/level-button-scroller.gd
- project/src/main/ui/menu/paged-level-buttons.gd
- project/src/main/ui/menu/region-info-panel.gd
- project/src/main/ui/menu/training-menu.gd
- project/src/main/world/career-map.gd
- project/src/test/puzzle/level/test-gameplay-difficulty-adjustments.gd
To apply difficulty tweaks, places used to call
'finish_criteria.adjusted_value()'. This could cause bugs, as some places might call adjusted_value() while others referenced the 'value' field directly.
We now adjust the level's finish criteria up-front. This also opens the possibility of more nuanced adjustments down the road, if we decide for example "Levels with a line goal should require 30% fewer points, but levels with a time goal should require 50% fewer points." We can now easily make these kinds of milestones codependent.
> Replaced 'adjusted_value()' with up-front adjustments

- project/src/main/puzzle/level/gameplay-difficulty-adjustments.gd
- project/src/test/puzzle/level/test-gameplay-difficulty-adjustments.gd
Before, instead of easier boss levels requiring something like "Get $300 in 3 minutes", they were adjusted to something like "Get $300 in 1 minute" which is much, much harder. Shortening normal levels made them easier, but shortening boss level made it much harder to meet the requirements.
Now, we scale the success criteria accordingly to "Get $100 in 1 minute", but also make an additional adjustment because novices won't be able to score as many points per minute as experts. So the final result is something silly like "Get $10 in 1 minute". If players think it is too easy, there are harder difficulties. The goal of Zen mode is to open up the game to all players.
> Easier difficulties have easier success criteria.

- project/src/main/data/system-data.gd
Specifically, if the player clicked the maximize button on windows, and then toggled VSync on and off, it would restore the window to its previous position.
> Bug: Toggling vsync sometimes unfullscreens the game

- project/project.godot
GLES3 causes console errors when the GodotSteam overlay is enabled, on AMD Radeon RX 7600, when verbose logging is on.
This isn't a big deal as it's only one graphics card (my graphics card) but we're not using any GLES3 features anyways.
> Downgrade from GLES3 to GLES2.
