- scenes/Piece.gd
'Instant nook DAS' now activates when the player is pushing a piece into
a wall, regardless of whether or not the piece has technically attempted
to move into a wall yet.
With the old logic pieces could slide past nooks in some annoying cases.
For example, sliding an O-piece into the right three columns would work
OK because the O-piece spawns on the right side of the playfield. But
sliding an O-piece into the left three columns would fail, because it
would successfully move and not activate 'instant nook DAS'.
> Fixed edge case for pieces sliding into nooks.

- scenes/Piece.gd
- scenes/Piece.tscn
- scenes/Playfield.gd
- scenes/PracticeMenu.gd
- scenes/StretchMap.gd
- todo.txt
I originally planned to have this 'stretch' logic apply to hard drops
and 20G, but it was too distracting and made the game feel slower. Now
it only applies to long-distance block smushes.
The original approach where pieces stretch in more circumstances is
branched at 'pieces-stretch'.
> Pieces stretch around when smushing through other blocks.

- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/piece/states/prelock.gd
- src/main/puzzle/piece/states/wait-for-playfield.gd
- src/main/state-machine.gd
- src/main/world/restaurant/CustomerView.tscn
There are some glitches with gdscript's 'setget' keyword. A statement
like $States._state.frames = 3600 gets incorrectly interpreted as a
'set_state' call. I've removed the 'setget' keyword to avoid these
issues.
Removed some unnecessary playfield null checks.
> Fixed piece physics glitches introduced in 56e0cb2.

- src/main/puzzle/piece/next-pieces.gd
- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/piece/states/move-piece.gd
- src/main/puzzle/piece/states/prelock.gd
- src/main/state-machine.gd
- src/main/state.gd
The prelock state can result in two states; writing the piece to the
playfield or going back to the move state if the player smushes or
performs a lock reset. If these two state changes overlapped, bugs
resulted such as infinite loops or freezes.
I've refactored the surrounding code to minimize the number of places
where we manage the piece state using 'set_state'. The states themselves
now monitor 'apply_player_input' and change the state themselves.
> Fixed puzzle freezing when prelock was interrupted.

- FpsLabel.tscn
- fps-label.gd
- src/main/world/Overworld.tscn
- src/main/world/overworld.gd
- src/main/world/turbo.gd
The FPS tracker can be enabled by typing 'BIGFPS' in the overworld. It
will most likely be capped at 60, although you can temporarily uncap the FPS by
disabling VSYNC in the project settings.
I encountered a transient error where landing on a platform caused the
player to constantly bounce up and down, with their Y value oscillating between
-4 and 0. I'm changing the gravity code to reset their Y velocity as a
countermeasure, although this bug is difficult to reproduce.
> Added FPS tracker; tweaked gravity physics

- assets/world/overworld-material-outline.tres
- assets/world/purple-box-library.tres
- src/main/world/Overworld.tscn
- src/main/world/PurpleBoxTexture.tscn
- src/main/world/turbo.gd
There was some unusual code in turbo.gd to reduce jitter. Controlling a box which is 2 units high causes 0.2 units of jitter in Godot, which is very noticable as it is 10% of the object's height. I attempted to reduce this jitter by snapping the character's Y coordinate to the nearest 0.2, but this was not a perfect fix. Some bouncing was still visible occasionally. It also didn't work if Turbo ever landed on a surface that wasn't a perfect multiple of 0.2.
I've made all 3D objects 900% bigger to reduce these physics glitches. Controlling a box which is 20 units high makes the jitter less visible. I also removed the snapping behavior for Turbo's movement.
Fixed lighting artifacts; orthogonal lights were introducing weird stripes on textures in editor
> Enlarged 3D objects to reduce physics glitches.

- src/main/world/turbo.gd
The camera now predicts Turbo's movement, so the player can see ahead of where
they're walking.
Fixed an issue where holding the button didn't trigger a jump. This was
already coded, but a bug in the gravity code caused the player's jump to
be nullified.
> Camera predicts movement. Minor jump physics fix

- project.godot
- src/demo/chat-ui-demo.gd
- src/main/puzzle/piece/piece-manager.gd
- src/main/ui/chat/ChatUi.tscn
- src/main/ui/chat/chat-frame.gd
- src/main/ui/chat/chat-ui.gd
- src/main/ui/chat/sentence-label.gd
- src/main/ui/chat/sentence-manager.gd
Player can rewind dialog with 'shift'. They can view the previous 100 chat
messages, even ones from previous conversations.
Player can skip through dialog with 'Z', and can advance messages that are
appearing too slowly.
> Player can rewind/fast forward dialog

- src/main/puzzle/Playfield.tscn
- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/piece/piece-speeds.gd
- src/main/puzzle/piece/piece-type.gd
- src/main/puzzle/piece/piece-types.gd
- src/main/puzzle/puzzle-trace.gd
The overall goal of these timing changes was:
1. Bring the overall max/min blocks per minute in line with other similar games
2. Allow faster players to play faster on easier difficulties
3. Allow slower players more leniency on easier difficulties
4. Have a smooth difficulty curve (except for the sudden 1G/20G increases)
The frame delay when creating a box or clearing a line has been decreased, especially on easier levels. This allows fast players to play faster.
The number of lock resets and floor kicks has been increased. This makes piece movement more lenient. I've also increased the lock delay from 30 frames to 40 frames for the middle difficulties.
The top speed of the crazy difficulties now remains unchanged for the last few levels. THis allows expert players to find and stick to a …
> Changed piece timings; faster but more lenient

- project.godot
- src/delint.sh
- src/main/ResourceCache.tscn
- src/main/puzzle/scenario-settings.gd
- src/main/resource-cache.gd
- src/main/ui/LoadingScreen.tscn
- src/main/ui/loading-screen.gd
- src/main/world/restaurant/Seat.tscn
- src/main/world/restaurant/customer-loader.gd
- src/main/world/restaurant/customer.gd
Resources were previously being loaded as needed, particularly for
customers. This had a few clunky results, such as having characters be
temporarily invisible on the 3D screen, and it was also still quite slow
(about 5 seconds of delay during transitions.)
My first idea was to load these resources in a background thread on the
main menu or maybe a title screen. However it was still too jerky -- even
when just navigating menus it looked bad. It's better just to preload things
and work on improving loading times.
Changed to multi-threading rendering model; this weirdly makes resources load
12% faster.
Increased chime delays in customer.gd to compensate for customers being
preloaded.
Removed 'long line' delint detection, as there's way too many currently.
it's interfering with my usual …
> Preload all resources to increase performance, decrease jitter

- src/main/resource-cache.gd
This can be helpful when running demos or testing individual scenes where
it's unnecessary to preload everything.
> Resource cache can be disabled.

- src/main/world/restaurant/customer.gd
- src/main/world/turbo-trace.gd
- src/main/world/turbo.gd
Turbo's velocity is now updated as she collides with the floor and other
obstacles. This made her feel overly slippery, so I also added some logic
which applies friction when you steer her in a new direction. Friction is
now visible when using the 'COYOTE' cheat.
I also fixed a bug in the velocity capping logic in _accelerate_player_xy.
While Turbo's max run speed was allegedly 60 units/sec, she was typically
running at about 85 units/sec because of how the old capping logic worked.
This has one questionable side effect, which is that it's no longer
possible to hold the jump button and jump around in different directions,
since Turbo maintains her previous velocity.
> Turbo physics tweak: preserve velocity, improved velocity cap

- src/main/resource-cache.gd
- src/main/ui/loading-screen.gd
ResourceCache is now explicitly enabled in the LoadingScreen, and disabled
otherwise. It was cumbersome needing to explicitly disable it when running
individual demos/scenes. I've removed its `disable` property since it feels
redundant now.
> ResourceCache is now only enabled through LoadingScreen.

- src/main/world/turbo.gd
Additional workaround for Godot issue #34596
(https://github.com/godotengine/godot/issues/34596). If acceleration via
gravity makes our vertical momentum something small and we collide with
two objects, there's a risk we won't collide with the surface we're
sitting on which causes an unpleasant jitter effect.
> Gravity collision jitter workaround; MIN_GRAVITY_SPEED

- src/main/world/Customer3D.tscn
- src/main/world/customer-3d.gd
- src/main/world/restaurant/Customer.tscn
- src/main/world/restaurant/customer.gd
- src/main/world/turbo.gd
Tilted meshes could potentially be problematic because tall sprites near a wall
would tilt towards the wall and clip. This would have been a problem for
background sprites such as trees or street lights. Customer3D mesh is now
vertically stretched instead of being tilted.
Vertically stretched meshes also take up less horizontal space, so I could
shrink the hit boxes into compact cylinders.
Modified the slip logic to avoid a bug where Turbo could slip if she bumped
into a customer horizontally.
Modified the movement animation logic to ignore infinitesmally small
movement vectors. This was resulting in a glitchy flickering look when the
character pressed into a wall.
> Customer3D mesh no longer tilts. Tweaked collisions, slipping

- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/piece/piece-types.gd
- src/test/test-piece-kicks-jl.gd
- src/test/test-piece-kicks-qp.gd
- src/test/test-piece-kicks-t.gd
- src/test/test-piece-kicks-u.gd
- src/test/test-piece-kicks-v.gd
- src/test/test-piece-kicks.gd
Some P/Q climb kicks were causing the piece to jump up unexpectedly instead of
squeezing into a gap.
Added the initial spawn locations to the initial DAS kicks. It felt bad
dying as a result of applying initial DAS, so now if you die, you would
have died anyways even without initial DAS.
> Removed some P/Q climb kicks. Prevent initial DAS from killing you.

- .gitignore
- export_presets.cfg
- src/main/resource-cache.gd
- src/main/ui/loading-screen.gd
- src/main/ui/scenario-menu.gd
HTML5 does not support threads, so I modified ResourceCache to support a
non-threading loading mechanism for HTML5.
The 3D stuff causes my browser to lock up. I'll have to investigate this
further, but it may just be infeasible for HTML5 to do the 3D parts of the
game. For now I've removed the '3D world' button from the scenario menu.
> Added HTML5 export (2D parts only)

- assets/ui/default_bus_layout.tres
- src/delint.sh
- src/main/puzzle/Playfield.tscn
- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/Scenario.tscn
- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/scenario-history.gd
- src/main/resource-cache.gd
- src/main/ui/CheatCodeDetector.tscn
- src/main/ui/chat/ChatChoices.tscn
- src/main/ui/chat/ChatFrame.tscn
- src/main/world/Customer3D.tscn
- src/main/world/restaurant/Customer.tscn
Wall kicks were playing a rotate and move sound effect simultaneously.
They now only play the rotate sound.
DAS move sfx now vary in pitch/volume. They had sort of a grating
machinegun-like quality to them before.
Fixed NPE when save file not found.
> Fixed repetitive sfx for wall kicks, DAS

- src/main/puzzle/piece/piece-types.gd
- src/test/test-piece-kicks-jl.gd
- src/test/test-piece-kicks-t.gd
J, L, T triples are useful in other games, but in Turbo Fat you can
accomplish the same thing with squish moves. We can add them back in if
they're missed. Or actually, I'd rather just let people choose between a
few piece kick presets (ARS-kicks, SRS-kicks, FAT-kicks, etc)
> Added 'snack kicks' for J, L pieces. Removed triples.

- assets/puzzle/scenario/sprint-expert.json
- assets/puzzle/scenario/sprint-normal.json
- assets/puzzle/scenario/ultra-expert.json
- assets/puzzle/scenario/ultra-hard.json
- assets/puzzle/scenario/ultra-normal.json
- src/demo/customer-view-demo.gd
- src/demo/restaurant-scene-demo.gd
- src/demo/results-hud-demo.gd
- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/Scenario.tscn
- src/main/puzzle/piece/next-piece-displays.gd
- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/playfield.gd
- src/main/puzzle/puzzle-hud.gd
- src/main/puzzle/puzzle-score.gd
- src/main/puzzle/puzzle.gd
- src/main/puzzle/rank-calculator.gd
- src/main/puzzle/results-hud.gd
- src/main/puzzle/scenario-settings.gd
- src/main/puzzle/scenario.gd
- src/main/resource-cache.gd
- src/main/world/restaurant/customer-view.gd
- src/main/world/restaurant/customer.gd
- src/test/test-rank-calculator.gd
There were some bugs with lines being cleared after the player had
completed Ultra mode. I've pushed the 'game is running' concept out of
playfield.gd and puzzle.gd, and moved it into puzzle-score.gd. This
greatly simplifies a lot of signals, eliminates several bugs, and lets us
push some code from puzzle.gd into its collaborators.
Split out win/finish conditions. Scenarios can now have a condition where
you win by doing something impressive (clearing 1,000 lines), or a condition
where you finish by doing something ordinary (waiting 2 minutes.) This
distinction was already embedded in scenario.gd, but now it's an aspect of
the scenario json definition.
Fixed lpm tests broken in b1345ec. These tests were originally written
assuming a perfect player would move the piece for 0/1 frames. I've …
> PuzzleScore state, win/finish conditions.

- src/main/global.gd
- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/ResultsHud.tscn
- src/main/puzzle/Scenario.tscn
- src/main/puzzle/piece/piece-types.gd
- src/main/puzzle/puzzle.gd
- src/main/puzzle/scenario-settings.gd
- src/main/puzzle/scenario.gd
- src/main/world/restaurant/Customer.tscn
- src/main/world/restaurant/customer-view.gd
- src/main/world/restaurant/customer.gd
- src/test/test-piece-kicks-u.gd
Started introducing tutorial UI element customization. Launching the
tutorial scenario hides the chalkboard, summons master fat.
Simplified milestone hud logic. Instead of granular methods like 'update
colors', 'update content', 'update goal', 'prepare', there's just two methods
now: 'prepare hud' and 'update hud'
Added some missing u-kick tests. The piece was stuck even though there were
clear places it could rotate.
> Moved MilestoneHud into Puzzle. Added u-kicks.

- src/delint.sh
- src/main/player-save.gd
- src/main/puzzle/editor/editor-json.gd
- src/main/puzzle/milestone.gd
- src/main/puzzle/rank-result.gd
- src/main/puzzle/scenario/blocks-start.gd
- src/main/puzzle/scenario/combo-break-rules.gd
- src/main/puzzle/scenario/lose-condition-rules.gd
- src/main/puzzle/scenario/other-rules.gd
- src/main/puzzle/scenario/piece-type-rules.gd
- src/main/puzzle/scenario/rank-rules.gd
- src/main/puzzle/scenario/scenario-library.gd
- src/main/puzzle/scenario/scenario-settings.gd
- src/main/puzzle/scenario/score-rules.gd
- src/main/ui/chat/chat-event.gd
- src/main/ui/chat/chat-library.gd
- src/main/ui/chat/chat-tree.gd
- src/test/test-player-data.gd
Json data is now loaded using json.get("foo", "default") instead of
json["foo"]. This ensures that old save data is more forwards-compatible,
and people won't need to start over every time the save format is changed
slightly.
In an additional attempt to reduce the number of save-breaking changes, save
data is now stored in turbofat0.save. When additional save slots are added, they
can be named turbofat1.save and turbofat2.save
Json methods now have universal names like 'from_json_dict',
'from_json_string_array', 'to_json_dict'
> Data load now handles missing fields. Renamed save file.

- src/main/puzzle/piece/piece-types.gd
- src/test/test-piece-kicks-jl.gd
- src/test/test-piece-kicks-qp.gd
- src/test/test-piece-kicks-t.gd
- src/test/test-piece-kicks-u.gd
- src/test/test-piece-kicks-v.gd
- src/test/test-piece-kicks.gd
This piece kick was missing, which meant you could drop a u-piece down a
2-cell shaft and be unable to rotate it at the bottom.
I've added this kick and rearranged the existing kicks in an attempt to
keep the u-piece kicks in line with the j and l pieces.
> New u-piece 'shaft kick'

- src/main/puzzle/PuzzleHud.tscn
- src/main/puzzle/piece/active-piece.gd
- src/main/puzzle/piece/piece-speed.gd
- src/main/puzzle/piece/piece-speeds.gd
- src/main/ui/ScenarioMenu.tscn
- src/main/ui/scenario-button.gd
- src/main/ui/scenario-menu.gd
A playtester reported that the lock time of 40 frames felt too oppressive
for what's meant to be a casual game. I've slowed it down to 60 frames for
the beginner levels (0-9)
I found the DAS reduction from FA to FB to be jarring when progressing
through expert difficulties; the pieces felt out of control with only 5 frames
of DAS. I've decreased it to 5 frames for FA as well, so now it feels out of
control all the time. Ha ha.
We can let players adjust their own DAS if they hate it. 5 frames feels OK
to me now that I've practiced it.
> Slower lock times for novices. Faster DAS for experts.

- project.godot
- src/demo/turbofat-v0.0517.save
- src/main/global.gd
- src/main/old-save.gd
- src/main/player-save.gd
- src/main/puzzle/editor/level-editor.gd
- src/test/test-player-data.gd
On the surface it's a waste of time to spend 2-3 hours writing code to
maintain save compatibility, when there is literally a single user.
However I think this will continue to be a problem in future versions of
the game, so it's important to establish a backwards compatibility
framework early.
Removed JSON formatting for player save data. This caused a noticable
stutter (~300 ms) when clearing a level.
> Save data is backwards-compatible.

- src/main/player-save.gd
Static factory methods cause console errors due to Godot #30668
(https://github.com/godotengine/godot/issues/30668)
> Removed static factory methods to avoid console errors.

- src/main/puzzle/piece/piece-queue.gd
Initial piece selection could give two consecutive T or O pieces because
of a typo.
> Fixed bug where initial piece selection could give two Ts or Os.

- project.godot
- src/main/player-data.gd
- src/main/player-save.gd
- src/main/puzzle/results-hud.gd
- src/main/puzzle/scenario/scenario-history.gd
- src/main/puzzle/scenario/scenario-settings.gd
- src/main/puzzle/scenario/scenario.gd
- src/main/ui/high-score-table.gd
- src/main/ui/menu/main-menu.gd
- src/main/volume-settings.gd
- src/test/test-backwards-compatible.gd
- src/test/test-player-data.gd
- src/test/test-scenario-history.gd
The previous design which saved the newest 1,000 (!) scores for each mode had
two flaws.
1. Each score takes about 500 bytes of disk space, so 1,000 scores would
take up 500k of memory and disk space for a single scenario.
2. In the unlikely change that a player played a single scenario more than
1,000 times, the previous strategy would always kick out the oldest record
which could be the player's high score. It would take a great player 5-6 hours
of playing nothing but Ultra Normal to finally kick out their oldest
score, so this is unlikely but it could happen.
The new design saves a maximum of 7 scores: the player's newest score,
their top 3 daily scores, and the top 3 all-time scores.
Extracted ScenarioHistory from PlayerData.
> Scenario history is saved more efficiently.

- assets/puzzle/scenario/oh-my.json
- project.godot
- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/combo-score-value-label.gd
- src/main/puzzle/milestone-hud.gd
- src/main/puzzle/piece-sfx.gd
- src/main/puzzle/piece/piece-speeds.gd
- src/main/puzzle/puzzle-score.gd
- src/main/puzzle/puzzle.gd
- src/main/puzzle/scenario/Scenario.tscn
- src/main/puzzle/scenario/scenario-settings.gd
- src/main/puzzle/scenario/scenario.gd
- src/main/puzzle/scenario/tutorial-hud.gd
- src/main/puzzle/score-value-label.gd
- src/main/puzzle/topout-tracker.gd
- src/main/ui/SettingsMenu.tscn
- src/main/ui/chat/ChatChoiceButton.tscn
- src/main/ui/chat/chat-choice-button.gd
- src/main/ui/font-fit-label.gd
- src/main/ui/menu/MainMenu.tscn
- src/main/ui/menu/practice-mode-selector.gd
A bug had been introduced where ultra no longer displayed something like
'$1000' on startup, and only displayed '2:30' in a tiny font. Upon further
consideration, I realized all modes for consistency should just display
the progress towards the goal.
Survival now displays the lines remaining. Ultra displays score remaining.
Sprint displays time remaining. The '5 customers' mode displays customers
remaining.
Also refactored the milestone label to use the same 'FontFitLabel' logic
as ChatChoiceLabel.
Extracted milestone-hud script from scenario.gd.
PuzzleScore now maintains the current level, and provides signals when
lines are cleared or the level is incremented.
Removed secret 'DB' level for easter egg. Level is no longer displayed,
and with the milestone hud changes this easter egg was …
> All puzzle modes display distance to goal.

- src/main/old-save.gd
- src/main/puzzle/rank-calculator.gd
- src/main/puzzle/rank-result.gd
- src/main/puzzle/scenario/scenario-history.gd
- src/main/puzzle/scenario/scenario-settings.gd
- src/main/ui/high-score-table.gd
- src/main/ui/menu/PracticeMenu.tscn
- src/test/test-backwards-compatible.gd
The old logic looked at a scenario name to see if it started with
'ultra-', and those scenarios were compared differently. This is a poor
design because it requires all goal-based scenarios to start with the word
'ultra-'.
Now, we take any scenarios with a 'score' goal and give them a different
'compare' property. For now this can be '+score' or '-seconds', but in the
future other scenarios could have other definitions of what it means to
'do a good job at a level'. Some might compare how many or how few customers
you served, reaching a target score in as few lines as possible, or
maximizing the number of boxes made. These could all be represented in
data as something like '+customers', '-customers', '-lines' or
'+box_score'.
> High score system no longer relies on 'ultra-' prefix

- src/main/puzzle/combo-score-value-label.gd
- src/main/puzzle/piece/piece-speeds.gd
- src/main/puzzle/puzzle-score.gd
- src/main/puzzle/score-value-label.gd
- src/main/ui/chat/ChatChoiceButton.tscn
- src/main/ui/chat/chat-choice-button.gd
- src/main/ui/chat/chat-choices.gd
- src/main/ui/menu/LoadingScreen.tscn
PuzzleScore had four different signals for different aspects of the score
changing, which was overkill.
Refactored 'chat choice' logic to use button groups. Button groups are
basically intended for this case, of "there's a bunch of of nodes in the
scene tree of this one type, and i want to do something with them'
> Simplified PuzzleScore signals. 'chat-choices' group.

- project.godot
- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/piece/PieceManager.tscn
- src/main/puzzle/piece/frame-input.gd
- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/playfield.gd
- src/main/puzzle/puzzle-trace.gd
- src/main/ui/HighScoreTable.tscn
Utilizing the input singleton circumvents the input event mechanism, so
that we can't do things like ignore inputs when the user is navigating
menus.
> PieceManager no longer uses input singleton in _physics_process

- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/piece/FrameInput.tscn
- src/main/puzzle/piece/PieceManager.tscn
- src/main/puzzle/piece/frame-input.gd
- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/piece/states/prelock.gd
- src/main/puzzle/piece/states/prespawn.gd
- src/main/puzzle/puzzle-trace.gd
- src/main/puzzle/puzzle.gd
- src/main/puzzle/rank-calculator.gd
- src/main/world/restaurant/Creature.tscn
The player is now given a 120 ms window where they can press a rotation or
movement key before the piece spawns, and it will move/rotate the piece.
This prevents the feeling of 'swallowed inputs' when you press an input a
few frames before the piece spawns.
Recent refactoring made it so the player would never 'top out'; pieces
would continue to spawn forever.
> Piece inputs are buffered. Fixed broken top out behavior.

- src/main/puzzle/editor/level-editor.gd
- src/main/puzzle/puzzle.gd
- src/main/puzzle/scenario/scenario.gd
If you played a level with levelups (such as Survival) and levelled up a few
times, and then played a level without levelups (such as Ultra), MilestoneHud
would default to a level which didn't exist, and throw an array index out of
bounds exception.
> Fixed MilestoneHud crash when changing scenarios

- project.godot
- src/main/world/creature-3d.gd
- src/main/world/restaurant/Creature.tscn
- src/main/world/restaurant/creature-body.gd
- src/main/world/restaurant/creature-loader.gd
- src/main/world/restaurant/creature-sfx.gd
- src/main/world/restaurant/creature-sprite.gd
- src/main/world/restaurant/creature.gd
- src/main/world/restaurant/emote-anims.gd
- src/main/world/restaurant/head-bobber.gd
- src/main/world/restaurant/mouth-anims.gd
- src/main/world/restaurant/seat.gd
- src/main/world/spira.gd
Extracted creature-sfx.gd from creature.gd, for creature sound effects
(chime, eating sounds, voices)
Extracted creature-sprite.gd from creature.gd, for orienting creature
sprites and making them invisible/visible as the creature moves
Extracted head-bobber.gd from creature.gd for handling 'head bob' effects,
including shuddering and laughing and other motions
Extracted mouth-anims.gd from creature.gd for managing mouth animations
Moved ambient animation logic from creature.gd into emote-anims.gd
creature.gd is still too big -- but, this is a start.
> Pushed sfx, sprite orientation logic out of creature.

- src/demo/world/restaurant/CreatureViewDemo.tscn
- src/demo/world/restaurant/creature-view-demo.gd
- src/main/global.gd
- src/main/world/creature/Creature.tscn
CreatureSfx was not a Node2D, so the spatial aspects of the creature's
voices were not working.
CreatureViewDemo's 'V' command was not always playing sounds because of the
greetiness parameter. There were also some runtime errors caused by
Creature refactorings.
> Fix Creature sfx refactoring issues. Fixed CreatureViewDemo

- src/demo/world/restaurant/creature-view-demo.gd
- src/main/puzzle/puzzle.gd
- src/main/puzzle/scenario/scenario.gd
- src/main/ui/overworld-ui.gd
- src/main/world/boatricia.gd
- src/main/world/bort.gd
- src/main/world/creature/Creature.tscn
- src/main/world/creature/creature-3d.gd
- src/main/world/creature/creature-sfx.gd
- src/main/world/creature/creature.gd
- src/main/world/ebe.gd
- src/main/world/restaurant/CreatureView.tscn
- src/main/world/restaurant/RestaurantScene.tscn
- src/main/world/restaurant/door-chime.gd
- src/main/world/restaurant/restaurant-scene.gd
- src/main/world/restaurant/seat.gd
- src/main/world/spira.gd
Fixed regression introduced in 379b73d4 (pushing Scenario logic into child
classes) where scenarios no longer featured the overworld creature you
spoke with. That creature was ousted from the restaurant because we
summmoned a fourth creature.
Moved door chime from Creature into RestaurantScene. This makes sense
thematically but also keeps our code cleaner.
Resolved 'resumed after yield, but class instance is gone' errors when
playing door chimes. This was caused because the door chime logic was all
in one function with yield statements. It's now handled by timers.
Creature's 'creature_def' attribute is now a metadata property, instead of
a function. This is the same as how chat_theme_def is handled.
> 'First customer' fix. Move door chime. creature_def change.

- project.godot
- src/main/puzzle/PuzzleHud.tscn
- src/main/puzzle/editor/LevelEditor.tscn
- src/main/puzzle/topout-tracker.gd
- src/main/ui/ButtonShortcutHelper.tscn
- src/main/ui/SettingsMenu.tscn
- src/main/ui/UiMenuShortcut.tres
- src/main/ui/button-shortcut-helper.gd
- src/main/ui/menu/MainMenu.tscn
- src/main/ui/menu/PracticeMenu.tscn
- src/main/ui/menu/SplashScreen.tscn
- src/main/ui/menu/SystemButtons.tscn
- src/main/ui/menu/settings-menu.gd
- src/main/ui/menu/system-buttons.gd
- src/main/ui/overworld-ui.gd
- src/main/world/environment/nature-library.tres
InputMappings now use 'escape' key as both ui_cancel and ui_menu. This
requires some unusual logic to handle the case where both actions are
activated at once.
Disabled 'shortcut in tooltip' for buttons.
Due to Godot #28914, InputEventAction shortcuts have crazy tooltips like
(InputEventAction : action=test, pressed=(true))
> Added gamepad support.

- src/main/world/creature/Creature.tscn
- src/main/world/creature/creature-sprite.gd
- src/main/world/creature/creature.gd
- src/main/world/creature/mouth-anims.gd
This bug occurred because when 'set_orientation' was called, their arms
would revert to their forward-facing state. However they had an additional
'emote anim' arm sprite which continued to hold their chin.
We no longer revert to the default 'facing in a direction' animation state
if we're simply turning to face left or right. We only revert if we're
going from facing north to facing south or vice-versa.
> Fixed bug where creatures had three arms when puzzled

- src/main/puzzle/line-clearer.gd
The ending sequence was triggerd after the final line clears completed.
But if the level ended without a line clear, (such as with time running
out,) then this resulted in a softlock.
> Fixed softlock when no lines to clear at end

- src/main/world/Overworld.tscn
- src/main/world/overworld-camera.gd
I initially tried to develop this in a way that mirrored the 3D camera, by
having two cameras in different places and toggling which was active.
However unlike 3D, there is no 2D concept of 'smoothly switch from this
target to that target', and the community-suggested solution appears to be
to create a third 'tweening camera' to temporarily lerp between the two
other cameras. Implementing this clumsy solution of two cameras and a
temporary tweening camera was glitchy and involved a lot of custom code,
some of which is available on issue #352.
This single camera approach has a risk of violating SRP and bloating into a
huge class if we have additional events or areas with custom camera behavior.
But, it seems to be the design that's best supported for 2D.
> 2D overworld camera zooms in during conversations.

- src/main/world/Overworld.tscn
- src/main/world/screwport-texrect.gd
The TextureRect displaying the shadows now follows the camera, and the
Viewport's transform is updated based on the TextureRect's position.
> 2D overworld shadows are no longer restricted to a small rectangle.

- src/main/resource-cache.gd
Two threads could increment work_done simultaneously, resulting in a
situation where the value is only incremented once instead of twice. The
symptom is that the game hangs on the loading screen with a progress of
99%.
There's now a mutex to prevent this threading issue.
> Fixed work_done deadlock in ResourceCache

- project.godot
- src/demo/ui/menu/SettingsMenuDemo.tscn
- src/demo/ui/menu/settings-menu-demo.gd
- src/main/player-data.gd
- src/main/player-save.gd
- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/PuzzleTouchButtons.tscn
- src/main/puzzle/puzzle-touch-buttons.gd
- src/main/touch-settings.gd
- src/main/ui/SettingsMenu.tscn
- src/main/ui/VolumeSetting.tscn
- src/main/ui/menu/practice-difficulty-selector.gd
- src/main/ui/menu/practice-high-scores.gd
- src/main/ui/menu/practice-mode-selector.gd
- src/main/ui/menu/settings-menu.gd
- src/main/ui/menu/settings-touch-size.gd
- src/main/ui/settings-touch-fat-finger.gd
- src/main/ui/settings-touch-scheme.gd
- src/main/ui/touch/action-button.gd
- src/main/ui/touch/eight-way.gd
- src/main/ui/volume-setting-control.gd
- src/main/utils.gd
- src/main/world/Overworld.tscn
- src/main/world/OverworldTouchButtons.tscn
- src/main/world/overworld-touch-buttons.gd
Three basic arrangements are available: a simple one for beginners, an
ambidextrous one for people who want to drop with both hands, and a
crazy one for hardcore players who don't mind a learning curve.
Fixed bug when dragging from one eightway to another. Because the
eightways were marking touch events as handled, a drag event from one eightway
to the other resulted in the first eightway not receiving the "touch event is
out of range" input event.
> Touch controls can be configured: size, sensitivity, arrangement

- project.godot
- src/main/puzzle/piece-sfx.gd
- src/main/puzzle/piece/PieceManager.tscn
- src/main/puzzle/piece/active-piece.gd
- src/main/puzzle/piece/frame-input.gd
- src/main/puzzle/piece/piece-manager.gd
- src/main/puzzle/piece/piece-type.gd
- src/main/puzzle/piece/piece-types.gd
- src/main/puzzle/puzzle-touch-buttons.gd
- src/main/world/overworld-touch-buttons.gd
Fixed left/right puzzle input issue. If you pressed left, then pressed right,
then released right -- the piece would not move left. While this isn't a
problem the way people usually play, it resulted in an unintuitive state where
you'd be holding the left arrow key with the piece stuck to the right wall.
Loco touchscreen controls no longer accept ui_left/ui_right together.
Pressing both rotate buttons simultaneously flips a piece.
Hid puzzle screen touch buttons. These were always visible, but they
should only be visible in touch mode.
> Control improvements; left+right, ccw+cw. Hid puzzle buttons.

- src/main/puzzle/Puzzle.tscn
- src/main/puzzle/editor/level-editor.gd
- src/main/puzzle/frosting-glob.gd
- src/main/puzzle/frosting-globs.gd
- src/main/puzzle/frosting-viewports.gd
- src/main/puzzle/playfield.gd
- src/main/puzzle/wall-frosting-sfx.gd
- src/main/puzzle/wall-glob-viewports.gd
- src/main/ui/chat/chat-choices.gd
- src/main/ui/high-score-table.gd
- src/main/ui/menu/practice-difficulty-selector.gd
- src/main/world/environment/grass-tufts.gd
Pooling frosting globs required us to move them back and forth between
several parent nodes. The remove_child calls required when moving a glob
from one parent to another sporadically altered the 2D render order because of
Godot #16213 (https://github.com/godotengine/godot/issues/16213).
This caused an unpleasant flickering effect in the frosting.
Removing the object pool addressed the issue. I've also removed all other
remove_child calls throughout the project. queue_free() will remove
children.
> Removed frosting pool. Removed 'remove_child' calls.

- src/main/ui/VolumeSetting.tscn
I had increments to make it easy to specifically pick specific settings.
But, some users have their volume set to where 5% or 10% is too loud.
Flexibility is more important than the obsessive players who want their sliders
exactly perfectly in the center.
> Removed volume slider increments.

- src/main/puzzle/editor/LevelChunkControl.tscn
- src/main/puzzle/editor/LevelEditor.tscn
- src/main/puzzle/editor/box-chunk.gd
- src/main/puzzle/editor/editor-json.gd
- src/main/puzzle/editor/editor-playfield.gd
- src/main/puzzle/editor/level-chunk-control.gd
- src/main/puzzle/editor/level-editor.gd
- src/main/puzzle/editor/piece-chunk.gd
- src/main/puzzle/editor/veg-chunk.gd
Instead of disabling/ZIndexing level editor components during a test,
they're now hidden (visible=false). JSON is now displayed vertically on
the right side of the screen.
Added placeholder 'Properties' tab in level editor. This is where other
properties such as difficulties and win conditions will go.
> Reorganized level editor.

- src/main/old-save.gd
- src/main/player-save.gd
- src/main/puzzle/puzzle-score.gd
- src/main/puzzle/scenario/scenario-history.gd
- src/main/ui/menu/main-menu.gd
- src/main/ui/menu/practice-difficulty-selector.gd
- src/main/ui/menu/practice-menu.gd
The save data now includes a list of all scenarios which were finished
successfully (lost = false) and a list of all scenarios which were
successful (success = true). This allows menus and game logic to trivially
check in O(1) time whether the player's passed a scenario.
The player must pass the tutorial to play the game. Before they could fail
the tutorial, quit the game, re-launch the game and have no way to play
the tutorial.
Fixed bug where rank highlights/lowlights were rendered incorrectly. This
was introduced by the recent removal of remove_child() calls, some of
which had side effects.
> Save finish/success data. Must pass tutorial.

- delint.sh
- edit-creature.sh
- generate_export_presets.sh
- project/assets/main/world/creature/1/eyes-packed.json
- project/assets/main/world/creature/2/eyes-packed.json
- project/assets/main/world/creature/3/eyes-packed.json
- project/project.godot
- project/src/main/packed-sprite.gd
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/creature-packed-sprite.gd
- project/src/main/world/creature/creature-sprite.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/emote-anims.gd
- project/src/main/world/creature/head-bobber.gd
- project/src/main/world/creature/mouth-anims.gd
- project/src/main/world/viewport-outline-material.tres
Creature tool scripts can now be toggled with an `edit-creature.sh`
shell script. The creature's appearance can be manipulated and reset with
three new properties, 'reset_frames', 'reset_creature' and
'random_creature'.
Eyes now have a north-facing frame 2, just like mouths and other body
parts. This lets eyes reuse the same 'CreaturePackedSprite' logic as all
other body parts. Eyes aren't visible when facing away, but eventually they
might be. (When that happens we'll need them on a different Z-layer than they
are now.)
Split 'fill_creature_def' function out of 'summon'. 'Summon' is now just
'set_creature_def'.
Minor refactoring. Fixed inconsistencies in shell scripts (unquoted
strings, header style). Renamed inaccurate 'creature' fields to
'creature_visuals'.
> Improved Creature.tscn behavior in editor. Changed eye frames.

- project/project.godot
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/frosting-glob.gd
- project/src/main/puzzle/frosting-globs.gd
- project/src/main/puzzle/puzzle-areas.gd
- project/src/main/puzzle/wall-frosting-sfx.gd
- project/src/main/ui/chat/ChatFrame.tscn
- project/src/main/ui/chat/chat-line-label.gd
- project/src/main/ui/chat/chat-line-panel.gd
ChatLinePanel, ChatLineLabel now share information about chat box sizes.
FrostingGlob's playfield areas are now calculated based on the position of
the playfield and next piece controls, instead of being hard-coded as
constants.
Removed 'gutter area' which frosting globs could hit. I originally
separated this because I wanted to spread frosting there, but now it seems
unnecessary.
> Refactoring: classes reuse magic numbers (sizes, positions)

- project/src/main/puzzle/editor/LevelEditor.tscn
- project/src/main/puzzle/editor/editor-json.gd
The level editor playfield was being drawn over top of pop up windows,
making it difficult to save.
The level editor also crashed because of some tilemap/tile_map
refactorings recently.
> Fixed UI issues, crashes with level editor

- project/assets/main/dialog/bort/creature.json
- project/src/demo/ui/chat/mood-demo.gd
- project/src/main/packed-sprite.gd
- project/src/main/world/chat-icon.gd
- project/src/main/world/chattable-manager.gd
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/arm-shadow.gd
- project/src/main/world/creature/creature-chat-icon.gd
- project/src/main/world/creature/creature-collision-shape.gd
- project/src/main/world/creature/creature-curve.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/fat-sprite-mover.gd
- project/src/main/world/overworld-camera.gd
Eventually, creatures will show up fatter as you feed them more. For now
it's just a hard-coded value in the creature definition.
Most emotes work for fat creatures. Their arm shadow disappears
appropriately when they bring their arms up to their face. The 'rage cloud'
emote doesn't look very good, but that's a hard one to fix. I opened #461 to
document this.
> Fat creatures can now appear on the overworld.

- project/src/main/puzzle/piece/PieceManager.tscn
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/piece-squisher.gd
Before, if you did a combination hard drop + squish move, the piece would
immediately lock if the piece squished once, but it would do a lock reset
if the piece squished twice. This made it difficult to play quickly, since
sometimes you needed to hard drop twice, and sometimes only once.
> Don't reset lock if doing combo hard drop + squish move

- project/src/main/puzzle/piece/piece-types.gd
- project/src/test/test-piece-kicks-qp.gd
- project/src/test/test-piece-kicks.gd
Kick tests were inadvertently invalidated in 6d79347b when the PieceManager's
inputs were refactored. They would always pass. I've fixed them so they
can fail again.
Added new 'bump kicks'; I ran into this today where I couldn't rotate a
piece that I should have been able to.
> Fixed kick tests. Added 'bump kicks' for p/q pieces

- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/piece-squisher.gd
Before, squish drops were sort of an accident of how the controls happened
to work, but this resulted in a few idiosyncracies:
* squish drops resulted in multiple squish signals
* squish drops requiring piece movement would cause a lock reset
* squish drops had a delay proportionate to the number of pieces being
squished through
I've added explicit logic where if the player is pressing hard drop and
soft drop, it triggers different logic which calculates the lowest
possible squish target and rockets the piece there.
> Added explicit 'squish drop' logic.

- project/src/main/puzzle/piece/piece-types.gd
- project/src/test/test-piece-kicks-u.gd
The U-piece used to pivot around its long straight part which is intuitive
because it's close to its center of mass. However, this makes it very
rigid and inflexible. I've changed it to pivot around its 'hole' which while
allows for more creative rotation options. Most importantly it allows the
U piece to climb up stacks of pieces, but also allows for rapid snack
boxes in the center column.
These changes are consistent with the P and Q pieces, which also initially
used a 'center of mass' rotation rule but were changed to allow for creative
rotation options.
> U-piece has new rotation rules to facilitate climbing.

- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/ear-anims.gd
- project/src/main/world/creature/emote-anims.gd
- project/src/main/world/creature/mouth-anims.gd
When creatures turned to face north while an idle animation was going on,
they'd end up with some visual oddities: mouths with the wrong z-index,
eyes on the back of their head, heads permanently tilted, etc
> Fixed bug with idle animations on north facing creatures

- project/src/main/ui/overworld-ui.gd
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/emote-anims.gd
Creatures who went from running to emoting had an extra arm, which was the
result of the 'idle' movement animation playing. The idle animation is now
stopped when emoting.
If Spira talked to a running creature, the creature wouldn't stop and
orient themselves correctly because the 'orient_toward' method said not
to. The orient_toward method now always orients a creature, and there's
some special logic in overworld-ui.gd which says that Spira is exempt from
orienting.
Fixed bug where some emotes would result in creatures having two eyes;
this was introduced in d6df127 when trying to fix some bugs with
north/south idle animations
> Fixed emote bugs related to arms, eyes, orientation

- delint.sh
- project/project.godot
- project/src/main/music-player.gd
- project/src/main/music-tween.gd
- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/scenario/scenario.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/main/puzzle/tutorial/tutorial-hud.gd
- project/src/main/puzzle/tutorial/tutorial-message.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/world/restaurant/creature-view.gd
Fixed bug where star seeds sometimes lingered during tutorial. This bug was
caused because the after_piece_written and lines_deleted signals were emitted in
the wrong order. This meant when changing tutorial scenes, the scene would
change, and then the new star seeds would get moved around based on the cleared
lines.
Star seeds for incomplete boxes (such as in the third part of the tutorial) are
no longer placed adjacent if possible.
Instructor is now summoned when restarting a tutorial. Before, if you restarted
a tutorial after customers showed up, the random customer would lead the tutorial.
Increased tutorial music volume. The tutorial music is about 4 db quieter
than other songs, so I've turned up its in-game volume to compensate.
It was kind of jarring when the 'real music' kicked in …
> Tutorial bugs: star seeds, instructor, music volume, messages

- project/src/main/gameplay-settings.gd
- project/src/main/player-save.gd
The gameplay_settings object wasn't being persisted, and it also had a
bug in its from_json_dict() function.
> Fixed bugs loading/saving 'ghost piece' setting.

- project/src/main/touch-settings.gd
The setting was 'fat-finger' in one place but 'fat_finger' in the other.
Closes #509
> Fixed fat finger setting; setting wasn't saved because of typo

- project/src/main/puzzle/piece/piece-mover.gd
Otherwise there was an edge case where you're holding a piece against a
nook, but the piece skips the nook in a very specific case:
1. the piece is moved left successfully, while soft dropping, and not
blocked on the left
2. the piece becomes blocked with the left as it drops, but DAS is not yet
active
3. the piece goes past the nook before DAS activates
> 'nook das' activates even if piece isn't moving.

- project/src/main/world/creature/body-shadows.shader
- project/src/main/world/rgb-palette.shader
This was noticable at the top of the neck as described in #492. But, it
also became noticable around the eyes and face after facial colors were
introduced recently.
This bug was caused because red/green/blue are mixed one after the other
-- but the old math would mix in red 33%, green 33% and blue 33% for
example, resulting in a color which still had some black in it. The new
logic will mix in red 100%, green 50%, and blue 33% for an opaque color
which is evenly distributed between all three colors.
> Fixed thin shader lines at boundaries, overlaps.

- project/src/main/world/creature/CreatureVisuals.tscn
The godot editor deleted all of these animations in 93ce7c52. This had
several side effects including creatures growing a third arm when emoting,
arms remaining still during movement animations, and disappearing as the
creature got fatter.
It's hard to remember what could have made the Godot editor do something so
destructive. Maybe I copied the FarArm node to create the Collar node, and
the editor got confused. Maybe I renamed it, and then renamed it back.
Closes #543, #500, #301.
> Restored FarArm creature animations.

- project/project.godot
- project/src/main/ui/VolumeSetting.tscn
10% is too loud and not granular enough, hence why #406 was created. 10%
is too big but 0% is not possible either. 1% seems OK.
> Decreased volume step from 10% to 1%.

- project/src/demo/ui/chat/mood-demo.gd
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/ear-anims.gd
- project/src/main/world/creature/emote-anims.gd
- project/src/main/world/creature/idle-timer.gd
- project/src/main/world/creature/mouth-anims.gd
Fixed a bug where creatures would blink too often. The blink ambient
animation didn't loop, and every time it stopped it would reset to a
random point in the middle.
Fixed a bug where creatures would get stuck looking over their shoulder.
This is because an idle animation would start but then be interrupted.
There's a new 'stop_idle_animation' signal which tells nodes to undo any
of their idle animation stuff.
Changed 'start_idle_animation' signal to 'idle_animation_started' for
consistency with AnimationPlayer
Closes #527.
> Fixed creatures overblinking, stuck looking over shoulder

- project/project.godot
- project/src/main/world/creature/Ear1Player.tscn
- project/src/main/world/creature/Ear2Player.tscn
- project/src/main/world/creature/Ear3Player.tscn
- project/src/main/world/creature/Mouth1Player.tscn
- project/src/main/world/creature/Mouth2Player.tscn
- project/src/main/world/creature/Mouth3Player.tscn
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/ear-player.gd
- project/src/main/world/creature/mouth-player.gd
Instead of having three AnimationPlayers and turning them on/off, it now only
has one. This solution scales better, and we'll eventually need to do something
similar for bodies so it's helpful to have the framework in place.
CreatureLoader hosts the preloaded list of AnimationPlayers. These cannot go in
CreatureVisuals or it causes a circular reference. CreatureLoader is now an
autoloaded node instead of a static class.
> Creature now only has one ear/mouth AnimationPlayer at once.

- project/src/main/world/creature/creature-curve.gd
- project/src/main/world/creature/smooth-path.gd
CreatureCurve had a bug where it would malfunction with fewer than 2
curves.
SmoothPath had a bug where it would report errors with fewer than 3
points.
> CreatureCurve, SmoothPath work better with small numbers

- project/src/main/puzzle/puzzle.gd
Instead of talking at [5, 8, 11, 14, 17...] lines, they talk at [6, 12,
18, 24, 30...] lines. The frequency of their lines was causing them to
interrupt themselves at faster speeds.
> Creature talks less frequently during combos.

- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/creature-curve.gd
- project/src/main/world/creature/creature-sfx.gd
- project/src/main/world/creature/creature-shadow.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/ear-player.gd
- project/src/main/world/creature/head-sweat-squirts.gd
- project/src/main/world/creature/idle-timer.gd
- project/src/main/world/creature/mouth-player.gd
- project/src/main/world/restaurant/RestaurantScene.tscn
- project/src/main/world/restaurant/door-chime.gd
Split CreatureVisuals._update_creature_properties into _unassign and
_assign methods. These are slightly more descriptive and help separate and
document the two distinct pieces of functionality the method was doing.
Extracted _add_visuals_node, _remove_visuals_node utility methods to cut
down on repetitive code.
The creature_arrived signal is now named 'dna_loaded' which is more
descriptive. This was originally named 'creature_arrived' because it coincided
with arriving at the restaurant, but now that is not always the case as it
applies to creatures being loaded in the overworld or elsewhere.
I removed the before_creature_arrived signal. It was only used for stopping
animations which is now unnecessary as the animation players get removed.
> Refactored CreatureVisuals methods, signals, repetitive code.

- project/assets/main/dialog/boatricia/creature.json
- project/assets/main/dialog/bort/creature.json
- project/assets/main/dialog/ebe/creature.json
- project/assets/main/dialog/instructor/creature.json
- project/src/main/puzzle/puzzle.gd
- project/src/main/world/creature/creature-loader.gd
Instead of repetitive assignments to red/green/blue/black values,
CreatureLoader now uses a utility method to assign all values at once.
Moved instructor's dna into a json file, instead of hard-coding it in
puzzle.gd.
Reordered CreatureLoader methods so that private methods are at the
bottom.
Alphabetized creature.json fields.
> CreatureLoader refactorings: repetitive code, instructor config

- project/src/main/breadcrumb.gd
- project/src/main/resource-cache.gd
Caching these resources improves the puzzle launch time from about 2
seconds to about 1 second.
Caching .tscn resources requires some special handling, since loading them
in a threaded manner causes problems. We need to load all of the resources
normally, and then load the scenes in the main thread.
Performance could be further improved by initializing and reusing a single
puzzle scene instead of initializing a new scene every time -- but this
introduces a lot of bugs reinitializing the scene, as well as errors/warnings
exiting the game.
> .tscn resources are cached, improving scene launch performance.

- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/dna-utils.gd
DNA is trimmed so it doesn't include extra textures and shader properties.
This gets rid of some visual clutter in the save files and also
significantly reduces the size.
Closes #567.
> DNA is trimmed before being saved.

- project/src/main/puzzle/puzzle-tile-map.gd
Clearing a line with a box would check the adjacent autotile coordinates,
but it wouldn't check the adjacent cell types. This meant it could make
vegetable blocks change to a different vegetable.
> Fixed autotile bug when clearing boxes next to vegetables.

- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/puzzle.gd
Before, the big finish cleared vegetable in big clumps which looked a
little strange. Also if there were only vegetables remaining and no boxes,
they stuck around so it felt a little inconsistent.
Closes #563.
> 'Big Finish' preserves vegetable rows, which fall to the bottom.

- project/assets/main/editor/creature/animals.txt
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/markov-model.gd
- project/src/main/name-generator.gd
- project/src/test/puzzle/test-playfield.gd
- project/src/test/test-markov-model.gd
A markov order of 2 results in nonsensical names like 'Woodd' because
'ood' and 'odd' are both valid letter clusters. A markov order of '3'
results in predictable names like 'Tarakeet' because the clusters 'ara'
and 'ake' only have a few valid continuations. Randomly alternating
between 2 and 3 mitigates these disadvantages.
Removed multi-word animals. These typically caused animalish names like 'Mistink
Bug' and 'Term Whale'.
Removed test-playfield.gd. It was testing a method which no longer exists.
> Markov model allows fractional values. Removed multi-word animals

- project/src/main/world/creature/creature-loader.gd
- project/src/test/test-rolling-backups.gd
Inky mouths were a side effect of creature refactorings in a24a01ef. Mouths used
to be a specific pink color which was defined in CreatureVisuals.tscn.
I've moved this pink color into CreatureLoader so it won't be overwritten
as easily.
Fixed long lines in 'test-rolling-backups.gd'
> Fixed inky mouths, long unit test lines

- project/project.godot
- project/src/main/world/ChatIcon.tscn
- project/src/main/world/Overworld.tscn
- project/src/main/world/chat-icon.gd
- project/src/main/world/chat-icons.gd
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/creature-chat-icon-hook.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/glowy-sphere.gd
Creatures no longer have a chat icon -- instead, a separate ChatIcons node
generates chat icons for all creatures, and anything else that is in the
chattables group. Instead of customizing the chat icon by changing the
chat icon's properties, nodes can define metadata which affects their chat
icon appearance, such as the 'chat_bubble_type' metadata
This is a slightly cleaner design as scaling/rotating a creature won't
mess with their chat icon, and we don't need to worry about chat icons
being hidden by the environment.
These chat icons can't go in the UI layer because they're positioned using
RemoteTransform2D. But they're in a Node2D separate from the creatures and the
environment.
Lowered chat bubbles for small squirrel creatures. Their heads are lower,
so the chat icons should be …
> ChatIcons are generated for all chattables. Lowered squirrel chat icons.

- project/assets/main/dialog/boatricia/level-1.json
- project/assets/main/dialog/boatricia/level-2.json
- project/src/main/editor/creature/reroll-ui.gd
- project/src/main/puzzle/combo-tracker.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/results-hud.gd
- project/src/main/puzzle/scenario/scenario-history.gd
- project/src/main/puzzle/scenario/scenario-settings.gd
- project/src/main/puzzle/scenario/scenario.gd
- project/src/main/puzzle/tutorial/tutorial-hud.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/chat/chat-ui.gd
- project/src/main/ui/high-score-table.gd
- project/src/main/ui/menu/practice-menu.gd
- project/src/main/world/creature/creature.gd
Changed scenario.name to scenario.id, to disambiguate between IDs like
'tutorial_beginner' and titles like 'Easy does it!'. ...Both of these
things could be construed as names, so I'm going to call one an 'ID' and
one a 'title'.
Minor refactorings; renames, warnings.
Boatricia's JSON data had some dangling commas.
> Scenario.name -> id. Minor refactorings, JSON syntax fixes.

- project/src/main/puzzle/milestone-manager.gd
- project/src/main/puzzle/puzzle-score.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/ui/level-select/LevelSelect.tscn
PuzzleScore now sets a 'no_more_customers' flag after feeding the last
customer. This prevents further customers from spawning and also signals
to the MilestoneManager that the 'feed five customers' milestone has been
met.
Closes #370.
Added a five pixel margin around the level select screen.
> Fixed extra customer for 'only 5 customers' scenarios.

- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/editor/creature/dialogs.gd
- project/src/main/editor/puzzle/LevelEditor.tscn
- project/src/main/editor/puzzle/dialogs.gd
- project/src/main/ui/DialogBackdrop.tscn
While HTML5 supports saving/loading files, it only gives you access to a
user sandbox and doesn't let you access any files on the filesystem. This
makes saving/loading pretty useless. We now pop up an error.
Closes #580.
Fixed issue where DialogBackdrop didn't reach the edges of the screen if
the screen was resized.
> Added error dialog when saving/loading files in HTML5.

- project/assets/main/dialog/ebe/creature.json
- project/assets/main/dialog/ebe/filler.json
- project/assets/main/dialog/ebe/no-vegetables.json
- project/assets/main/dialog/level-select-1.json
- project/project.godot
- project/src/main/editor/creature/creature-shadows.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/scenario/scenario-settings.gd
- project/src/main/puzzle/scenario/scenario.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/menu/practice-menu.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/Overworld.tscn
- project/src/main/world/chat-icons.gd
- project/src/main/world/overworld-world.gd
- project/src/test/ui/chat/test-chat-library.gd
Selecting certain scenarios from the level select screen now plays a
little cutscene.
The 'level select' chat tree now includes an extra 'chit chat' choice,
which is what they'll say on the overworld if they have no level.
launched_scenario_name -> launched_scenario_id. level_int -> level_num
Moved OverworldUi fields related to 'launched scenario', 'launched
creature dna' into Scenario.
> Added cutscene logic for Ebe/Boatricia on overworld.

- project/src/main/puzzle/playfield-fx.gd
There was some logic which checked if the tileset was initialized, and if
it was already initialized, then the _color_tile_indexes map was left
empty. This logic was flawed because tilesets are sometimes cached if not
unique to a scene, but the _color_tile_indexes map needs to be initialized
every time.
These two objects are now initialized independently.
Closes #622.
> Fixed issue where playfield lights were not always initialized properly.

- project/src/main/global.gd
- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle-score.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/scenario/scenario-history.gd
- project/src/main/puzzle/scenario/scenario.gd
- project/src/main/puzzle/tutorial/tutorial-hud.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/level-select/level-info-panel.gd
- project/src/main/ui/menu/loading-screen.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/menu/practice-menu.gd
- project/src/main/ui/menu/splash-screen.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/Overworld.tscn
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/creature.gd
- project/src/main/world/overworld-world.gd
- project/src/main/world/restaurant/RestaurantScene.tscn
- project/src/main/world/restaurant/door-chime.gd
- project/src/main/world/restaurant/restaurant-scene.gd
Creatures are closer together during cutscenes, especially skinny
creatures.
Extracted 'SCENE_' constants into Global.
Can always restart puzzles, original creature shows up. Thematically it's
interesting to say 'you only get one chance' but this will frustrate players,
and there's no compelling gameplay reason to forbid players from retrying a
level.
Rewrote tutorial to use creature queue instead of custom logic.
Instead of checking 'is the fatness 1.0' to see if a creature has been
fed, it checks a custom 'feed_count' variable. Some creatures will
eventually be >1.0 fatness by default, so this logic is more robust.
Suppress sound effects when restarting level; restarting shouldn't play
chime and 'hello' sounds.
Fixed bug where quitting a puzzle while 'upbeat' music was playing caused
it …
> Cleaned up minor issues discovered during cutscene logic.

- project/src/main/creature-library.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/restaurant/customer-camera-mover.gd
Overworld creatures like Bort, Ebe and Boatricia appear fat on the
overworld and during puzzles if they eat too much. Secondary creatures
like Pandon, Mocha and Nardine maintain their weight from puzzle to puzzle
as well.
Fixed camera listener bug introduced in a0d9389e. Instead of registering a
listener on all three creatures, it was only being registered on the
first.
> Creatures maintain their weight. Fixed camera listener bug.

- project/src/main/creature-library.gd
- project/src/main/editor/creature/TweakSizeRow.tscn
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/global.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/world/chattable-manager.gd
- project/src/main/world/creature/creature-loader.gd
The filler characters weight isn't generated from scratch; it's now
pulled from a pool of 150 filler weights. If the player plays well these
weights will increase, if they play poorly their weights will decrease.
Extracted CREATURE_ID_PLAYER constant.
Moved CreatureEditor.FATNESSES constant into Global, so it can be reused
by CreatureLibrary.
> Generic filler creatures get fatter over time.

- license/asset-license.txt
- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/editor/creature/dialogs.gd
- project/src/main/editor/puzzle/LevelEditor.tscn
- project/src/main/editor/puzzle/dialogs.gd
- project/src/main/file-utils.gd
- project/src/main/utils.gd
With the old behavior, I had '/workspace/turbofat/project' hard-coded in
these FileDialogs which worked OK on my computer, but would just default
to 'C:\' on other people's computers.
I've changed the file dialogs to locate specific resource paths if
available (if you're running the game in the Godot editor) and, if
unavailable, it'll default to the user's data directory. (I would rather
default to something like 'My Documents' but this appears to be
unsupported.)
Renamed LevelEditor dialog nodes to avoid redundancy in paths like
'Dialogs/OpenFileDialog'.
Fixed some asset license paths.
> FileDialogs default to better paths.

- project/src/main/world/creature/Mouth3Player.tscn
When the creature yawned while an emote was launched, the chin didn't
reset appropriately. This was because of a missing chin animation key.
Closes #656.
> Fixed 'weird chin' bug.

- project/src/main/puzzle/tutorial/skill-tally-item.gd
- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
Tally items were no longer incrementing; this was broken when making
tutorials modular. Signals weren't getting reconnected.
If you cleared a box line quickly in the second part of the basic tutorial, you
could wipe way the "make a snack box" message without seeing it. The
message will now appear again.
Fixed bug where snack boxes got incremented twice in the second part of
the tutorial, despite only making one snack box.
> Fixed tutorial regressions: tally items, sequence breaks

- project/src/main/puzzle/tutorial/skill-tally-item.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
For some reason, the old duplicate() implementation I had causes ObjectDB
leaks even when the method is renamed, and even when it is never invoked.
It is very strange.
> Fix ObjectDB leaks introduced in 507ea7b

- project/assets/main/puzzle/levels/accelerator.json
- project/assets/main/puzzle/levels/veggie-patty.json
- project/assets/main/puzzle/worlds.json
- project/src/main/editor/puzzle/level-editor.gd
- project/src/main/puzzle/duration-calculator.gd
- project/src/main/puzzle/level/milestone.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/milestone-hud.gd
- project/src/main/puzzle/milestone-manager.gd
- project/src/main/puzzle/piece/NextPieceDisplay.tscn
- project/src/main/puzzle/piece/next-piece-display.gd
- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/puzzle-performance.gd
- project/src/main/puzzle/puzzle-score.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/rank-result.gd
- project/src/main/puzzle/results-hud.gd
- project/src/test/puzzle/test-rank-calculator.gd
New levels, 'veggie patty', 'accelerator'.
We now perform 'speed ups' before line clears, because it sounds better
for speedups caused by a piece milestone. Otherwise the sound effects play when
the player drops a piece, except when they clear lines, and then there's a
delay, which is jarring.
We still perform 'level finishes' after line clears, because otherwise the
player won't earn the points from their final line clear.
For this reason MilestoneManager now performs most level checks after line
clears, instead of checking for them every frame. This also required some
minor tweaks to signals in LineClearer and PuzzleScore.
For levels with limited pieces, the next piece queue runs out.
> Scenarios can now impose a piece limit.

- project/src/main/puzzle/piece/next-piece-display.gd
The next piece displays only refreshed their '_displayed_piece' field for
non-empty cases, resulting in a small chance that an empty piece wouldn't
refresh. This resulted in a temporary gap in the next piece queue.
> Fixed bug with empty next pieces.

- delint.sh
- project/src/demo/ui/chat/MoodDemo.tscn
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/dna-loader.gd
Jitter seems to mostly stem from editing too many shader parameters in one
frame; this is now spread out over multiple frames.
DnaLoader is now separate because it needs to have pausing disabled; otherwise
creature colors don't update properly when using the color pickers in the
creature editor.
Note: I initially attempted an approach where instead of loading shader
parameters gradually, I loaded all DNA properties gradually. This
introduced problems because the code would try to animate partially-loaded
textures, and required stuff like mutexes and new signals to keep track of
whether the DNA was unloaded, partially loaded, or fully loaded. It was a
big mess, but if you want to pursue this in the future you can see my work
in 59e1f6e.
> Added jitter fix. Split DnaLoader from CreatureVisuals.

- project/src/main/packed-sprite.gd
- project/src/main/resource-cache.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/menu/practice-menu.gd
- project/src/main/ui/menu/splash-screen.gd
- project/src/main/ui/menu/tutorial-menu.gd
- project/src/main/ui/wallpaper/Wallpaper.tscn
- project/src/main/utils.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/dna-loader.gd
PackedSprite was throwing errors because it depended on ResourceCache
which was not a tool. ResourceCache shouldn't be a tool because caching
resources in the editor has the potential to cause headaches, as resources
change frequently during development. PackedSprite now has the capability
of loading non-cached resources in the editor.
Improved singleton logic to allow for further singletons. Instead of
specifically saving and loading a wallpaper singleton, ResourceCache now saves
and loads all nodes in the 'singletons' node group.
> Fixed PackedSprite editor errors, improved singleton logic

- project/src/main/ui/chat/chat-choices.gd
Chat choices started appearing in tutorials after the new 'Columns'
parameter was introduced. This parameter was incorrectly implemented
because the 'columns' parameter was shadowing the identically named
'columns' field.
I've renamed the parameter.
> Fixed regression where chat choices appears in columns.

- project/src/main/breadcrumb.gd
- project/src/main/creature-library.gd
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/editor/puzzle/level-editor.gd
- project/src/main/ui/level-select/level-select.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/creature/creature.gd
CreatureDef now defines min_fatness, not fatness. The CreatureDef json still
uses 'fatness' for simplicity and backwards compatibility.
Moved duplicated 'popping top level of breadcrumb trail' logic into
Breadcrumb class. This unfortunately makes Breadcrumb a little more
project-specific, since it depends on ResourceCache and LoadingScreen.
> Refactored CreatureDef.min_fatness and breadcrumb pop logic

- project/assets/main/creatures/secondary/lango.json
- project/assets/main/puzzle/levels/tutorial-basics-0.json
- project/assets/main/puzzle/levels/tutorial-basics-1.json
- project/assets/main/puzzle/levels/tutorial-basics-2.json
- project/assets/main/puzzle/levels/tutorial-basics-3.json
- project/assets/main/puzzle/levels/tutorial-squish-0.json
- project/assets/main/puzzle/levels/tutorial-squish-1.json
- project/assets/main/puzzle/levels/tutorial-squish-2.json
- project/assets/main/puzzle/levels/tutorial-squish-3.json
- project/assets/main/puzzle/levels/tutorial-squish-4.json
- project/assets/main/puzzle/levels/tutorial-squish-5.json
- project/assets/main/puzzle/levels/tutorial-squish-6.json
- project/project.godot
- project/src/main/creature-library.gd
- project/src/main/creature-queue.gd
- project/src/main/editor/creature/dialogs.gd
- project/src/main/global.gd
- project/src/main/player-data.gd
- project/src/main/puzzle/level/level.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/tutorial/tutorial-messages.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/ui/level-select/hookable-grade-label.gd
- project/src/main/ui/level-select/level-description-panel.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/creature/creature-loader.gd
Extracted new CreatureQueue class. This logic used to be spread between
Global and CreatureLoader, but is now collected in a single class. Also
moved some creature constants and initialization logic into CreatureDef.
This was necessary to avoid circular references while refactoring.
Tutorials now reset combo when the player clears a section. This lets us remove the 'don't build combos' flag from the tutorial level data. This also lets the player build combos on tutorial sections which should be more intuitive.
Removed redundant 'how to render hard locked levels' logic. Hard locked
levels were once rendered, but they're not anymore.
> Refactored creature queue, tutorial combos, dead code

- project/src/main/creature-queue.gd
- project/src/main/editor/creature/dialogs.gd
- project/src/main/puzzle/tutorial/tutorial-messages.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/creature/creature-loader.gd
CreatureDef cannot have a method returning a CreatureDef or Godot will
throw warnings/errors. See Godot #30668.
> Fix resource leak introduced in CreatureQueue refactoring.

- project/src/main/puzzle/combo-counters.gd
- project/src/main/puzzle/combo-tracker.gd
- project/src/main/puzzle/line-clear-sfx.gd
- project/src/main/puzzle/playfield-fx.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/puzzle-score.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/ui/chat/chat-nametag-panel.gd
- project/src/main/ui/nametag-panel.gd
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/dna-loader.gd
- project/src/main/world/restaurant/RestaurantView.tscn
Combined ComboTracker.combo and PuzzleScore.creature_line_clears. We were
storing this information in two places before. It's now stored in PuzzleScore's
new combo field.
Pushed logic for refreshing nametag appearance into NametagPanel to keep
RestaurantView smaller.
DnaLoader no longer emits a signal on CreatureVisuals. Nodes should emit
their own signals, even if it's technically a little less efficient in
this case.
> Refactored combos, restaurant nametags, dna loader.

- project/src/main/puzzle/piece/piece-queue.gd
- project/src/test/puzzle/piece/test-piece-queue.gd
The old algorithm shuffled pieces up to 48 times and hoped that one of the
random arrangements resulted in having no back-to-back pieces. But it was
random, and even though the most I ever saw it take was 15-20 tries, it
could theoretically have bad luck and fail to come up with an arrangement.
The new algorithm finds a location for each piece deterministically, and
is more reliable. It will only fail if it's impossible to find an
arrangement (e.g a custom level with a piece queue with 3 T pieces and an
O piece)
> Rewrote piece shuffling algorithm to be more reliable.

- project/src/demo/ui/chat/mood-demo.gd
- project/src/main/editor/puzzle/LevelEditor.tscn
- project/src/main/editor/puzzle/level-editor.gd
- project/src/main/puzzle/FrostingViewports.tscn
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/combo-counters.gd
- project/src/main/puzzle/food-items.gd
- project/src/main/puzzle/frosting-globs.gd
- project/src/main/puzzle/frosting-viewports.gd
- project/src/main/puzzle/leaf-poofs.gd
- project/src/main/puzzle/piece/piece-mover.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/main/puzzle/wobbler.gd
- project/src/main/utils.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/dna-utils.gd
Added a DnaUtils.random_dna() method; this is a trivial method but many
places wanted a random creature so now it's in one place
Alleles are now shuffled before DnaUtils picks them. This avoids any sort
of 'pecking order' where one allele trumps another allele when they
conflict. Otherwise we could have a subtle preference where noses are more
common than beaks, or vice-versa
DnaUtils.fill_dna now fills color alleles with a random palette, instead
of a fixed palette
Replaced '.tscn' strings with PackedScene exports. Using PackedScene exports
allows Godot to keep these scenes hooked up during move/rename operations.
> DNA refactoring, PackedScene replacements

- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/menu/splash-screen.gd
Main quit button quits to splash screen. Splash screen quit button no
longer exists. The player can close the browser window to quit.
Closes #700.
> Fixed HTML5 quit button.

- project/project.godot
- project/src/main/puzzle/Playfield.tscn
- project/src/main/ui/SettingsMenu.tscn
- project/src/main/ui/VolumeSetting.tscn
- project/src/main/ui/menu/settings-menu.gd
- project/src/main/ui/volume-setting-control.gd
- project/src/main/world/Overworld.tscn
The settings panel is going to allow custom keyboard controls, but this
will occupy a lot of visual real estate. A tabbed UI will prevent the
settings panel from being too busy.
Closes #643.
'Touch' settings are now hidden if touch isn't enabled.
Players expect space bar to hard drop, based on other similar games.
VolumeSetting signals are now connected in GDScript, instead of through
configuration. Signals connected through configuration frequently get
disconnected.
> Settings tabs. Hide touch settings. Space hard drops.

- project/src/main/world/chat-icon.gd
When the player runs near different creatures, their chat icon is supposed
to light up. But when this happened, all of the chat bubbles blinked. This
is because the tween's parameters were using the wrong node's modulate
proeprty.
I also added a check to avoid launching unnecessary chat icon tweens. This
shouldn't have any visible effect, but fewer tweens is good for performance and
simplicity.
> Fixed bug where all chat icons blinked sometimes.

- project/src/main/world/overworld-camera.gd
When the camera zoomed out there were a few frames of jitter. This may
reflect an inherent flaw in our texture zooming logic, but for now it's
unnoticable if the camera zoom eases in and out, instead of only easing in
one direction.
Closes #741.
> Smoother zooming to avoid camera jitter.

- project/assets/main/creatures/primary/richie/creature.json
- project/assets/main/creatures/primary/richie/pomodoro.json
- project/project.godot
- project/src/main/creature-library.gd
- project/src/main/global.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/chattable-manager.gd
- project/src/main/world/creature/bort.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/ebe.gd
- project/src/main/world/creature/instructor.gd
- project/src/main/world/overworld-camera.gd
- project/src/main/world/overworld-world.gd
Added 'pomodoro' dialog sequence which includes instructor.
Moved INSTRUCTOR_ID constant from creature-loader.gd to global.gd,
alongside CREATURE_ID_PLAYER. Also created a
CreatureLibrary.instructor_def field so that we can quickly grab the
instructor's name.
Minor changes to facing direction of chat participants. Intuitively, I
tried changing the characters to face 'the center of the conversation', but this
often resulted in awkward conversations where the player was facing away from
the character they were talking to.
Closes #744.
> Instructor can now participate in overworld chats.

- project/assets/main/creatures/primary/boatricia/creature.json
- project/assets/main/creatures/primary/ebe/creature.json
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/chattable-manager.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/overworld-camera.gd
- project/src/main/world/overworld-world.gd
Fixed bug with the wrong dialog showing on the overworld when you selected
the 'level 1'/'level 2'/'chit chat' options.
Fixed bug with facial expressions no longer working.
These two bugs were caused because ChattableManager was loading all of the
creatures on _ready(), but it's an autoload node which will only be loaded
once. This meant it would work OK if Overworld.tscn was loaded directly,
but didn't work when the game was launched normally through the title
screen.
Closes #750.
Fixed bug where arms/legs pointed the wrong way if you talked to a character
walking backwards. This is because the 'idle-nw' animation overrode the newly
set arm and leg frames.
Closes #751.
> Fixed bugs in overworld dialog, limbs

- project/project.godot
- project/src/main/player-data.gd
- project/src/main/player-save.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/level-select/level-library.gd
- project/src/main/ui/level-select/level-select.gd
Other classes and logic need to know things like 'which levels does the
player have unlocked' outside of the level select UI, and it makes sense
for this to be a singleton node so we don't need to reload the JSON
everywhere.
Fixed potential tutorial bug. There was some logic setting the tutorial world to
LevelLock.STATUS_CLEARED (1) if all levels in the tutorial were complete.
However, tutorial worlds don't use this particular enum, and it resulted in the
tutorials being marked as LockStatus.LOCK (1) instead.
> Extracted LevelLibrary. Fixed possible 'inaccessible tutorial' bug.

- project/src/main/ui/overworld-ui.gd
- project/src/main/ui/scene-transition-rect.gd
- project/src/main/world/overworld-bg.gd
Many UI components had listeners to refresh their screen size when aspect
ratios changed, but they didn't have code to set their screen size
initially. I've moved this functionality into several
'_refresh_screen_size' methods which are called on _ready.
> Fixed layout issues with tall aspect ratios

- project/project.godot
- project/src/main/breadcrumb.gd
- project/src/main/global.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/ui/scene-transition-rect.gd
- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/OverworldObstacles.tscn
- project/src/main/world/OverworldUi.tscn
- project/src/main/world/chat-icons.gd
- project/src/main/world/chattable-manager.gd
- project/src/main/world/creature/bort.gd
- project/src/main/world/creature/ebe.gd
- project/src/main/world/creature/sensei.gd
- project/src/main/world/overworld-camera.gd
- project/src/main/world/overworld-world.gd
Nodes now use OverworldUi dependency instead of OverworldUiLayer dependency.
This dependency is referenced with a global utility function
(Global.get_overworld_ui) instead of complex relative paths (../../../Ui)
ChattableManager.clear() is now handled with a breadcrumb listener. Ideally this
would be with a scene_changed signal on the node tree, but the node tree does
not provide signals like that.
Fixed oversight where sensei was not purged from ChattableManager.
> Overworld refactorings; OverworldUi scene, simpler paths.

- project/project.godot
- project/src/main/puzzle-connect.gd
- project/src/main/puzzle/PuzzleTileMap.tscn
- project/src/main/puzzle/box-builder.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/piece/PuzzleCornerMap.tscn
- project/src/main/puzzle/piece/puzzle-corner-map.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/puzzle/squish-map.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/main/ui/chat/chat-history.gd
- project/src/main/ui/chat/chat-library.gd
Changed 'never had this conversation' logic to return 99999999 instead of
-1. Returning a very large number lines up with the rest of the logic so
that we don't need a third branch.
Extracted common 'creature chat state' logic a little. More work could be
done here but this is a start.
PuzzleConnect and PuzzleCornerMap were originally developed as generic class,
but after becoming aware of autotiling and TileSet.BIND_TOP constants, these are
more specialized than I thought. I've renamed and commented them to make that
more apparent.
> Chat refactorings. PuzzleConnect/PuzzleCornerMap.

- project/assets/main/creatures/primary/boatricia/creature.json
- project/assets/main/puzzle/levels/cutscenes/boatricia1.json
- project/assets/main/puzzle/levels/cutscenes/boatricia2.json
- project/assets/main/puzzle/levels/cutscenes/five-customers-no-vegetables.json
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-everyone.json
- project/assets/main/puzzle/worlds.json
- project/src/demo/world/CutsceneDemo.tscn
- project/src/demo/world/cutscene-demo-fatness.gd
- project/src/demo/world/cutscene-demo.gd
- project/src/main/creature-library.gd
- project/src/main/global.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/puzzle/level/level.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/level-select/level-library.gd
- project/src/main/ui/level-select/level-lock.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/OverworldObstacles.tscn
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/player.gd
- project/src/main/world/overworld-world.gd
- project/src/test/ui/chat/test-chat-library.gd
Cutscenes can take place indoors or outdoors. Added logic for spawning
cutscene characters at different locations.
Level dialog used to be attached to creatures who had specific logic for
'use this dialog for level 1, this dialog for level 2.' This logic is now
implicit, and level dialog is in /assets/main/puzzle/levels/cutscenes
Levels no longer have 'level numbers'. A creature used to have the idea of
their first and second level. This is now implicit based on the contents
of worlds.json and how the levels are organized.
Creature clipping is disabled during cutscene. Very, very, very fat
creatures will inevitably break cutscenes a little but it's better for it
to be cosmetic stuff (creatures clipping or looking funny) and not
functional stuff (creatures spawning out of bounds or not …
> Initial cutscene location logic. Level dialog is no longer on creatures.

- project/src/main/world/creature/creature.gd
d06c8a83 introduced a Creature.chat_selectors field, but did not populate
it appropriately in get_creature_def(). As a result the most recent chat
refactoring broke the chat selector logic, meaning special dialog would
never show up.
> Fixed bug where chat_selectors were no longer populated properly

- project/src/main/ui/chat/chat-ui.gd
- project/src/main/world/chattable-manager.gd
The logic for dialog bubbles appearing on one side or the other was broken
in 9c4c4b2f when the get_orientation function was removed. The code didn't
throw errors because ChatUi tried to invoked this function leniently using
reflection, instead of enforcing the chatter's class.
ChatUi now assumes all chatters are creatures.
> Fix bug where dialog bubbles didn't appear on the correct side.

- project/assets/main/puzzle/levels/cutscenes/marsh/hello-everyone.json
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/overworld-camera.gd
Camera zooms out further if characters are further apart. The old camera
behavior zoomed in too much which would clip characters off the top and
bottom of the screen.
Changed 'get_center_of_chatters' to 'get_chatter_bounding_box'. The
OverworldCamera needs to zoom out more if characters are further apart,
so it needs a rectangle and not just a coordinate.
Removed Shirts from 'hello everyone' scene.
> Cutscene camera improvements.

- project/src/main/ui/chat/ChatChoices.tscn
- project/src/main/ui/chat/ChatUi.tscn
- project/src/main/ui/chat/chat-choices.gd
- project/src/main/ui/chat/chat-ui.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/OverworldTouchButtons.tscn
- project/src/main/world/OverworldUi.tscn
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/player.gd
- project/src/main/world/overworld-buttons.gd
- project/src/main/world/overworld-touch-buttons.gd
Added 0.8s delay before chat choices can be picked. This avoids an issue where
the player could accidentally choose something while mashing through dialog.
Closes #799.
Restored signals for OverworldButtons, OverworldTouchButtons. Disconnecting
these signals kept the UI buttons visible during conversations and cutscenes,
allowing the player to quit or select levels while cutscenes were playing.
Closes #800. Closes #801.
Disable player input and halt their movement when the UI has focus. This
fixes some weird behavior. One example is if you were moving and a
conversation popped up, you'd keep running in that direction. Another
example is when the cell phone menu was popped up, you could navigate the
menu with the arrow keys, but if you navigated to a corner button you
could also move your …
> Fixed bugs related to overworld input, buttons, focus

- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/music-popup-tween.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/overworld-exit.gd
Overworld exits are now disabled while a conversation is going on. This
fixes a bug where talking to a creature and then walking into a restaurant
mid-conversation caused some strange behavior.
Closes #804.
Talking to a creature you've spoken to already no longer zooms the camera
in for the one-line dialog summary.
Closes #775.
If the music popup was half-way popped in and out during a scene change,
it froze in that half-popped state. The MusicPopupTween now tracks its
state and restores its tweens and timers when it re-enters the scene tree.
Closes #764.
> Bug fixes: mid-chat exit, repeat chat zoom, music popup

- project/src/main/ui/MusicPopup.tscn
- project/src/main/ui/music-popup-tween.gd
Fixed bug: The puzzle buttons such as the 'Start' button became unclickable if
the music popup interrupted while popping in and out.
Fixed bug: The music popup didn't always appear. Sometimes the popout
function would be called 3-4 times in a row because the same yield()
statement was called multiple times while navigating menus.
These bugs were introduced by the code changes in 810625c which tried to
preserve the music popup's state across scenes. I've made this logic more
robust.
> Fixed music popup bugs introduced in 810625c

- project/assets/main/creatures/secondary/rhonk.json
- project/assets/main/puzzle/levels/marsh/hello-everyone.json
- project/assets/main/puzzle/worlds.json
- project/src/main/puzzle/combo-tracker.gd
- project/src/main/puzzle/level/combo-break-rules.gd
- project/src/main/puzzle/level/level.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/level-select/level-lock.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/idle-timer.gd
- project/src/main/world/letter-projectile.gd
- project/src/main/world/restaurant/RestaurantScene.tscn
- project/src/main/world/restaurant/chef-camera-mover.gd
- project/src/main/world/restaurant/restaurant-scene.gd
Added customer_ids property to worlds.json, so the level can have a
different character and customer. Not all levels will involve serving the person
you talk to; sometimes you'll talk to employees, or someone will want you to
cater for their friends.
Added weight_gain_scale, metabolism_scale settings. Rhonk gains weight very
slowly and sheds weight very quickly. This is for thematic reasons.
Changed combo_break rule logic so that a value of 999,999 disables combo breaks
entirely. Previously, it was technically possible for someone to break
their combo by dropping 1,000,000 pieces, if they were willing to play the
same level for a week.
combo_break 999,999 rule now includes a special case, just in case the
player actually drops 1,000,000 pieces (!?)
Scenarios can have different chefs, as …
> Scenarios support chefs, customers. Added customer metabolism

- project/assets/main/puzzle/levels/cutscenes/marsh/hello-bones-100.json
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-shirts-000.json
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-skins-100.json
- project/assets/main/puzzle/worlds.json
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/OverworldObstacles.tscn
- project/src/main/world/chattable-manager.gd
- project/src/main/world/overworld-world.gd
Added 'creature-exit' cutscene metadata
Cutscene logic removes creatures from the tree to avoid a scenario
where a creature like 'bones' in a cutscene had queue_free() called, and
then the freed creature was manipulated in the cutscene.
Fixed bug with overworld camera where it would recalculate the bounding
box every frame, because the new enlarged bounding box didn't match the
calculated box.
Fixed bugs with intro-less scenarios, visible cutscene bubbles
'set_focus_enabled' emits signals appropriately
Removed orphaned import files.
Fixed crash/name when talking to crystal.
> New 'hello' cutscenes.

- project/src/main/ui/CreatureStressTest.tscn
- project/src/main/ui/creature-stress-test.gd
- project/src/main/ui/fps-label.gd
- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/main-menu-debug.gd
Added creature stress test which allows developers to measure the
performance impact of adding more and more creatures. This stress test
can be launched from the main menu in debug builds.
get_frames_per_second returns a float, but it is always an integer
value. It was unnecessary to always show '60.00 fps' so now this is
instead shown as '60'
> Added creature stress test. FPS displayed as integer.

- project/src/demo/localization-demo.gd
- project/src/demo/world/cutscene-demo.gd
- project/src/main/editor/creature/creature-editor-nametags.gd
- project/src/main/old-save.gd
- project/src/main/puzzle/level/piece-type-rules.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/string-utils.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/world/overworld-world.gd
- project/src/main/world/restaurant/restaurant-scene.gd
- project/src/test/test-string-utils.gd
ChatLibrary now exposes 'has_preroll', 'has_postroll' functions. This
prevents redundant warnings and avoids the need for a warning toggle.
Extracted constants for preroll/postroll cutscene suffixes.
Added StringUtils.default_if_empty function. Replaced StringUtils.remove_start,
StringUtils.remove_end with Godot's trim_prefix, trim_suffix functions.
> Refactorings: preroll/postroll, StringUtils functions.

- project/src/main/creature-library.gd
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/editor/creature/tweak-name-row.gd
- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/main-menu-create.gd
- project/src/main/ui/menu/main-menu-play.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/creature/creature.gd
Lots of code wanted to derive short_names and ids from creature_name, so
this is now a function on Creature and CreatureDef.
Split create and play scripts from main-menu.gd. This seems unnecessarily
modular, but it's consistent with the debug and settings panel.
> Extracted new Creature.rename() function. Split up main menu script.

- project/src/main/world/chattable-manager.gd
- project/src/main/world/creature/creature-animations.gd
There was a bug where if you stepped on an exit and started a chat, the
game wouldn't let you talk to anyone. This exposed two problems.
1. ChattableManager wasn't fully resetting its state when exiting a
scene. I've modified it to flush the 'focus_enabled' and
'creatures_by_id' properties the same way it flushes the others.
2. ChattableManager wasn't preventing chat interactions during scene
changes. I've connected it to a signal so that scene transitions
block the player from interacting with stuff.
Closes #834.
> Fixed bug when starting a chat after using an exit

- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldUi.tscn
The viewports used to be huge and scaled down, which looked nicer at
higher resolutions. But it makes the game run much slower, especially on
mobile devices.
> Smaller overworld viewports.

- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/body.gd
- project/src/main/world/creature/creature-sfx.gd
- project/src/main/world/creature/creature.gd
Surprisingly, despite the fact that these body lines and polygons are rarely
drawn, disabling anti-aliasing improves FPS by about 20%.
Moved Hop/Bonk sfx under CreatureSfx node. It makes sense for these sfx
to be siblings.
> Disabled anti-aliasing for body lines. Moved hop/bonk sfx.

- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
- project/src/main/ui/settings-language.gd
Fixed 'mega_pause_charaters' typo. This method was renamed to
mega_lull_characters but the reference was not changed. The result was
that triggering the tutorial easter egg would make the tutorial
unfinishable.
Fixed bug where unsupported locale caused menu to be inconsistent.
Specifically, when testing the game my locale was 'en_US' but this did
not match our supported locale of 'en', so it set the selected language
menu item to 'Spanish' even though the game was displayed in english.
The game now matches 'en' to the locale 'en_US', and 'es' to the local
'es_MX' in the settings menu. It does this with an algorithm similar to
the algorithm used by Godot for locale matching.
> Fixed localization bugs: tutorial, fuzzy match

- project/src/main/puzzle/puzzle-tile-map.gd
puzzle-tile-map.gd was throwing an error because corner_map wasn't assigned
before set_block() and clear() were invoked
> Fixed level editor NPE in puzzle-tile-map.gd

- project/src/main/music/music-player.gd
- project/src/main/music/music-transition.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/menu/splash-screen.gd
The music fade in/fade out logic introduced in c3074853 conflicted with
the logic in MainMenu.tscn for playing music. Sometimes both scripts
would try to play music at once.
I fixed this in a few places. MusicPlayer now stops any existing 'fade
in' tween when playing a new song. MusicTransition will no longer try to
fade in a song more than once. Scenes which play music now check
MusicTransition for a conflict. Any one of these would have been
sufficient to address the bug, but they all could cause problems.
> Fixed bug in music transitions where two songs could play

- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/menu/splash-screen.gd
Before, the game would briefly show the main menu when launching the
first tutorial. Now, splash screen goes to the tutorial directly.
Before, the 'Back' button would briefly change to 'Continue' when you
clicked it upon finishing a tutorial. It no longer changes.
> Fixed 'fade out' tutorial bug, back button bug.

- project/src/main/gameplay-settings.gd
- project/src/main/puzzle/piece/ghost-mover.gd
- project/src/main/ui/scene-transition.gd
Toggling the ghost piece in the middle of a puzzle caused some unusual
behavior. The shadow offset would retain the value for the most recent
shadow piece. So the ghost piece stuck around, it was just in a silly
place. We now enable/disable the ghost piece correctly and respond to
the player changing their settings mid-puzzle.
Closes #853.
Fixed a bug where clicking 'Play' while the splash screen was still
fading in resulted in all the subsequent menus fading in and out as
well.
> Fix ghost piece toggle bug, splash fade bug.

- project/src/main/editor/creature/CreatureEditor.tscn
- project/src/main/world/creature/creature.gd
Creatures who had eaten showed up in the creature editor as very fat,
and would grow and shrink. The creature editor now ignores any extra
fatness from food they've eaten.
Closes #856.
> Fixed bug with editing creatures who'd eaten.

- project/src/main/gameplay-settings.gd
- project/src/main/packed-sprite.gd
set_frame() frequently gets called with the current frame, triggering
unnecessary calls to update() and _draw(). PackedSprite now ignores
these redundant calls, granting a 6% increase in performance when
drawing large numbers of creatures.
GameplaySettings.from_json_dict now correctly emits a ghost_piece_changed
signal.
> PackedSprite no longer redraws after redundant setter calls.

- project/src/main/world/creature/creature.gd
ChatIconHook and CollisionShape2D require a CreatureVisuals reference to
position and size themselves. This reference was broken during the
recent 'low quality creature visuals' change, so the chat icons would
always be in the same place, and fat creatures would still have small
hit boxes.
Closes #861.
> Restored broken creature_visuals listeners.

- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/screwport-texrect.gd
When the window had a very small aspect ratio like 1:30,
ScrewportTexRect used to resize itself to a very wide size such as
(15,000, 30) which caused rendering problems. It now consistently
resizes itself to the size of the screen, adjusting the scale of the
items in the viewport to compensate.
Closes #733.
> Fixed rendering issues with very, very wide aspect ratios.

- project/src/main/puzzle/food-items.gd
When resizing the game window, the mouth position needs to be adjusted
based on the top-level viewport
> Fixed mouth positioning bug when resizing game

- delint.sh
- project/project.godot
- project/src/main/puzzle/food-items.gd
- project/src/main/ui/wallpaper/wallpaper-border.gd
Added fix for NPE when food items were deleted at unexpected times
As of Godot 3.3, this wallpaper sprite bug does not appear to be an
issue. Or, it's transient and I can't figure it out. It happened this
morning after the 3.3 upgrade, but after restarting Godot it hasn't
happened again -- even if I remove the invisible textlabel which was the
workaround for older Godot versions.
> Enabled vsync. Food NPE fix. Removed wallpaper kludge.

- project/assets/main/creatures/sensei/creature.json
- project/src/main/puzzle/frame-drops-label.gd
- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/rainbow-metaball.shader
- project/src/main/puzzle/texture-metaball.shader
- project/src/main/world/creature/creature.gd
- project/src/main/world/goop-ground.shader
Removed/relocated specialized sensei weight gain logic. Sensei's lack of weight
gain is now handled by the 'weight_gain_scale' field. Other creatures
can be configured to not gain weight as well.
Creatures now fade in during scene transitions. This hides visual
artifacts as their body parts load.
Renamed 'perlin_noise' function to 'get_noise_2d'. We no longer use perlin
noise, and instead use OpenSimplexNoise, so the old name was inaccurate.
'get_noise_2d' is a function in noise_texture so it seems like a consistent
name choice.
Resolved warnings. Prefixed shadowed parameters with 'in_' prefix.
> Sensei weight gain. Creature fading. Noise renames. Warnings.

- project/project.godot
- project/src/demo/world/cutscene-demo.gd
- project/src/main/creature-library.gd
- project/src/main/editor/puzzle/editor-json.gd
- project/src/main/editor/puzzle/editor-playfield.gd
- project/src/main/editor/puzzle/level-chunk-control.gd
- project/src/main/editor/puzzle/piece-chunk.gd
- project/src/main/old-save.gd
- project/src/main/puzzle/level/blocks-start-rules.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/piece/next-piece-display.gd
- project/src/main/puzzle/piece/next-piece.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/piece-type.gd
- project/src/main/puzzle/piece/puzzle-corner-map.gd
- project/src/main/puzzle/puzzle-tile-map-reader.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/string-utils.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/scene-transition.gd
- project/src/main/world/environment/obstacle-map-shadows.gd
- project/src/main/world/goop-ground-map.gd
- project/src/main/world/overworld-corner-map.gd
Extracted 'rotate piece' logic into PieceType.
Extracted 'underscores_to_hyphens' utilities. These are one-liners, but
we may eventually move away from hyphenated filenames in which case it will be
nice having this logic centralized.
Extracted PuzzleTileMapReader.
Changed 'tile map' to 'tilemap' to conform to Godot's documentation.
SceneTransition stores a FuncRef instead of a method name.
> PieceType.rotate_piece, underscores_to_hyphens, PuzzleTileMapReader

- project/src/main/puzzle/food-item.gd
- project/src/main/puzzle/food-items.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
The old starting customer logic had conflicting logic in the RestaurantView and
Puzzle scripts. 'Puzzle' would reload all the new creatures, and then
'RestaurantView' would try to scroll to a new creature if they had been fed, but
since all creatures had just been reloaded, it would always just scroll to a new
creature.
The new starting customer logic is more robust, and handles edge cases
such as restarting a puzzle when no creatures have been fed, restarting
a story puzzle when the camera is on the starting creature, and so on.
FoodItems target calculations are now cached, instead of being
recalculated 20 times for 20 different food items. They're all going to
the same location so it's silly to perform multiple lerps/transforms
over and over to get the same answer.
> Improve starting customer logic, food targeting efficiency

- project/project.godot
- project/src/main/puzzle/crumb-cluster.gd
- project/src/main/puzzle/food-crumbs.gd
- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/piece/piece-dropper.gd
- project/src/main/puzzle/piece/piece-mover.gd
- project/src/main/puzzle/piece/piece-speeds.gd
- project/src/main/puzzle/piece/squish-fx.gd
- project/src/main/puzzle/squish-map.gd
Initializing the first crumb cluster sometimes causes a performance hiccup. I've
introduced a pool so that this hiccup occurs on load, rather than during
gameplay.
Squish moves trigger DAS. This fixes misdrops related to rocket drops,
which occurred when trying to squish a piece into a nook while playing
quickly or during 20G.
> Avoid crumb performance hiccup. Squishes trigger DAS.

- project/src/main/world/creature/dna-utils.gd
- project/src/main/world/goop-ground-map.gd
- project/src/main/world/screwport-texrect.gd
The goop viewport adjustment was consistently a frame behind any camera
movement, making the goop and textures drift around if you paid close
attention.
Birds can no longer have 'iguana nose'. This was accidentally omitted
from the list of bad body part combos.
> Added fix for lagging viewport glitch. Iguana nose fix.

- project/src/main/world/Overworld.tscn
I experimented with many parameters and settings to try and measure and
mitigate stutter. This stutter is not caused by the camera, but having a
slow camera smoothing seems to make it more noticable. (It's possible
the difference is all in my head.)
> Adjusted camera smoothing speed to mitigate stutter.

- project/src/main/world/creature/MovementPlayer.tscn
- project/src/main/world/creature/creature-animations.gd
If your character was heavy enough to do the bipedal running animation,
their head would stop bobbing after you sat still. I've added some
head_bob_mode keys to the idle animations so that the head bob will be
restored.
> Fixed bug where head would stop bobbing sometimes

- project/src/main/puzzle/puzzle.gd
This regression was introduced in 22f4e7a0. Restarting a puzzle
restores a creature's fatness, but this logic shouldn't be applied to
the tutorial creature who has no fatness.
> Fixed 'missing sensei fatness' error when starting new game

- project/assets/main/creatures/primary/boatricia/creature.json
- project/project.godot
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/level/level-history.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/chat/chat-bool-evaluator.gd
- project/src/main/ui/chat/chat-bool-parser.gd
- project/src/main/ui/chat/chat-history.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/level-select/level-info-panel.gd
- project/src/main/ui/level-select/level-library.gd
- project/src/main/ui/menu/splash-screen.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/chattable-manager.gd
- project/src/test/test-backwards-compatible.gd
- project/src/test/ui/chat/test-chat-bool-evaluator.gd
- project/src/test/ui/chat/test-chat-bool-parser.gd
- project/src/test/ui/chat/test-chat-library.gd
Chat 'skip_if' conditions are evaluated. This supports boolean operators
like 'and', 'or' and 'not'. It also supports order of operations and
parentheses.
This new conditional logic has been pushed to the chat selectors as
well. Instead of an array of simple if_conditions, it now supports a
single complex if_condition which accepts boolean operators.
LevelHistory.reset() clears successful_levels, finished_levels. Failing
to clear these was resulting in unpredictable unit tests
Added is_level_finished() utility method
> Added 'skip_if' to cutscenes, chat library.

- project/assets/main/puzzle/worlds.json
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/level-select/level-library.gd
- project/src/test/ui/chat/test-chat-library.gd
Replaced 'if_condition' with 'available_if'. The term if_condition is woefully
ambiguous when there are multiple conditional statements.
Added missing creature_id entries in worlds.json. This should allow
more levels to be available when walking around on the overworld.
> Added missing level creature_ids. if_condition -> available_if.

- project/assets/main/puzzle/levels/cutscenes/marsh/hello-bones-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-shirts-000.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-skins-100.chat
- project/assets/main/puzzle/worlds.json
- project/src/test/ui/level-select/test-level-library.gd
Added prioritized_if/skip_if flags to Merrymellow Marsh levels. The
cutscenes are prioritized when they're next in sequence, and skipped if
the player's past that point in the story.
Level sequence changes; only need to complete about 70% of the
Merrymellow Marsh levels
Set creature id to richie for marsh cutscenes. Without a creature_id,
these cutscenes cannot be accessed outside of the phone menu.
> Merrymellow Marsh sequence changes.

- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/creature/sensei.gd
- project/src/main/world/overworld-camera.gd
- project/src/main/world/overworld-world.gd
Moved cutscene camera lower. The dialog bubbles were hiding the creatures.
Fix cutscene camera bug for levels with no creature. The 'no creature'
creature would be spawned at a default location and the camera would
struggle to keep them in frame.
Creatures no longer turn left and right during cutscenes. This was
resulting in unnatural behavior where, in a group of 5 creatures, they would all
face the player even when someone else was talking.
The sensei and player orient correctly during conversations between the player
and the sensei. The 'calculate the midpoint of the chatters' logic was not
behaving correctly when they were the only ones talking.
Sensei no longer follows player during cutscenes
Fixed bug where cutscenes would dump player back to the title screen
after a puzzle, if the …
> Cutscene camera, orientation fixes.

- project/assets/main/puzzle/levels/cutscenes/marsh/hello-everyone-000.chat
- project/src/demo/world/CutsceneDemo.tscn
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/overworld-camera.gd
Creatures entering or exiting a cutscene now launch a tween which smoothly moves
the camera instead of lerping. The previous lerp effect caused the camera to
leap into motion which was unpleasant.
Cutscene camera zooms and pans slower than before. The rapid zooming and
panning was also unpleasant.
Better camera adjustments for fat creatures. Camera is adjusted vertically to
keep fat creature's faces in frame. Camera is zoomed out when fat creatures are
in a cutscene, this logic was accidentally removed in f0f31d1
hello-everyone-000 cutscene no longer fades in three creatures on the
first line of dialog. This was unnoticable, but resulted in the camera
(correctly) zooming in on just the two visible creatures, and pulling out to all
five creatures, which looked strange.
> Smoother cutscene cameras. Better camera adjustments for fat creatures.

- project/assets/test/ui/chat/chat-newlines.chat
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/test/ui/chat/test-chatscript-parser.gd
Godot's JSON parser automatically translates '\n' into newlines in
strings, but my Chatscript parser did not do this.
> Chatscript handles '\n' characters.

- project/src/main/ui/overworld-ui.gd
- project/src/main/world/overworld-camera.gd
The camera tween now follows the player when they exit a conversation.
Before, the camera would tween to the player's previous position, and
then snap to them if they moved. This resulted in an awkward behavior
where they could run almost off the screen, and then the camera would
jolt over to them.
Chat icons no longer reappear at the end of a cutscene. This was
especially strange when characters had left a chat, as it resulted in a
floating chat icon with no target.
> Camera tween follows player. No chat icons in cutscenes.

- project/assets/main/creatures/secondary/tunathy.json
- project/src/main/editor/puzzle/LevelEditor.tscn
- project/src/main/puzzle/piece/next-piece-display.gd
This crash occurred when the next piece display needed to display a
'null piece'. The null piece check was not properly changed after the 'next
pieces can rotate' gimmick was implemented.
New creature: Tunathy
> Fixed crash in 'only drop X pieces' levels

- delint.sh
- project/src/main/world/creature/creature-animations.gd
- project/src/main/world/creature/dna-loader.gd
- project/src/main/world/creature/emote-player.gd
delint.sh now sorts signal connections. By default Godot shuffles signal
connections randomly, and sometimes randomly drops signal connections as
well. This makes it easy to accidentally remove signals, and for those
deletions to be obfuscated in a huge sea of changes. Alphabetizing the
list should give us a chance to catch those kinds of bugs during code
review.
The 'reset_creature' option in CreatureVisuals.tscn now resets their
colors, shader parameters, and emote positions. This cuts down on
unnecessary noise during commits involving the CreatureVisuals class.
Delint.sh now uses bash script instead of shell script. In POSIX sh,
proecss substitution is undefined.
> Sort signal connections. Reset creature colors, emote positions

- project/assets/main/creatures/primary/boatricia/creature.json
- project/src/demo/ui/chat/chat-frame-demo.gd
- project/src/demo/world/cutscene-demo.gd
- project/src/main/keybind/keybind-manager.gd
- project/src/main/puzzle/chalkboard.gd
- project/src/main/puzzle/frame-drops-label.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/piece/next-piece-displays.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/puzzle-trace.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/fps-label.gd
- project/src/main/ui/level-select/LevelSelectPanel.tscn
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/level-select/level-select.gd
- project/src/main/ui/menu/settings-menu.gd
- project/src/main/ui/overworld-ui.gd
- project/src/test/ui/chat/test-chat-library.gd
Replaced '!' operator with 'not'. GDScript guidelines recommend plain english
versions of operators.
level-select.gd now references its LevelButtons instance with a NodePath. This
requires more code but prevents things from breaking when reorganizing
the node tree.
Removed vestigial 'creature_chat_state' from ChatLibrary. The 'notable'
and 'level_id' functionality were moved into other places, so we were just
passing around a dictionary with a creature_id.
Minor tweaks to ChatLibrary to ensure focused_chattable_chat_tree() is
not invoked when starting a level. This prevents creatures from making
incongruent chit chat before their level is launched.
Changed CurrentLevel.push_cutscene_trail() to push_preroll_trail() to
make its purpose more clear.
Fixed boatricia's chat tree to use …
> Refactor: '!' -> 'not'. LevelSelect nodepath. ChatLibrary 'state' dict.

- project/src/demo/DemoSave.tscn
- project/src/demo/demo-save.gd
- project/src/demo/world/CutsceneDemo.tscn
- project/src/demo/world/cutscene-demo-flags.gd
- project/src/demo/world/cutscene-demo-open.gd
- project/src/demo/world/cutscene-demo.gd
Added 'flags' field to CutsceneDemo. This allows developers to specify
things like 'chat_finished foo' 'not level_finished bar' to test
cutscenes under specific circumstances.
CutsceneDemo stores its state using a new 'DemoSave' script. This script
is generic and can save state for other demos as well.
> CutsceneDemo improvements; 'flags', save state

- delint.sh
- project/src/main/world/OverworldUi.tscn
- project/src/test/ui/chat/test-chatscript-parser.gd
The overworld labels now stay in corners when the game is resized.
Before they would stay towards the center of the screen.
> Overworld labels stay in corners.

- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/Overworld.tscn
- project/src/main/world/environment/ButtercupSign.tscn
- project/src/main/world/environment/MarshCrystal.tscn
- project/src/main/world/overworld-world.gd
Fixed bug where certain filler chats would never play because the logic
was checking for '-1' instead of 'CHAT_AGE_NEVER'
Fixed bug where creatures didn't face each other during locationless
cutscenes, such as Boatricia's 'real meal' cutscene
Overworld obstacle scenes (ButtercupSign, MarshCrystal) are positioned at 0,0
instead of an arbitrary overworld coordinate
> Boatricia filler, facing fixes. Obstacle coordinates.

- project/project.godot
- project/src/demo/world/cutscene-demo.gd
- project/src/main/misc-settings.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/level/levels.gd
- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/puzzle/start-end-sfx.gd
- project/src/main/ui/cutscene-button.gd
Other classes depend on the CutsceneState enum. These classes introduce cyclic
dependencies with an upcomic CutsceneManager enhancement. Introducing a
static Levels class to house level-related enums resolves these cyclic
dependency issues.
> Extracted Levels from CurrentLevel to avoid cyclic references

- project/project.godot
- project/src/demo/world/cutscene-demo.gd
- project/src/main/breadcrumb.gd
- project/src/main/ui/chat/chat-history.gd
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/creature/Mouth7Player.tscn
- project/src/main/world/creature/creature.gd
- project/src/main/world/environment/overworld-obstacle.gd
- project/src/main/world/environment/stool.gd
- project/src/main/world/overworld-world.gd
- project/src/test/ui/chat/test-chat-history.gd
- project/src/test/ui/chat/test-chatscript-parser.gd
Fixed bug where angry turtles would continue opening/closing their mouths after
speaking because of some bad animation keys.
Fixed bug where creatures who were supposed to not be present at the
start of a cutscene were still shown. This was inadvertently broken when
adding a 'fade in' effect to creatures as the world was loaded.
Fixed bug where 'player' and 'sensei' could not make use of the mood
metadata during cutscenes. Their names were not translated into the
placeholder '#player#' and '#sensei#' values.
Moved 'history_key_from_path' method from ChatscriptParser into ChatHistory.
Overworld is now given a default breadcrumb trail if the scene is loaded
directly. Without this, the cutscene pushing/popping logic would
sometimes cause the game to quit or error during development, because …
> Turtle/cutscene bugs. ChatHistory utilities. Breadcrumb fixes.

- project/assets/main/chat/meet-the-competition.chat
- project/assets/main/creatures/primary/diota/creature.json
- project/assets/main/creatures/primary/diota/hard-times.chat
- project/src/demo/world/cutscene-demo.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/Overworld.tscn
- project/src/main/world/environment/ButtercupSign.tscn
- project/src/main/world/environment/MarshCrystalForSign.tscn
- project/src/main/world/environment/buttercup-sign.gd
- project/src/main/world/environment/marsh-crystal-for-sign.gd
Added Diota's 'hard times' cutscene dialog, including logic for having
the bush get cut and the sign changing its description.
Added logic where cutscenes can be 'inplace', which means they do not
require a scene change.
> 'hard times' cutscene. Bush gets cut. Inplace logic.

- delint.sh
- project/src/demo/world/cutscene-demo.gd
- project/src/main/ui/chat/chat-event.gd
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/cutscene-manager.gd
- project/src/test/ui/chat/test-chat-history.gd
Cutscene queueing logic. Chatscript now supports 'next scene foo' to
queue up a cutscene.
Creatures don't face eachother during thoughts. This avoids an odd
circumstance where you think 'i shouldn't disturb this customer' but they turn
to face you anyways.
> Cutscene queuing. Creatures don't reorient for thoughts.

- project/src/main/world/creature-spawner.gd
- project/src/main/world/creature/creature-collision-shape.gd
- project/src/main/world/creature/player.gd
It makes sense they should increase, but this causes bugs when they can't sit on
certain seats anymore. It means there are edge cases where certain areas
work fine for skinny NPCs, but they appear glitchy or block player
access when NPCs gain weight.
> Creature collision shapes no longer increase as they get fatter.

- project/assets/main/chat/meet-the-competition.chat
- project/assets/main/creatures/primary/diota/hard-times.chat
- project/assets/main/creatures/primary/diota/having-trouble.chat
- project/assets/main/creatures/primary/jayton/soliciting-buttercup-customers-2.chat
- project/assets/main/creatures/primary/jayton/soliciting-buttercup-customers.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/goodbye-bones-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/goodbye-shirts-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/goodbye-skins-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-bones-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-everyone-000.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-everyone-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-shirts-000.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/hello-skins-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/lets-all-get-merry-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-bones-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-everyone-000.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-everyone-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-shirts-100.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-skins-100.chat
- project/assets/test/ui/chat/chat-condition.chat
- project/assets/test/ui/chat/chat-newlines.chat
- project/assets/test/ui/chat/cutscene-full.chat
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/cutscene-manager.gd
- project/src/test/ui/chat/test-chatscript-parser.gd
Chatscript was mixing snake case, kebab case and multiple words in
different contexts. Things like 'next scene', 'link_if' and
'part-2' were all inconsistent with each other. It now uses snake case
consistently.
Snake case is preferable because our JSON uses snake case. Chatscript
derives from (and gets translated to) JSON.
Changed spawn IDs to use underscores too. This is consistent with our
creature IDs (and our JSON conventions.)
> Chatscript uses snake case - not kebab case, not multiple words.

- project/assets/test/turbofat-2783.json
- project/project.godot
- project/src/main/old-player-save.gd
- project/src/main/player-data.gd
- project/src/main/player-save.gd
- project/src/main/rolling-backups.gd
- project/src/main/ui/chat/chat-history.gd
- project/src/test/test-old-player-save.gd
- project/src/test/test-player-save.gd
- project/src/test/test-rolling-backups.gd
PlayerData now tracks seconds played.
Restored 199c backwards compatibility tests. These were inadvertently
removed in cd7cb49a
Fixed 'float to int' errors stemming from chat history. ChatHistory was
saving/loading ints from JSON, but Godot's JSON parser converts all
numeric in JSON to floats. ChatHistory now explicitly converts these to
ints.
Renamed test-backwards-compatible.gd to test-old-player-save.gd
Updated data version to 27bb
> Save improvements: seconds played, 199c compatibility, float to int

- project/src/main/ui/SettingsMenu.tscn
- project/src/main/ui/menu/settings-menu.gd
- project/src/main/world/environment/MarshCrystalSpawner.tscn
- project/src/main/world/obstacle-map.gd
Fixed bug where obstacle-map.gd was not clearing invisible obstacles
appropriately.
Made SettingsMenu invisible again, including its new dialogs. If it's
visible it makes it hard to edit scenes which use a settings menu.
Fixed scale of marsh crystal spawners (in editor). The spawners were
slightly smaller than actual crystals resulting in a mismatch when
starting the game, and also making the overworld look strange in the
editor as different crystals were different sizes.
> Overworld bugs: impassable tiles, settings visible, spawner scale

- project/src/demo/localization-demo.gd
- project/src/demo/ui/chat/chat-frame-demo.gd
- project/src/demo/world/cutscene-demo.gd
- project/src/main/creature-library.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/chat/ChatUi.tscn
- project/src/main/ui/chat/chat-frame.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/chat/chat-line-panel.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/chat/chat-ui.gd
- project/src/main/ui/chat/touch-translator.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/OverworldUi.tscn
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/player.gd
- project/src/main/world/cutscene-manager.gd
Replaced ChatUi's 'pop_out_completed' signal with 'chat_finished'
signal. Its windows popping in and out is sort of a UI detail, callers care
about the chat ending.
Extracted ChatLibrary.chat_tree_for_key method from CutsceneDemo. Renamed
ChatLibrary's chat_tree_for_chat_id method to be creature specific. A 'chat_id'
sounds like it could maybe be comparable to a history_key, but they're not the
same. The new method names make this slightly more evident.
Renamed ChatFrame.chat_window_showing to is_chat_window_showing to adhere to
typical conventions, and for consistency with ChatFrame.is_all_text_visible
Split up OverworldUi.start_chat method and added comments around some unusual
code.
Changed CreatureVisuals.southeast_dir from an export variable to a
constant. I don't think anyone will …
> Chat/cutscene refactorings, method renames.

- project/src/main/world/creature/sensei.gd
Fat Sensei's movement logic was confusing non_iso and iso directions causing
them to move the wrong way sometimes.
> Fixed sensei isometric movement bug.

- project/src/demo/ui/chat/chat-frame-demo.gd
- project/src/main/ui/chat/chat-event.gd
- project/src/main/ui/chat/chat-frame.gd
- project/src/main/ui/chat/chat-ui.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/chattable-manager.gd
Instead of basing it on which way the creature is facing, it now
calculates the midpoint of the conversation and attaches metadata to
each ChatEvent specifying whether the nametag should appear on the left
or right.
This is more consistent. Creatures might talk to each other when they're
both walking in the same direction. Or a creature might turn left and
right during a cutscene.
> Improved left/right nametag algorithm

- project/assets/main/chat/marsh-epilogue.chat
- project/assets/main/puzzle/levels/cutscenes/marsh/pulling-for-everyone-100.chat
- project/assets/main/puzzle/worlds.json
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/level-select/level-library.gd
- project/src/main/ui/level-select/world-lock.gd
- project/src/main/ui/menu/main-menu-play.gd
- project/src/main/ui/overworld-ui.gd
Epilogue is played when the player beats the last level of Merrymellow
Marsh. Epilogue/prologue cutscene paths are defined in worlds.json.
Swapped seats for the 'pulling for everyone' cutscene so that the player
faces Bones.
> Added epilogue. Cutscene tweaks.

- project/src/main/ui/level-select/LevelSelectPanel.tscn
- project/src/main/ui/level-select/grade-labels.gd
- project/src/main/ui/level-select/level-buttons.gd
These checkmarks were erased in 39c8ba1 which changed the LevelSelect
script to load its LevelButtons once at startup. However the tutorial
selector removes and recreates all its buttons, but the LevelButtons
script did not recreate a new set of grade labels to go with them.
This new logic automatically creates/removes grade labels every time a
LevelButton is created/destroyed.
> Fixed button where tutorial selection didn't show checkmarks.

- project/src/main/ui/menu/settings-menu.gd
Deleting the current save slot now returns the player to the splash
screen with a new save. Before, it would let you continue playing on
your deleted save slot, and your deleted data would be overwritten.
Closes #1004.
> Intuitive behavior when deleting current save slot.

- project/assets/main/puzzle/levels/marsh/hello-everyone.json
- project/assets/main/puzzle/levels/marsh/hello-skins.json
- project/assets/main/puzzle/levels/marsh/pulling-for-skins.json
- project/src/demo/puzzle/level/LevelRankDemo.tscn
- project/src/demo/puzzle/level/level-rank-demo-grade.gd
- project/src/demo/puzzle/level/level-rank-demo-open.gd
- project/src/demo/puzzle/level/level-rank-demo.gd
- project/src/demo/world/cutscene-demo.gd
- project/src/main/editor/puzzle/dialogs.gd
- project/src/main/editor/puzzle/level-editor.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/test/puzzle/level/test-level-settings.gd
- project/src/test/puzzle/test-rank-calculator.gd
Created a new LevelRankDemo which can calculate appropriate values for
'extra_seconds_per_piece', 'box_factor' and 'combo_factor' based on the
player's best performance.
Fixed malformed 'extra_seconds_per_piece' parameters in level data.
Recalculated 'extra_seconds_per_piece' metadata.
Refactored LevelSettings utility methods. The old utility methods were
only used by the LevelEditor and were sort of specialized and strange.
The new utility methods should be more reusable.
> Improved rotation rank parameters. LevelRankDemo.

- project/project.godot
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/puzzle/piece/next-piece-display.gd
- project/src/main/puzzle/piece/next-piece-displays.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/rank-calculator.gd
PieceQueue was an autoload singleton to support LevelTriggerEffects,
which needed to rotate the pieces in the queue. However this sets a
difficult precedent for future effects which need to change the
active piece or add rows to the playfield. We don't want autoload
singletons for the active piece, playfield, and a hundred other
puzzle-specific things.
I've changed the design so that CurrentLevel keeps a reference to the
Puzzle scene, which contains a PieceQueue. When a puzzle is active,
LevelTriggerEffects can go through CurrentLevel to obtain references to
its piece queue, active piece, playfield, or a hundred other
puzzle-specific things.
> Removed PieceQueue autoload singleton.

- project/src/demo/puzzle/puzzle-demo.gd
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/line-inserter.gd
- project/src/main/puzzle/piece/PieceManager.tscn
- project/src/main/puzzle/piece/piece-dropper.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/piece-squisher.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/puzzle/star-seeds.gd
Inserting a new row can have many side effects, including shifting the
piece, shifting the ghost piece, changing which rows are being
deleted/shifted during a line clear, or altering the squish behavior.
These are all updated using a new 'piece_disturbed' signal.
This row insertion logic is currently only accessible through
PuzzleDemo.
> Added row insertion logic.

- project/src/main/ui/chat/ChatUi.tscn
- project/src/main/ui/chat/touch-translator.gd
Fixed bug where narration frames couldn't be skipped on Android. This
bug occurred because TouchTranslator ignored inputs unless the regular
ChatFrame was showing, but it also needs to check if the
NarrationFrame is showing.
Fixes #1023 .
> Fixed android narration frame input bug.

- project/project.godot
- project/src/main/old-player-save.gd
- project/src/main/old-system-save.gd
- project/src/main/player-save.gd
- project/src/main/save-converter.gd
- project/src/main/system-save.gd
- project/src/test/test-old-player-save.gd
All save conversion logic was doing the same logic for iterating over
save data items, converting each one, and updating the version number.
Additionally, there was redundancy where multiple places had the concept
of 'these 12 versions can be upgraded', both in the transformation logic
and the 'is old save item' checking logic.
These redundancies have been resolved by extracting a new SaveConverter
class. This class can be configured with methods to convert specific
versions of save items.
Fixed some OldPlayerSave tests, which would error (and pass!) if it
tried to assert something about an empty array
> Extracted SaveConverter from OldPlayerSave, OldSystemSave

- project/src/demo/music/music-player-demo.gd
- project/src/main/music/music-player.gd
- project/src/main/music/music-transition.gd
- project/src/main/puzzle/puzzle-music-manager.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/ui/menu/main-menu.gd
- project/src/main/ui/menu/practice-menu.gd
- project/src/main/ui/menu/splash-screen.gd
- project/src/main/ui/menu/tutorial-menu.gd
- project/src/main/world/CreatureSpawner.tscn
- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/creature-spawner.gd
- project/src/main/world/obstacle-spawner.gd
- project/src/main/world/overworld-walk-world.gd
- project/src/main/world/overworld-world.gd
Many different scripts had logic saying 'if a chill song isn't playing, fade in
a new chill song'. This logic is now centralized within MusicPlayer with a
'fade_in' parameter.
Added default overworld_world_path for spawners. This prevents us from needing
to assign it everywhere, cutting down on cruft in overworld scenes
> Refactoring: music fading, overworld_world_path

- project/src/main/editor/creature/dialogs.gd
- project/src/main/editor/puzzle/LevelEditor.tscn
- project/src/main/editor/puzzle/dialogs.gd
- project/src/main/editor/puzzle/level-editor.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/test/puzzle/level/test-level-settings.gd
When importing/exporting files, the creature editor and level editor now
remember the path which was imported and recommend to export to the same
path. This way if you want to import from File A and export to File A,
you don't need to navigate to it twice.
The level editor's 'level_key' field is no longer editable. It is for
display purposes only, and shows the path the level was loaded from.
Removed unused level editor quit code. The level editor had some edge-case code
when quitting a level. This code never seemed to execute, and was causing an
error 'Can't take value from empty array.'
> Creature/level editor path refactoring. Removed unused code.

- project/src/main/creature-library.gd
- project/src/main/editor/creature/creature-editor.gd
- project/src/main/editor/creature/dialogs.gd
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/player.gd
The player's creature_id in the save data corresponded to their name like
'gordo' or 'dusty' which could cause problems. It meant that other creatures in
the world could share their creature id. It meant the player could 'feed
themselves' and get fat.
In the spirit of refactoring week, it also meant that Creature.gd needed
some clumsy code to ask 'wait, are we loading the creature'. The
resulting code is now cleaner, as the special case code is pushed out
into special places.
> Player's creature_id is always '#player#'.

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/demo/puzzle/puzzle-demo.gd
- project/src/main/editor/puzzle/dialogs.gd
Level editor preserves dialog state when switching between
file/resource dialogs. Assigning a file dialog's path to something like
'res://' results in the dialog just getting reset to the file root 'C:\'
so it's important to globalize/localize paths.
PuzzleDemo now accepts a level resource path for quickly trying
arbitrary levels.
> LevelEditor dialog state fixes. PuzzleDemo accepts path.

- project/assets/main/puzzle/levels/experiment/004.json
- project/assets/main/puzzle/worlds.json
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/level/level-tiles.gd
- project/src/main/puzzle/line-inserter.gd
- project/src/main/puzzle/pickups.gd
- project/src/main/puzzle/playfield.gd
- project/src/test/puzzle/level/test-level-settings.gd
Pickups now appear before the player hits 'start'. StarSeeds are not
shown before the player hits 'start' because their locations are random,
but pickups are deterministic.
Removed redundant block_cells and pickup_cells LevelTiles fields. These
might make sense to restore if the order of the cells matters, but for
now i don't see a reason to keep them.
Added experiment 004 to worlds.json.
Improved failure messages for some LevelSettings tests.
> Pickups before level start. Redundant LevelTiles fields.

- project/src/main/editor/puzzle/PlayfieldEditor.tscn
- project/src/main/editor/puzzle/editor-playfield.gd
In the level editor, if you dragged some tiles into the playfield
editor, and dragged your mouse away and released the button, the tile
preview would persist forever.
I fixed the bug by adding a check for 'mouse exit'
> Fixed residual level editor drop preview bug.

- project/src/main/editor/puzzle/PlayfieldEditor.tscn
- project/src/main/editor/puzzle/editor-pickups.gd
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/pickups.gd
- project/src/main/world/CreatureSpawner.tscn
- project/src/main/world/creature-spawner.gd
'SeedPickupScene' field is now just called PickupScene to match the
Pickup.tscn filename.
CreatureSpawner's CreatureScene is now exported, instead of being
hard-coded into the script. Godot seems to play better with exported
scene files as the editor can keep them hooked up during renames.
Additionally, it's consistent with the rest of the project.
> Refactorings: SeedPickupScene, CreatureScene

- project/assets/main/puzzle/levels/experiment/005.json
- project/assets/main/puzzle/worlds.json
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/level/blocks-during-rules.gd
- project/src/main/puzzle/pickups.gd
Levels now support floating pickups which regenerate.
Pickups are no longer erased on line clear. I couldn't think of a use
case for this, and it's weird for regenerating powerups to erase.
> Different pickup modes: float, float_regen

- project/assets/main/puzzle/levels/experiment/003.json
- project/assets/main/puzzle/levels/experiment/004.json
- project/assets/main/puzzle/levels/experiment/005.json
- project/assets/main/puzzle/levels/experiment/006.json
- project/assets/main/puzzle/levels/marsh/hello-everyone.json
- project/assets/main/puzzle/worlds.json
- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/demo/puzzle/level/level-rank-demo.gd
- project/src/main/puzzle/duration-calculator.gd
- project/src/main/puzzle/level/rank-rules.gd
- project/src/main/puzzle/piece/piece-queue.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/rank-result.gd
- project/src/main/puzzle/results-hud.gd
- project/src/test/puzzle/test-duration-calculator.gd
- project/src/test/puzzle/test-rank-calculator.gd
The rank and duration algorithms now apply pickup scores. Pickup scores
can be manually applied via two new JSON tags, 'master_pickup_score' and
'master_pickup_score_per_line'
The player's pickup rank can be shown at the end of a level with the new
'show_pickups_rank' rule. There are similar rules for things like
'hide_boxes_rank' and 'hide_combos_rank'
New level: 'Just Cream'
> Pickup scores are ranked, shown. Rank screen shows/hides categories.

- project/assets/main/puzzle/levels/experiment/004.json
- project/assets/main/puzzle/levels/experiment/005.json
- project/assets/main/puzzle/levels/experiment/006.json
- project/src/demo/puzzle/level/level-rank-demo.gd
- project/src/main/puzzle/level/score-rules.gd
On a default level, an experienced player can earn ¥1000 per minute. But
on other levels, even with tons of powerups, it is difficult to score
more than ¥500 per minute. I want powerups to offset the disadvantage of
harder levels, but it is hard to do that unless they are worth more
points.
Fixed a calculation issue in LevelRankDemo. Rebalanced level rank data
for new powerup levels.
> Doubled default pickup points. Rebalanced levels.

- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/pickups.gd
In 12791c9a, pickups were modified to not erase when lines are erased.
This makes sense in most circumstances such as line clears, but during
topouts pickups need to be erased. Otherwise new pickups can spawn on
top of them.
> Pickups are erased on topout.

- project/project.godot
- project/src/main/editor/puzzle/LevelEditor.tscn
- project/src/main/editor/puzzle/editor-json.gd
- project/src/main/editor/puzzle/editor-playfield.gd
- project/src/main/editor/puzzle/level-editor.gd
- project/src/main/editor/puzzle/properties-editor-control.gd
Level editor's 'properties' tab now has a panel for the pickup score.
The player can enter a score, or click the 'calculate' button to sum up
all of the visible pickups.
Dragging from the level editor playfield will now repeat the previously
dropped item for convenience. This makes it easier to create puzzles
with tons of veggies or powerups.
> Level editor calculates pickup score. Level editor drag/drop shortcut.

- project/src/main/editor/puzzle/PlayfieldEditor.tscn
- project/src/main/editor/puzzle/editor-json.gd
- project/src/main/editor/puzzle/level-editor.gd
- project/src/main/editor/puzzle/playfield-editor-control.gd
- project/src/main/editor/puzzle/properties-editor-control.gd
The level editor could crash if you picked an alternate tiles key like
'0' and loaded another level. It now automatically loads the tiles key
'start' when loading a level.
Added small block chunks to level editor (1x2, 3x1, etc). These are
useful for decorating levels.
> Fixed alternate tiles level editor bug. New editor block chunks.

- project/src/main/puzzle/level/score-rules.gd
- project/src/main/puzzle/star-seeds.gd
Levels with zero cake/snack points will have zero wobblers. Levels with
double cake/snack points will have double wobblers.
> Wobbler count changes based on cake/snack points

- project/src/main/puzzle/piece/piece-mover.gd
This kludge was introduced in 69672802 to prevent pieces from slipping past
nooks during squish moves. I can't remember the exact circumstances where this
was frustrating, but activating DAS results in weird piece handling at times.
Performing a squish move and moving the piece into an open area makes the piece
suddenly zip across the playfield. If this 'slipping past nooks' issue is a
consistent problem we need a more specific fix for it -- perhaps something that
only activates for a frame, only activates at 20G, or something like that.
> Removed instant das squish kludge, I don't like it.

- project/src/main/puzzle/food-item.gd
- project/src/main/puzzle/food-items.gd
If a food is flying to a customer who's been replaced with the current customer,
the food now disappears. This is preferable to the previous behavior where the
food would fly to the current customer's mouth, but they wouldn't eat it.
Closes #876.
> Fixed visual bug when food flies to a customer who didn't order it.

- project/src/main/puzzle/rank-calculator.gd
- project/src/test/puzzle/piece/test-piece-kicks-jl.gd
- project/src/test/puzzle/test-rank-calculator.gd
Fixed bug where rank calculator calculated a value of '1#INF' which got
converted to JSON, but couldn't be converted back from JSON. This
occurred when calculating the log of zero. The rank calculator now
clamps the resulting rank to a value of 999.
Added tests for vee kicks which I want to implement -- but which
conflict with wall kicks and snack kicks.
> Fixed save corruption bug with pickups. Vee kick tests.

- project/src/main/puzzle/pickups.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/state-machine.gd
When topping out, the player's piece was no longer visible. This was caused by
the pickup layering changes in 54710bc3
Pickups revert from their 'food form' to their 'seed form' when
restarting a level.
> Top out layering bug. Pickups revert on restart.

- project/assets/main/puzzle/levels/marsh/pulling-for-bones.json
- project/assets/main/puzzle/levels/placeholder06.json
- project/src/main/puzzle/level/piece-type-rules.gd
Some levels defined a 'piece_start_t' property instead of
'start_piece_t'. I've fixed the levels and changed piece-type-rules to
report these typos.
> Fixed 'piece_start_t' typo in levels

- project/src/main/editor/puzzle/editor-json.gd
- project/src/main/puzzle/input-replay.gd
- project/src/main/puzzle/level/blocks-during-rules.gd
- project/src/main/puzzle/level/combo-break-rules.gd
- project/src/main/puzzle/level/level-settings.gd
- project/src/main/puzzle/level/level-trigger-effect.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/level/lose-condition-rules.gd
- project/src/main/puzzle/level/milestone.gd
- project/src/main/puzzle/level/other-rules.gd
- project/src/main/puzzle/level/phase-condition.gd
- project/src/main/puzzle/level/piece-type-rules.gd
- project/src/main/puzzle/level/rank-rules.gd
- project/src/main/puzzle/level/score-rules.gd
Changed 'from_json_string_array' methods to 'from_json_array'.
'from_json_string_array' is more informative, but we don't provide similar
granularity for other json methods. We don't have a 'from_json_dict_array'
method for LevelTriggers, or a 'from_json_string_to_string_dict' methods in a
number of places. The main reason for not calling it something super simple like
'from_json' is to clarify that this is a json object, and not a string of json
text.
Fixed 'an dictionary' typo.
Reordered LevelSettings fields. Grouped up and alphabetized 'rules
fields' together. Simpler fields like the id/title/description are up
top.
Changed some rules properties to use explicit defaults. This seems
especially helpful for enum fields like 'Milestone.type'.
> Rules refactoring: json_array, 'an dictionary', reordering

- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/level/milestone.gd
- project/src/main/utils.gd
- project/src/test/puzzle/level/test-level-trigger.gd
- project/src/test/test-utils.gd
These utilities allow for converting from snake case strings to enum
values and vice versa. This precludes the need for enum-specific
dictionaries.
> Created enum snake case utilities.

- project/src/main/puzzle/level/piece-type-rules.gd
- project/src/main/puzzle/level/rank-rules.gd
- project/src/main/puzzle/level/rule-parser.gd
- project/src/main/puzzle/level/score-rules.gd
The recent RuleParser change introduced circular references between the
RuleParser and the different Rules classes. This prevents resources from
being released, resulting in a warning when exiting the game. I've changed
RuleParser's references to weak references to avoid leaking resources.
> Fixed resource leaks introduced by RuleParser change.

- project/src/main/puzzle/line-inserter.gd
This stems from a type conversion error which affects released versions of the
game. When performing float operations, Godot will haphazardly store the result
as a float or an int depending on the circumstances. In the Godot editor, it
likes storing them as ints more often. But when exported, it likes storing them
as floats more often.
> Fixed bug where inserted lines did not work.

- project/src/main/creature-library.gd
- project/src/main/ui/music-popup-tween.gd
- project/src/test/test-system-save.gd
Fix crash which occurs launching StoryMode after the initial tutorial.
The crash occurred because the player's ID was changed from '#player#'
to 'Spira'. This edge case was overlooked when fixing issue #903.
Fixed sporadic yield error in MusicPopupTween. Godot's official tutorials
recommend `yield(get_tree().create_timer(...` for one shot timers, perhaps as a
cruel prank against novice developers. I have since learned this practice
invariably causes 'Resumed function after yield but class instance is gone'
errors unless your project has only one scene -- and possibly, even in
single-scene projects as well.
Fixed test-system-save.gd leaving behind a 'test254.save' file because
of its buggy cleanup code.
> Fix WalkingBuddy crash after initial tutorial. Minor bugfixes.

- project/src/main/creature-library.gd
- project/src/main/editor/creature/dialogs.gd
Let's have set_player_def always set the creature_id to
PLAYER_ID so the player's creature_id can never be out of sync.
This makes the creature_id field in the json save file unneeded
and makes some extra assignments unnecessary.
> Enforce player creature_id to be PLAYER_ID.

- project/src/main/world/chattable-manager.gd
- project/src/main/world/creature/player.gd
- project/src/main/world/creature/sensei.gd
- project/src/main/world/creature/walking-buddy.gd
- project/src/main/world/overworld-walk-world.gd
- project/src/main/world/overworld-world.gd
ChattableManager requires a refresh every scene change where
it steps through the entire node tree looking for Creatures.
Let's use that to discover the player and sensei,
simplifying _ready Node notifications that nonlocally set
ChattableManager.player and ChattableManager.sensei.
> Move ChattableManager.player assignment inside ChattableManager.

- delint.sh
- project/project.godot
Disabled 2D batching for Android. Android 2D batching reduces FPS by
80%:
* On android, with batching off, the game runs at about 60 FPS on the
overworld, and 15 FPS for a 35 creature stress test.
* On android, with batching on, the game runs at about 15 FPS on the
overworld, and 3 FPS for a 35 creature stress test.
* On windows, with batching off, the game runs at about 410 FPS on the
overworld, and 130 FPS for a 35 creature stress test.
* On windows, with batching on, the game runs at about 580 FPS on the
overworld, and 160 FPS for a 35 creature stress test.
Disabled vsync. With vsync off, I don't notice stuttering during the puzzles on
desktop.
> Disabled 2D Batching on android. Disabled vsync on all targets.

- project/src/main/puzzle/piece/piece-dropper.gd
This allows pieces to squeeze into gaps after a squish move.
Specifically, for squish moves like this:
```
oo
oo
:::
:
:
::
::
::
```
Before, this setup would result in the O piece dropping before it could
be slid to the left.
> Allow piece movement during post squish frames.

- project/src/main/editor/puzzle/editor-pickups.gd
- project/src/main/puzzle/combo-counters.gd
- project/src/main/puzzle/food-items.gd
- project/src/main/puzzle/pickups.gd
- project/src/main/utils.gd
- project/src/main/world/GroundMap.tscn
- project/src/main/world/environment/ground-library.tres
- project/src/main/world/environment/obstacle-library.tres
Minor adjustments to overworld texture and collision offsets. The
empty outer cell collisions were slightly misaligned with the obstalce
collisions. The ground and obstacle tilemaps were also not very well
aligned with the tilemap grid. This became especially apparent when
adding goop waves because they were asymmetrical on the left and right.
Fixed some overworld tilesets which did not have collision shapes
defined. This was broken when we recently got rid of the goop shader and
generated pre-colored tilesets.
Extracted Utils.map_to_world_centered() utility. We were doing this in
many traditional tilemaps, but the procedure for calculating the center of a
cell in an isometric tilemaps is more complex.
> Overworld offset, collision fixes. map_to_world_centered() utility.

- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-copy-save-data.gd
- project/src/main/ui/settings/settings-open-user-folder.gd
When balancing the game, I'd really like to get access to other player's
play statistics (combos, boxes, pieces per minute). For players on
Windows/Linux, they can send me their 'saveslot0.json' file. For players
on the web, they can copy it to their clipboard and pastebin it.
> Added 'Open User Folder', 'Copy to Clipboard' buttons

- project/src/main/puzzle/level/blocks-during-rules.gd
- project/src/main/puzzle/level/rank-rules.gd
- project/src/main/puzzle/tutorial/skill-tally-item.gd
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/ui/settings/settings-language.gd
- project/src/main/ui/wallpaper/sticker-row.gd
- project/src/test/puzzle/level/test-rank-rules.gd
- project/src/test/puzzle/piece/test-piece-kicks.gd
Removed unused constants from blocks-during-rules script.
Changed RankRules.top_out_penalty from int to float for consistency with
RankRules.success_bonus
Replaced push_error with push_warning in non-fatal places. For recoverable
errors, like a missing locale or a background that can't scroll, push_warning
is more appropriate. push_error should be for things which prevent the game
from being playable.
> Unused constants. top_out_penalty float. push_warning.

- project/assets/main/puzzle/levels/rank/10d.json
- project/assets/main/puzzle/levels/rank/4k.json
- project/assets/main/puzzle/levels/rank/7d.json
- project/assets/main/puzzle/levels/rank/8d.json
- project/assets/main/puzzle/levels/rank/9d.json
- project/assets/main/puzzle/levels/rank/m.json
- project/src/demo/puzzle/level/level-rank-demo.gd
- project/src/demo/puzzle/level/rank-mode-demo.gd
- project/src/main/puzzle/duration-calculator.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/test/puzzle/test-duration-calculator.gd
- project/src/test/puzzle/test-rank-calculator.gd
Grade system now awards an 'M' rank for speed as long as you clear 65
lines per minute. It used to only award an 'M' rank based on the maximum
theoretical speed for each level, which was in some cases much faster
than anybody can play (yet).
Grade system now separates endurance/speed and grades them separately.
This means that clearing 90/100 lines for a Marathon course scores a
low grade, but playing at 90% speed for a Sprint course scores a high
grade.
Adjusted Rank courses to provide a more linear increase in difficulty.
There used to be a monumental jump between Rank 6d/7d which required you to
play at about 50 pieces per minute, and Rank 8d/9d which required double
that. It now gradually ramps up from 50 ppm to 110 ppm.
> Grade changes: pieces per minute, endurance/speed

- project/src/main/puzzle/rank-calculator.gd
- project/src/test/puzzle/test-rank-calculator.gd
Especially short levels (levels lasting ~10 seconds) were giving very generous
ranks. An optimal strategy for these levels is just to make a lot of vertical
boxes resulting in a big combo at the end of the level. The rank algorithm was
assuming the player would clear ~5 horizontal lines traditionally, which does
not yield as many points.
The rank calculator now expects the player to stack extra lines in
Marathon/Sprint levels. It decrements the target_lines to compensate.
Removed test_two_rank_s. The gap between rank S+ and SS is pretty large for
legitimate reasons.
> High rank for short levels

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/food-items.gd
- project/src/main/puzzle/pickups.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/star-seeds.gd
In levels ending after a fixed number of customers, the final customer
would get skinny again during the final sequence of line clears. This is
because their fatness was based on the bonus score, but the bonus score
decreased for those kinds of puzzles. Their fatness is now based on a
separate 'fatness score'.
During sequential line clears, the final foods eaten added a lot more
weight than the earlier foods. Imagine a series of ten simultaneous line clears,
each worth 35 points. The creature's weight for each line could be calculated as
adding 10% of the total score, or 100% of the line score. However the bug
occurred because the calculation was doing both; early line clears were lerping
10% of 35 points, but late line clers were lerping 90% of the way towards 350
points. I've fixed the …
> Fixed bugs related to creature weight during puzzles.

- project/project.godot
- project/src/main/global.gd
- project/src/main/player-data.gd
- project/src/main/player-save.gd
- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/menu/MainMenu.tscn
- project/src/main/ui/menu/main-menu-play.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/CareerWin.tscn
- project/src/main/world/career-data.gd
- project/src/main/world/career-map.gd
- project/src/main/world/career-win.gd
- project/src/test/world/test-career-data.gd
A 'Career' button has been added to the main menu. This gives the player
a random series of levels, keeping track of their earnings as they play.
This career data is saved, so they can stop in the middle of a session
or view statistics for their previous sessions.
> Rudimentary career logic. Player can play a random series of levels

- project/src/main/puzzle/rank-calculator.gd
- project/src/test/puzzle/test-rank-calculator.gd
The old calculations didn't factor in boxes at all, and factored in
combo factor very heavily. This meant it had very low expectations for
levels with a combo factor of 0.0 (snack box blitz) and very high
expectations for levels with a low box factor (a little extra)
Veggie piece levels no longer expect leftover lines.
> Adjusted leftover calculations.

- project/src/main/puzzle/piece/states/prelock.gd
- project/src/main/settings/gameplay-settings.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-lock-cancel.gd
Twitch user PrincessMomo13 couldn't get used to the 'soft drop cancels
piece lock' functionality of Turbo Fat, so I've made it optional. It's
enabled by default.
> Added toggle setting for 'Soft Drop Lock Cancel'

- project/assets/main/puzzle/levels/boatricia1.json
- project/assets/main/puzzle/levels/boatricia2.json
- project/assets/main/puzzle/levels/marsh/goodbye-bones.json
- project/assets/main/puzzle/levels/marsh/goodbye-everyone.json
- project/assets/main/puzzle/levels/marsh/goodbye-skins.json
- project/assets/main/puzzle/levels/marsh/hello-bones.json
- project/assets/main/puzzle/levels/marsh/hello-everyone.json
- project/assets/main/puzzle/levels/marsh/hello-shirts.json
- project/assets/main/puzzle/levels/marsh/hello-skins.json
- project/assets/main/puzzle/levels/marsh/lets-all-get-merry.json
- project/assets/main/puzzle/levels/marsh/pulling-for-bones.json
- project/assets/main/puzzle/levels/marsh/pulling-for-everyone.json
- project/assets/main/puzzle/levels/marsh/pulling-for-shirts.json
- project/assets/main/puzzle/levels/marsh/pulling-for-skins.json
- project/assets/main/puzzle/levels/placeholder01.json
- project/assets/main/puzzle/levels/placeholder02.json
- project/assets/main/puzzle/levels/placeholder03.json
- project/assets/main/puzzle/levels/placeholder04.json
- project/assets/main/puzzle/levels/placeholder05.json
- project/assets/main/puzzle/levels/placeholder06.json
- project/assets/main/puzzle/levels/placeholder07.json
- project/assets/main/puzzle/levels/placeholder09.json
- project/assets/main/puzzle/levels/placeholder10.json
- project/assets/main/puzzle/levels/placeholder12.json
- project/assets/main/puzzle/levels/placeholder13.json
- project/assets/main/puzzle/levels/placeholder14.json
- project/src/main/puzzle/level/rank-rules.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/test/puzzle/test-rank-calculator.gd
Some levels such as 'Teensy Taste' had boxes or pieces already on the
playfield. This meant the game would award an M rank for a time of 0:16 seconds
because it thought the player needed 30 pieces to finish the level. However it
should require a time of 0:12 seconds for an M rank, because the player only
needs 25 pieces.
The 'preplaced pieces' value for each level factors in how helpful the
pieces are. On Teensy Taste for example, there are five pieces on the
playfield, but preplaced_pieces is deliberately set to four, because the
boxes are arranged in a way that requires slow play.
> Added 'preplaced pieces' rank logic

- project/src/main/ui/level-select/level-description-panel.gd
- project/src/main/ui/level-select/level-info-panel.gd
These two panels now store their label in an onready field to avoid
making multiple get_node calls, and copy/pasted nodepaths. This will
make the nodepath easier to change in the future.
> LevelDescriptionPanel, LevelInfoPanel set_text refactoring

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/step-meter.gd
The puzzle now shows a meter next to the player which indicates how far
they'll travel. This meter increases (and sometimes decreases) as they
progress through a puzzle.
The step calculation now makes it harder to travel 2, 3 or 4 steps.
Before, it was incredibly trivial to travel 2 or 3 steps -- it could
often be done in 2-3 line clears.
> Added career meter to puzzles. Tightened step calculation.

- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/milestone-hud.gd
- project/src/main/puzzle/milestone-manager.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/step-meter.gd
'milestone_progress' was a confusing name, as it was unclear whether it
returned a progress percent like 0.78 or an integer like 580. Its new
name 'progress_value' disambiguates that it returns a value and not a
percent.
> MilestoneManager renames: progress_value, is_met

- project/assets/main/puzzle/career-worlds.json
- project/assets/main/puzzle/levels/career/1000-race.json
- project/assets/main/puzzle/levels/career/90-second-sprint.json
- project/assets/main/puzzle/levels/career/a-little-garbage.json
- project/assets/main/puzzle/levels/career/dark/3000-race.json
- project/assets/main/puzzle/levels/career/dark/muffin-impossible-2.json
- project/assets/main/puzzle/levels/career/dark/three-minute-sprint.json
- project/assets/main/puzzle/levels/career/lets-all-get-merry.json
- project/assets/main/puzzle/levels/career/muffin-impossible-2.json
- project/assets/test/ui/level-select/career-worlds.json
Added dark, ultra, sprint levels to career mode. I accidentally added
these to the test resource before instead of the one used by the game.
I've also fixed the path to the dark levels, as they were referencing
invalid resources before.
Renamed career regions. Cannoli Sandbar thematically fits for being
the region with only four customers.
Sprint/ultra career mode levels now have an appropriate piece speed.
This allows them to scale in difficulty.
Made 'muffin impossible' and 'a little garbage' levels easier. They were
disproportionately difficult.
> Career level tweaks: dark, ultra/sprint, name switch

- project/src/main/world/CareerMap.tscn
- project/src/main/world/Overworld.tscn
- project/src/main/world/obstacle-manager.gd
The 'Obstacles' node was reorganized in a recent commit, breaking the
add_creature function. This would cause the game to crash when loading
cutscenes.
> Fixed add_creature NPE from bad $Obstacles reference

- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-map-level-select.gd
The buttons were overlapping the settings menu in an ugly way before.
> Career map hides level buttons when showing settings menu.

- project/src/main/puzzle/results-hud.gd
- project/src/main/world/career-world.gd
- project/src/main/world/creature/creature.gd
Customers in career mode now emote when you choose their level. Usually
they're happy but sometimes they're anxious.
Decreased the number of periods in the end of level results display, to
prevent it from wrapping its lines unnecessarily.
Closes #1061.
> Customers emote when selected. Results screen line breaks.

- license/asset-license.txt
Also changed 'Various Icons' sections to be more specific, since most of
these icon authors were only used for a single icon
> Split out 'icons' category in asset-license.txt

- project/project.godot
- project/src/main/career-data.gd
- project/src/main/ui/career/career-distance-label.gd
- project/src/main/ui/career/career-map-level-select.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-map.gd
- project/src/test/world/test-career-data.gd
The rightmost level is selected by default. Selecting an earlier level
reduces the player's distance travelled by up to 4 steps.
Closes #1140.
> Career mode decreases distance if you pick certain levels.

- project/src/main/ui/career/career-distance-label.gd
- project/src/main/ui/career/career-distance.gd
- project/src/main/ui/career/career-map-level-select.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-map.gd
With the distance buttons taking vertical space below the status bar,
the buttons needed to be lower which blocked more of the scene. Moving
the distance buttons up lets the creatures take up more of the screen.
> Moved distance buttons to status bar.

- project/src/demo/puzzle/tutorial/TutorialHudDemo.tscn
- project/src/demo/puzzle/tutorial/tutorial-hud-demo.gd
- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-diagram.gd
- project/src/main/puzzle/tutorial/tutorial-hud.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/puzzle/tutorial/tutorial-squish-module.gd
Added TutorialHud.change_level() method to change levels after all
tutorial messages are shown. The timer was starting when the first
letter of the message was shown, which meant the player had less time to
read longer messages. I've decreased the delay durations to compensate,
so hopefully the delays are roughly the same length as before.
TutorialHudDemo accepts a level_id property to try out different demos.
It also suppresses the level_settings.other.start_level property so that
later tutorial sections can be tested.
TutorialHud now supports diagrams without prompts.
> Tutorial improvements: timing, demo, promptless diagrams

- project/src/main/world/career-map.gd
CareerMap's _refresh_ui() function was throwing a 'resumed function
after yield' error because its distance_changed listener was being
triggered immediately before a scene change, so there was never an idle
frame. It now uses a one-shot listener instead.
> Fixed 'resumed function after yield' error in CareerMap

- project/src/main/career-data.gd
- project/src/main/puzzle/puzzle.gd
- project/src/test/world/test-career-data.gd
Career mode advanced the clock and set distance earned to '0' to
discourage savescumming -- but for boss levels this isn't enough,
because they actually apply a penalty on failure. Career mode now
applies this penalty before the level starts.
Renamed 'advance_distance' to 'advance_clock' and changed its behavior
slightly. This allows us to reuse it for the savescumming logic.
> Prevent save scumming of career mode boss levels.

- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/OverworldWalk.tscn
This ObstacleManager was introduced in deeabe1c to manage overworld
assets, but was only introduced in the Overworld scene and not other
similar scenes such as OverworldIndoors and OverworldWalk.
Closes #1187.
> Fixed missing 'ObstacleManager' in OverworldIndoors scene.

- project/src/main/career-data.gd
JSON parses all numbers as floats. They are corrected to ints in debug
mode, but not when the game is released. I've changed career-data's
from_json_dict to explicitly cast these values to ints.
> Fixed '?:?? zm' error in career clock from type error

- project/src/main/ui/career/CareerWin.tscn
- project/src/main/ui/career/career-win.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/OverworldUi.tscn
- project/src/main/world/career-map.gd
Career mode's map screen and win screen were missing the 'play_chill_bgm' so
music wouldn't play in HTML5. It was also missing the
SceneTransitionCover so it would play the wrong music.
> Fixed career mode music bug: no music on HTML5

- project/src/main/career-data.gd
- project/src/main/ui/career/career-win.gd
- project/src/main/ui/scene-transition-cover.gd
The transition to Career Mode's win screen was broken when introducing
the fade in effect. This is because the CareerMap scene would apply a
fade in and fade out scene transition simultaneously, resulting in an
empty CareerMap screen loading.
Fixed bug where CareerWin did not remove singletons, resulting in errors
when the singleton MusicPopup was freed.
Fixed 'Class Instance Is Gone' errors in SceneTransitionCover if the
scene changes while fading in.
> Fixed career mode win transition bugs

- project/src/main/ui/music-popup-tween.gd
- project/src/main/ui/scene-transition.gd
During career mode, the player could mash the level button repeatedly to
cause unpredictable behavior. Transitioning to a new scene should really
be treated as an atomic operation; the player shouldn't be able to
interrupt it.
We now block the player's input when fading out to prevent them from
mashing buttons or triggering other scene transitions. We restore the
player's input immediately when a new scene is loaded; we don't wait for
the 'fade in' to complete.
Fixed 'signal already connected' error in MusicPopupTween.
> Ignore input when fading out.

- delint.sh
This script is written in a peculiar way because of limitations of grep
and sed. Sed does not work well with multiple lines of input, and most
recommendations are either 'use perl' or 'don't use newlines'.
> delint.sh checks for gut test settings

- project/src/main/ui/career/CareerWin.tscn
- project/src/main/ui/career/career-win.gd
CareerWin had a redundant SceneTransitionCover. This caused redundant
calls to BreadCrumb and bugs in ResourceCache. However, these bugs only
seemed to occur when CareerWin was launched standalone, and don't appear to
affect the released game.
Changed CareerWin from a Node to a Control.
When CareerWin was a Node, a baffling side effect occurred. When
launched as a standalone scene, if you clicked 'OK' and navigated to the
main menu, the main menu's wallpaper would overlay its buttons. Changing it from
a Node to a Control fixes this somehow.
> CareerWin fixes: SceneTransitionCover, Control.

- project/src/main/ui/career/career-win.gd
- project/src/main/ui/career/chalkboard-earned.gd
- project/src/main/ui/career/chalkboard-served.gd
- project/src/main/ui/career/chalkboard-steps.gd
- project/src/main/ui/career/chalkboard-time.gd
- project/src/main/ui/career/chalkboard-title.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-menu-bottom.gd
- project/src/main/ui/settings/settings-menu.gd
Extracted child nodes within SettingsMenu, CareerWin. Both these scripts had
some very long node paths for logic which could be handled by the bottom node.
I've moved the node paths and logic.
> Refactoring: SettingsMenuBottom, CareerWin subcomponents

- project/src/main/ui/career/ChalkboardMapRow.tscn
- project/src/main/ui/career/LandmarkLine.tscn
Giving the connecting lines for the chalkboard the same line color created a
little bit too much visual homogeneity and reduced the readability of the thing
as a whole. Having the connecting lines darker helps the player's position stand
out.
> Darker landmark lines.

- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-map.gd
Fixed visual bug where career map's status bar didn't fade out. Fixed
visual bug where career map's status bar stayed in the foreground when the
settings menu was up.
Fixed bug where selecting an earlier level in Career mode made all the
buttons change.
> Career bugfixes: layers, buttons changing

- project/src/main/ui/career/CareerWin.tscn
- project/src/main/world/CareerMap.tscn
- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/OverworldWalk.tscn
- project/src/main/world/ScrewportTexrect.tscn
This means configuration like ScrewportTexrect's mouse filter can be
specified in one place instead of five places.
> Extracted ScrewportTexrect scene

- project/src/main/ui/career/career-distance-label.gd
- project/src/main/world/career-map.gd
After selecting a level in Career mode, the status bar would briefly
flash from '53 (+3)' to '52 (+1)' because the distance label would
detect the distance_travelled change signal. However, the
distance_travelled change was applying a penalty which the distance
label display already displays -- so this value was incorrect.
CareerMap now includes an explicit step to overwrite this label with the
correct value, so it flashes from '53 (+3)' to '53'
> Fix temporary status bar visual glitch when selecting a level.

- project/src/main/ui/career/career-map-level-select.gd
- project/src/main/ui/level-select/hookable-grade-label.gd
- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-map.gd
Career mode's level select buttons are added one-by-one, like
LevelSelectPanel's buttons. This is less weird than its current
implementation, where it always has three buttons but turns them
visible/invisible.
Removed unused 'level info changed' signal. LevelSelectButtons are now
removed and re-added each time, their properties don't change.
> Career mode's level buttons are added one-by-one.

- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/world/creature/creature-sfx.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/emote-player.gd
- project/src/main/world/restaurant/door-chime.gd
- project/src/main/world/restaurant/restaurant-scene.gd
Globally changed 'start_suppress_sfx_timer' to 'briefly_suppress_sfx'
with an optional parameter. This mirrors the
'briefly_suppress_sfx_signal' method. It is more semantic and less technical.
EmotePlayer and DoorChime use onready variables instead of repeated
get_node calls.
Added missing food_type parameter to Creature's food_eaten signal
declaration.
Simplified 'preemptively initialize onready variables' comment. This is
likely to become a projectwide pattern, and any more detailed
descriptions as to why it's necessary will become unnecessary and likely
inaccurate.
> Refactor: briefly_suppress_sfx, onready variables, food_eaten signal

- project/src/main/ui/career/career-map-level-select.gd
- project/src/main/world/career-map.gd
Previously in career mode, when clicking the settings button and then clicking
'OK', the level buttons would be deselected. It now reselects the previously
selected level button.
Previously in career mode, when clicking to choose a new start level,
the level buttons would be deselected. It now reselects the previously
selected level button.
> Career mode keeps level buttons focused

- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/creature-animations.gd
- project/src/main/world/creature/creature-sfx.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/restaurant/RestaurantScene.tscn
Merged CreatureVisuals' suppress_sfx_timer with CreatureSfx's
suppress_sfx_timer. CreatureSfx emits signals and exposes its
'should_play_sfx' property so that other nodes such as CreatureVisuals
can use it.
Removed redundant SuppressSfxTimer.autostart configuration in
RestaurantScene. This timer is started in the ready function.
> Refactor: Combine suppress_sfx mechanisms.

- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
- project/src/main/puzzle/tutorial/tutorial-cakes-module.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/puzzle/tutorial/tutorial-squish-module.gd
- project/src/main/ui/chat/ChatChoiceButton.tscn
- project/src/main/ui/menu/TutorialMenu.tscn
Fixed bug where basics tutorial (and other tutorials) couldn't be
finished. This bug was introduced in 6a1f692e by making
PuzzleState.reset() disable the game_active flag. Having this flag
disabled in tutorials meant that they wouldn't end the level, because
they didn't think the player was playing.
Fixed bug where mouse/keyboard input was ignored after quitting to the
tutorial menu. This is because the TutorialMenu scene was missing its
scene transition cover, which is responsible for restoring input.
Fixed bug where tutorial buttons like "Ok, I get it!" weren't responding
to mouse input. This occurred because the PuzzleMessages control was
blocking the mouse signals. I've disabled mouse input for the
PuzzleMessages control (not for its children.)
Fixed bug where squish tutorial would …
> Fixed many tutorial bugs.

- project/project.godot
- project/src/demo/ui/career/chalkboard-map-row-demo.gd
- project/src/main/ui/career/ChalkboardMapRow.tscn
- project/src/main/ui/career/chalkboard-map-row.gd
- project/src/main/ui/career/landmark-container.gd
- project/src/main/ui/career/landmark-lines.gd
- project/src/main/ui/career/landmark.gd
- project/src/main/ui/career/player-landmark.gd
Rather than ChalkboardMapRow creating and adding lines, adding landmarks and
calculating the player position, this is now handled by child scripts such as
landmark-lines.gd and player-landmark.gd.
This is honestly more complex than the old implementation, but being
more granular should allow these pieces to change independently and
prevent the parent node from ballooning in size if we add more features
to ChalkboardMapRow.
> Pushed ChalkboardMapRow logic into child nodes

- project/src/main/world/OverworldWalk.tscn
The Camera2D.current flag was accidentally unassigned in a1c71244.
> Fixed bug where prologue camera did not follow characters.

- project/src/demo/world/cutscene-demo.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/menu/main-menu-play.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/cutscene-manager.gd
The name 'cutscene' has more semantic meaning, as it's not clear that enqueuing
a chat tree has anything to do with cutscenes. The data type is a chat
tree, so I don't feel information is lost.
> Refactor: Renamed CurrentCutscene 'chat_tree' methods to 'cutscene'

- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/step-meter.gd
- project/src/test/puzzle/test-rank-calculator.gd
Improved rank algorithm to calculate how many seconds it takes to get a
fixed number of lines, instead of basing it on points per second. The
points per second approach is flawed because you cannot score points at
a constant rate. If it takes you 10 seconds to get 150 points, you
still cannot get 15 points in 1 second. You only earn points at
intervals, when clearing lines.
Fixed empty step meter at the start of certain timed levels. For levels
with a high scoring requirement, the cap of 9999 seconds was still
enough to affect the meter.
> Rank tweaks: target lines for score, empty step meter

- project/src/main/ui/chat/choice-theme.tres
This bug appears to happen because the 'normal' button definition had a
different corner radius than the other button definitions
> Fixed chat choice overrun bug

- project/src/main/career-data.gd
- project/src/main/ui/career/career-map-ui.gd
- project/src/main/ui/level-select/career-region.gd
- project/src/main/ui/scene-transition.gd
Instead of CareerData and other places calling Breadcrumb directly to
avoid the 'don't fade out while fading in' scenario, they all delegate
to SceneTransition which handles it internally.
Consistency changes for SceneTransition. It now assigns 'fading = false'
for all of its transitions instead of just one, and handles the '::'
paths for all of its transitions instead of just one or two.
Minor fixes to comments
> SceneTransition handles 'don't fade out while fading in' scenario

- project/src/main/global.gd
- project/src/main/ui/career/CareerWin.tscn
- project/src/main/ui/career/career-win-world.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/ChatIcons.tscn
- project/src/main/world/Overworld.tscn
- project/src/main/world/OverworldIndoors.tscn
- project/src/main/world/OverworldWalk.tscn
- project/src/main/world/career-world.gd
- project/src/main/world/chat-icons.gd
- project/src/main/world/environment/EmptyEnvironment.tscn
- project/src/main/world/environment/overworld-environment.gd
- project/src/main/world/overworld-walk-world.gd
- project/src/main/world/overworld-world.gd
Overworld environments can now be substituted in the editor by changing
the EnvironmentScene property.
Fixed missing shadows for spawned items.
> Worlds can replace environments in the editor

- project/project.godot
- project/src/main/global.gd
- project/src/main/player-data.gd
- project/src/main/story-data.gd
- project/src/main/ui/menu/main-menu-play.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/cutscene-manager.gd
- project/src/main/world/overworld-exit.gd
- project/src/main/world/overworld-world.gd
The player_spawn_id and sensei_spawn_id are specific to story mode and
don't need to be in Global. I've moved them into a new StoryData script under
PlayerData. They're currently not persisted, but they could be some day
if we want the player to continue from their previous location.
> Refactor: Extracted StoryData from Global.

- project/assets/main/chat/career/marsh/prologue.chat
- project/assets/main/chat/marsh-epilogue.chat
- project/assets/main/chat/marsh-prologue.chat
- project/assets/test/ui/chat/cutscene-full.chat
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/Cutscene.tscn
- project/src/main/world/cutscene-camera.gd
- project/src/main/world/cutscene-world.gd
Added fixed_zoom cutscene flag. This replaces the walk detection logic.
Some cutscenes need to zoom out so that you can see the environment,
such as those in front of the Buttercup Cafe.
> fixed_zoom cutscene flag.

- project/assets/main/chat/career/marsh/10-d.chat
- project/assets/main/chat/career/marsh/30-d.chat
- project/assets/main/chat/career/marsh/50-d.chat
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/menu/main-menu-play.gd
Added diota's scenes to career mode.
Added logic for career mode to launch a cutscene immediately when career
mode is selected from main menu. This avoids an edge case where the
player is in an area, and then selects a level for that area, and then
the player is shown a prologue for that area.
> Add diota's career scenes. Career button can launch cutscene.

- project/src/main/career-data.gd
- project/src/main/puzzle/level/level-history.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/career/career-distance-label.gd
- project/src/main/world/career-world.gd
Fixed bug where CareerData referenced 'PlayerData.career' instead of referencing
itself.
Broke up CareerData.advance_clock() function which was growing large.
Extracted new CareerData.process_puzzle_result() function from Puzzle to keep the
career-specific logic separate from the puzzle logic.
Extracted new level_choice_count() method. Currently this only toggles
based on whether the player is playing a boss level, but in the future
there are other reasons why the player will have only one level to
choose.
> Refactorings: Career mode advancement logic improvements.

- project/src/main/career-data.gd
Cutscenes are skipped if you don't complete a boss level, or if you skip
a level.
> Career mode skips cutscenes sometimes.

- project/src/main/career-data.gd
- project/src/main/ui/career/career-distance-label.gd
- project/src/test/world/test-career-data.gd
If the player hits a boss level they haven't cleared, instead of the
steps being thrown away, they're 'banked' and applied the next time the
player advances forward.
> Added 'banked steps' logic for career mode.

- project/src/main/career-data.gd
- project/src/test/world/test-career-data.gd
Before, you could advance into a region and end up back in an older
region if you chose an earlier level.
> Career mode penalties cannot send you to a previous region.

- project/src/demo/world/cutscene-demo-flags.gd
- project/src/main/puzzle/level/level-history.gd
- project/src/main/ui/chat/chat-history.gd
- project/src/main/ui/level-select/career-level-library.gd
- project/src/main/ui/level-select/career-region.gd
- project/src/test/world/test-career-data.gd
Added new LevelHistory.delete() function. Changed ChatHistory.delete_history_item()
to return true/false based on the result of the deletion. This return
value isn't used, but it implicitly documents that it's OK to erase
non-existent items from the history.
Expanded some comments.
> Refactor: LevelHistory.delete, comments

- project/src/main/ui/career/career-distance-label.gd
- project/src/main/world/career-map.gd
Distance label was incorrectly displaying values like '4 (+4) instead of
'53 (+4)'. This was broken in 8c356a5d when adding the 'banked steps'
logic.
Career map now initializes a breadcrumb trail, if one is not already
initialized. This avoids bugs when launnching CareerMap directly from
the editor.
> Fixed career distance label, breadcrumb trail

- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/test/ui/chat/test-career-cutscene-library.gd
Fixed tree traversal order with
CareerCutsceneLibrary.filter_chat_key_pairs(). It was appending items to
the start and end of a queue, which worked for simple linear tree
traversal cases but failed for more complex trees.
CareerCutsceneLibrary now ignores special keys such as 'prologue' and
'intro_level'. Before, these keys would receive the same treatment as
numeric cutscenes like '10-a'. The only reason they were never selected
is because the player views them immediately upon entering a region, and
we avoid showing the player duplicate cutscenes. But this would cause
noticable bugs for boss or epilogue cutscenes.
Renamed CareerCutsceneLibrary methods. The initialization method is now
called 'refresh_chat_key_pairs' to disambiguate it from
'find_chat_key_pairs' which is responsible for …
> CareerCutsceneLibrary improvements: traversal order, special keys

- project/assets/main/chat/career/marsh/epilogue.chat
- project/src/main/player-data.gd
- project/src/main/ui/career/career-map-ui.gd
- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/level-select/career-region.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/Overworld.tscn
- project/src/main/world/career-map.gd
- project/src/main/world/current-cutscene.gd
- project/src/test/ui/chat/test-career-cutscene-library.gd
Merrymellow Marsh defines an epilogue cutscene. This epilogue plays after
the last normal cutscene of the region. When activated, the player is
automatically advanced past the area.
Added new 'epilio' cheat to force an epilogue to play.
> Added epilogue cutscene to career mode. Added 'epilio' cheat.

- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/piece/piece-rotator.gd
- project/src/main/puzzle/piece/piece-types.gd
- project/src/test/puzzle/piece/test-piece-kicks-u.gd
Added piece kick test for U pieces. Moved piece flip kick logic from
PieceRotator.apply_rotate_input() into ActivePiece.kick_piece()
> U pieces can flip in narrow columns.

- project/assets/main/chat/career/marsh/10-a-end.chat
- project/assets/main/chat/career/marsh/10-b.chat
- project/assets/main/chat/career/marsh/10-c-end.chat
- project/assets/main/chat/career/marsh/30-a-end.chat
- project/assets/main/chat/career/marsh/30-c-end.chat
- project/assets/main/chat/career/marsh/30-d.chat
- project/assets/main/chat/career/marsh/50-a-end.chat
- project/assets/main/chat/career/marsh/50-b-end.chat
- project/assets/main/chat/career/marsh/50-c-end.chat
- project/assets/main/puzzle/levels/career/boss-4k.json
- project/assets/main/puzzle/levels/career/boss-5k.json
Swapped titles for Canolli Sandbar/Merrymellow Marsh. The order of these
worlds was flipped but these levels still had the old names.
> Removed 'skip_if' flags from career levels. Title fixes.

- project/src/main/ui/chat/chat-library.gd
- project/src/test/ui/chat/test-career-cutscene-library.gd
- project/src/test/ui/chat/test-chatscript-parser.gd
This is slightly cleaner than having source code in the /main source
branch which references the 'res://assets/test' path. It also allows the
'path_from_chat_key' function to work for tests.
Added test showing that ChatScriptParser populates ChatTree.chat_key
> ChatLibrary now exposes chat_key_root_path for tests.

- project/src/main/ui/career/career-map-ui.gd
- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/world/career-map.gd
'cutsio' cheat now causes a scene change. Enabling different cutscenes may force
different levels to play, and this is also consistent with other similar cheat
codes (bossio, epilio)
Renamed next_chat_key_pair() to next_interlude_chat_key_pair(). Without
the word 'interlude' it's unclear why other chat key pairs are being
skipped over.
> 'cutsio' cheat causes scene change. next_chat_key_pair() rename.

- project/assets/main/puzzle/levels/career/just-cream.json
- project/src/main/puzzle/level/piece-type-rules.gd
- project/src/main/puzzle/piece/piece-queue.gd
New 'no_suppress_o_pieces' flag disables the 'suppress o piece' logic
just for that level. Most levels suppress O pieces because they're hard
to work with, but this specific level is incredibly difficult if there
is not a 50/50 ratio of pieces.
> Fixed piece distribution in 'Just Cream'

- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/world/career-map.gd
Fixed erroneous check for 'not result' instead of 'result.empty()' when
checking whether a region has cutscenes or not. This logic worked when
we used Dictionaries, but does not work for ChatKeyPairs.
Fixed a few comments which used incorrect types and incorrect language.
> Career cutscene bugfixes, comments

- project/src/main/career-data.gd
- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/overworld-ui.gd
- project/src/main/world/career-map.gd
- project/src/main/world/chat-key-pair.gd
- project/src/main/world/cutscene-manager.gd
- project/src/test/ui/chat/test-career-cutscene-library.gd
Failing a boss level should skip boss cutscenes, but should not skip
interlude cutscenes. To facilitate this, ChatKeyPair has a new 'type'
property, and CutsceneManager has a new 'cutscene_flag' property. These
tools allow the puzzle script to tell whether a boss level cutscene is
playing.
> Fixed bug where interludes were skipped after failed boss level

- project/assets/main/chat/career/marsh/10-a-end.chat
- project/assets/main/chat/career/marsh/10-b.chat
- project/assets/main/chat/career/marsh/10-c-end.chat
- project/assets/main/chat/career/marsh/20-end.chat
- project/assets/main/chat/career/marsh/20.chat
- project/assets/main/chat/career/marsh/30-a-end.chat
- project/assets/main/chat/career/marsh/30-b-end.chat
- project/assets/main/chat/career/marsh/30-c-end.chat
- project/assets/main/chat/career/marsh/50-a-end.chat
- project/assets/main/chat/career/marsh/50-b-end.chat
- project/assets/main/chat/career/marsh/50-c-end.chat
- project/assets/main/chat/career/marsh/intro-level-end.chat
- project/assets/main/chat/career/marsh/intro-level.chat
- project/assets/test/ui/chat/cutscene-full.chat
- project/assets/test/ui/chat/fake-career-2/a.chat
- project/assets/test/ui/chat/fake-career-2/b.chat
- project/assets/test/ui/chat/fake-career-2/c.chat
- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/ui/level-select/career-level-library.gd
- project/src/main/ui/level-select/career-level.gd
- project/src/main/world/career-map.gd
- project/src/test/ui/chat/test-career-cutscene-library.gd
- project/src/test/ui/chat/test-chatscript-parser.gd
- project/src/test/ui/level-select/test-career-level-library.gd
Chatscript now allows cutscenes to specify chefs/customers so they can
be matched up between cutscenes and levels.
When selecting levels in career mode, we now only allow the player to choose
levels featuring creatures from potential upcoming cutscenes.
When selecting a cutscene in career mode, we now only select cutscenes featuring
creatures from the chosen level.
> Career mode ensures cutscenes and levels match.

- project/src/main/ui/level-select/career-level-library.gd
- project/src/test/ui/level-select/test-career-level-library.gd
'Anonymous customer' unlock behavior was not working properly, resulting
in no levels appearing once the player got to Diota's story arc
> Fixed unlock behavior for 'anonymous customer' levels.

- project/src/main/world/creature/emote-player.gd
After a creature turned their head, their head would remain turned if
they changed their mood. This could be verified in MoodDemo by pressing
'W' and then '1'.
After a creature showed the 'love eyes' animation, their eyes could
stay distorted if they quickly changed their mood. This could be
verified in MoodDemo by quickly pressing 'UF' one after the other.
> Fixed unemote bugs when turning head, heart eyes

- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/chat/chatscript-parser.gd
- project/src/main/ui/level-select/career-level-library.gd
- project/src/main/world/career-map.gd
- project/src/test/ui/chat/test-career-cutscene-library.gd
- project/src/test/ui/chat/test-chatscript-parser.gd
ChatTree accepted one chef id, but multiple customer ids before -- but,
only one customer id was actually used. It now only stores one customer
id.
Chatscript parser now warns if a chatscript file declares more than one
chef or customer.
> ChatTree only accepts one customer, chef.

- project/src/main/ui/overworld-ui.gd
- project/src/main/world/Cutscene.tscn
- project/src/main/world/creature/player.gd
- project/src/main/world/creature/sensei.gd
- project/src/main/world/cutscene-world.gd
OverworldUi's cutscene flag is now togglable in the editor, eliminating a line
of code from the cutscene-world script.
player.gd and sensei.gd scripts now disable their logic by polling
the OverworldUi.cutscene flag directly, eliminating a few lines of code
from the cutscene-world script.
> Simplified cutscene-world script.

- project/src/main/string-utils.gd
- project/src/test/test-string-utils.gd
StringUtils was missing tests for many of its functions, and its
functions did not handle edge cases very well (negative values, empty
values). It's now slightly more robust.
> StringUtils tests, fixes

- project/src/main/career-calendar.gd
- project/src/main/career-data.gd
- project/src/main/career-flow.gd
- project/src/main/ui/career/career-distance.gd
- project/src/main/ui/career/career-map-ui.gd
- project/src/main/ui/level-select/career-level-library.gd
- project/src/main/world/career-map.gd
- project/src/main/world/career-world.gd
Extracted utility methods for CareerData.current_region(),
previous_region() and next_region().
Reordered CareerLevelLibrary methods. _ready() should be at the top,
private methods should be at the bottom.
CareerLevelLibrary.required_cutscene_characters() no longer refers to
PlayerData. It only referred to it in one place, and I prefer it to be
stateless.
> Refactor: Extracted CareerData.current_region() methods.

- project/src/main/ui/level-select/hookable-grade-label.gd
In Godot 3.4.4, GradeLabel's buttons are assigned before they enter the
tree causing NPEs.
> Fixed GradeLabel NPE.

- project/src/main/world/career-map.gd
Array out of bounds could occur when picking a level with a chef but no
customers
> Fixed array out of bounds error in career mode

- project/src/main/world/environment/invisible-obstacle-tiler.gd
- project/src/main/world/obstacle-map-indoors.gd
Fixed nil reference errors in InvisibleObjectTiler. Fixed
InvisibleObjectTiler constantly autotiling stuff in editor, instead of
only when the user toggles the 'autotile' setting.
Fixed obstacle-map-indoors to only autotile in the editor when the
'autotile' property is toggled. This prevents unintentional changing of
tilemaps which happened in the previous few commits.
Fixed obstacle-map-indoors variables which should have been declared as
constants.
> Cleaned up overworld tilers to match frosted tiler.

- project/src/demo/world/environment/RippleWavesDemo.tscn
- project/src/main/world/environment/LemonWinEnvironment.tscn
- project/src/main/world/environment/MarshEnvironment.tscn
- project/src/main/world/environment/MarshWinEnvironment.tscn
- project/src/main/world/environment/OverworldEnvironment.tscn
- project/src/main/world/environment/OverworldWalkEnvironment.tscn
Without these tile IDs, ripple waves would be inappropriately generated
on bare terrain
> Fixed RippleWaves nodes with correct tile ids

- project/src/main/world/environment/frosted-overworld-tiler.gd
- project/src/main/world/environment/overworld-obstacle.gd
FrostedOverworldTiler was autotiling ground tiles which include
randomness. This meant the tiles were constantly changing even when no
deliberate edits were made. It now only autotiles the corners, which are
deterministic.
OverworldObstacle no longer changes metadata/groups in the editor. This
was causing editor errors for obstacles which were also tool scripts.
> FrostedOverworldTiler only autotiles corners.

- project/src/demo/music/music-player-demo.gd
- project/src/demo/ui/career/chalkboard-map-row-demo.gd
- project/src/demo/ui/chat/chat-frame-demo.gd
- project/src/demo/ui/chat/mood-demo.gd
- project/src/demo/world/letter-shooter-demo.gd
- project/src/demo/world/restaurant/restaurant-scene-demo.gd
- project/src/demo/world/restaurant/restaurant-view-demo.gd
- project/src/main/ui/cheat-code-detector.gd
At some point in a recent Godot release, KEY_BRACELEFT stopped working,
and now KEY_BRACKETLEFT works instead.
> Replaced KEY_BRACELEFT/RIGHT with KEY_BRACKETLEFT/RIGHT

- project/src/demo/world/restaurant/RestaurantPuzzleSceneDemo.tscn
- project/src/demo/world/restaurant/RestaurantViewDemo.tscn
- project/src/demo/world/restaurant/restaurant-puzzle-scene-demo.gd
- project/src/demo/world/restaurant/restaurant-view-demo.gd
- project/src/main/puzzle/puzzle.gd
Customer count is no longer hardcoded at '3' for puzzle restaurant logic, we
now count the number of customers in the scene.
RestaurantViewDemo, RestaurantPuzzleSceneDemo extend Node instead of
Node2D/Control, for consistency with other demos.
Extracted onready variables.
Fixed outdated RestaurantScene.get_player() reference. This was renamed
to get_chef() when we added levels where the player was not the chef.
> Avoid hardcoding customer count. Restaurant demo refactorings.

- project/src/main/global.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/player.gd
- project/src/main/world/creature/sensei.gd
- project/src/main/world/free-roam-exit.gd
- project/src/main/world/restaurant/RestaurantView.tscn
- project/src/main/world/restaurant/customer-camera-mover.gd
- project/src/main/world/restaurant/customer-switch-tween.gd
Fixed a few potential NPEs in classes like FreeRoamExit, Sensei and
Player. These scripts were written assuming they'd only be used in
freeroam/career mode where there is a chat ui, player and sensei -- but with
upcoming code changes they are also used in puzzle mode where many of these
assumptions are violated.
Extracted Creature.body_pos_from_head_pos function.
> Fixed potential overworld related NPEs. body_pos_from_head_pos

- project/src/main/puzzle/level/level-settings.gd
- project/src/main/puzzle/rank-calculator.gd
lenient_value was occasionally assigned as an int (in level-settings.gd)
but occasionally set as a string (when parsed from json). This caused
type cast errors in rank-calculator.gd. (These type errors seem new.
It's possible older versions of Godot cast ints and strings implicitly
in this circumstance.)
> Fixed type error with 'lenient_value'

- project/src/main/world/career-camera.gd
- project/src/main/world/career-world.gd
With the camera as zoomed in as it was, you couldn't see certain details
like the signs on buildings. It's now zoomed out more so more of the
environment is visible.
> Zoomed out career mode camera.

- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/start-end-sfx.gd
- project/src/main/puzzle/tutorial/tutorial-basics-module.gd
- project/src/main/puzzle/tutorial/tutorial-cakes-module.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-squish-module.gd
Previously, the 'Regret...' message showed up if we made the player
repeat a scenario. But there are times when we'll advance tutorials even
if they fail. The new 'Regret...' message logic keys off of
PuzzleState.level_performance.lost.
> Change 'Regret...' condition for tutorials

- project/src/demo/puzzle/puzzle-demo.gd
- project/src/main/puzzle/duration-calculator.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/test/puzzle/test-rank-calculator.gd
PuzzleDemo now ignores the start_level so we can test the middle part of
tutorials.
DurationCalculator no longer calculates the duration of tutorials.
Tutorials have many parts so it was inaccurate to calculate 'The player only
has to clear two lines, so it is a short tutorial'
Fixed divide by zero in RankCalculator with very short levels, such as
levels with only one piece. Target_lines was zero (you can't clear a
line with only one piece) resulting in errors trying to figure out how
the player's performance compared with the expected zero lines.
Moved tutorial's 'game_active = true' statement. This was causing
problems in PuzzleDemo -- when testing the last section of a tutorial,
it would display 'Ready?' but never proceed to 'Go!' because it thought
the game was already active.
> Tutorial framework bugs: TutorialDemo, tutorial duration, target_lines

- project/project.godot
- project/src/demo/puzzle/tutorial/tutorial-hud-demo.gd
- project/src/main/puzzle/HudFlash.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/hud-flash.gd
- project/src/main/puzzle/tutorial/tutorial-hud.gd
This involved pulling the TutorialHud's flash effect into Puzzle's Canvas
node where it could fill the entire canvas. Instead of TutorialHud
having a HudFlash node, it now has a reference to one.
> Fixed Tutorial's flash effect to fill the entire screen.

- project/project.godot
- project/src/demo/puzzle/tutorial/tutorial-hud-demo.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/tutorial/TutorialHud.tscn
- project/src/main/puzzle/tutorial/skill-tally-item.gd
- project/src/main/puzzle/tutorial/skill-tally-panel.gd
- project/src/main/puzzle/tutorial/tutorial-cakes-module.gd
- project/src/main/puzzle/tutorial/tutorial-combo-module.gd
- project/src/main/puzzle/tutorial/tutorial-diagram.gd
- project/src/main/puzzle/tutorial/tutorial-hud.gd
- project/src/main/puzzle/tutorial/tutorial-module.gd
- project/src/main/puzzle/tutorial/tutorial-squish-module.gd
Extracted SkillTallyPanel script from TutorialHud. TutorialHud provides
facade methods for both SkillTallyPanel and TutorialMessages.
Added onready variables for TutorialHud's diagram and messages. This
reduces the amount of get_node calls amde at runtime.
Pushed some of TutorialHud's listeners out into Puzzle and
SkillTallyPanel.
> TutorialHud refactoring: SkillTallyPanel, onready fields

- project/src/main/ui/career/career-win-world.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/FreeRoam.tscn
- project/src/main/world/career-world.gd
- project/src/main/world/cutscene-world.gd
- project/src/main/world/free-roam-world.gd
- project/src/main/world/free-roam.gd
- project/src/main/world/overworld-world.gd
- project/src/main/world/puzzle-world.gd
FreeRoam's breadcrumb trail is no longer initialized by FreeRoamWorld.
I've split a new 'free-roam' script out of the old 'free-roam-world'
script which handles non-environmental things like the breadcrumb trail
and music.
Replaced OverworldWorld.prepare_environment_resource() with
initial_environment_path(). This method name isn't perfect but instead
of child classes needing to load and assign an environment scene, they
just return the path of the resource they want to load. It's slightly
less repetitive code this way.
> Refactor: FreeRoam breadcrumb trail, prepare_environment_resource

- project/src/main/world/creature-spawner.gd
- project/src/main/world/creature/creature-visuals.gd
- project/src/main/world/environment/grass-overworld-tiler.gd
- project/src/main/world/environment/invisible-obstacle-tiler.gd
- project/src/main/world/environment/kitchen-obstacle-tiler.gd
- project/src/main/world/environment/pebble-overworld-tiler.gd
- project/src/main/world/letter-shooter.gd
Added range to some export hints. Fatness is always 1-10.
MarshIndoorsEnvironment no longer autotiles when it is loaded. This was
causing the tiles to be constantly swapped out resulting in unnecessary
noise in git diffs.
> Refactor: export range, indoor autotile.

- project/src/main/world/chattable-manager.gd
ChattableManager no longer unregisters creatures. This was causing
get_creature_by_id lookups to fail for the `#player#` and `#sensei#`
values.
> Fixed bug where cutscenes caused game crash.

- project/src/main/ui/menu/main-menu-play.gd
The main menu now forces the player into free roam mode after the
prologue.
> Fixed bug where free roam prologue returned player to main menu.

- project/src/main/world/cutscene-ui.gd
This bug occurred because many cutscenes dropped the player into
non-interactive environments like 'MarshEnvironment' instead of
interactive environments like 'MarshFreeRoamEnvironment'
> Fixed bug where player couldn't move in free roam mode.

- project/assets/main/puzzle/career-worlds.json
- project/assets/test/ui/level-select/career-worlds-simple.json
- project/project.godot
- project/src/main/ui/career/career-map-ui.gd
- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/level-select/career-level-library.gd
- project/src/main/ui/level-select/career-level.gd
- project/src/main/ui/level-select/career-region.gd
- project/src/main/world/CareerMap.tscn
- project/src/main/world/career-map.gd
- project/src/main/world/career-world.gd
- project/src/main/world/level-posse.gd
- project/src/test/ui/chat/test-career-cutscene-library.gd
- project/src/test/ui/level-select/test-career-level-library.gd
Regions can define quirky chefs and customers who only show up for specific
levels. They can also define regular chefs and customers who show up for other
levels.
When limiting the player's level selection, the game only considers
'quirky characters'. When cosmetically deciding which chefs/customers
will show up for fun, the game considers characters in cutscenes and
characters defined for the region.
Added new 'CYCLIO' cheat for cycling through levels/chefs/customers
without advancing the clock.
> New 'quirky customer' cutscene logic. New cyclio cheat.

- project/src/main/ui/career/career-win-world.gd
- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/main/ui/level-select/career-region.gd
- project/src/main/world/career-world.gd
- project/src/test/ui/chat/test-chat-tree.gd
Added logic to conditionally exclude cutscenes with Fat Sensei and the
restaurant. Early chapters (and perhaps later chapters) will have the
player by themselves, so we don't want a random cutscene which doesn't
make sense where Fat Sensei shows up.
> Conditionally exclude cutscenes with sensei/restaurant

- project/src/main/ui/level-select/career-region.gd
- project/src/test/ui/chat/test-career-cutscene-library.gd
Sorted CareerRegion fields, it was getting difficult to find them. Also
refactored some repetitive code for storing CreatureAppearances.
Fixed failing CareerCutsceneLibrary test. We changed the cutscene
selection logic to require 'quirky' creatures, but we didn't update the
tests to define anyone as quirky. The tests also now need some test
CareerData because the CareerCutsceneLibrary now depends on it.
> Sorted CareerRegion fields. Fixed CareerCutsceneLibrary test.

- project/src/main/ui/level-select/career-region.gd
- project/src/main/world/career-world.gd
Fixed bug where when the player was alone, the center career creature
would face away from them instead of toward them. The creatures all now
face toward the player, using their 'X' coordinates instead of their
creature index
Refactored CreatureAppearance weighted selection logic to use
Utils.weighted_rand_value() utility method
Changed float division line for clarity
> Fixed career customer orientation bug. CreatureAppearance refactoring.

- project/assets/main/puzzle/levels/career/fruit-on-the-top.json
- project/src/main/puzzle/level/blocks-during-rules.gd
- project/src/main/puzzle/line-filler.gd
- project/src/main/puzzle/piece/piece-speed.gd
- project/src/main/puzzle/top-out-tracker.gd
This new flag enables levels which want to reset the playfield when the
player tops out. For example, a level might start with 6 'garbage rows'
but if the player digs past them, higher scoring rows start to spawn.
The default top out logic would reward a player who tops out by deleting
these garbage rows for them. With this new flag, a player who tops out
will lose their progress and have to try again (which is perhaps
preferable.)
> New 'refresh on top out' logic.

- project/assets/main/puzzle/levels/career/just-cream.json
- project/src/main/puzzle/level/piece-type-rules.gd
- project/src/main/puzzle/piece/piece-queue.gd
This 'no_suppress_repeat_piece' setting disables the behavior where the
bag algorithm avoids repeat pieces. It's especially useful in levels
with only two or three piece types which otherwise become too
predictable.
> Added 'no_suppress_repeat_piece' level setting.

- project/project.godot
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/line-filler.gd
- project/src/main/puzzle/piece/piece-manager.gd
- project/src/main/puzzle/piece/piece-physics.gd
- project/src/main/puzzle/piece/states/move-piece.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/top-out-tracker.gd
- project/src/main/puzzle/top-out.gd
When the player tops out but doesn't die, they can now buffer inputs by
tapping the rotate/move/drop keys with remarkable timing -- or they can
activate DAS by holding the rotate/move/drop keys.
This prevents a frustrating case where the player would watch a length
top out animation while holding a movement direction, and then after the
top out animation finished the piece still wouldn't move (unless they pressed
the key again.)
> Apply das/buffered inputs after top out.

- project/src/main/puzzle/piece/piece-squisher.gd
- project/src/main/puzzle/piece/presquish-sfx.gd
Fixed bug where pieces could lock in mid air with a squish move. This
would occur if the player exhausted all of the piece's lock resets and
then performed a squish move which left the piece in mid-air.
Fixed bug where squish sound effects would sometimes continue after the
squish was completed or cancelled. This was caused by Godot  #37148, a
bug which causes the 'AudioStreamPlayer.stop()' to malfunction if
playback was started in the same frame
(https://github.com/godotengine/godot/issues/37148)
> Squish move bugs: sfx, mid-air locks

- project/src/test/puzzle/piece/test-piece-kicks-jl.gd
- project/src/test/puzzle/piece/test-piece-kicks-pq.gd
- project/src/test/puzzle/piece/test-piece-kicks-t.gd
- project/src/test/puzzle/piece/test-piece-kicks-u.gd
- project/src/test/puzzle/piece/test-piece-kicks-v.gd
Piece kick tests consistently use '0r' 'r2' notation instead of ambiguous 'cw'
'ccw' notation. Tests consistently have floor kicks/wall kicks before other
tests.
Renamed test-piece-kicks-qp to test-piece-kicks-pq to preserve
alphabetical order convention followed by other similar tests.
Fixed grammar of 'j/l piece's kick behavior' which I don't think should
use the singular possessive.
> Reorganized piece kick tests.

- project/assets/main/chat/career/lemon/boss-level-end-2.chat
- project/assets/main/chat/career/marsh/epilogue.chat
- project/assets/main/chat/career/marsh/prologue.chat
- project/src/main/career-data.gd
- project/src/main/puzzle/puzzle.gd
Replaced epilogue check with 'advance_region' flag. Some cutscenes other
than the epilogue (such as the Lemony Thickets boss region flag) should
also force the player to advance.
Fixed bug which which prevented the 'Epilogue Skips The Chapter' logic
from triggering after a puzzle. Puzzles were checking whether a player
had cleared the region, but finishing every cutscene in a region is
supposed to act as an alternative to clearing the region for players who
aren't skilled enough to advance far enough normally.
Removed unnecessary 'destination' flag from career cutscenes. This flag
is only used in free roam mode.
> epilogue logic tweaks, advance_region flag

- project/src/main/ui/chat/ChatChoiceButton.tscn
- project/src/main/ui/level-select/LevelSelectButtonFocus.tres
- project/src/main/ui/level-select/LevelSelectButtonPressed.tres
The focused/pressed blue selection colors had some variance which was
seemingly incidental and not deliberate. The pressed background color is
now brighter and more opaque, so the button lights up when you press it.
Removed default 'choice_text' from ChatChoiceButton.
> Blue level selection color tweak.

- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/level-select/level-description-panel.gd
- project/src/main/ui/level-select/level-info-panel.gd
- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/ui/level-select/level-select.gd
- project/src/main/ui/level-select/world-select-button.gd
- project/src/main/utils.gd
CareerCutsceneLibrary comments now explicitly mention 'interlude
cutscenes' in more places. Most of this script's functionality centers around
interludes, and excludes things like epilogues and intro cutscenes. Its
comments now communicate this better.
Fixed unnecessary public methods in level-description-panel.gd,
level-info-panel.gd
Added missing comments. Added comments describing what 'lowlighted level
buttons' mean, because I couldn't remember.
Removed unreachable code from level-select.gd
> Level button refactorings: interlude comments, private methods

- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/puzzle-messages.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/step-meter.gd
Retrying doesn't affect how far they advance, and the meter stays still.
But it lets them retry a level if they want to get better at it, even if
it doesn't count.
> Player can retry levels in career mode.

- project/src/main/player-save-upgrader.gd
- project/src/main/puzzle/level/level-settings-upgrader.gd
- project/src/main/save-item-upgrader.gd
- project/src/main/system-save-upgrader.gd
Upgraders used to compare the newest version to a constant which worked
because SystemSaveUpgrader and PlayerSaveUpgrader were in sync. After
making a change where the player save data uses a different version, the
SystemSaveUpgrader started complaining that it didn't know about version
27bb, even though 27bb was the newest version of the system data.
I've changed upgraders to compare the newest version to a
current_version variable. I've also made this change in
LevelSettingsUpgrader for symmetry, even though it's unnecessary there
because its upgrader is not reused.
> Added current_version property to upgraders.

- project/src/main/puzzle/rank-result.gd
- project/src/main/ui/level-select/hookable-level-grade-label.gd
- project/src/main/ui/level-select/level-buttons.gd
- project/src/main/ui/menu/region-buttons.gd
- project/src/main/ui/menu/region-info-panel.gd
Extracted new RankResult.overall_rank() utility method for obtaining the
overall rank for a RankResult -- the time for timed levels and the score
for all other levels.
RankResult now leverages WORST_RANK instead of hard-coding 999.0.
> Extracted overall_rank(). Leveraged WORST_RANK in RankResult.

- project/project.godot
- project/src/main/career-data.gd
- project/src/main/career-flow.gd
- project/src/main/region-completion.gd
- project/src/main/world/cutscene-ui.gd
Pulled RegionCompletion out into its own script. CareerData is large
(~500 SLOC) and this is something easy to pull out.
Moved 'should_play_prologue' method into CareerFlow. CareerFlow is
responsible for redirecting the player to prologues/cutscenes so this
seems like it fits here, and it keeps CareerData smaller.
Removed redundant is_career_cutscene method.
> Refactoring: Removed/moved code from CareerData.

- project/src/main/world/environment/lemon/LemonEnvironment.tscn
- project/src/main/world/environment/lemon/LemonRestaurantEnvironment.tscn
- project/src/main/world/environment/marsh/MarshEnvironment.tscn
- project/src/main/world/environment/marsh/MarshFreeRoamEnvironment.tscn
- project/src/main/world/environment/marsh/MarshIndoorsEnvironment.tscn
These spawn nodes are now grouped under a parent 'Spawns' node so the old naming
convention is redundant.
> Renamed spawns from 'SpawnForest' to 'Forest2'

- project/src/demo/ui/chat/MoodDemo.tscn
- project/src/main/ui/menu/CareerRegionSelectMenu.tscn
- project/src/main/ui/menu/TutorialMenu.tscn
- project/src/main/world/FreeRoamUi.tscn
When using the arrow keys on the Chapter Select screen, if you arrowed
off to the right the selection focus would disappear. This is because it
selected an invisible 'Spacer' button in the upper right corner of the
screen. I've changed the Spacer so it is not a button and cannot obtain
focus.
Changed the background of MoodDemo to a more neutral grey. I'm featuring
this in a YouTube video and the old background was kind of ugly.
> Fixed bug where Spacer could get focus

- project/src/demo/toolkit/fix-chats-button.gd
- project/src/main/career/career-level-library.gd
- project/src/main/ui/chat/career-cutscene-library.gd
ReleaseToolkit clears chatscript problems each time the button is
pressed. It also no longer counts files more than once. Before, its
counts would be inflated and increase continuously.
ReleaseToolkit detects unusual hyphens in chatscript files, such as the
kind that were fixed in [#1435](https://github.com/Poobslag/turbofat/pull/1435)
Fixed comments in CareerLevelLibrary.required_cutscene_characters() to
make it clear this refers to quirky characters.
Added break statement to CareerCutsceneLibrary 'quirky' logic. We do not
need to continue looping after we find a quirky character.
> ReleaseToolkit detects chatscript hyphens.

- project/assets/test/secondary-creatures/cold.json
- project/assets/test/secondary-creatures/cough.json
- project/src/main/creature-queue.gd
- project/src/test/test-creature-queue.gd
Fixed references from CreatureQueue to PlayerData.creature_queue. These
references are nonsensical and the class should just reference itself.
Added a few CreatureQueue tests. CreatureQueue now exposes a
secondary_creatures_path property which can be injected in unit tests.
> CreatureQueue tests, improvements

- project/src/main/creature-queue.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/world/cutscene-queue.gd
- project/src/test/test-creature-queue.gd
When the player picks a career level, we now push any matching secondary
creatures to the end of the queue so they won't be picked. This prevents
the player from picking a level with a creature, and then having that
creature immediately visit the restaurant again during the same puzzle.
> Avoid repeating secondary creatures.

- project/src/main/ui/RegionSelectButton.tscn
- project/src/main/ui/career/hookable-region-grade-label.gd
- project/src/main/ui/level-select/hookable-level-grade-label.gd
- project/src/main/ui/region-select-button.gd
Failed levels (levels where the player does not finish) no longer show a
level grade. This prevents an edge case where the region button shows
a region as 93% complete (because the player failed) but the level
shows they got an SSS (because they played well.) Now, the level will
show no label.
Fixed a bug where the region grade hook was above the button instead of
over top of the button, for buttons which were aligned at the bottom.
> Region fixes: failed level grades, grade hook position

- project/src/main/editor/creature/creature-editor.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/creature/creature-loader.gd
The CreatureEditor has no way of editing chat themes, so it was giving
all creatures the same theme. It now randomizes the themes.
> CreatureEditor randomizes chat themes.

- project/assets/test/turbofat-375c.json
- project/src/main/player-save-upgrader.gd
- project/src/main/player-save.gd
- project/src/main/puzzle/level/level-history.gd
- project/src/main/save-item-upgrader.gd
- project/src/main/system-save-upgrader.gd
- project/src/test/puzzle/level/test-level-history.gd
- project/src/test/test-player-save-upgrader.gd
A typo in the LevelHistory script made it so that if the player was
successful in a level (e.g clearing 100 lines in Marathon Normal) the
level was added to LevelHistory.successful_levels, but not to
LevelHistory.finished_levels. I've fixed the bug.
This bug affects player save data, as any finished levels in earlier
versions were not recorded. I've upgraded the player data to 3776 and
added a translation step which fills any gaps in finished_levels with
their entries from successful_levels.
> Bug: successful_levels entries missing from finished_levels

- project/src/main/puzzle/box-builder.gd
- project/src/main/puzzle/playfield.gd
In Paranormal Tetrominon it's possible for a line clear to create a 3x4.
Before, this new box would only be created when the player dropped a
piece which looked strange. It is now created immediately following the
line clear.
In Paranormal Tetrominon it's possible for a piece to build two possible
boxes at once, such as by sliding a second O piece between two horizontal line
pieces. Before, this would always create the top box which was
inconvenient. It now creates the bottom box so the player can continue
working on the top box.
> Paranormal tetrominon box building tweaks.

- project/src/main/ui/menu/CareerRegionSelectMenu.tscn
- project/src/main/ui/menu/TutorialMenu.tscn
The first 'Close' button was made to close the map menu so it had some
weird idiosyncracies. It had a small gap left for the settings menu, and
it closed with the 'Tab' key because this is the way the menu was
opened. None of these idiosyncracies make sense for the
Tutorial/CareerRegion menu, so I've reverted them. The buttons are in
the corner, and the menus close with escape not tab.
> Moved close buttons to corner. Changed shortcut.

- project/project.godot
- project/src/main/ui/menu/CareerRegionSelectMenu.tscn
- project/src/main/ui/menu/career-region-select-menu.gd
- project/src/main/ui/menu/paged-region-buttons.gd
RegionButtons no longer loads all regions, it can be populated with a
set of regions.
RegionButtons no longer launches a level, it emits a signal which can trigger
other behaviors instead.
RegionButtons no longer focuses the newest region, it exposes a
focus_region() function which can focus any region.
> Tweaked RegionButtons to be more generic.

- project/project.godot
- project/src/demo/ui/level-select/LevelSelectButtonDemo.tscn
- project/src/demo/ui/level-select/level-select-button-demo.gd
- project/src/main/ui/level-select/grade-label.gd
- project/src/main/ui/level-select/hookable-level-grade-label.gd
- project/src/main/ui/level-select/level-select-button.gd
Colors now use color constants like '7dff49' instead of calculated
colors like '4eff49, but with its hue modulated to 0.4667'. This makes
it easier to reuse colors in different places.
Grade label colors more closely match level status icons. The outlines
are still slightly different due to details about how they're rendered.
Added LevelSelectButtonDemo to show off different grades/icons
> Level button/grade color tweaks.

- project/src/main/puzzle/level/level-speed-adjuster.gd
- project/src/test/puzzle/level/test-level-speed-adjuster.gd
Level speed adjustment now adjusts based on start speed, not maximum
speed. This results in a more intuitive result for things like Marathon
Normal -- before, adjusting it from speed 0 to 5 resulted in no change.
Now, it results in a level which starts at a faster speed but then tops
out half way.
> Level speed adjustment now adjusts based on start speed.

- project/assets/test/turbofat-375c.json
- project/src/main/player-save-upgrader.gd
- project/src/test/test-player-save-upgrader.gd
Older versions of sandbox mode awarded the player a failing grade
because they technically 'lost' (they did not finish an unfinishable
mode.) Newer versions award them an 'M' rank, but players who played the
older versions may still have bad ranks floating around in their save
data. These ranks will now be replaced with master ranks.
> Upgrade old sandbox data to 'M' rank.

- project/project.godot
- project/src/main/world/environment/lemon/LemonEnvironment.tscn
- project/src/main/world/environment/marsh/MarshEnvironment.tscn
FreeRoam mode and cutscenes can still benefit from exits because they
give context to the buildings, so you know characters are at an
entrance/exit
> Added decorative exits to environments

- project/src/main/world/environment/overworld-environment.gd
ChattableManager provides a 'get_creature_by_id' functionality. This
functionality is important even in cutscenes and other contexts where
creatures aren't necessarily in the chattables list.
> Register creatures even if they're not chattables.

- project/project.godot
- project/src/main/career/career-data.gd
- project/src/main/career/career-level-library.gd
- project/src/test/career/test-career-level-library.gd
- project/src/test/world/test-career-data.gd
Before, beating Lemony Thickets' boss level on a new save game file would skip a
skilled player to distance 25, instead of halting them at distance 24.
This bug occurred because there are cutscenes marked as 'skip the player
to the next region' but because the player had already advanced from
Lemony Thickets to the next region, it would skip them even further.
The new skip logic locates the region corresponding to the cutscene and
only skips them past THAT region, not past their current region.
> Fixed autoadvancement bug which skipped regions

- project/src/main/ui/chat/chat-history.gd
- project/src/test/ui/chat/test-chat-history.gd
The chat counts were off by one, indicated by a failing unit test
> Bug: ChatHistory was return negative chat age

- project/project.godot
- project/src/main/puzzle/ComboBurst.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/combo-burst.gd
- project/src/main/puzzle/combo-bursts.gd
I like the word 'burst' because it sounds more like a UI element,
instead of 'counter' which could just be something which abstractly
counts things like Godot's orphan_counter
Combo burst now uses hard-coded colors like '4a9fff' instead of
calculated colors like '4eff49 with a hue of 0.5889'. This makes the
colors easier to reuse elsewhere.
> ComboCounter -> ComboBurst. Combo colors.

- project/src/main/puzzle/piece/PieceManager.tscn
- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/piece/piece-dropper.gd
- project/src/main/puzzle/piece/piece-manager.gd
Fixed bug where the 'soft_dropped' and 'hard_dropped' signals were
emitted even if the piece's position didn't change. This behavior was
inconsistent with other signals such as 'moved_left' which only fired
when the movement was successful.
Added a new 'dropped' signal which is emitted when the piece falls due
to gravity. There was no signal for this before.
> Improved drop signals. Added 'dropped' signal.

- project/src/main/puzzle/piece/piece-mover.gd
- project/src/main/puzzle/piece/piece-physics.gd
- project/src/main/puzzle/piece/piece-rotator.gd
The rotate/move signals were emitted incorrectly, causing PieceSfx to
emit the 'click' sound at times when it wasn't supposed to. More
specifically, the 'rotate' signal would be emitted between initial
rotation and initial movement, when the piece could still be obstructing
another piece.
Initial rotation and initial movement signals are now emitted after the
piece's movement is complete, and only in the case where the piece does
not cause a top out.
> Fixed bug with 'click' sounds at top of playfield.

- project/src/demo/puzzle/puzzle-demo.gd
The 'FINISH' cheat in PuzzleDemo caused the game to crash, because the
line clear key was manipulating LineClearer's internal state in an
illegal way. This appears to be an unnecessary step which was added in
2020 when the LineClearer was less mature.
> Fixed bug with PuzzleDemo's line clear key

- project/src/main/career/career-flow.gd
- project/src/main/editor/creature/dialogs.gd
- project/src/main/player-save.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/career/career-win.gd
Writing the player save JSON file takes about 50 ms, which is enough to
cause a noticable stutter. When adding a 'swoosh' effect to end-of-level
messages, for example, this effect was interrupted by the save data
being written.
Player data saves are now scheduled to occur between levels. I think
this might also help the HTML5 builds, where these stutters would affect
music playback.
> Player data is saved during scene transitions.

- project/src/main/ui/menu/PracticeMenu.tscn
- project/src/main/ui/menu/practice-menu.gd
When entering the practice menu, I am often just mashing buttons to
hurry up and play a level. Having a level select menu open just so that
I could pick the same level I already had highlighted felt annoying to
me.
> Practice menu highlights 'start' button.

- project/src/main/puzzle/piece/piece-physics.gd
- project/src/main/puzzle/piece/piece-rotator.gd
This functionality was broken by the signal changes in dc23a9ba. Initial
rotation was being allowed on levels which were not supposed to allow
it.
> Restore 'suppress piece initial rotation' functionality

- project/src/demo/world/environment/marsh/MarshFreeRoamEnvironment.tscn
- project/src/main/world/ObstacleSpawner.tscn
- project/src/main/world/environment/lemon/LemonRestaurantEnvironment.tscn
- project/src/main/world/environment/marsh/ButtercupTableSpawner.tscn
- project/src/main/world/environment/marsh/MarshCrystalSpawner.tscn
- project/src/main/world/environment/marsh/MarshEnvironment.tscn
- project/src/main/world/environment/marsh/MarshIndoorsEnvironment.tscn
Godot 3.5 now allows scenes to inherit each other more efficiently.
Child scenes no longer need to define redundant fields like these
'target_properties' fields which are already defined in their parent.
> Updated target_properties for Godot 3.5

- project/assets/main/puzzle/career-regions.json
This was inadvertently removed in 7bd757eb when adding the new career
region.
> Restored lemony thickets story

- project/src/main/career/career-calendar.gd
- project/src/main/career/career-data.gd
best_distance_travelled now updates automatically when
distance_travelled updates. This means we can rely on it during a career
session.
> CareerData.best_distance_travelled updates more frequently.

- project/src/main/puzzle/puzzle-messages.gd
Fixed a bug where the 'Ready?' message would appear at the start of
tutorials and never disappear.
> Fixed tutorial 'Ready?' bug

- project/assets/demo/chat/tableside.chat
- project/src/demo/world/environment/marsh/MarshIndoorsFreeRoamEnvironment.tscn
- project/src/main/world/environment/marsh/MarshIndoorsEnvironment.tscn
- project/src/main/world/environment/marsh/UndecoratedIndoorsEnvironment.tscn
CutsceneDemo accepts 'best_distance_travelled' flag
CutsceneDemo can load cutscenes from demo folder.
CutsceneDemo correctly assigns focus when a dialog is closed.
CutsceneDemo validates its initial cutscene path, reporting warnings
appropriately.
CutsceneDemo handles invalid cutscene selections differently. Before, it
would pop up a dialog and ignore the player's selection. Now it pops up
the dialog and saves the player's selection, but disables the start
button. This allows better consistency for the case where the player has
bad data already saved.
comments, delint
> CutsceneDemo enhancements. Tableside cutscene.

- project/src/main/ui/chat/chat-history.gd
- project/src/test/ui/chat/test-chatscript-parser.gd
ChatHistory.reset() now resets the chat_count
test-chatscript-parser now resets the chat history
Neither of these were causing immediate problems but they would have
made tests more unreliable as we added more
> Chat bugfixes: chat_count, unit test fix

- project/src/main/creature-library.gd
- project/src/main/ui/nametag-panel.gd
- project/src/test/test-creature-library.gd
This extra 'full_name' parameter was only used in one place, for
substituting long names in nametags. This is easier to do with something
like a match statement rather than having to scan the entire string.
Added missing CreatureLibrary unit test.
> Refactored substitute_variables to remove parameter.

- project/assets/demo/chat/tableside.chat
- project/assets/test/ui/chat/chat-default-phrase.chat
- project/assets/test/ui/chat/chat-set-phrase.chat
- project/src/demo/toolkit/extract-localizables-button.gd
- project/src/main/ui/bool-expression-parser.gd
- project/src/main/ui/chat/chat-history.gd
- project/src/main/ui/chat/chat-tree.gd
- project/src/test/ui/chat/test-chatscript-parser.gd
If we add cutscenes which reference the player's chosen restaurant name,
people who have already progressed past that part in the story will just
see '#restaurant_name#' or something like that because they made no
selection. The 'default_phrase' meta item helps us fill in this gap.
Ideally, this 'default_phrase' item would not be written to the player's
chat history and maybe even be scoped to a specific variable reference.
But in addition to being more difficult to implement, this would intrude
on localization since a phrase like 'I love eating at
%favorite_restaurant%' is reasonable for a non-coder to localize (just
ignore the weird code-looking part) but a phrase like 'I love eating at
%favorite_restaurant|Junjorito%' requires a deeper understanding of
chatscript nuances.
> Chatscript: default_phrase, has_phrase

- project/src/main/ui/menu/paged-level-buttons.gd
- project/src/main/ui/menu/paged-region-buttons.gd
- project/src/main/ui/menu/region-submenu.gd
Before, drilling down into the practice menu often resulted in no
buttons being focused, which meant you had to use the mouse.
> Level/region buttons receive default focus.

- delint.sh
- license/asset-license.txt
- project/project.godot
- project/src/main/creature-library.gd
- project/src/main/tracery.gd
- project/src/main/ui/chat/career-cutscene-library.gd
- project/src/test/test-creature-library.gd
- project/src/test/test-tracery.gd
https://github.com/Althar93/GDTracery
Added GDTracery. We were already using tracery-like syntax for things
like #player# and #sensei#, but the new cutscenes also needed to be able
to say things like "I'm Tom's business partner" which was not possible.
I've modified the tracery implementation in a few ways:
* I've added localization. English and spanish have their own modifiers for how
to make a word possessive, and it is easy to add more.
* I've removed most modifiers, even common ones such as '-ed' and '-s'. We can
reintroduce these as necessary, but if we have 10 modifiers and 10 languages
that is 100 functions to write. Fewer is better.
* Bugfixes, specifically a flaw in GDTracery's 'set_rng' function.
This flawed setter was unnecessary so I've removed it.
Tracery may be overkill for …
> Tracery. #player.possessive# works.

- project/assets/main/chat/career/marsh/intro-level-end.chat
- project/assets/test/ui/chat/cutscene-full.chat
- project/src/demo/puzzle/tutorial/tutorial-hud-demo.gd
- project/src/main/name-utils.gd
- project/src/main/puzzle/results-hud.gd
- project/src/main/puzzle/results-label.gd
- project/src/main/ui/chat/chat-library.gd
- project/src/main/ui/chat/label-typer.gd
- project/src/test/test-name-utils.gd
- project/src/test/ui/chat/test-chat-library.gd
The forward-slash character has occasional conversational use, like 'I'm
asking you a simple yes/no question!' Or 'I didn't mean to confuse
and/or offend you'. I've changed the lull character to a different
character so that we can use it in dialog. (The lull character is used
to inject pauses into some sentences for dramatic effect.)
I've also changed NameUtils to filter out more special characters,
including the lull character and the number sign (used for Tracery.)
> Switch lull from '/' to '|'. Illegal name chars.

- project/src/main/tracery.gd
- project/src/test/test-tracery.gd
Number signs are useful in dialog for phrases like `I'm your #1 fan!`
but they would conflict with Tracery's syntax, and sentences with two
number signs would have their number signs removed.
Tracery's regex now doesn't match pound signs separated by spaces.
> Fix conflict with number signs in tracery.

- project/src/main/ui/chat/chat-library.gd
- project/src/test/ui/chat/test-chat-library.gd
Our dialog parsing logic adds lull characters after periods. But tracery
uses periods for its modifier syntax. Our dialog parsing logic now
checks for this and removes lull characters from tracery tags.
> Fixed conflict with tracery and lull characters.

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/practice-data.gd
- project/src/main/puzzle/level/level-history.gd
- project/src/main/ui/menu/tutorial-menu.gd
The most recently selected tutorial is stored in the 'PracticeData'
node. It felt like overkill to have an entire 'TutorialData' mode just
to store one string.
> Tutorial menu defaults to the last selected tutorial.

- project/src/demo/ui/chat/chat-frame-demo.gd
- project/src/main/ui/chat/chat-line-panel.gd
- project/src/main/ui/chat/chat-theme.gd
- project/src/main/utils.gd
- project/src/test/test-utils.gd
- project/src/test/ui/chat/test-chat-theme.gd
Chat themes with green on black and red on black looked OK, but
blue/purple on black was hard to read. The border_color/accent_color
logic now incorporates a brightness calculation which distinguishes
between the brightness of different hues.
> Fixed hard-to-read chat themes.

- project/assets/test/turbofat-37b3.json
- project/src/main/player-save-upgrader.gd
- project/src/main/player-save.gd
- project/src/test/test-player-save-upgrader.gd
Two-digit cutscenes were expanded to three digits in fd6b909f, but the
player's chat history was not updated. This meant players who'd played
the game previously would lose all their cutscene progress and have to
rewatch all the same cutscenes again.
> Update two-digit chat history entries

- project/assets/demo/chat/chat-narrator.chat
- project/assets/main/chat/career/marsh/060-end.chat
- project/assets/main/chat/career/marsh/epilogue.chat
- project/assets/main/chat/career/marsh/intro-level-end.chat
- project/assets/main/chat/career/marsh/prologue.chat
- project/assets/main/creatures/sensei/creature.json
- project/assets/test/ui/chat/cutscene-full.chat
Fat Sensei's name was going to be in the game code as 'Turbo' as a
misdirect but I'm going to approach this differently.
> Hard-code fat sensei's name in chats. Change name from 'Turbo'.

- project/src/main/ui/chat/chat-advancer.gd
- project/src/main/ui/chat/chat-ui.gd
- project/src/main/ui/overworld-ui.gd
The 'nametag sides' logic wasn't working for cutscenes where creatures
enter/exit. This was because it was based on the creature positions, but for
these scenes the creatures didn't exist yet.
I've changed the logic so the nametag sides are recalculated each time a
creature enters or exits the scene.
I also refactored ChatUi so it uses its own ChatTree instance instead of
digging into ChatAdvancer, and changed both to unassign their ChatTree
instance when the conversation ends.
> Fixed 'nametag sides' logic for appearances

- project/src/main/world/cutscene-world.gd
This 'remove all characters but the player and sensei' logic was for
when freeroam scenes doubled as cutscene scenes, but now it doesn't
really make sense because these scenes are single-purpose
> Remove player/sensei before playing cutscenes

- project/src/main/world/cutscene-world.gd
Player/sensei were being removed from walking cutscenes, resulting in
NPEs during cutscenes.
> Fixed walking cutscenes.

- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/ui/menu/main-menu-play.gd
This fixes a bug when playing a level in Career mode with a special
chef/customer. If you quit and then played practice mode, the same
chef/customer would appear.
Closes #1584.
> Puzzle clears out chefs/customers when quitting.

- project/src/main/puzzle/restaurant-view.gd
The chef used to randomly be angry/confused. But at some point the 'top
out' emotion of being sad overwrote the random emotion.
Closes #1585.
> Bug: Chef always appears sad on game over

- project/src/main/world/career-map.gd
Fixed a bug where the career map would show a certain chef/customer, but
the level would show a different one.
This bug occurred because the 'level posse' for each level was not
stored, but was generated each time it was needed. So when generating
the map it would randomly select one chef, and then when loading the
level it would randomly select a different chef.
The level posse is now generated once and stored, so that it will be
consistent.
> Fixed mismatch between career map/level character

- project/src/main/career/career-calendar.gd
- project/src/main/career/career-data.gd
- project/src/test/world/test-career-data.gd
Intro level cutscenes were dependent on whether the player had played
that specific level before. This meant intro cinematics could be skipped
if the intro level was recycled or if the player tried it in practice
mode.
The intro level cutscenes are now dependent on whether the player has progressed
through career mode or not. This makes many of the existing career tests
redundant or overly convoluted, such as tests where the player progresses
through several boss levels in regions with no intro level. I've removed these
tests, because I anticipate most regions having an intro level anyways so the
tests aren't worth preserving.
> Fixed bug where intro level cutscenes could be skipped

- project/src/main/puzzle/piece/piece-types.gd
Organizing these so they're consistently one-item-per-line with a comma
at the end makes it easier to reorder them. It also means Git's diffs
are cleaner.
> Reorganized piece-types.gd arrays.

- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/piece/piece-type.gd
- project/src/main/puzzle/piece/piece-types.gd
https://github.com/26F-Studio/Techmino/blob/e1885bdb609706783f6ba83ebf52dd003c1f1894/parts/RSlist.lua
Taking inspiration from Techmino, Turbo Fat's piece kick tables are now
stored as dictionaries with a 'from' and 'to' orientation as the key.
This simplifies a lot of things:
- We don't need a separate table for piece flips
- It simplifies the process for detecting the presence/absence of
inverse piece kicks
- We don't need to store redundant entries for inverse flip kicks
- It is more human readable because each line of code says which
orientation the kicks apply to
- It is easier to look up the kicks for a specific orientation since
they are all in one place
> Refactored piece kick tables.

- project/src/main/puzzle/piece/active-piece.gd
- project/src/main/puzzle/piece/piece-type.gd
- project/src/main/puzzle/piece/piece-types.gd
- project/src/test/puzzle/piece/test-piece-kicks-u.gd
U pieces used to spawn pointy-side down, and kick the floor twice during
a full 360 degree rotation. They now spawn flat-side down, and only kick
the floor once. This provides a few benefits:
- The piece movement now resembles J/L pieces so it will be more
familiar
- U pieces no longer need to permit extra floor kicks. They used to
permit 5 floor kicks because otherwise they were too unforgiving at
20G compared to other pieces
- U pieces now look like a 'U' in the next piece queue :)
There is one drawback: U pieces and T pieces no longer interlock when hard
dropping without the rotate key. But, this is a rather superficial drawback in
my opinion. We could preserve it if we spawned the U piece in its '2'
orientation, but then the piece rotates off the top of the screen which
is …
> U pieces now rotate like J/L pieces.

- project/src/main/ResourceCache.tscn
- project/src/main/resource-cache.gd
Added ResourceCache.threaded flag. ResourceCache can be configured to be
threaded or non-threaded. This allows us to disable threading even for
targets which support it.
Added ResourceCache.load_seconds flag. ResourceCache can be configured
to load resources gradually. This makes the loading screen less
stuttery.
Added ResourceCache.low_priority_resource_paths parameter. ResourceCache
has a few resources such as 'Puzzle.tscn' which, if loaded too early,
take a long time to cache because they load other scenes and resources.
Loading them last results in fewer stutters when caching resources.
> ResourceCache: threaded, load_seconds, low_priority

- project/src/main/music/music-transition.gd
- project/src/main/ui/menu/loading-screen.gd
- project/src/main/ui/scene-transition-cover.gd
- project/src/main/ui/scene-transition.gd
This scene transition looks pretty so it's nice to draw attention to it.
But we don't want every scene transition to be this slow or the game
will be tedious to navigate.
> Splash screen scene transition is slower than others.

- project/src/main/world/creature/MovementPlayer.tscn
When facing away from the camera, characters had the wrong arm/leg
sprites. This bug was introduced in f367881d when adding 'RESET'
animations.
> Fixed backwards arms/legs in FreeRoam.

- project/src/test/test-system-save-upgrader.gd
SystemSaveUpgrader was using the 'legacy filename' instead of the
regular filename. It now alternates between teh legacy/regular filename
from test to test.
SystemSaveUpgrader was changing the locale but not changing it back.
> test-system-save-upgrader non-legacy tests, locale

- project/src/test/test-creature-library.gd
- project/src/test/test-player-save-upgrader.gd
test-creature-library.gd could fail depending on the order of prior tests. If
the career data was assigned so that the player was earlier in the story, the
sensei's name would be hard-coded to 'Turbo' and fail the replacement test.
test-player-save-upgrader.gd was loading everything as legacy player
data, even later versions which should have been loaded traditionally.
> Fix tests: CreatureLibrary, PlayerSaveUpgrader

- project/src/main/puzzle/piece/piece-rotator.gd
- project/src/main/puzzle/piece/piece-types.gd
I tried getting used to the upside-down U piece but it was too
unintuitive. Every other Turbo Fat piece lets you drop the quadromino
and tetromino on top of each other without rotating, but with U pieces
breaking this rule I kept stacking them upside-down, even after
practicing for a few hours.
To prevent the flipped U piece from immediately rotating off the top of the
screen, I've added 'piece nudges' which will push a piece down if it attempts
to rotate offscreen. I hate the idea of messing with piece rotation in such an
unintuitive way so it only happens in a very specific case:
- the piece is rotating offscreen
- the piece was not already offscreen
- the piece is not triggering any piece kicks
In rotating the U piece, I also moved its shape one cell upward.
Otherwise topping out with …
> U piece spawns smooth-side up.

- project/src/main/ui/career/career-win-world.gd
- project/src/main/world/career-world.gd
- project/src/main/world/creature-manager.gd
- project/src/main/world/cutscene-world.gd
- project/src/main/world/environment/overworld-environment.gd
Removed redundant OverworldEnvironment.find_creature. This did the same thing as CreatureManager.get_creature_by_id.
Removed CreatureManager.register_creature. OverworldEnvironment's implementation of using node groups was simpler.
> Refactor: find_creature, register_creature

- project/src/main/puzzle/level/level-speed-adjuster.gd
- project/src/main/puzzle/piece/piece-speeds.gd
- project/src/main/ui/menu/practice-menu.gd
- project/src/test/puzzle/piece/test-piece-speeds.gd
This piece speed matrix was copy/pasted in LevelSpeedAdjuster and PracticeMenu. It is now centralized in PieceSpeeds and generated in a better way to avoid repetition.
> Centralized piece speed matrix.

- project/src/demo/ui/level-select/level-select-button-demo.gd
- project/src/main/ui/level-select/LevelSelectButton.tscn
- project/src/main/ui/level-select/level-select-button.gd
- project/src/main/ui/menu/paged-level-buttons.gd
Levels are no longer strictly arranged in columns, the CareerMap arranges them in a row. This property is redundant with rect_min_size anyways.
> Eliminated LevelSelectButton.level_column_width

- project/src/main/puzzle/puzzle.gd
If a customer was already seated, resetting the secondary customer queue could summon them a second time. We now purge all seated customers from the secondary customer queue.
> Fixed bug where customer could appear twice.

- project/assets/main/creatures/primary/bones.json
- project/assets/main/creatures/primary/diota.json
- project/assets/main/creatures/primary/richie.json
- project/assets/main/creatures/primary/shirts.json
- project/assets/main/creatures/primary/sidger.json
- project/assets/main/creatures/primary/skins.json
- project/assets/main/creatures/primary/tunathy.json
- project/assets/main/creatures/secondary/rhonk.json
- project/assets/main/creatures/sensei/creature.json
- project/src/main/editor/creature/dialogs.gd
- project/src/main/world/creature/creature-def.gd
- project/src/main/world/creature/creature-library.gd
- project/src/main/world/creature/creature-loader.gd
Creatures can now define a customer_if flag. It defaults to 'true' so all existing creature definitions are customers. Setting it to 'false' will prevent them from appearing as a random customer. It can also be set to an expression like 'region_cleared marsh' which will make the customer appear once the criteria are met. (Or, prevent the customer from appearing once the criteria stop being met.)
> Added 'customer_if' flags

- project/src/main/data/player-data.gd
- project/src/main/puzzle/customer-queue.gd
- project/src/main/puzzle/level/current-level.gd
- project/src/main/puzzle/puzzle.gd
- project/src/main/puzzle/restaurant-view.gd
- project/src/main/world/creature/creature-loader.gd
- project/src/main/world/cutscene-queue.gd
- project/src/test/puzzle/test-customer-queue.gd
The names priority/standard are less ambiguous than primary/secondary. They have an analogy with priority passengers on an airplane, they board first. This also disambiguates the idea of the 'secondary queue' with creatures in the 'secondary directory', two concepts which were muddled together.
> CustomerQueue has 'priority' and 'standard' queues

- project/src/main/puzzle/customer-queue.gd
Creature IDs are embedded in the creature json. They are usually the same as the filename but not necessarily.
> Remove creature_id assignment from CustomerQueue.

- project/src/demo/toolkit/extract-localizables-button.gd
- project/src/demo/toolkit/fix-creatures-button.gd
- project/src/main/utils/utils.gd
- project/src/test/utils/test-utils.gd
ReleaseToolkit's 'Fix Creatures' button will now look for creatures which are in the inappropriate directory. Creatures who have cutscenes should be in the /story directory. Creatures with no cutscenes should be in the /nonstory directory.
> Added script to fix /story /nonstory creatures.

- project/src/main/ui/menu/PagedLevelPanel.tscn
- project/src/main/ui/menu/PracticeMenu.tscn
- project/src/main/ui/menu/TutorialMenu.tscn
- project/src/main/ui/menu/level-submenu.gd
- project/src/main/ui/menu/paged-level-buttons.gd
- project/src/main/ui/menu/paged-level-panel.gd
- project/src/main/ui/menu/paged-region-buttons.gd
- project/src/main/ui/menu/practice-menu.gd
- project/src/main/ui/menu/region-submenu.gd
- project/src/main/ui/menu/tutorial-menu.gd
This avoids some copy/pasted node trees in PracticeMenu and TutorialMenu. They still need a little duplication because they have slightly different UI -- the tutorial menu has a round splash panel while the practice menu has a black backdrop.
> Extracted common 'paged-level-panel'.

- project/src/main/career/CareerRewinder.tscn
- project/src/main/career/career-rewinder.gd
- project/src/main/ui/menu/CareerRegionSelectMenu.tscn
- project/src/main/world/CareerMap.tscn
This avoids copying/pasting the 'chap01' 'chap02' codes in multiple places.
> CareerRewinder adds its own cheats to the cheat code detector.

- project/src/main/ui/menu/loading-orb.gd
- project/src/main/utils/utils.gd
- project/src/main/world/career-camera.gd
- project/src/main/world/creature/player.gd
Loading screen now reuses ui_pressed_dir utility method.
Loading screen normalizes launch vectors. This prevents a bug where pieces launched diagonally travelled further than pieces launched in an orthagonal direction.
> Loading screen ui_pressed_dir, normalization

- project/src/main/puzzle/tutorial/skill-tally-item.gd
- project/src/main/world/creature/creature.gd
Reordered creature signal methods to be grouped together.
Replaced skill-tally-item.gd 'get_node' references with onready variables.
> Creature method ordering. Skill tally code cleanup.

- project/src/main/puzzle/GoopGlob.tscn
- project/src/main/puzzle/HudFlash.tscn
- project/src/main/puzzle/LeafPoof.tscn
- project/src/main/puzzle/Pickup.tscn
- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/Puzzle.tscn
- project/src/main/puzzle/food-item.gd
- project/src/main/puzzle/goop-glob.gd
- project/src/main/puzzle/hud-flash.gd
- project/src/main/puzzle/leaf-poof.gd
- project/src/main/puzzle/pickup.gd
- project/src/main/puzzle/playfield-fx.gd
- project/src/main/puzzle/puzzle-money-hud.gd
- project/src/main/puzzle/tutorial/SkillTallyItem.tscn
- project/src/main/puzzle/tutorial/skill-tally-item.gd
- project/src/main/ui/MoneyLabel.tscn
- project/src/main/ui/settings/SettingsMenu.tscn
- project/src/main/ui/settings/settings-copy-save-data.gd
- project/src/main/utils/utils.gd
- project/src/main/world/creature/Creature.tscn
- project/src/main/world/creature/CreatureVisuals.tscn
- project/src/main/world/creature/EmotePlayer.tscn
- project/src/main/world/creature/creature-animations.gd
- project/src/main/world/creature/creature.gd
- project/src/main/world/creature/emote-player.gd
- project/src/main/world/environment/ripple-sprite.gd
This reverts commit a1b1dbb8162c689787cea538a33916c818af4710.
Godot 3.5 introduced SceneTreeTweens, but these are still buggy and result in reference leaks. When running Turbo Fat's puzzle mode, the number of nodes gradually increases from 1,000 to 2,000, 3,000, and keeps growing without limit. After a few minutes the game becomes choppy and unplayable.
Removing the SceneTreeTweens fixes the problem. We can restore this code once Godot #52699 is closed, and SceneTreeTweens work as intended.
See https://github.com/godotengine/godot/issues/52699
> Revert "Rewrote tweens to use Godot 3.5 syntax."

- project/project.godot
- project/src/main/puzzle/level/config-string-utils.gd
- project/src/main/puzzle/level/phase-conditions.gd
- project/src/test/puzzle/level/test-config-string-utils.gd
This breaks the AfterLineCleared phase condition into three simple easy-to-understand parts -- translating strings to int arrays, inverting the int arrays, and combining those two pieces in the AfterLineCleared phase condition. The first two parts are generic and can be reused by other phase conditions or effects in the future.
> Extracted ConfigStringUtils.

- project/assets/main/puzzle/career-regions.json
- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/demo/toolkit/fix-levels-button.gd
- project/src/main/career/career-level-library.gd
These were added to the career folder, but never assigned regions. I've updated the ReleaseToolkit to detect unused levels.
> Add unused career levels; perfect_fit, fruit_on_the_top

- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/puzzle/line-inserter.gd
Fixed bug where if levels had multiple tiles_keys arrays, LineInserter would continue using the previously used one. This was because it could only keep track of one 'previous tiles key' even if there were multiple arrays in use.
The new implementation stores one 'previous tiles key' for each tiles keys array. This works because we always pass in the same tiles key reference from our configuration.
> Fixed LineInserter bug with tiles_key arrays. invert_lines typo.

- project/src/demo/puzzle/PuzzleDemo.tscn
- project/src/main/puzzle/level/level-settings-upgrader.gd
- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/level/levels.gd
- project/src/main/puzzle/level/phase-conditions.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/line-filler.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/test/puzzle/level/test-level-settings.gd
- project/src/test/puzzle/level/test-level-trigger.gd
- project/src/test/puzzle/level/test-level-triggers.gd
- project/src/test/puzzle/level/test-phase-conditions.gd
These phases explicitly specified 'AFTER line cleared' and 'AFTER piece written' in anticipation of other more granular phase conditions being written some day. However, I don't see a need for those.
Additionally, the timing of these triggers needs to be very specific to avoid unwanted side effects. The 'after line cleared' phase condition used to coincide with the after_line_cleared signal, but they now occur at different times, so I'm renaming these phase conditions to avoid confusion.
> Renamed level trigger phases: 'line_cleared', 'piece_written'

- project/src/main/puzzle/level/config-string-utils.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/test/puzzle/level/test-level-trigger-effects.gd
Adding a 'y' coordinate highlighted some bugs in the timing of inserts/line_cleared triggers. More specifically, saying something like 'when line 5 is deleted, insert a new line at row 5' didn't work because all of the line_cleared signals were fired at the end, after the lines have already shifted.
line_cleared triggers are now fired at a very specific timing -- after the lines are erased but before the lines are deleted. This required exposing some internals of PuzzleTileMap to LineClearer.
Additionally, we don't want 'line_cleared' signals to fire when resetting a level, so I've added a top out detector similar to what exists in line_filler.
> insert_line level trigger effect accepts 'y'

- project/src/main/puzzle/box-builder.gd
- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/level/phase-conditions.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/test/puzzle/level/test-phase-conditions.gd
This 'box built' phase trigger lets us create levels where special things happen when the player makes snack boxes or cake boxes (or both.) In the future this could be expanded to reward specific boxes (like JLO boxes) but this feels too obscure to be fun.
This 'line cleared' phase trigger lets us create levels where surprises happen after clearing a certain number of lines. Or, after clearing 5, 10, 15... lines.
> New level triggers: 'box built', 'line_cleared n=5'

- project/src/demo/puzzle/level/LevelRankDemo.tscn
- project/src/demo/puzzle/level/level-rank-demo.gd
- project/src/main/puzzle/level/level-settings.gd
LevelRankDemo now shows an entire `"rank": []` json block. This makes it faster to update a level's json data.
LevelSettings now reports file not found errors better, instead of crashing.
> LevelRankDemo format. LevelSettings file not found handling.

- project/assets/demo/puzzle/levels/experiment.json
- project/src/main/puzzle/puzzle-tile-map.gd
This prevents broken pieces/boxes from showing up during new levels such as 'shelf' which insert empty rows in the middle of the playfield.
> PuzzleTileMap detaches neighbors when inserting lines.

- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/pickups.gd
- project/src/main/puzzle/puzzle.gd
Fixed a bug where if the mole dug up a pickup while a piece was overlapping them, the pickup would appear 'behind' the piece.
> Fixed bug with mole pickups overlapping the active piece.

- project/assets/demo/puzzle/levels/experiment.json
- project/src/main/puzzle/puzzle-tile-map.gd
Inserting lines converted ALL adjacent pieces to veggies -- even if they were not broken. I've changed the logic so that pieces are only converted if they are interrupted by the inserted line.
> Fixed bug where inserting lines converted pieces to veggies

- project/src/main/puzzle/critter/moles.gd
- project/src/main/puzzle/level/blocks-during-rules.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/line-filler.gd
- project/src/main/puzzle/playfield.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/puzzle/top-out-tracker.gd
LineClearer refers to 'lines' instead of 'rows' in more places.
Disambiguated 'filled lines' -- out of context it's ambiguous whether these are lines which the player filled with pieces, or lines which are filled from the top by LineFiller
Added missing level trigger comments.
Reordered some LineClearer methods; private methods should be below public ones.
Added after_lines_deleted signal parameter.
Replaced PuzzleTileMap -1 references with INVALID_TILE
Added PuzzleTileMap.erase_cell method. This will be useful for levels which erase cells.
> Line clear refactorings: row->line, comments, reorder

- project/src/main/puzzle/line-clearer.gd
LineClearer was iterating over different dictionaries, but treating them all like the 'lines to preserve' dictionary instead of referencing the new_dict iterator.
> Fixed newly introduced LineClearer bool bug

- project/src/main/puzzle/level/level-trigger.gd
- project/src/main/puzzle/playfield.gd
Clearing lines results in an after_piece_written signal sometimes, so triggers were being called twice. Rather than requiring levels to explicitly specify some triggers as 'after_piece_written' and other triggers as 'piece_written', I've pushed this complexity into the LevelTrigger parser.
> Fixed conflict with after_piece_written and clear_filled_lines

- project/src/main/puzzle/top-out-tracker.gd
Piece spawn delay was irreversibly set to 0 after topping out. It's supposed to be temporarily set to 0 and then set back, but a line of code was missing.
> Bug: Piece spawn delay removed after topping out

- project/src/main/puzzle/Playfield.tscn
- project/src/main/puzzle/line-filler.gd
- project/src/main/puzzle/line-inserter.gd
Lines with only pickups were considered empty by the line inserter and line filler, so the logic for iterating over multiple lines wouldn't work properly. The inserter and filler now considered pickups when determining if a line is empty.
> Fixed bug where line inserter/filler did not handle pickup rows

- project/src/main/puzzle/playfield-fx.gd
For levels which break on 3 or more dropped pieces, the combo patterns now stay in the 'on' pattern until the combo is about to break, and then switch to the 'half' pattern.
For levels which break on 1 dropped piece, the combo patterns now immediately switch to the 'half' pattern.
This helps provide more useful feedback to the player about the current level's rules and state.
> Combo patterns now indicate when a combo will break.

- project/src/main/editor/puzzle/editor-playfield.gd
- project/src/main/editor/puzzle/veg-level-chunk-control.gd
- project/src/main/puzzle/level/level-trigger-effects.gd
- project/src/main/puzzle/line-clearer.gd
- project/src/main/puzzle/line-filler.gd
- project/src/main/puzzle/line-inserter.gd
- project/src/main/puzzle/pickups.gd
- project/src/main/puzzle/puzzle-tile-map.gd
- project/src/main/puzzle/star-seeds.gd
- project/src/test/puzzle/level/test-level-trigger-effects.gd
LineInserter now accepts 'count' parameter for inserting multiple lines.
Fixed bug where inserting lines in response to line clears could result in blank lines being inserted.
Fixed bug where LineClearer was assigning 'true' into a dictionary which was supposed to have numeric values only.
LineInserter/LineFiller now randomize vegetables.
> Line insert improvements: multiline, bugfixes, random veg

- project/src/demo/puzzle/ScoreDemo.tscn
- project/src/demo/puzzle/score-demo.gd
- project/src/main/puzzle/Score.tscn
- project/src/main/puzzle/combo-score-value-label.gd
- project/src/main/puzzle/puzzle-state.gd
- project/src/main/puzzle/rank-calculator.gd
- project/src/main/puzzle/results-hud.gd
- project/src/main/puzzle/score-value-label.gd
- project/src/test/puzzle/test-rank-calculator.gd
Topping out no longer affects the rank algorithm. Instead, it takes away ¥100 and plays a long 'top out' animation which takes some time anyways. This is enough of a penalty.
The score panel now shows a red number and particle effect when the player tops out.
> Replace top out rank penalty with money penalty

- project/src/main/puzzle/puzzle-timer.gd
The timer which counts up as you play a level was made visible/invisible in _ready() and not when a level's settings changed, meaning that if a new level was loaded (such as in the level editor or puzzle demo) the timer would not be reinitialized, and it would be inappropriately visible/invisible
> Fixed PuzzleDemo timer visibility bug

- project/assets/main/puzzle/levels/career/a-thousand-moles.json
- project/assets/main/puzzle/levels/career/above-and-below.json
- project/assets/main/puzzle/levels/career/checkerboard-vault.json
- project/assets/main/puzzle/levels/career/dark/above-and-below.json
- project/assets/main/puzzle/levels/career/dark/fruit-on-the-top.json
- project/assets/main/puzzle/levels/career/dark/hungry-moles.json
- project/assets/main/puzzle/levels/career/dark/surprise-guests.json
- project/assets/main/puzzle/levels/career/hungry-moles.json
- project/assets/main/puzzle/levels/career/mole-money-mole-problems.json
- project/assets/main/puzzle/levels/career/paranormal-tetrominon.json
- project/assets/main/puzzle/levels/career/rice-bear-island.json
- project/assets/main/puzzle/levels/career/shelf.json
- project/assets/main/puzzle/levels/career/slow-service-2.json
- project/assets/main/puzzle/levels/career/strawberry-slowcake.json
- project/assets/main/puzzle/levels/career/surprise-guests.json
- project/assets/main/puzzle/levels/career/three-course-meal.json
- project/assets/main/puzzle/levels/career/two-box-buffet.json
Removed errant 'pickups rank' for paranormal tetrominon. Did this level have pickups during its inception?
> Added missing 'show_pickups_rank' 'hide_box_rank' flags

- project/assets/main/puzzle/career-regions.json
Now that the career day is only 6 days long, the player only has 5 turns to reach the boss level. Shortening the regions makes this slightly more forgiving.
> Shortened career regions.

- project/src/main/world/overworld-ui.gd
Without this code, it's possible for someone to finish a level, watch a cutscene, quit to the main menu and quit the game -- but have to watch the same cutscene next time.
> Immediately save after viewing a cutscene.

- project/src/main/puzzle/line-clearer.gd
LineClearer and Playfield were having their 'game_prepared' listeners invoked in the wrong order, so the blocks were prepared, the 'lines to preserve' array was initialized, and then it was immediately cleared.
LineClearer now keys off of Playfield's 'blocks_prepared' to reset itself.
> Fixed bug where preplaced boxes weren't preserved
